xmake-io/xmake-repo

packages/l/libuv/xmake.lua

`xmake` is great! 🎉
This the way I generate the checksum shasum for `libuv`.
```bash
versions="v1.27.0 v1.26.0 v1.25.0 v1.24.1 v1.24.0 v1.23.2"
for v in $versions
do
wget -q https://github.com/libuv/libuv/archive/${v}.zip
shasum -a 256 ${v}.zip
done
```
```
02d4a643d5de555168f2377961aff844c3037b44c9d46eb2019113af62b3cf0a  v1.27.0.zip
b9b6ae976685a406e63d88084d99fc7cc792c3226605a840fea87a450fe26f16  v1.26.0.zip
07aa196518b786bb784ab224d6300e70fcb0f35a98180ecdc4a672f0e160728f  v1.25.0.zip
a8dd045466d74c0244efc35c464579a7e032dd92b0217b71596535d165de4f07  v1.24.1.zip
e22ecac6b2370ce7bf7b0cff818e44cdaa7d0b9ea1f8d6d4f2e0aaef43ccf5d7  v1.24.0.zip
0bb546e7cfa2a4e7576d66d0622bffb0a8111f9669f6131471754a1b68f6f754  v1.23.2.zip
```
BTW, is it possible for users to require the latest version of …

libuv: add latest version with checksum

---

packages/l/luajit/port/xmake.lua

The `lua.hpp` include was missing from the package, this just adds it.

luajit - add lua.hpp to includefiles

---

packages/n/nana/xmake.lua

Adds version 1.7.4 of **nana** to the repository. Every version below 1.7.3 is not compatible with windows so I added this version. I had to write this code
```lua
if is_plat("windows") then
local file_name = path.join(os.curdir(), "source", "system", "split_string.cpp")
local contents = io.readfile(file_name)
contents = contents:gsub(" and ", " && ")
io.writefile(file_name, contents)
end
```
because a patch somehow didn't work.

Add nana 1.7.4

---

packages/l/libuv/xmake.lua

Here's a clean PR with the description scope linux syslink call instead of following what was already there with the windows links.

libuv: fix windows and linux links

---

packages/l/libcurl/xmake.lua

Currently libcurl is built with tests, which can be long and can break installation (7.64.1 doesn't build with msvc because of an empty test file).
This PR disables libcurl test building.

libcurl: Disable testing build

---

packages/b/blosc/xmake.lua
packages/g/glew/xmake.lua
packages/g/glfw/xmake.lua
packages/o/openvdb/xmake.lua
packages/p/pkg-config/xmake.lua

在windows上的处理比较麻烦，windows下动态链接库.dll文件会生成在/bin下，并且由于windows上没有linux -rpath这样的功能，必须把bin加入path才能在运行时搜索到这些dll文件。感觉如果cmake.install可以针对windows特殊处理下，然后主程序有一个类似windeployqt的应用，自动搜索用到的dll并复制到可执行文件的文件夹，编写包的时候一致性会好很多

add package openvdb & rewrite glfw package as well as fix some previous packages

---

packages/g/glm/xmake.lua

- 非semantic-versioning，暂取后三位为版本号
- 由于是header-only的库，直接支持全平台（以及未来可能的平台），就没在on_install里面限定平台了

add package glm

---

packages/l/libcurl/xmake.lua

I just ran into an issue with libcurl where it was lacking ws2_32 link on Windows, this fixes it.

libcurl: Link to ws2_32 on Windows

---

packages/s/sol2/xmake.lua

In the case of Lua, it's not uncommon to ship a custom Lua library (to update the langage a bit for example), but sol2 forces the lua dependency, this adds an option to disable the default lua shipping.

Sol2: Add includes_lua option to be able to ship a custom Lua library

---

packages/s/sfml/xmake.lua

If the graphics module is disabled, like this:
```lua
add_requires("sfml", {configs={graphics = false}})
```
the installation check will fail. This PR updates it to check the system library, as it's always included.

Fix SFML check (check only system module as other can be disabled)

---

packages/v/vulkan-headers/xmake.lua

Now the Vulkan-Headers version name is vx.x.xxx, update to it.
And the newer version is v1.2.162
log: change pacages/v/vulkan-headers

Update Vulkan-Headers version and regular version name

---

packages/e/eabase/xmake.lua

EABase is a small set of header files that define platform-independent data types and platform feature macros.
And it is depending on EASTL which is widely used in game developing
log: Add file package/e/eastl/xmake.lua to support package eabase

feat: Add package EABase

---

packages/v/volk/xmake.lua

volk xmake get two on_install function, delete unused function.
log: fix packages/v/volk/xmake.lua

fix: volk xmake file get two on_install funciton

---

packages/e/eastl/xmake.lua

EASTL stands for Electronic Arts Standard Template Library.
Add xmake file to support package
log: Add file packages/e/eastl/xmake.lua

feat: Add package eastl

---

packages/l/libsdl/xmake.lua

This fixes the test of **libsdl**. ```SDL_MAIN_HANDLED``` has been added as a define. Previously there was the following line
```lua
local configs = package:is_plat("windows") and {ldflags = "/SUBSYSTEM:CONSOLE"}
```
Is this required in some way? On my Windows PC it runs fine without it.

Fix test of libsdl

---

packages/l/libcurl/xmake.lua

libcurl currently cannot use SSL on Windows (so no HTTPS), this enables it.

libcurl: Enable schannel on Windows

---

packages/s/sol2/xmake.lua

sol2 test will fail if includes_lua is set to false, even though it would be valid to use it in a application like this:
```lua
add_requires("sol2", {config = {includes_lua = false}})
-- This is the lua library, patched by the user and bundled with the application as a static library
target("custom_lua")
set_kind("static")
add_files("src/custom_lua/*.c")
-- This is the application
target("app")
set_kind("binary")
add_files("src/app/*.cpp")
add_deps("custom_lua")
add_packages("sol2")
```

Sol2 Disable test if includes_lua is set to false

---

packages/l/libsdl/xmake.lua

This pull request adds the latest SDL2 version at the time, which is v2.0.14
I don't know why the MacOS CI fails, maybe it needs a bit of investigation, or maybe this version of SDL2 doesn't work on MacOS (but it seems pretty unlikely) 🤷

Add SDL2 latest version (2.0.14)

---

packages/t/tclap/xmake.lua

This commit adds tclap, a templatized C++ library for parsing commandline arguments.
I'm not sure if `-DBUILD_DOC=false` really disable documentation building since I don't have doxygen installed on my machine.
I don't know how to patch the CMakeLists.txt file, but it would be good to avoid useless computation by building examples.
I have tested it and added python3 as a dependency (I don't know if this information is relevant but here it is: I've got python 3.9.2 installed on my machine, the latest in the repo is 3.8.5, and so xmake downloaded python 3.8.5) because it is required to run the tests.
I don't know, maybe we don't want the tests to run, and in this case, we could later patch the CMakeLists.txt file by removing the following lines:
```
add_subdirectory(docs) …
```

Add tclap package

---

packages/l/libusb/xmake.lua

With add_extsources, xmake will first try to find pkgconfig::libusb before falling back on pkgconfig::libusb-1.0.
The problem here is that pkgconfig::libusb is the old libusb library (0.1), not the one referred by this package.
Using on_fetch fixes this (as it's called before xmake tries to find it by name).
Maybe this should be extended with other packages managers (would `return find_package("libusb-1.0")` work?)

libusb: Use on_fetch instead of add_extsources to fix a priority issue

---

packages/i/imgui/xmake.lua

**Problem**
ImGui has a way to override some things with custom config, which is completely inaccessible from xmake. There is no way to override assertions with custom ones for example cause of this.
**Solution**
Provide new config option with which user can set user config. Downside is that this cannot be properly tested against, so tests have to pass when this option is specified. ~~I added some warning print to let user know that there may be some issues when using library in this way inside on_test.~~
Would be great if there was something like this, as we would like to override ImGui assertions in our project and we cannot currently. This solution was tested on it .
As ImGui is compiled as static library, we can just define how assertion function looks and define IM_ASSERT inside …

Add ability to set user_config for ImGui at user's own risk

---

packages/l/luajit/port/xmake.lua

The `buildvm` should be compiled with the `LUAJIT_ENABLE_LUA52COMPAT` define to enable all Lua 5.2 extensions in LuaJIT.
Very basic test:
```lua
print('rawlen is ' .. type(rawlen))
print('table.pack is ' .. type(table.pack))
print('table.unpack is ' .. type(table.unpack))
```
Correct output without extensions:
```
rawlen is nil
table.pack is nil
table.unpack is nil
```
Correct output with enabled extensions:
```
rawlen is function
table.pack is function
table.unpack is function
```
Current output is incorrect:
```
rawlen is nil
table.pack is nil
table.unpack is function
```

fix luajit lua 5.2 compat

---

packages/b/bzip2/xmake.lua
packages/c/cairo/port/cairo-features.h.in
packages/c/cairo/port/xmake.lua
packages/c/cairo/xmake.lua
packages/e/entt/xmake.lua
packages/e/expat/xmake.lua
packages/h/houdini/xmake.lua
packages/i/itk/xmake.lua
packages/o/opencv/xmake.lua
packages/o/openjpeg/xmake.lua
packages/o/openssl/xmake.lua
packages/r/range-v3/xmake.lua
packages/t/tmxparser/xmake.lua
packages/v/vtk/xmake.lua

openjpeg出了个问题：当前xmake处理cmake包用的是先安装到`$(buildir)/install`下面然后复制各文件到安装目录下面。但有些包的cmake importfile也就是xxxTarget.cmake里面用的是绝对路径，这就会导致这些库一旦移动位置cmake文件的指示就不准了，其他依赖这个库的cmake库就会报错，openjpeg就是此例。
xmake是否考虑换一种形式处理：直接安装到指定位置，然后删除多余的文件夹（不需要copy的文件夹）？这样对cmake的库更加友好

add itk, vtk and range-v3

---

packages/m/miniz/xmake.lua
packages/p/python/xmake.lua

windows上通过xrepo安装python后pip不能直接使用，而是需要先升级
```
> xrepo env shell
[repo] > pip -V
Fatal error in launcher: Unable to create process using '"c:\users\ruki\appdata\local\programs\python\python38\python.exe"  "C:\Users\xq114\AppData\Local\.xmake\packages\p\python\3.8.5\bc33c7694ee44a7a872afa7b5dcfbac2\Scripts\pip.exe" -V': The system cannot find the file specified.
[repo] > python -m pip install -U pip
...
[repo] > pip -V
pip 21.0.1 from ...
```

add miniz and fix python

---

README.md
README_zh.md

This removes the broken links in the README.md
#372 
It also makes it clearer which links link to which documentation (In the english README).
#373 
I replaced one link to the xmake homepage by a more relevant link to the section about remote packages(In the english README). I can't do this for the chinese version as I don't speak chinese.

Rework documentation links 

---

packages/f/filament/xmake.lua
packages/n/nanoflann/xmake.lua
packages/t/tinyfiledialogs/xmake.lua

filament在macos/linux上要求用新版的clang编译，不支持gcc; 是否可以在package描述里面指定toolchain，或者判断当前toolchain是否符合要求？
filament暂不支持shared library，见https://github.com/google/filament/issues/1075

add nanoflann, tinyfiledialogs and filament

---

packages/l/libmpdclient/xmake.lua

This fixes an issue I encountered where the `version.h` header wasn't 
being installed due to it being generated at build time, and then
removes the `version.h.in` file that isn't needed.

update libmpdclient package

---

packages/l/libsdl/xmake.lua
packages/l/libsdl_gfx/xmake.lua
packages/l/libsdl_image/xmake.lua
packages/l/libsdl_mixer/xmake.lua
packages/l/libsdl_net/xmake.lua
packages/l/libsdl_ttf/xmake.lua

libsdl_gfx, libsdl_image, libsdl_mixer, libsdl_net and libsdl_ttf had the same issue libsdl had, .dll were copied to the wrong folder which causes issue when using `xmake run` on Windows

Fix libsdl_* .dll installation and run

---

packages/x/xcb-proto/xmake.lua

xcb-proto is broken with Python 3.9:
```
Failed to load the xcbgen Python package!
Make sure that xcb/proto installed it on your Python path.
If not, you will need to create a .pth file or define $PYTHONPATH
to extend the path.
Refer to the README file in xcb/proto for more info.
```
this has been fixed by 1.14.1

Update xcb-proto to 1.14.1 (fixes installation with Python 3.9)

---

packages/g/gflags/xmake.lua
packages/g/glog/xmake.lua
packages/l/libtiff/xmake.lua
packages/o/opencv/xmake.lua
packages/r/re2/xmake.lua
packages/v/vcglib/xmake.lua

opencv里面的links目前是在on_install里面加的（相当于自动探测）
```
-- scanning for links
for _, f in ipairs(os.files(path.join(instdir, linkdir, "*.lib"))) do
package:add("links", path.basename(f))
end
```
但有时候`add_packages("opencv")`会漏掉一些链接（opencv内部的libpng、libtiff等），不知道是为什么

update re2, glog and improve opencv

---

packages/c/catch2/xmake.lua
packages/e/expected/xmake.lua
packages/f/function_ref/xmake.lua
packages/h/hopscotch-map/xmake.lua
packages/s/sol2/xmake.lua
packages/t/tl_expected/xmake.lua
packages/t/tl_function_ref/xmake.lua

Made by the same guy that made the `expected` package, maybe we should name them tl_expected and tl_function_ref as they're common names.

Add function_ref and add headeronly flag on some libs

---

packages/g/gtest/xmake.lua

Configuration options have been added to decide whether or not `gtest_main` should be linked against.
For consistency, a similar option was added for the `gmock` target.
Example usage with C++ 20:
```lua
-- use master for C++ 20 support (see https://github.com/google/googletest/issues/2914)
add_requires("gtest master", {configs = {main = true, gmock = true}})
target("my_test")
set_languages("cxx20")
set_kind("binary")
add_files("my_test.cpp")
add_packages("gtest")
if is_plat("windows") then
-- fixes "LINK : fatal error LNK1561: entry point must be defined"
add_ldflags("/subsystem:console")
end
```
Fixes #475.

Add `gtest_main` and configs to `gtest`

---

packages/f/fx-gltf/xmake.lua

[fx-gltf] is a simpler and more efficient glTF loader than [tinygltf].
It's a header only library, so the installation simply copies the single header to the installation directory.
Because [fx-gltf] claims to be compatible with both C++14 and C++17, both are tested in `on_test` with `package:check_cxxsnippets`.
[fx-gltf]: https://github.com/jessey-git/fx-gltf
[tinygltf]: https://github.com/syoyo/tinygltf

Add `fx-gltf` package

---

packages/l/luajit/xmake.lua

Forgot to forward the new `gc64` option added in #510 to `port/xmake.lua`.

fix luajit gc64 option

---

packages/e/expat/xmake.lua
packages/p/pcre/xmake.lua
packages/s/sqlite3/xmake.lua

sqlite3测试的时候装的仍然是3.35.0+400而不是最新的3.36.0+000，有点奇怪

update pcre, expat and sqlite3

---

packages/o/openssl/xmake.lua

I had this issue with the openssl package building on Windows where xmake would not install strawberry-perl because it did find the perl.exe included in GitForWindows.
However, since it wasn't in the path, the installation would fail.
I tried to fix this using
```lua
local perl_dep = package:dep("strawberry-perl")
if perl_dep:is_system() then
local perl_program = perl_dep:fetch()
os.vrunv(perl_program.program, args)
else
os.vrunv("perl", args)
end
```
but this failed with this message:
```
Configuring OpenSSL version 1.1.1k (0x101010bfL) for VC-WIN64A
Using os-specific seed configuration
******************************************************************************
This perl implementation doesn't produce Windows like paths (with backward
slash directory separators).  Please use an …
```

Fix openssl building on Windows with GitForWindows perl

---

packages/i/imgui/xmake.lua
packages/l/libigl/xmake.lua

关于imgui的修改：
1. imgui默认不带backend，这使得用户想开发imgui程序必须自己处理backend问题。在xmake-repo中加入imgui最简单、使用最广泛的glfw+opengl3 backend作为选项可以大大降低imgui程序上手难度。
2. libigl使用imgui/imgui.h的方式引入imgui头文件，因此改进了imgui的目录结构，同时兼容之前的程序。

improve libigl+imgui workflow

---

packages/i/imgui/xmake.lua

This PR adds the latest stable docking branch version of imgui
to its xmake.lua package. It is up-to-date with the main one.
See: ocornut/imgui#4424
The extra code in the on_load function matches all the versions
containing '-docker' in their name and removes the precompiled
archive url, thus avoiding an obvious curl failure.
This allows to reduce CI build time by avoiding requesting
an HTTP 404 resource.

Add docking branch version to imgui package

---

packages/c/chipmunk2d/patches/7.0.3/android.patch
packages/c/chipmunk2d/xmake.lua

See https://github.com/DigitalPulseSoftware/NazaraEngine/issues/347
Compilation is failing on recent Linux distributions because `sys/sysctl.h` has been removed, this fixes it.
Also I noticed that the GitHub uses `Chipmunk-7.0.3` and not 7.0.3 as a tag, so git clone + checkout basically failed.

Chipmunk fixes

---

.github/workflows/archlinux.yml
.github/workflows/fedora.yml
packages/a/abseil/xmake.lua
packages/i/itk/xmake.lua
packages/m/magnum/xmake.lua
packages/v/vtk/patches/9.0.3/limits.patch
packages/v/vtk/xmake.lua

os.tmpdir()返回的是“临时文件存放的目录”而不是“临时目录”，因此用在buildir里不合适（多个包安装会引发冲突），这里修改了一些误用

fix some os.tmpdir misusing

---

packages/l/libsdl_gfx/xmake.lua
packages/l/libsdl_image/xmake.lua
packages/l/libsdl_mixer/xmake.lua
packages/l/libsdl_net/xmake.lua
packages/l/libsdl_ttf/xmake.lua

All libsdl_xx packages (and libsdl itself) can be included by omitting the SDL2 folder, like this:
```cpp
#include <SDL2_gfxPrimitives.h>
#include <SDL_image.h>
#include <SDL_mixer.h>
#include <SDL_net.h>
#include <SDL_ttf.h>
```
This is not possible with xmake packages, I fixed that by adding include dirs

Add includedirs for libsdl_xx

---

packages/c/ca-certificates/xmake.lua
packages/g/gn/xmake.lua
packages/o/openh264/xmake.lua
packages/p/python/xmake.lua
packages/p/python2/xmake.lua

之前python经常遇到的ssl错误都是xmake安装的openssl缺少cert文件导致的，只要加上cert文件就可以了

add cacert and openh264

---

packages/s/spirv-headers/xmake.lua
packages/s/spirv-tools/xmake.lua
packages/v/vulkan-headers/xmake.lua
packages/v/vulkan-hpp/xmake.lua
packages/v/vulkan-loader/xmake.lua
packages/v/vulkan-tools/xmake.lua
packages/v/vulkan-validationlayers/xmake.lua

Updated:
* `vulkan-headers` to sdk 1.2.198
* `vulkan-hpp` to sdk 1.2.198
* `vulkan-loader` to sdk 1.2.198
* `vulkan-tools` to sdk 1.2.198
* `vulkan-validationlayers` to sdk 1.2.198

update vulkan packages to 1.2.198

---

packages/o/openmp/xmake.lua

这里仍有一些问题：
1. 有的老编译器不支持openmp，这时应该报错找不到openmp，on_fetch不应该直接返回true
2. 只有apple clang才需要额外链接libomp，llvm clang即使在macos上也不需要链接libomp。应该区分这两种编译器，cmake中可以用`if(AppleClang) ...`来区分，xmake中也应该有类似的机制

improve openmp

---

packages/v/vulkan-hpp/xmake.lua

To build vulkan-hpp the VulkanHppGenerator needs to build for the host system. With this change xmake will temporarily switch the platform to the host to use cmake and then switch back.

Add mingw support to vulkan-hpp

---

packages/a/assimp/xmake.lua

It looks like Assimp requires advapi32: https://github.com/DigitalPulseSoftware/NazaraEngine/runs/4652831084?check_suite_focus=true#step:9:707 on Windows
https://github.com/assimp/assimp/blob/6693e7e08c7f12c9d569ab6baef44ec176734fae/code/CMakeLists.txt#L1256
Not sure why CI didn't fail

Assimp: add advapi32 syslink

---

packages/l/libunwind/xmake.lua

The original description is copied from `libunistring`. This PR fixes this.

libunwind: fix description, use official home page.

---

packages/g/gflags/xmake.lua

`gflags` by default adds registry file under `$HOME/.cmake` during install, which should be avoided when using Xrepo.
I've several questions related to `gflags` and `glog` pacakge, which I'd like to contribute further PRs but need guidance.
1. Is there any specific reason to use `mt=false` as default? I personally prefer to enable multi-thread by default for `gflags`, and this is also the default in vcpkg's `gflags` portfile.
2. Can I make `gflags` and `glog` packages to support "cross" platform? I wish for this because I want to specify different compilers when using xrepo-cmake. I can do this in my private repo, but would like to contribute if there's no problems for this.

gflags: disable register cmake user package registry.

---

packages/h/hiredis/patches/v1.0.2/cmake.patch
packages/h/hiredis/xmake.lua

The hiredis `CMakeLists.txt` does not provide option to build static or shared library. They are always built together.
The `Makefile` provides `dynamic`, `static` target, but seems to work only on Unix-like systems.
So I choose to use cmake in this PR.

add hiredis

---

packages/h/hiredis/patches/v1.0.2/cmake.patch
packages/h/hiredis/xmake.lua

By installing cmake module to common `lib/cmake/hiredis` dir, xrepo-cmake can use this package easier.

hiredis: install cmake module to lib/cmake/hiredis.

---

packages/p/python/xmake.lua
packages/u/unicorn/xmake.lua

add unicorn

---

packages/l/libunwind/xmake.lua

libunwind package on Arch Linux depends on `xz` and `zlib`.
I'm not sure whether minidebuginfo and zlibdebuginfo is widely used. To keep the package behaves the same as before, these two options are disable by default.

libunwind: add version v1.6.2, new options: minidebuginfo, zlibdebuginfo

---

packages/g/gflags/xmake.lua

gflags 默认开启多线程支持。
xmake.lua 中有这么一段：
```lua
if is_plat("windows", "mingw") then
add_syslinks("shlwapi")
elseif is_plat("linux") then
add_syslinks("pthread")
end
```
其实应该只有 `mt=true` 的才需要加上，不过我没找到怎样控制仅在 `mt=false` 时加上 syslink。试过用 `has_config`，但 `xrepo  install` 报 `has_config` 是 nil 不能用。

gflags: config mt=true as default.

---

packages/l/librdkafka/xmake.lua

librdkaka 在 cross 编译时遇到了奇怪的[编译错误](https://github.com/cyfdecyf/xmake-repo/runs/5354139942?check_suite_focus=true)，所以没有打开 cross。
因为 android 编译能成功，看了下 librdkafka 打包相关代码中有 arch arm64，应该支持 arm，不确定我遇到的错误是否跟 toolchain 设置有关。

librdkafka: add more platforms.

---

packages/p/pcre2/xmake.lua

我自己的 fork 中发现 iphoneos action 打开 jit 编译失败。搜到了苹果自己使用的 [pcre2 changelog](https://opensource.apple.com/source/pcre/pcre-12/pcre/ChangeLog.auto.html)，里面提到 `JIT is now supported on jailbroken iOS devices`，之后再没有关于 iOS JIT compilation 的消息，所以先 disable 掉。
另外移除了 autoconf 编译的代码，统一用 cmake。

pcre2: support all platforms.

---

packages/r/re2/xmake.lua

原先 linux platform 编译没有加上 `-fPIC`，在编译 arrow 时无法用于创建动态库。
这样改完也支持所有 platform。

re2: use cmake for all platforms.

---

packages/f/flex/xmake.lua

只有 MinGW 不支持。编译时 configure 脚本会寻找 `sys/wait.h`，但 mingw 没有这个头文件。

flex: add more platforms.

---

packages/d/doctest/xmake.lua

The doctest repo has been moved to doctest/doctest. This PR does also add the appropriate links.

Add doctest 2.4.8 and links to new repo

---

packages/g/gsl/xmake.lua
packages/m/microsoft-gsl/xmake.lua

实际上大部分时候gsl指gnu-gsl，而非microsoft-gsl，这里重名的处理不太好。为了保持兼容，还是把gsl重定向到microsoft-gsl

rename gsl to microsoft-gsl

---

packages/l/libomp/xmake.lua
packages/t/tbb/patches/2021.5.0/i386.patch
packages/t/tbb/xmake.lua

https://github.com/xmake-io/xmake-repo/runs/5571547803?check_suite_focus=true
看起来libomp 13开始要求必须先安装LLVM 13，不太好解决，暂时先回退了

fix some packages

---

packages/z/zstd/xmake.lua

1.5.2 中的汇编代码编译方式参考了 zstd 源码中 [`meson.bulid`](https://github.com/facebook/zstd/blob/v1.5.2/build/meson/lib/meson.build#L48-L55) 的做法。
对 xmake 的用法不熟悉，如果有更好的写法请反馈。

zstd: version 1.5.2

---

packages/q/qt5lib/xmake.lua

I noticed I introduced an error in qt5lib on macOS, the frameworks wasn't registered anymore:
<https://github.com/DigitalPulseSoftware/NazaraEngine/runs/5612712167?check_suite_focus=true#step:8:21376>

Fix qt5lib for macOS

---

packages/t/turbobase64/patches/2022.02.21/header.patch
packages/t/turbobase64/port/CMakeLists.txt
packages/t/turbobase64/port/cmake/turbobase64-config.cmake.in
packages/t/turbobase64/xmake.lua

turbobase64 最初版本的 cmake 代码来自 ClickHouse，vcpkg 里用的也是那个版本。
我适配了最新的 turbobase64 代码，发了 PR 等了一段时间还未接受，就先单独把 cmake 相关文件拷贝过来了。

add turbobase64

---

packages/z/zstd/xmake.lua

pkgconfig 文件缺少 version 信息导致不可使用，libcurl 依然无法安装 #1074 #1077

zstd: add version for pkgconfig file.

---

packages/b/brotli/port/xmake.lua
packages/b/brotli/xmake.lua

pkgconfig 文件缺少 version 信息导致不可使用，libcurl 依然无法安装 #1074 #1079

brotli: add version for pkgconfig file.

---

packages/l/librdkafka/xmake.lua

最初写的时候对每个依赖包添加了 syslinks。按 #1071 的建议，这个是不应该添加的，而且添加后会导致启用 ssl 时 `on_test` 失败。
第二个 commit 是因为用 `rg 'add_configs.*ssl'` 看了下，整个 xmake-repo 中 openssl config 名字用 `ssl` 的只有 libwebsockets, cpp-httplib, mariadb-connector-c 这三个。librdkafka 当时写的时候应该是从哪个拷贝过来的。
如果不希望做此修改，我 force push 去掉这个修改。

librdkafka: remove unnecessary syslinks.

---

packages/n/nlohmann_json/xmake.lua

nlohmann_json is written in vanilla C++11. It compiles with gcc-4.8 which don't support -std=c++14 option.

nlohmann_json: use c++11 for on_test.

---

packages/l/libevent/xmake.lua

`DEVENT__LIBRARY_TYPE` defaults to `BOTH`, so the original version build both static and dynamic lib.

libevent: fix build for shared or static lib.

---

packages/a/arrow/xmake.lua

The current `arrow` package contains a definition with a duplicated D.

fix(packages/a/arrow): typo in ARROW_BUILD_SHARED

---

packages/l/librdkafka/xmake.lua

没有这个 patch 时，若开启 lz4 支持，`find_package(RdKafka)` 无法找到 librdkafka 安装目录下的 `FindLz4.cmake` 文件。

librdkafka: patch for installed cmake config files.

---

packages/l/librdkafka/xmake.lua

Restore `CMAKE_MODULE_PATH` after the fix.

librdkafka: better fix for find lz4 fix.

---

packages/c/cuda/xmake.lua

在带on_fetch的package里面应该多加一些log，这样在fetch失败的时候更容易解决问题。反面例子见 https://github.com/xmake-io/xmake/issues/2257

improve cuda logging

---

packages/f/freeglut/xmake.lua

freeglut上游更改了所有release的tag，原来的url已经404了， 此处修复

fix freeglut

---

packages/s/sentry-native/xmake.lua

Order of libs was wrong when autodetected, also added a backend selector

Improve sentry-native linux support

---

packages/a/arrow/xmake.lua

It is not clear to me where the `config` parameter comes from.

update(packages/a/arrow): remove configs for thrift dep

---

packages/a/assimp/patches/5.2.4/fix_x86_windows_build.patch
packages/a/assimp/xmake.lua

Since assimp compiles with -Werror, a GCC update breaks the compilation.
See https://github.com/assimp/assimp/issues/4433

Assimp: Fix compilation with GCC 12 and update to v5.2.4

---

packages/l/libsdl_gfx/xmake.lua

When VS 2019 isn't installed (and thus toolset v142 isn't available), package compilation fails. This fixes that (but isn't very future proof, I think this should be handled by `package.tools.msbuild`)

libsdl_gfx: Fix compilation with only VS 2022

---

packages/u/utfcpp/xmake.lua

cl compiler requires utf-8 flag.

fix utfcpp test failed on windows

---

packages/q/quickjspp/xmake.lua
packages/r/redex/xmake.lua

add quickjspp library 

---

packages/g/glfw/xmake.lua
packages/l/libcurl/patches/7.84.0/sched.patch
packages/l/libcurl/versions.lua
packages/l/libcurl/xmake.lua

python从系统里找的时候，不需要安装openssl/zlib/libffi等，直接调用就可以，因此修改了依赖逻辑

update libcurl and glfw

---

packages/b/brotli/xmake.lua

@waruqi on ubuntu, the executable `brotli` is in its own package separated from the rest (`libbrotli-dev`). I do not know how the xmake repository handles this.

Add extsources to brotli

---

packages/f/ffmpeg/xmake.lua

**Question**: ffmpeg dev files on ubuntu are splitted into multiple packages. So instead of installing one pacman package named `ffmpeg` (on msys2, brew, arch linux for example) that will contain the executable and all the dev files, you need to install multiple packages on ubuntu:
```
ffmpeg, libavcodec-dev, libavdevice-dev, libavfilter-dev, libavformat-dev, libavutil-dev, libpostproc-dev, libswresample-dev, libswscale-dev
```
That means it should be possible, using `add_extsources`, to require multiple packages to be installed to consider the dependency ffmpeg installed, something that could look like:
```lua
add_extsources("pacman::ffmpeg", {"apt::ffmpeg", "apt::libavcodec-dev", "apt::libavdevice-dev", "apt::libavfilter-dev", "apt::libavfilter-dev", "apt::libavformat-dev", …
```

Add extsources to ffmpeg

---

packages/l/libomp/xmake.lua

https://github.com/xmake-io/xmake/issues/2318
由于brew没提供libomp的pkg-config文件，只能借助直接查找了。不过我这没有mac环境，需要在mac环境下测试一下能不能用

improve libomp

---

packages/f/freetype/xmake.lua

The makefile can't find brotli when installed by xmake: <https://github.com/NazaraEngine/xmake-repo/runs/7544869084?check_suite_focus=true#step:5:1026>
I think it's same to use cmake to build it (as this is what vcpkg does)

Update freetype and use cmake on Linux/macosx

---

packages/c/cmdline/xmake.lua

add https://github.com/tanakh/cmdline

add cmdline

---

packages/c/catch2/xmake.lua

Fixes this issue: https://stackoverflow.com/questions/66227246/catch2-undefined-reference-to-catchstringmaker

Catch2: Add cxx17 option and build using C++17 by default

---

packages/k/kiwisolver/xmake.lua

sha256 hash wasn't correct which made xmake clone the repository

kiwisolver: Fix sha256 hash

---

packages/l/libdeflate/xmake.lua
packages/l/libtiff/xmake.lua
packages/n/nlohmann_json/xmake.lua
packages/s/simage/xmake.lua
packages/s/sqlite3/xmake.lua

libtiff 本身可以不依赖第三方库编译，而在启用zlib等第三方库时会导致其他依赖tiff的cmake包找不到zlib等，从而导致链接错误。这里参考vcpkg，默认禁用了这些第三方codec，加入了选项控制

update libtiff, libdeflate, nlohmann_json, simage

---

packages/r/rapidjson/xmake.lua

Update rapidjson to git master branch.
The latest rapidjson release(v1.1.0) was published in 2016 which should not be used any more since it has not been updated for over 5 years. The v1.1.0 release is still using `std::iterator` which is marked as deprecated in C++17. Thus, the master branch should be used instead.

update rapidjson to master branch

---

packages/d/doxygen/xmake.lua

这里我一直觉得很奇怪：其他平台上既然没有预编译功能，package:is_built()应该直接返回true才对，直接把dep都放在on_load里也不会有问题。
另外一点就是何时使用预编译包？我试了下在windows上运行xrepo install doxygen，并没有安装预编译包而是从源码编译，而且还编译失败了。理论上对binary类型应该都用预编译才对。

improve doxygen

---

packages/o/opencv/xmake.lua

This allows successful compilation in debug modes (for windows targets)

Fixed "debug=true" and "vs_runtime="MTd" builds

---

packages/i/imgui/xmake.lua

Use the merge master commit after release v1.88
https://github.com/ocornut/imgui/commit/9cd9c2eff99877a3f10a7f9c2a3a5b9c15ea36c6

Update imgui docking

---

packages/p/parallel-hashmap/xmake.lua

cmake options `PHMAP_BUILD_TESTS` and `PHMAP_BUILD_EXAMPLES` already exist in version 1.33. They are turned on by default in version 1.35, thus need to explicitly disable them.

parallel-hashmap: add version 1.34 and 1.35

---

packages/l/libzip/xmake.lua

Fixes unresolved symbol when using libzip on Windows
```
[ 88%]: linking.release odttomd.exe
error: zip.lib(zip_source_file_win32_named.obj) : error LNK2019: symbole externe non résolu __imp_GetSecurityInfo référencé dans la fonction _zip_win32_named_op_create_temp_output
build\windows\x64\release\odttomd.exe : fatal error LNK1120: 1 externes non résolus`
```

libzip: Add Advapi32 syslink

---

packages/p/python/xmake.lua

Adds support python package support for bsd
Currently it says
note: the following packages are unsupported on bsd/x86_64:
-> python 3.9.13
but its supported according to the documentation

Support bsd in python

---

scripts/test.lua

libtorch 目前设置 `shared=true` 为默认值，对这种情况现有的 CI 脚本无法执行 static build。
这个改动通过总是设置 `shared` 配置来解决这个问题。
另一个问题，执行 `xrepo install --kind=static libtorch` 触发的依然是 shared build。是否 `--kind=static` 的处理有类似的问题，即假设包的 `shared` 选项默认为 `static` 因此没有再强制指定？

fix: static build for packages with shared=true as default.

---

packages/l/libtorch/patches/1.12.1/clang.patch
packages/l/libtorch/patches/1.12.1/vs2022.patch
packages/l/libtorch/xmake.lua

Besides adding libtorch version v1.12.1, this PR makes it possible to build libtorch as static library. 
Some notes:
1. This PR keeps building libtorch as shared library by default, as disscussed in https://github.com/xmake-io/xmake-repo/pull/1502
2. ~~Static link to libtorch has some issues I haven't solved.~~
- ~~Neither `OMP_NUM_THREADS` nor `MKL_NUM_THREADS` can control number of threads used when using static link.
These two environment variables work fine when using shared link.~~
- ~~The end result is worse performance because using too many threads on servers with many cores.~~
- When link to MKL, avoid use of TBB. Mixing TBB and OpenMP is not a good idea. libtorch's cmake file comments that `USE_TBB` is deprecated.
3. According to our simple benchmark, using Intel MKL is faster …

libtorch v1.12.1, support static linking

---

packages/a/aws-sdk-cpp/xmake.lua

* By default, all SDKS are built, if only AWS S3 is required, then set build_only="s3", with multiple SDKS separated by commas.
------
* 默认情况下，构建所有的SDK，如果只需要AWS S3，那么设置build_only=" s3 "，多个SDK用逗号分隔。

add aws-sdk-cpp

---

packages/r/redis-plus-plus/xmake.lua

* This is a C++ client library for Redis. It's based on [hiredis](https://github.com/redis/hiredis), and is compatible with C++ 17, C++ 14, and C++ 11.
* 这是一个用于Redis的c++客户端库。它基于hiredis，兼容c++ 17、c++ 14和c++ 11。

Add redis-plus-plus

---

packages/t/tesseract/xmake.lua

When I updated tesseract, I tought that is was the commit hash in `add_versions` but it's not, so I fix this mistake

Fix Tesseract checksum

---

packages/c/commonlibsse-ng/port/xmake.lua
packages/c/commonlibsse-ng/rules/plugin.lua

Doesn't build with `clang-cl` yet due to a known problem causing warnings, such as `argument unused during compilation: '-external:W0'`. Will look into further in the future.
Also removed a few redundant/unnecessary flags.

[commonlibsse-ng] Improve `clang-cl` support

---

packages/b/boost/xmake.lua

Allow to control whether turn on `lto` for the package via `add_requireconfg`

Support to control `lto` flag in boost

---

packages/p/pdcurses/xmake.lua

原 `pdcurses` 包描述只支持 SDL2 端口，现添加 Windows Console 端口。
另：配置 `port = "wincon"` 只在 Windows 下支持，我不清楚这里是否应该做一些限制（比如不在 Windows 下加载的时候报错？）

Add Windows Console port for pdcurses

---

packages/p/pdcursesmod/xmake.lua

添加了 `pdcurses` 的一个改进版分支。
- 基本和 `pdcurses` 相同，修改了源码 URL；同样支持 `sdl2` 和 `wincon` 两个后端；
- 增加了 `utf8` 选项，默认开启；为此增加了一些依赖关系处理。

Add PDCursesMod

---

packages/p/python/xmake.lua

Python can be installed without pip/setuptools/wheel that python package otherwise guarantees.
This PR requires https://github.com/xmake-io/xmake/pull/3059 to work

Python: Dismiss local python installation if pip is not present

---

packages/p/python/xmake.lua

Starting with Python 3.10, Python requires OpenSSL 1.1.1 or newer.
See https://peps.python.org/pep-0644/

Python 3.10 requires OpenSSL 1.1.1

---

packages/c/catch2/xmake.lua

Fix version names for catch2.
It previously only worked when downloading the archive but failed to checkout the commit when falling back to cloning the repo.

fix catch2

---

packages/i/imgui/port/xmake.lua

这两行应该是原作者 https://github.com/xmake-io/xmake-repo/pull/1217 从下面freetype选项copy paste的时候忘记删除了，导致设置 wchar32=true 时候必须同时设置 freetype=true才能编译

fix wchar32 option for imgui

---

packages/d/dynareadout/xmake.lua

This PR also removes all old versions, because those are not compatible with the new xmake.lua code anymore.

Add dynareadout version 22.12

---

packages/w/wayland/xmake.lua

Fixes this:
```
/usr/bin/tar -xf wayland-1.19.0.tar.xz -C source.tmp
downloading resource(protocols: https://wayland.freedesktop.org/releases/wayland-protocols-1.21.tar.xz) to wayland-1.19.0 ..
/usr/bin/tar -xf /home/lynix/.xmake/cache/packages/2212/w/wayland/1.19.0/resources/protocols/wayland-protocols-1.21.tar.xz -C /home/lynix/.xmake/cache/packages/2212/w/wayland/1.19.0/resources/protocols/wayland-protocols-1.21.tar.xz.dir.tmp
meson -Ddocumentation=false -Dc_link_args=-lm --libdir=lib --prefix=/home/lynix/.xmake/packages/w/wayland/1.19.0/d4813a414d234036bb8606e1e07c959d --libdir=lib -Dbuildtype=release -Db_staticpic=true build_d4813a41
The Meson build system
Version: 0.62.1
Source dir: /home/lynix/.xmake/cache/packages/2212/w/wayland/1.19.0/source
Build dir: …
```

Fix wayland installation if pkg-config is not installed

---

packages/c/catch2/xmake.lua

Adds catch2 versions 2.13.10, 3.1.1, 3.2.0, and 3.2.1

Add latest releases to catch2 package

---

packages/o/out_ptr/xmake.lua

> `ztd.out_ptr` is a simple parameter wrapper for output pointers.
https://github.com/soasis/out_ptr

Add out_ptr

---

packages/s/scnlib/xmake.lua

`scnlib` is up to v1.1.2: https://github.com/eliaskosunen/scnlib/releases

Update `scnlib` to v1.1.2

---

packages/r/redis-plus-plus/xmake.lua

redis-plus-plus already supports Windows. (https://github.com/sewenew/redis-plus-plus#windows-support)
It has released v1.3.7 last week.

Port redis-plus-plus to Windows && Dump to 1.3.7

---

packages/w/workflow/xmake.lua

Since workflow adds xmake.lua to compile the project, it can greatly simplify the writing of our xrepo xmake.lua
https://github.com/xmake-io/xmake-repo/pull/1713

Use workflow xmake.lua to compile

---

packages/c/catch2/xmake.lua

Add custom main option for Catch2. 
If set main == "catch2", it will link Catch2Main, which is the default option for catch2. 
If set main == "custom", it will link your custom main.

add custom main option for Catch2

---

packages/s/stb/xmake.lua

pacman::stb and apt::libstb-dev put stb includes in a stb/ folder. this commit updates stb to match this but keeps retrocompatibility using includedirs

stb: move includes to stb folder

---

packages/l/libiconv/xmake.lua

macosx support for libiconv is removed in #1784 , re-add the macosx support

libiconv: re-add support for macosx

---

packages/i/indicators/xmake.lua

fix indicators include error

---

packages/w/wayland/xmake.lua

Should fix this:
```
=> download https://wayland.freedesktop.org/releases/wayland-1.19.0.tar.xz .. ok
downloading resource(protocols: https://wayland.freedesktop.org/releases/wayland-protocols-1.21.tar.xz) to wayland-1.19.0 ..
/usr/bin/curl -SL -A "Xmake/2.7.6+HEAD.7fd2cec12 (Linux;5.15.0-1031-azure) curl/7.81.0" https://wayland.freedesktop.org/releases/wayland-protocols-1.21.tar.xz -o /home/runner/work/NazaraEngine/xmake-global/.xmake/cache/packages/2302/w/wayland/1.19.0/resources/protocols/wayland-protocols-1.21.tar.xz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  114k  100  114k    0     0   236k      0 --:--:-- --:--:-- --:--:-- …
```

wayland: ensure ninja >= 1.8.2 is present

---

packages/d/discord/xmake.lua
packages/t/tinyxml2/xmake.lua
packages/x/x264/xmake.lua

package:configs 改为 package:config
[configs ](https://github.com/xmake-io/xmake/blob/master/xmake/core/package/package.lua#L1276) 返回是个元组而不是 config 的别名，导致有些库的 shared 开关永远是开的，外部无法切换到静态。

fix: package:configs change to package:config

---

packages/i/imgui/port/xmake.lua
packages/i/imgui/xmake.lua

- Added versions `v1.89.3` and `v1.89.3-docking`.
- Added backend options `dx9`, `dx10`, `dx11`, `dx12`, `glfw`, `opengl2`, `opengl3`, `sdlrenderer`, `vulkan`, and `win32`.
- For compatibility reasons the option `sdl2` will still enable the `sdlrenderer` backend.
- Deprecated `glfw_opengl3`, `glfw_vulkan`, and `sdl2_opengl3`.
- For compatibility reasons these options will still work. If you are using these please move to the new options.
This is a project that builds all of the available backends using imgui examples along with a copy of this pr as a custom repo:
[imgui-test.zip](https://github.com/xmake-io/xmake-repo/files/10829705/imgui-test.zip)
```
xmake && xmake run
```

[imgui] Update and improve package

---

packages/i/imgui/xmake.lua

Commit sha previously pointed to master branch tag 1.89.3 instead of equivalent commit in docking branch.

Fix ImGui v1.89.3-docking version

---

packages/g/gdextension/xmake.lua
packages/g/godotcpp4/xmake.lua

This is the Godot 4 version of `godotcpp`, but since the API changed drastically I created a new package for it. I don't use `import("package.tools.scons")` directly, because this version of godotcpp uses different arguments. The different arguments such as `plat`, `arch`, `use_mingw` and so on are not universal to scons. They are unique to godot. Therefore the build function for scons needs to be reworked accordingly.
In the mean time I am just using `import("lib.detect.find_tool")` directly and then generate the arguments manually.

Add GDExtension library

---

packages/c/cppast/xmake.lua
packages/d/debug_assert/xmake.lua
packages/t/type_safe/xmake.lua

I'm trying to add [cppast](https://github.com/foonathan/cppast) which is based on LLVM, I couldn't make the llvm package work on Windows (as a library) so I'm working on Linux, however I'm not sure how to link properly LLVM (I only need clang-cpp, clang and clangAST libraries for this example)

Add cppast, debug_assert and type_safe (WIP)

---

packages/i/imgui/port/xmake.lua
packages/i/imgui/xmake.lua

Adds versions 1.89.4, 1.89.4-docking, 1.89.5, and 1.89.5-docking.
Also adds a `sdl2_no_renderer` option that enables the sdl2 backend but not sdlrenderer. The existing `sdl2` option enables both because of backwards compatibility, so it pulls in extra files when sdlrenderer is not needed.

Improve imgui

---

packages/l/libevent/xmake.lua

修复#2031 中的MSVC编译debug版libevent报错"fatal error C1041"的问题。

Fixes compilation of libevent under debug mode MSVC

---

packages/u/units/xmake.lua

```
% xmake l scripts/test.lua -v -D units
{ 
"units" 
}
create test ...
[+]: xmake.lua
[+]: src/main.cpp
[+]: .gitignore
create ok!
/private/var/folders/gw/ygflm0814f14b9r3fdt77dyh0000gn/T/.xmake501/230506/xmake-repo/test
add local repository(local-repo): /Users/user/OSS/xmake-repo ok!
local repositories:
local-repo /Users/user/OSS/xmake-repo 
global repositories:
build-artifacts https://gitlab.com/xmake-mirror/build-artifacts.git main 
xmake-repo https://gitlab.com/tboox/xmake-repo.git master 
builtin-repo /Users/user/.local/share/xmake/repository 
4 repositories were found!
checking for platform ... macosx
checking for architecture ... arm64
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... no
checking for SDK version of Xcode for …
```

Add nholthaus/units v2.3.3

---

packages/l/libffi/xmake.lua
packages/p/python/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/2065
python is installed to /lib64 which is unwanted.

fix python

---

packages/i/icu4c/xmake.lua

- Adds version 73.1.
- Fixes links on Windows (they match those on mingw but not macOS/Linux).

Update icu4c, fix links on Windows

---

packages/v/vtk/rules/autoinit.lua
packages/v/vtk/xmake.lua

这里vtk的parse还挺复杂的，最好可以在全局执行而不是对每个target都执行一遍，现在的实现非常冗余。然而xmake并没有全局on_config_global接口，只能先这么实现了

add rule vtk.autoinit

---

packages/c/commonlibsse-ng/port/xmake.lua
packages/c/commonlibsse-ng/xmake.lua

Forgot to add this when I fixed `spdlog`'s `fmt_external` option. This is necessary because the library always included external fmt

[commonlibsse-ng] Set `fmt_external` for spdlog

---

packages/o/openssl/xmake.lua

这里命令行的cflags会覆盖makefile中的  会出现编译错误  前面的config中使用buildenv已经设置了makefile  所以去掉这里的makeconfigs

fix openssl

---

packages/y/yy-thunks/rules/link.lua
packages/y/yy-thunks/xmake.lua

Fix DecodePointer, EncodePointer,RegDeleteKeyEx etc. APIs not found in Windows XP RTM.
usage:
```lua
add_requires("yy-thunks")
add_packages("yy-thunks")
add_rules("@yy-thunks/xp")
-- add_rules("@yy-thunks/2k")
-- add_rules("@yy-thunks/vista")
```

add yy-thunks

---

packages/s/s7/xmake.lua

Here is the error message: https://github.com/XmacsLabs/mogan/actions/runs/5098606818/jobs/9165841420
```
/usr/bin/ld: /home/runner/.xmake/packages/s/s7/2023.04.13/2a08221166c344c1b133bf3ba8e5b21c/lib/libs7.a(s7.c.o): in function `load_shared_object':
s7.c:(.text+0xab780): undefined reference to `dlopen'
/usr/bin/ld: s7.c:(.text+0xab805): undefined reference to `dlsym'
/usr/bin/ld: s7.c:(.text+0xab8e1): undefined reference to `dlerror'
/usr/bin/ld: s7.c:(.text+0xabacf): undefined reference to `dlerror'
/usr/bin/ld: s7.c:(.text+0xabafe): undefined reference to `dlclose'
```
Tested via:
```
xmake l scripts/test.lua  -vD  s7
```
And the above command line does not on loongarch, we need:
https://github.com/xmake-io/xmake/pull/3783

S7: fix link on_test

---

packages/l/libffi/xmake.lua
packages/n/ncurses/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/2129
https://github.com/libffi/libffi/issues/127 这里应该是加--disable-multi-os-directory让libffi装到lib 文件夹更好，而不是xmake中加入lib64兼容

fix libffi with correct flag

---

packages/q/quill/xmake.lua

- Fix link error: https://github.com/xmake-io/xmake-repo/pull/2019
- Update version.

quill: fix link

---

packages/i/imgui/port/xmake.lua
packages/i/imgui/xmake.lua

- Add version `v1.89.6` and `v1.89.6-docking`
- Include misc cpp helpers like `imgui_stdlib`
- Change `sdlrenderer` to `sdlrenderer2` to coincide with upcoming `sdl3` and `sdlrenderer3` support

[imgui] Add `v1.89.6`, include misc cpp

---

packages/m/microsoft-detours/xmake.lua

Detours is a software package for monitoring and instrumenting API calls on Windows. It is distributed in source code form.

microsoft-detours: add package

---

packages/b/bzip2/xmake.lua

otherwise it fails since it cannot copy bzip binaries

bzip2: Don't build tools on wasm

---

packages/t/trantor/patches/1.5.8/fix-win-off_t.patch
packages/t/trantor/xmake.lua

in lib trantor, on windows off_t is defined with long, not longlong, it will be error when off_t is more than 4GB .
patch it.

update trantor patch for win(off_t)

---

packages/b/benchmark/xmake.lua

We need c++14 to compile the test of 1.8.0.

Update c++ standard

---

packages/e/entt/xmake.lua

New version of entt detected (package version: v3.11.1, last github version: v3.12.1)

Auto-update entt to v3.12.1

---

packages/o/ordered_map/xmake.lua

New version of ordered_map detected (package version: v1.0.0, last github version: v1.1.0)

Auto-update ordered_map to v1.1.0

---

packages/s/sfml/xmake.lua

For some reason, the dependencies of the audio module of SFML were only taken into account when targetting Linux. 
I just moved the dependency code out of the if statement.
Just tested it in local and it works.

Fixing sfml package for mingw

---

packages/l/libpng/xmake.lua

New version of libpng detected (package version: v1.6.37, last github version: v1.7.0beta89)

Auto-update libpng to v1.6.40

---

packages/c/catch2/xmake.lua

When building in debug mode, the linker fails to find Catch2 symbols because the link name is incorrect.

Fix Catch2 link error when debug is enabled

---

packages/s/sentry-native/xmake.lua

New version of sentry-native detected (package version: 0.6.3, last github version: 0.6.4)

Auto-update sentry-native to 0.6.4

---

packages/e/entt/xmake.lua

New version of entt detected (package version: v3.12.1, last github version: v3.12.2)

Auto-update entt to v3.12.2

---

packages/l/libpng/xmake.lua

I put the .tar.gz hash when fixing the version in #2222

libpng: Fix v1.6.40 hash

---

packages/h/hopscotch-map/xmake.lua

New version of hopscotch-map detected (package version: v2.3.0, last github version: v2.3.1)

Auto-update hopscotch-map to v2.3.1

---

packages/b/boost/xmake.lua

When building boost statically without specifying an msvc version in the config file, b2 will call the environment setup for msvc and activate the latest toolset. This works for the default case, but when you have multiple toolsets installed and aren't using the latest one, the libraries will fail because link.exe will not match the user's environment.
An example error when compiling program_options with msvc 14.1 from Visual Studio 2022 build tools:
```
error LNK2019: unresolved external symbol "__std_count_trivial_1" referenced in function...
```

Fix link error when building boost with a different toolset

---

packages/b/boost/xmake.lua

1. boost.python has 2 sub-library python and numpy, but the numpy is missing here.
2. the library name is added `-d` as suffix when turned on debug, so we need to append `-d` at the end of linkname if `package:debug()`

Fix missing `numpy` when linking boost.python and linking wrong library name when turn debug on.

---

packages/b/benchmark/xmake.lua

The function `DoNotOptimize` was deprecated in this scope since 1.8.0 and the url was changed.

benchmark: update url and test

---

packages/e/emscripten/xmake.lua

I got the env variables from executing `emsdk activate latest`. It displays this on Windows:
```
Resolving SDK alias 'latest' to '3.1.42'
Resolving SDK version '3.1.42' to 'sdk-releases-9d73bf4bd5b5c9ce6e51be0ed5ce6599fcb28e9e-64bit'
Setting the following tools as active:
node-16.20.0-64bit
python-3.9.2-nuget-64bit
java-8.152-64bit
releases-9d73bf4bd5b5c9ce6e51be0ed5ce6599fcb28e9e-64bit
Adding directories to PATH:
PATH += D:\compiler\emsdk
PATH += D:\compiler\emsdk\upstream\emscripten
Setting environment variables:
PATH = D:\compiler\emsdk;D:\compiler\emsdk\upstream\emscripten;...
EMSDK_NODE = D:\compiler\emsdk\node\16.20.0_64bit\bin\node.exe
EMSDK_PYTHON = D:\compiler\emsdk\python\3.9.2-nuget_64bit\python.exe
JAVA_HOME = D:\compiler\emsdk\java\8.152_64bit
```
And on Linux:
```
Setting up …
```

Add emscripten

---

packages/l/libpng/xmake.lua

Currently, I'm using mirrors.ustc.edu.cn, and later, we can find a better way, let the user always choose the fastest mirrors.
eg.
```
add_ubuntu_archives("pool/main/libp/libpng1.6/libpng1.6_$(version).orig.tar.gz")
```
I think it would be a good way to improve locality of the package archives.

libpng: add_urls from deb-src

---

packages/s/sentry-native/xmake.lua

New version of sentry-native detected (package version: 0.6.4, last github version: 0.6.5)

Auto-update sentry-native to 0.6.5

---

packages/p/protobuf-cpp/xmake.lua

debug模式下会有lib会有后缀d 导致links里没有lib

protobuf-cpp: fix debug mode link

---

packages/d/dr_mp3/xmake.lua

New version of dr_mp3 detected (package version: 0.6.36, last github version: 0.6.37)

Auto-update dr_mp3 to 0.6.37

---

packages/s/spdlog/xmake.lua

New version of spdlog detected (package version: v1.11.0, last github version: v1.12.0)

Auto-update spdlog to v1.12.0

---

packages/l/libwebp/patches/0001-fix-dll-export.patch
packages/l/libwebp/xmake.lua

Fixes linker error when libwebpmux is enabled
```
LINK : fatal error LNK1181: cannot open input file 'Release\webp.lib' [C:\Users\calebmagiya\AppData\Local\.xmake\cache\packages\2307\l\libw
ebp\v1.2.4\source\build_62a8009b\webpdemux.vcxproj]
```
------

Fix libwebp dll exports

---

packages/c/cimg/xmake.lua

Add [`cimg`](https://github.com/greyclab/cimg) header-only image processing package. This one has a strange versioning quirk.

[cimg] Add package

---

packages/t/toml++/xmake.lua

Compilation fails for Clang-Cl toolchain when it tries to test the package due to failure on implicit conversion to toml::table.
I simply replaced it with auto in the test snippet which seems to resolve this issue.
Log from error: (same happens for latest release version)
```
=> install toml++ master .. failed
C:\Users\andre\AppData\Local\Temp\.xmake\230715\_04EC0038C54040C282A93F45FB54B05B.cpp(18,29): error: conversion from 'toml::parse_result' to 'toml::table' is ambiguous
toml::table tbl = toml::parse(some_toml);
^     ~~~~~~~~~~~~~~~~~~~~~~
C:\Users\andre\AppData\Local\.xmake\packages\t\toml++\master\91dd63516d5447209d6768a849484ffd\include\toml++/impl/parse_result.h(203,18): note: candidate function
/* implicit */ operator toml::table&() noexcept
^ …
```

Fix TOML++ compilation with Clang-Cl toolchain

---

packages/l/libsamplerate/xmake.lua

Adds new libsamplerate package. Included is latest 0.2.2 version, tested with Clang-Cl and MSVC (both from VS2022) on Windows 11 22H2. Did not test other platforms. Tested both static and shared builds and also debug and release modes.

Add libsamplerate 0.2.2

---

packages/d/dbus/xmake.lua

With the default system bus setting, initialization fails on some systems with "Socket name too long"/"No such file or directory".

Update D-Bus, add system bus config

---

packages/x/xxhash/xmake.lua

New version of xxhash detected (package version: v0.8.1, last github version: v0.8.2)

Auto-update xxhash to v0.8.2

---

packages/q/qtifw/xmake.lua

aqt may failed on Windows because py7zr failed to decompress.
a follow-up pr of https://github.com/xmake-io/xmake-repo/pull/2342

qtifw: use 7z on windows but not on sub_host msys

---

packages/f/flecs/xmake.lua

New version of flecs detected (package version: v3.2.4, last github version: v3.2.5)

Auto-update flecs to v3.2.5

---

packages/f/fmt/xmake.lua

New version of fmt detected (package version: 10.0.0, last github version: 10.1.0)

Auto-update fmt to 10.1.0

---

packages/u/utfcpp/xmake.lua

New version of utfcpp detected (package version: v3.2.3, last github version: v3.2.4)

Auto-update utfcpp to v3.2.4

---

packages/w/wgpu-native/xmake.lua

I tried to support debug builds as well but I couldn't because artifacts are processed before the "load" script is.
```lua
on_load("windows|x64", "windows|x86", "linux|x86_64", "macosx|x86_64", "macosx|arm64", function (package)
local suffix = package:debug() and "debug" or "release"
if package:is_plat("windows") and package:is_arch("x64") then
package:add("url", "https://github.com/gfx-rs/wgpu-native/releases/download/$(version)/wgpu-windows-x86_64-" .. suffix .. ".zip", {version = function(version) return version:gsub("%+", ".") end})
if package:debug() then
package:add("version", "v0.17.0+2", "ddcaa0542149be17e47e3f85f8df637814318668d03c341cfddcd3ccd9269f28")
else
package:add("version", "v0.17.0+2", "1b8ae05bb7626e037ab7088f9f11fc8bb8341a32800d33857c09ff2fb1b3893f")
end
elseif …
```

Add wgpu-native

---

packages/s/soloud/patches/miniaudio_v11.patch
packages/s/soloud/xmake.lua

Added a package for the soloud sound library. This works on macos, windows, and linux.
It uses a miniaudio backend. It requires an older miniaudio version than the one in xrepo. The internal miniaudio symbols should be properly hidden. In the future, other backends could be supported.

added a package for soloud

---

packages/r/rsm-binary-io/xmake.lua

- Add version `2.0.6`
- Remove unnecessary `kind` config, this is already passed by xmake
- Remove args from test function

[rsm-binary-io] Add `2.0.6`

---

packages/f/fmt/patches/10.1.0/utf8.patch
packages/f/fmt/xmake.lua

fix fmt parsing error on windows

---

packages/z/zlib/xmake.lua

New version of zlib detected (package version: v1.2.13, last github version: v1.3)

Auto-update zlib to v1.3

---

packages/f/flecs/xmake.lua

New version of flecs detected (package version: v3.2.5, last github version: v3.2.6)

Auto-update flecs to v3.2.6

---

packages/k/kiwisolver/xmake.lua

New version of kiwisolver detected (package version: 1.4.4, last github version: 1.4.5)

Auto-update kiwisolver to 1.4.5

---

packages/q/qr-code-generator-c/xmake.lua

"Unfortunately, the library is unsuitable for embedded microcontroller environments (e.g. Arduino) due to the use of the heavyweight STL std::vector class and dynamic memory allocation. The C port is the one specifically designed to support embedded environments." from https://www.nayuki.io/page/qr-code-generator-library#cpp

qr-code-generator-c: add package

---

packages/f/fmt/xmake.lua

New version of fmt detected (package version: 10.1.0, last github version: 10.1.1)

Auto-update fmt to 10.1.1

---

packages/b/brotli/xmake.lua

New version of brotli detected (package version: v1.0.9, last github version: v1.1.0)

Auto-update brotli to v1.1.0

---

packages/g/glew/port/xmake.lua

I was getting this error when trying to install glew on a debian machine without x11 installed with apt.
```
error: In file included from src/glew.c:55:
include/GL/glxew.h:98:10: fatal error: X11/Xlib.h: Aucun fichier ou dossier de ce type
98 | #include <X11/Xlib.h>
|          ^~~~~~~~~~~~
compilation terminated.

add missing x11 dependecies for glew

---

packages/f/flecs/xmake.lua

New version of flecs detected (package version: v3.2.6, last github version: v3.2.7)

Auto-update flecs to v3.2.7

---

packages/s/sfml/xmake.lua

I'm not sure why it passes the CI without it, but I have it failing in local

sfml: Add User32.lib syslinks on Windows

---

packages/m/mkl/xmake.lua

I'm not xmake expert so I simply added MKL version 2023.2.0 checksums and urls for all platforms.  Checksums were calculated on a windows machine with powershell command:
```
(Get-FileHash <file>).Hash.ToLower();
```
I verified that I could reproduce the checksums of older versions. 
Tests passed when I did `xmake l scripts/test.lua -v mkl` but I couldn't test directly in my project because I don't know how. 
Maybe @xq114 knows if I need to add anything else. I don't see anything in the MKL release notes that point to changes in the Link Line Advisor.

Update MKL to 2023.2.0

---

packages/u/utfcpp/xmake.lua

New version of utfcpp detected (package version: v3.2.4, last github version: v3.2.5)

Auto-update utfcpp to v3.2.5

---

packages/o/opencv/xmake.lua

在macos上编译opencv会出现CMAKE_SYSTEM_PROCESSOR未定义的问题，导致了编译失败

Fix bug when compiling opencv on macosx

---

packages/c/cppp-reiconv/xmake.lua

Name: cppp-reiconv
Version: v2.1.0
Homepage: https://github.com/cppp-project/cppp-reiconv
Description: A character set conversion library based on GNU LIBICONV.
License: LGPL-3

cppp-reiconv: New package.

---

packages/l/libcpuid/xmake.lua

New version of libcpuid detected (package version: v0.6.3, last github version: v0.6.4)

Auto-update libcpuid to v0.6.4

---

packages/f/flecs/xmake.lua

New version of flecs detected (package version: v3.2.7, last github version: v3.2.8)

Auto-update flecs to v3.2.8

---

packages/l/libcurl/versions.lua

https://www.zhihu.com/question/625527244 libcurl之前版本有严重漏洞，8.4.0才解决，这个是否需要加入提示？

add libcurl 8.4.0

---

packages/m/miniaudio/xmake.lua
packages/s/soloud/xmake.lua

It's an entitlements issue that is solved with a #define for miniaudio: <https://github.com/mackron/miniaudio/issues/203>
This also lets us simplify the soloud xmake.lua file somewhat, since it inherits the linker flags.

Fixed miniaudio on macos

---

packages/w/wayland-protocols/rules/wayland_protocols.lua

It seems that The `wayland.protocols` rule in package `wayland-protocols` didn't seem to work at all before. This PR fixes the rule and adds more options to the rule to provide more flexibility.
```lua
add_rules("@wayland-protocols/wayland.protocols", {
outputdir = "...",  -- Path for generated files, default is `path.join(target:autogendir(), "rules", "wayland.protocols")`
client = "...",     -- Path format for client protocol header files, default is `"%s.h"`, set to `false` to disable its generation
server = "...",     -- Path format for server protocol header files, default is `nil`
code = "...",       -- Path format for code files, default is `"%s.c"`
public = false,     -- Visibility for headers and symbols in generated code, can be `false` or `true`, default is `false`
})
```

wayland-protocols: Improve rule wayland.protocols

---

packages/w/wayland-protocols/xmake.lua

- Add `wayland-protocols/1.25~1.32`
- Add `apt::wayland-protocols`
- Add `-Dtests=false` to disable tests in `on_install`, speed up installation
- Remove unnecessary `-Ddefault_library=...`, because wayland-protocols only have some `.xml`s, no binary

wayland-protocols: Bump to 1.32

---

packages/u/utfcpp/xmake.lua

New version of utfcpp detected (package version: v4.0.0, last github version: v4.0.1)

Auto-update utfcpp to v4.0.1

---

packages/d/dr_mp3/xmake.lua

New version of dr_mp3 detected (package version: 0.6.37, last github version: 0.6.38)

Auto-update dr_mp3 to 0.6.38

---

packages/u/utfcpp/xmake.lua

New version of utfcpp detected (package version: v4.0.1, last github version: v4.0.2)

Auto-update utfcpp to v4.0.2

---

packages/g/gmssl/xmake.lua

GMSSL is using Windows Crypto API such as `CryptAcquireContext` ([here](https://github.com/guanzhi/GmSSL/blob/v3.1.0/src/rand_win.c#L32C1-L32C1)), and this API needs to link to library `Advapi32` ([msdoc](https://learn.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-cryptacquirecontexta#requirements)).
This patch fixes this missing `add_syslinks`.

Fix gmssl missing syslink

---

packages/d/drogon/xmake.lua

Add hiredis as an option to drogon. On systems with hiredis installed as a system library drogon will enable redis support but without the hiredis dependency fail to link.
Redis is now optional and if enabled with all the required dependency

drogon: fix redis build (#2819)

---

packages/f/fast_float/xmake.lua

New version of fast_float detected (package version: v5.2.0, last github version: v5.3.0)

Auto-update fast_float to v5.3.0

---

packages/s/sentry-native/xmake.lua

New version of sentry-native detected (package version: 0.6.6, last github version: 0.6.7)

Auto-update sentry-native to 0.6.7

---

packages/f/flecs/xmake.lua

New version of flecs detected (package version: v3.2.8, last github version: v3.2.9)

Auto-update flecs to v3.2.9

---

packages/j/joltphysics/xmake.lua

New version of joltphysics detected (package version: v4.0.0, last github version: v4.0.1)

Auto-update joltphysics to v4.0.1

---

packages/l/libtasn1/xmake.lua

`libtasn1` library provide some binary executables. The might be useful when building (e.g. `asn1Parser` can generate `.c` file from `.asn` definition file.).
With this patch, we can define rules to build `.asn` (something like `batchcmds:vexecv("asn1Parser" ...`)

Add PATH env when installing libtasn1

---

packages/i/ixwebsocket/xmake.lua

- The file 'ixwebsocket/IXSocketMbedTLS.cpp' had `errorMsg` commented out
- Fix windows TLS 
- Always add dep if TLS is enabled

ixwebsocket: fix TLS

---

packages/f/fast_float/xmake.lua

New version of fast_float detected (package version: v5.3.0, last github version: v6.0.0)

Auto-update fast_float to v6.0.0

---

packages/u/utfcpp/xmake.lua

New version of utfcpp detected (package version: v4.0.3, last github version: v4.0.4)

Auto-update utfcpp to v4.0.4

---

packages/l/libusb/xmake.lua

#2926 broke `#include "libusb.h"` which is used in samples by libusb and other libs depending on it

libusb: Fix include dirs

---

packages/a/alsa-lib/xmake.lua

Should fix
```
checkinfo: cannot runv(autoreconf --version), No such file or directory
checking for autoreconf ... no
error: @programdir/modules/package/tools/autoconf.lua:432: autoreconf not found!
stack traceback:
[C]: in function 'error'
[@programdir/core/base/os.lua:923]: in function 'raiselevel'
[@programdir/core/sandbox/modules/utils.lua:149]: in function 'assert'
[@programdir/modules/package/tools/autoconf.lua:432]: in function 'configure'
[@programdir/modules/package/tools/autoconf.lua:478]: in function 'build'
[@programdir/modules/package/tools/autoconf.lua:507]: in function 'install'
[...ke/repositories/xmake-repo/packages/a/alsa-lib/xmake.lua:27]: in function 'script'
[...dir/modules/private/action/require/impl/utils/filter.lua:125]: in function 'call' …
```

alsa-lib: Add autoconf dependencies

---

packages/f/flecs/xmake.lua

New version of flecs detected (package version: v3.2.9, last github version: v3.2.10)

Auto-update flecs to v3.2.10

---

packages/m/matio/xmake.lua

hdf5 cannot found if `packagedeps` is not set
https://github.com/xmake-io/xmake/issues/4519

Matio: Add `packagedeps` for hdf5

---

packages/a/alsa-lib/xmake.lua

This fixes the compilation of alsa-lib and libsndio on Linux when autoconf and m4 are not installed

alsa-lib: Add m4 dependency

---

packages/l/libgpiod/port/xmake.lua

add_deps("gpiod") does not work for target "gpiodcxx"
```
/usr/bin/ld: /home/admin/.xmake/packages/l/libgpiod/v2.0.1/157e18a575a14285a70fae64f41d3a6d/lib/libgpiodcxx.a(chip.cpp.o): in function `gpiod::(anonymous namespace)::open_chip(std::filesystem::__cxx11::path const&)':
chip.cpp:(.text+0x3c): undefined reference to `gpiod_chip_open'
/usr/bin/ld: /home/admin/.xmake/packages/l/libgpiod/v2.0.1/157e18a575a14285a70fae64f41d3a6d/lib/libgpiodcxx.a(chip.cpp.o): in function `gpiod::chip::path[abi:cxx11]() const':
chip.cpp:(.text+0x398): undefined reference to `gpiod_chip_get_path'
/usr/bin/ld: /home/admin/.xmake/packages/l/libgpiod/v2.0.1/157e18a575a14285a70fae64f41d3a6d/lib/libgpiodcxx.a(chip.cpp.o): in function `gpiod::chip::get_info() const':
chip.cpp:(.text+0x3f0): undefined reference to …
```

libgpiod: fix cxx bindings not having c links

---

packages/j/joltphysics/xmake.lua

New version of joltphysics detected (package version: v4.0.1, last github version: v4.0.2)

Auto-update joltphysics to v4.0.2

---

packages/c/concurrentqueue/xmake.lua

https://github.com/xmake-io/xmake-repo/commit/095e769f1f6db3aa501300ecbe8ad5fb4bb4c5d4 reworked concurrentqueue which no longer has `concurrentqueue/concurrentqueue.h` includes, this breaks compilation for existing project using it.

concurrentqueue: Restore concurrentqueue/concurrentqueue.h include

---

packages/c/catch2/xmake.lua

New version of catch2 detected (package version: v3.5.0, last github version: v3.5.1)

Auto-update catch2 to v3.5.1

---

packages/u/utfcpp/xmake.lua

New version of utfcpp detected (package version: v4.0.4, last github version: v4.0.5)

Auto-update utfcpp to v4.0.5

---

packages/f/fmt/xmake.lua

New version of fmt detected (package version: 10.1.1, last github version: 10.2.0)

Auto-update fmt to 10.2.0

---

packages/d/dr_flac/xmake.lua
packages/d/dr_mp3/xmake.lua
packages/d/dr_wav/xmake.lua

dr_libs has a miniaudio submodule which takes some time to clone for some reason, but it's used only for testing and is not required for the libs

dr_libs: Don't checkout submodules

---

packages/f/fmt/xmake.lua

New version of fmt detected (package version: 10.2.0, last github version: 10.2.1)

Auto-update fmt to 10.2.1

---

packages/s/sentry-native/xmake.lua

New version of sentry-native detected (package version: 0.6.7, last github version: 0.7.0)

Auto-update sentry-native to 0.7.0

---

packages/r/robin-map/xmake.lua

New version of robin-map detected (package version: v0.6.3, last github version: v1.2.1)

Auto-update robin-map to v1.2.1

---

.github/workflows/autoupdate.yml
scripts/autoupdate.lua

fix autoupdate

---

packages/m/md4qt/xmake.lua

New version of md4qt detected (package version: 2.1.0, last github version: 2.4.2)

Auto-update md4qt to 2.4.2

---

packages/g/glfw3webgpu/xmake.lua

New version of glfw3webgpu detected (package version: v1.0.1, last github version: v1.1.0)

Auto-update glfw3webgpu to v1.1.0

---

packages/r/rtaudio/xmake.lua

New version of rtaudio detected (package version: 6.0.0, last github version: 6.0.1)

Auto-update rtaudio to 6.0.1

---

packages/n/nghttp2/xmake.lua

New version of nghttp2 detected (package version: 1.46.0, last github version: 1.58.0)

Auto-update nghttp2 to 1.58.0

---

packages/i/imgui-file-dialog/xmake.lua

New version of imgui-file-dialog detected (package version: v0.6.5, last github version: v0.6.6)

Auto-update imgui-file-dialog to v0.6.6

---

packages/f/function2/xmake.lua

New version of function2 detected (package version: 4.2.3, last github version: 4.2.4)

Auto-update function2 to 4.2.4

---

packages/p/prvhash/xmake.lua

New version of prvhash detected (package version: 4.0, last github version: 4.3.2)

Auto-update prvhash to 4.3.2

---

packages/z/zfp/xmake.lua

New version of zfp detected (package version: 0.5.5, last github version: 1.0.1)

Auto-update zfp to 1.0.1

---

packages/c/cpp-semver/xmake.lua

New version of cpp-semver detected (package version: v0.3.1, last github version: v0.3.3)

Auto-update cpp-semver to v0.3.3

---

packages/l/libpng/xmake.lua

because it is unstable sometimes, the orig tar gz provided by debian might change over time.

libpng: remove ustc mirror

---

packages/a/aws-c-event-stream/xmake.lua

New version of aws-c-event-stream detected (package version: v0.3.2, last github version: v0.4.1)

Auto-update aws-c-event-stream to v0.4.1

---

packages/c/corrade/patches/2020.06/msvc.patch
packages/c/corrade/rules/resource.lua
packages/c/corrade/xmake.lua
packages/i/imgui/port/xmake.lua
packages/i/imgui/xmake.lua
packages/m/magnum-integration/xmake.lua
packages/m/magnum/patches/2020.06/msvc.patch
packages/m/magnum/xmake.lua
packages/m/meshoptimizer/xmake.lua

这里加了 corrade resource compilation 的 rule
问题：
1. corrade-rc 是 corrade 这个包带的代码生成器，用 path.join(target:pkg("corrade"):installdir(), "bin") 找路径是否合理？有没有更好的方案？
2. xmake 源码里的 rule 有的是 target:autogendir() ，有的是 target:autogenfile() ，这两个有什么区别？用哪一个更好？
3. 从 xmake-repo 为文件指定 rule 也是用 rule = "@corrade/resource" 这样的写法吗？能识别吗？
4. batchcmds:set_depcache 应该给什么参数？源码中有的是 set_depcache(objectfile) ，有的是 set_depcache(sourcefile_cx) ，这两个在什么情况下有区别呢？

add corrade resource compile rule

---

packages/i/ittapi/xmake.lua

New version of ittapi detected (package version: v3.24.4, last github version: v3.24.6)

Auto-update ittapi to v3.24.6

---

packages/b/blake3/xmake.lua

New version of blake3 detected (package version: 1.3.3, last github version: 1.5.0)

Auto-update blake3 to 1.5.0

---

packages/k/kokkos/xmake.lua

New version of kokkos detected (package version: 4.0.01, last github version: 4.2.00)

Auto-update kokkos to 4.2.00

---

packages/o/onednn/xmake.lua

New version of onednn detected (package version: v2.5.4, last github version: v3.3.4)

Auto-update onednn to v3.3.4

---

packages/m/mds/xmake.lua

1. add example: use Fraction in Eigen to show exact representation.
2. resolve template derivation conflicts on g++.

update mds from 1.1.0 to 1.1.1

---

packages/f/fast-cdr/xmake.lua

New version of fast-cdr detected (package version: v1.1.0, last github version: v2.1.3)

Auto-update fast-cdr to v2.1.3

---

packages/l/littlefs/xmake.lua

New version of littlefs detected (package version: v2.5.0, last github version: v2.8.2)

Auto-update littlefs to v2.8.2

---

packages/o/opencl-headers/xmake.lua

New version of opencl-headers detected (package version: v2021.06.30, last github version: v2023.12.14)

Auto-update opencl-headers to v2023.12.14

---

packages/y/yy-thunks/xmake.lua

New version of yy-thunks detected (package version: 1.0.7, last github version: 1.0.9)

Auto-update yy-thunks to 1.0.9

---

packages/n/nowide_standalone/xmake.lua

New version of nowide_standalone detected (package version: 11.2.0, last github version: 11.3.0)

Auto-update nowide_standalone to 11.3.0

---

packages/p/pahomqttcpp/xmake.lua

New version of pahomqttcpp detected (package version: v1.2.0, last github version: v1.3.2)

Auto-update pahomqttcpp to v1.3.2

---

packages/s/simpleini/xmake.lua

New version of simpleini detected (package version: v4.19, last github version: v4.22)

Auto-update simpleini to v4.22

---

packages/e/entt/xmake.lua

New version of entt detected (package version: v3.12.2, last github version: v3.13.0)

Auto-update entt to v3.13.0

---

packages/c/catch2/xmake.lua

New version of catch2 detected (package version: v3.5.1, last github version: v3.5.2)

Auto-update catch2 to v3.5.2

---

packages/m/mxml/xmake.lua

New version of mxml detected (package version: 3.3, last github version: 3.3.1)

Auto-update mxml to 3.3.1

---

packages/m/minizip-ng/xmake.lua

New version of minizip-ng detected (package version: 3.0.5, last github version: 4.0.4)

Auto-update minizip-ng to 4.0.4

---

packages/n/ndk/xmake.lua

Add latest  NDK LTS:
https://github.com/android/ndk/wiki
Package for darwin systems are not provided as zip anymore but as .dmg files.
I don't know how  to handle them, so skipping for now

Add NDK r26

---

packages/e/egl-headers/xmake.lua
packages/o/opengl-headers/xmake.lua

Note that I didn't try to match system packages because it seems complicated.
for example, Debian has libgl-dev which has:
- GL/gl.h
- GL/glcorearb.h
- GL/glext.h
- KHR/khrplatform.h
but GL/* and KHR headers are on two different repositories.
Maybe we could improve xmake extsources to be able to specify multiple required dependencies:
```lua
add_extsources({ "apt::libgl-dev", "apt::libegl-dev" })
```
meaning "both are required"

Add egl-headers and opengl-headers packages

---

packages/z/zlib/xmake.lua

New version of zlib detected (package version: v1.3, last github version: v1.3.1)

Auto-update zlib to v1.3.1

---

packages/r/rapidcsv/xmake.lua

New version of rapidcsv detected (package version: 8.50, last github version: 8.80)

Auto-update rapidcsv to 8.80

---

packages/l/libmspack/xmake.lua

New version of libmspack detected (package version: v0.10.1alpha, last github version: v1.11)

Auto-update libmspack to v1.11

---

packages/q/quickjs/xmake.lua

Adding two missing releases into xmake repo. I didn't update the windows one yet, because I noticed there's some patches on xmake mirror.

Add QuickJS versions 2023.12.09 and 2024.01.13

---

packages/p/plog/xmake.lua

New version of plog detected (package version: 1.1.9, last github version: 1.1.10)

Auto-update plog to 1.1.10

---

packages/g/gspell/xmake.lua
packages/g/gtk+3/xmake.lua

This was needed for wxwidgets non-system package to build on Linux Manjaro.
It's not a fully featured package, but it's in the same style as the gtk+3 package:
https://github.com/xmake-io/xmake-repo/blob/67a84e98bd284cc908c561fd4af77bf40be09161/packages/g/gtk%2B3/xmake.lua#L1-L13

add gspell package

---

packages/g/glpk/xmake.lua

This PR adds the GLPK package. "The GLPK (GNU Linear Programming Kit) package is intended for solving large-scale linear programming (LP), mixed integer programming (MIP), and other related problems."

add GLPK package

---

packages/z/zeromq/xmake.lua

New version of zeromq detected (package version: 4.3.4, last github version: 4.3.5)

Auto-update zeromq to 4.3.5

---

packages/r/redis-plus-plus/xmake.lua

New version of redis-plus-plus detected (package version: 1.3.9, last github version: 1.3.11)

Auto-update redis-plus-plus to 1.3.11

---

packages/p/prometheus-cpp/xmake.lua

New version of prometheus-cpp detected (package version: v1.0.0, last github version: v1.2.1)

Auto-update prometheus-cpp to v1.2.1

---

packages/b/b2/xmake.lua

New version of b2 detected (package version: 4.9.6, last github version: 5.0.0)

Auto-update b2 to 5.0.0

---

packages/g/g3log/xmake.lua

New version of g3log detected (package version: 2.3, last github version: 2.4)

Auto-update g3log to 2.4

---

packages/l/liboai/xmake.lua

New version of liboai detected (package version: 3.1.0, last github version: 3.2.1)

Auto-update liboai to 3.2.1

---

packages/n/ngtcp2/xmake.lua

New version of ngtcp2 detected (package version: 0.1.0, last github version: 1.2.0)

Auto-update ngtcp2 to 1.2.0

---

packages/l/libpng/xmake.lua

New version of libpng detected (package version: v1.6.40, last github version: v1.6.42)

Auto-update libpng to v1.6.42

---

packages/f/fast_float/xmake.lua

New version of fast_float detected (package version: v6.0.0, last github version: v6.1.0)

Auto-update fast_float to v6.1.0

---

packages/t/toml11/xmake.lua

New version of toml11 detected (package version: v3.7.0, last github version: v3.8.1)

Auto-update toml11 to v3.8.1

---

packages/g/gcem/xmake.lua

New version of gcem detected (package version: v1.16.0, last github version: v1.17.0)

Auto-update gcem to v1.17.0

---

packages/n/nameof/xmake.lua

New version of nameof detected (package version: 0.10.3, last github version: 0.10.4)

Auto-update nameof to 0.10.4

---

packages/l/libsais/xmake.lua

New version of libsais detected (package version: v2.7.1, last github version: v2.7.3)

Auto-update libsais to v2.7.3

---

packages/l/libtins/xmake.lua

New version of libtins detected (package version: v4.4, last github version: v4.5)

Auto-update libtins to v4.5

---

packages/s/s2n-tls/xmake.lua

New version of s2n-tls detected (package version: v1.3.51, last github version: v1.4.3)

Auto-update s2n-tls to v1.4.3

---

packages/g/gyp-next/xmake.lua

New version of gyp-next detected (package version: v0.11.0, last github version: v0.16.1)

Auto-update gyp-next to v0.16.1

---

packages/a/alembic/xmake.lua

New version of alembic detected (package version: 1.8.5, last github version: 1.8.6)

Auto-update alembic to 1.8.6

---

packages/e/entt/xmake.lua

New version of entt detected (package version: v3.13.0, last github version: v3.13.1)

Auto-update entt to v3.13.1

---

packages/h/hypre/xmake.lua

New version of hypre detected (package version: v2.23.0, last github version: v2.30.0)

Auto-update hypre to v2.30.0

---

packages/a/argparse/xmake.lua

New version of argparse detected (package version: 2.9, last github version: 3.0)

Auto-update argparse to 3.0

---

packages/m/meson/xmake.lua

New version of meson detected (package version: 1.3.0, last github version: 1.3.1)

Auto-update meson to 1.3.1

---

packages/l/libpng/xmake.lua

This fixes an error if zlib is found by xmake
```
pinging the host(github.com) ... 18 ms
pinging the host(download.savannah.gnu.org) ... 96 ms
pinging the host(downloads.sourceforge.net) ... 144 ms
pinging the host(gitlab.freedesktop.org) ... 65535 ms
/usr/bin/tar -xf v1.6.42.tar.gz -C source.tmp
./configure --enable-shared=no --enable-static=yes --with-pic --with-zlib-prefix=/home/lynix/.xmake/packages/z/zlib/v1.3.1/994fafa590ed48ac9f71516cc846d155 --prefix=/home/lynix/.xmake/packages/l/libpng/v1.6.42/dee67a21a7974735aa2865c15ac96579 --with-pic
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking …
```

libpng: Compile using xmake on all platforms

---

packages/l/libusb/xmake.lua

New version of libusb detected (package version: v1.0.26, last github version: v1.0.27)

Auto-update libusb to v1.0.27

---

packages/e/etl/xmake.lua

New version of etl detected (package version: 20.38.0, last github version: 20.38.10)

Auto-update etl to 20.38.10

---

packages/n/nativefiledialog-extended/xmake.lua

New version of nativefiledialog-extended detected (package version: v1.1.0, last github version: v1.1.1)

Auto-update nativefiledialog-extended to v1.1.1

---

packages/t/trompeloeil/xmake.lua

New version of trompeloeil detected (package version: v43, last github version: v47)

Auto-update trompeloeil to v47

---

packages/a/arduinojson/xmake.lua

New version of arduinojson detected (package version: v6.21.4, last github version: v7.0.3)

Auto-update arduinojson to v7.0.3

---

packages/r/rhash/xmake.lua

New version of rhash detected (package version: 1.4.2, last github version: 1.4.4)

Auto-update rhash to 1.4.4

---

packages/c/cglm/xmake.lua

New version of cglm detected (package version: v0.9.0, last github version: v0.9.2)

Auto-update cglm to v0.9.2

---

packages/f/flecs/xmake.lua

New version of flecs detected (package version: v3.2.10, last github version: v3.2.11)

Auto-update flecs to v3.2.11

---

packages/p/pegtl/xmake.lua

New version of pegtl detected (package version: 3.2.5, last github version: 3.2.7)

Auto-update pegtl to 3.2.7

---

packages/c/cgns/xmake.lua

New version of cgns detected (package version: v4.2.0, last github version: v4.4.0)

Auto-update cgns to v4.4.0

---

packages/x/xtl/xmake.lua

New version of xtl detected (package version: 0.7.6, last github version: 0.7.7)

Auto-update xtl to 0.7.7

---

packages/m/meson/xmake.lua

New version of meson detected (package version: 1.3.1, last github version: 1.3.2)

Auto-update meson to 1.3.2

---

packages/p/parallel-hashmap/xmake.lua

New version of parallel-hashmap detected (package version: 1.35, last github version: 1.37)

Auto-update parallel-hashmap to 1.37

---

packages/k/kokkos-kernels/xmake.lua

New version of kokkos-kernels detected (package version: 4.0.01, last github version: 4.2.01)

Auto-update kokkos-kernels to 4.2.01

---

packages/u/utf8proc/xmake.lua

New version of utf8proc detected (package version: v2.8.0, last github version: v2.9.0)

Auto-update utf8proc to v2.9.0

---

packages/b/bzip2/port/xmake.lua

In clang 15+ versions they made "-Wint-conversion" as an error:
https://www.redhat.com/zh/blog/new-warnings-and-errors-clang-15
```
bzlib.c:1431:12: warning: implicit declaration of function 'fdopen' [-Wimplicit-function-declaration]
1431 |       fp = fdopen(fd,mode2);
|            ^
bzlib.c:1431:10: warning: incompatible integer to pointer conversion assigning to 'FILE *' (aka 'struct _IO_FILE *') from 'int' [-Wint-conversion]
1431 |       fp = fdopen(fd,mode2);
bzip2.c:967:7: warning: incompatible integer to pointer conversion assigning to 'FILE *' (aka 'struct _IO_FILE *') from 'int' [-Wint-conversion]
967 |    fp = fdopen(fh, mode);
```

Fix bzip2 compilation on clang 15+

---

packages/c/cxxopts/xmake.lua

New version of cxxopts detected (package version: v3.1.1, last github version: v3.2.0)

Auto-update cxxopts to v3.2.0

---

packages/b/boost/xmake.lua

Fix boost package when toolchain is set to MinGW and its path contain spaces. It led to the following error:
`error: provided command '"C:/Program" "Files/mydevtools/MinGW-w64/bin/x86_64-w64-mingw32-g++"' not found`
See https://github.com/xmake-io/xmake/issues/4745.

Fix boost build with mingw toolchain which has spaces in its path.

---

packages/l/libpng/xmake.lua

New version of libpng detected (package version: v1.6.42, last github version: v1.6.43)

Auto-update libpng to v1.6.43

---

packages/t/tinygltf/xmake.lua

New version of tinygltf detected (package version: v2.8.13, last github version: v2.8.21)

Auto-update tinygltf to v2.8.21

---

packages/s/stx/xmake.lua

New version of stx detected (package version: v1.0.3, last github version: v1.0.5)

Auto-update stx to v1.0.5

---

packages/m/moltenvk/xmake.lua

Update moltenvk to 1.2.7

---

packages/k/kokkos/xmake.lua

New version of kokkos detected (package version: 4.2.00, last github version: 4.2.01)

Auto-update kokkos to 4.2.01

---

packages/n/nghttp2/xmake.lua

New version of nghttp2 detected (package version: 1.58.0, last github version: 1.59.0)

Auto-update nghttp2 to 1.59.0

---

packages/l/libsais/xmake.lua

New version of libsais detected (package version: v2.7.3, last github version: v2.7.5)

Auto-update libsais to v2.7.5

---

packages/a/ada/xmake.lua

New version of ada detected (package version: 2.4.1, last github version: 2.7.6)

Auto-update ada to 2.7.6

---

packages/m/mcut/patches/1.2.0/install.patch
packages/m/mcut/xmake.lua

New version of mcut detected (package version: v1.1.0, last github version: v1.2.0)

Auto-update mcut to v1.2.0

---

packages/l/libsigcplusplus/xmake.lua

New version of libsigcplusplus detected (package version: 3.4.0, last github version: 3.6.0)

Auto-update libsigcplusplus to 3.6.0

---

packages/n/nuklear/xmake.lua

New version of nuklear detected (package version: 4.10.5, last github version: 4.12.0)

Auto-update nuklear to 4.12.0

---

packages/l/libsvm/xmake.lua

New version of libsvm detected (package version: v325, last github version: v332)

Auto-update libsvm to v332

---

.github/workflows/macos_aarch64.yml
.github/workflows/macos_x64.yml
packages/o/openjdk/xmake.lua

------
------
This pull request accomplishes two main tasks:
1. It removes the non-LTS version of JDK 20 and adds direct support for JDK 17 and JDK 21 LTS versions, which can now be downloaded directly from Oracle.
2. It adds support for macOS ARM instances …

rework jdk toolchain 17 & 21

---

packages/o/openblas/xmake.lua

openblas: remove {system = true} and force to use `gfortran` if not find `openmp`

---

packages/d/dr_mp3/xmake.lua

New version of dr_mp3 detected (package version: 0.6.38, last github version: 0.6.39)

Auto-update dr_mp3 to 0.6.39

---

packages/c/catch2/xmake.lua

New version of catch2 detected (package version: v3.5.2, last github version: v3.5.3)

Auto-update catch2 to v3.5.3

---

packages/m/msgpack-cxx/xmake.lua

New version of msgpack-cxx detected (package version: nil, last github version: 6.1.0)

Auto-update msgpack-cxx to 6.1.0

---

packages/i/implot/xmake.lua

New version of implot detected (package version: nil, last github version: v0.16)

Auto-update implot to v0.16

---

packages/g/ghc_filesystem/xmake.lua

New version of ghc_filesystem detected (package version: nil, last github version: v1.5.14)

Auto-update ghc_filesystem to v1.5.14

---

packages/a/aws-c-common/xmake.lua

New version of aws-c-common detected (package version: nil, last github version: v0.9.13)

Auto-update aws-c-common to v0.9.13

---

packages/a/aws-checksums/xmake.lua

New version of aws-checksums detected (package version: nil, last github version: v0.1.18)

Auto-update aws-checksums to v0.1.18

---

packages/c/cli11/xmake.lua

New version of cli11 detected (package version: nil, last github version: v2.4.1)

Auto-update cli11 to v2.4.1

---

packages/m/miniaudio/xmake.lua

New version of miniaudio detected (package version: nil, last github version: 0.11.21)

Auto-update miniaudio to 0.11.21

---

packages/h/haclog/xmake.lua

New version of haclog detected (package version: nil, last github version: v0.1.6)

Auto-update haclog to v0.1.6

---

packages/b/b2/xmake.lua

New version of b2 detected (package version: nil, last github version: 5.0.1)

Auto-update b2 to 5.0.1

---

packages/d/dbg-macro/xmake.lua

New version of dbg-macro detected (package version: nil, last github version: v0.5.1)

Auto-update dbg-macro to v0.5.1

---

packages/p/pyincpp/xmake.lua

New version of pyincpp detected (package version: nil, last github version: v1.3.3)

Auto-update pyincpp to v1.3.3

---

packages/l/libassert/xmake.lua

New version of libassert detected (package version: nil, last github version: v1.2.2)

Auto-update libassert to v1.2.2

---

packages/l/lvgl/xmake.lua

New version of lvgl detected (package version: nil, last github version: v9.0.0)

Auto-update lvgl to v9.0.0

---

packages/f/fdk-aac/xmake.lua

New version of fdk-aac detected (package version: nil, last github version: 2.0.3)

Auto-update fdk-aac to 2.0.3

---

packages/l/libfabric/xmake.lua

New version of libfabric detected (package version: nil, last github version: 1.20.1)

Auto-update libfabric to 1.20.1

---

packages/a/aws-c-io/xmake.lua

New version of aws-c-io detected (package version: nil, last github version: v0.14.5)

Auto-update aws-c-io to v0.14.5

---

packages/c/c-blosc2/xmake.lua

New version of c-blosc2 detected (package version: nil, last github version: v2.13.2)

Auto-update c-blosc2 to v2.13.2

---

packages/c/cutlass/xmake.lua

New version of cutlass detected (package version: nil, last github version: v3.4.1)

Auto-update cutlass to v3.4.1

---

packages/c/coost/xmake.lua

New version of coost detected (package version: nil, last github version: v3.0.2)

Auto-update coost to v3.0.2

---

packages/m/md4qt/xmake.lua

New version of md4qt detected (package version: nil, last github version: 2.8.0)

Auto-update md4qt to 2.8.0

---

packages/p/partio/xmake.lua

New version of partio detected (package version: nil, last github version: v1.17.3)

Auto-update partio to v1.17.3

---

packages/l/ls-qpack/xmake.lua

New version of ls-qpack detected (package version: nil, last github version: v2.5.4)

Auto-update ls-qpack to v2.5.4

---

packages/q/quill/xmake.lua

New version of quill detected (package version: nil, last github version: 3.6.0)

Auto-update quill to 3.6.0

---

packages/p/pdfhummus/xmake.lua

New version of pdfhummus detected (package version: nil, last github version: v4.6.3)

Auto-update pdfhummus to v4.6.3

---

packages/e/effolkronium-random/xmake.lua

New version of effolkronium-random detected (package version: nil, last github version: v1.5.0)

Auto-update effolkronium-random to v1.5.0

---

packages/a/aws-c-event-stream/xmake.lua

New version of aws-c-event-stream detected (package version: nil, last github version: v0.4.2)

Auto-update aws-c-event-stream to v0.4.2

---

packages/y/yoga/xmake.lua

New version of yoga detected (package version: nil, last github version: v3.0.0)

Auto-update yoga to v3.0.0

---

packages/c/cgal/xmake.lua

New version of cgal detected (package version: nil, last github version: 5.6.1)

Auto-update cgal to 5.6.1

---

packages/s/sheenbidi/xmake.lua

New version of sheenbidi detected (package version: nil, last github version: v2.7)

Auto-update sheenbidi to v2.7

---

packages/h/hypre/xmake.lua

New version of hypre detected (package version: nil, last github version: v2.31.0)

Auto-update hypre to v2.31.0

---

packages/n/ngtcp2/xmake.lua

New version of ngtcp2 detected (package version: nil, last github version: 1.3.0)

Auto-update ngtcp2 to 1.3.0

---

packages/a/aws-c-io/xmake.lua

New version of aws-c-io detected (package version: nil, last github version: v0.14.6)

Auto-update aws-c-io to v0.14.6

---

packages/w/wasm-micro-runtime/patches/1.2.3/cmake.patch
packages/w/wasm-micro-runtime/patches/1.3.2/cmake.patch
packages/w/wasm-micro-runtime/patches/libc_uvwasi.patch
packages/w/wasm-micro-runtime/patches/ntapi.patch
packages/w/wasm-micro-runtime/xmake.lua

- Fix https://github.com/xmake-io/xmake-repo/issues/3380
- Fix static/shared build type (patch cmake)
- Support uvwasi on windows/linux/macosx (patch cmake)
- New version 1.3.2

wasm-micro-runtime: refractor build script

---

packages/e/easyloggingpp/xmake.lua

New version of easyloggingpp detected (package version: nil, last github version: v9.97.1)

Auto-update easyloggingpp to v9.97.1

---

packages/l/log4cplus/xmake.lua

New version of log4cplus detected (package version: nil, last github version: 2.1.1)

Auto-update log4cplus to 2.1.1

---

packages/s/ssp/xmake.lua

New version of ssp detected (package version: nil, last github version: v1.8.0)

Auto-update ssp to v1.8.0

---

packages/a/astc-encoder/xmake.lua

New version of astc-encoder detected (package version: nil, last github version: 4.7.0)

Auto-update astc-encoder to 4.7.0

---

packages/y/yoga/xmake.lua

New version of yoga detected (package version: nil, last github version: v3.0.2)

Auto-update yoga to v3.0.2

---

packages/o/openexr/xmake.lua

New version of openexr detected (package version: nil, last github version: v3.2.3)

Auto-update openexr to v3.2.3

---

packages/p/prometheus-cpp/xmake.lua

New version of prometheus-cpp detected (package version: nil, last github version: v1.2.4)

Auto-update prometheus-cpp to v1.2.4

---

packages/t/trantor/xmake.lua

New version of trantor detected (package version: nil, last github version: v1.5.17)

Auto-update trantor to v1.5.17

---

packages/s/scons/xmake.lua

New version of scons detected (package version: nil, last github version: 4.6.0)

Auto-update scons to 4.6.0

---

packages/s/stringzilla/xmake.lua

New version of stringzilla detected (package version: nil, last github version: v3.6.2)

Auto-update stringzilla to v3.6.2

---

packages/o/onnx/xmake.lua

New version of onnx detected (package version: nil, last github version: v1.15.0)

Auto-update onnx to v1.15.0

---

packages/i/imgui/port/xmake.lua
packages/i/imgui/xmake.lua

This is a similar problem to #1493. When using Clang on Windows with the Microsoft STL, imgui fails to install because it is set to compile with C++11 but some STL headers use C++14 features:
```
error: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\utility:162:22: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
162 | _NODISCARD constexpr auto&& _Tuple_get(tuple<_Types...>&& _Tuple) noexcept;
|                      ^
In file included from misc\cpp\imgui_stdlib.cpp:11:
In file included from misc\cpp\imgui_stdlib.h:12:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\string:10:
In file included from C:\Program Files\Microsoft Visual …
```

Fix Clang errors with imgui

---

packages/h/hlslpp/xmake.lua

New version of hlslpp detected (package version: nil, last github version: 3.4)

Auto-update hlslpp to 3.4

---

packages/c/c-ares/xmake.lua

New version of c-ares detected (package version: nil, last github version: 1.27.0)

Auto-update c-ares to 1.27.0

---

packages/d/directx-headers/xmake.lua

New version of directx-headers detected (package version: nil, last github version: v1.613.0)

Auto-update directx-headers to v1.613.0

---

packages/l/libsais/xmake.lua

New version of libsais detected (package version: nil, last github version: v2.8.0)

Auto-update libsais to v2.8.0

---

packages/s/samurai/xmake.lua

New version of samurai detected (package version: nil, last github version: v0.10.0)

Auto-update samurai to v0.10.0

---

packages/a/aws-c-sdkutils/xmake.lua

New version of aws-c-sdkutils detected (package version: nil, last github version: v0.1.15)

Auto-update aws-c-sdkutils to v0.1.15

---

packages/m/maddy/xmake.lua

New version of maddy detected (package version: nil, last github version: 1.3.0)

Auto-update maddy to 1.3.0

---

packages/l/libspng/xmake.lua

New version of libspng detected (package version: nil, last github version: v0.7.4)

Auto-update libspng to v0.7.4

---

packages/d/double-conversion/xmake.lua

New version of double-conversion detected (package version: nil, last github version: v3.3.0)

Auto-update double-conversion to v3.3.0

---

packages/n/ngtcp2/xmake.lua

New version of ngtcp2 detected (package version: nil, last github version: 1.4.0)

Auto-update ngtcp2 to 1.4.0

---

packages/g/gyp-next/xmake.lua

New version of gyp-next detected (package version: nil, last github version: v0.16.2)

Auto-update gyp-next to v0.16.2

---

packages/c/cpp-ipc/xmake.lua

New version of cpp-ipc detected (package version: nil, last github version: 1.3.0)

Auto-update cpp-ipc to 1.3.0

---

packages/u/unity_test/xmake.lua

New version of unity_test detected (package version: nil, last github version: v2.6.0)

Auto-update unity_test to v2.6.0

---

packages/l/libenvpp/xmake.lua

New version of libenvpp detected (package version: nil, last github version: v1.4.0)

Auto-update libenvpp to v1.4.0

---

packages/c/cppcheck/xmake.lua

New version of cppcheck detected (package version: nil, last github version: 2.13.4)

Auto-update cppcheck to 2.13.4

---

packages/a/arduinojson/xmake.lua

New version of arduinojson detected (package version: nil, last github version: v7.0.4)

Auto-update arduinojson to v7.0.4

---

packages/l/lightgbm/xmake.lua

New version of lightgbm detected (package version: nil, last github version: 4.3.0)

Auto-update lightgbm to 4.3.0

---

packages/c/cpptrace/xmake.lua

New version of cpptrace detected (package version: nil, last github version: v0.5.1)

Auto-update cpptrace to v0.5.1

---

packages/e/emio/xmake.lua

New version of emio detected (package version: nil, last github version: 0.7.0)

Auto-update emio to 0.7.0

---

packages/d/draco/xmake.lua

New version of draco detected (package version: nil, last github version: 1.5.7)

Auto-update draco to 1.5.7

---

packages/t/tree-sitter/xmake.lua

New version of tree-sitter detected (package version: nil, last github version: 0.22.2)

Auto-update tree-sitter to 0.22.2

---

packages/o/openpgl/xmake.lua

New version of openpgl detected (package version: nil, last github version: 0.6.0)

Auto-update openpgl to 0.6.0

---

packages/m/microsoft-proxy/xmake.lua

New version of microsoft-proxy detected (package version: nil, last github version: 2.2.1)

Auto-update microsoft-proxy to 2.2.1

---

packages/g/glfw/xmake.lua

When no `GLFW_INCLUDE_` macro is defined, GLFW includes the OpenGL headers from the system. (https://www.glfw.org/docs/latest/build_guide.html#build_macros)

Add system include option for GLFW

---

packages/s/sentry-native/xmake.lua

New version of sentry-native detected (package version: 0.7.0, last github version: 0.7.1)

Auto-update sentry-native to 0.7.1

---

packages/f/fast_float/xmake.lua

New version of fast_float detected (package version: v6.1.0, last github version: v6.1.1)

Auto-update fast_float to v6.1.1

---

packages/h/hffix/xmake.lua

New version of hffix detected (package version: nil, last github version: v1.4.0)

Auto-update hffix to v1.4.0

---

packages/e/expat/xmake.lua

New version of expat detected (package version: nil, last github version: 2.6.2)

Auto-update expat to 2.6.2

---

packages/e/emmylua_debugger/xmake.lua

New version of emmylua_debugger detected (package version: nil, last github version: 1.7.1)

Auto-update emmylua_debugger to 1.7.1

---

packages/q/quickjs/patches/2024.01.13/msvc.patch
packages/q/quickjs/xmake.lua

Fix https://github.com/xmake-io/xmake-repo/issues/3586

quickjs: fix windows build

---

packages/f/functionalplus/xmake.lua

New version of functionalplus detected (package version: nil, last github version: v0.2.23)

Auto-update functionalplus to v0.2.23

---

packages/s/span-lite/xmake.lua

New version of span-lite detected (package version: nil, last github version: 0.11.0)

Auto-update span-lite to 0.11.0

---

packages/a/aws-c-common/xmake.lua

New version of aws-c-common detected (package version: nil, last github version: v0.9.14)

Auto-update aws-c-common to v0.9.14

---

packages/a/aws-c-mqtt/xmake.lua

New version of aws-c-mqtt detected (package version: nil, last github version: v0.10.3)

Auto-update aws-c-mqtt to v0.10.3

---

packages/c/cli/xmake.lua

New version of cli detected (package version: nil, last github version: v2.1.0)

Auto-update cli to v2.1.0

---

packages/q/quill/xmake.lua

New version of quill detected (package version: nil, last github version: 3.8.0)

Auto-update quill to 3.8.0

---

packages/l/libde265/xmake.lua

New version of libde265 detected (package version: nil, last github version: 1.0.15)

Auto-update libde265 to 1.0.15

---

packages/r/rtm/xmake.lua

New version of rtm detected (package version: nil, last github version: v2.3.1)

Auto-update rtm to v2.3.1

---

packages/m/md4qt/xmake.lua

New version of md4qt detected (package version: nil, last github version: 2.8.1)

Auto-update md4qt to 2.8.1

---

packages/u/ufbx/xmake.lua

New version of ufbx detected (package version: nil, last github version: v0.11.1)

Auto-update ufbx to v0.11.1

---

packages/a/aws-crt-cpp/xmake.lua

New version of aws-crt-cpp detected (package version: nil, last github version: v0.26.4)

Auto-update aws-crt-cpp to v0.26.4

---

packages/h/highs/xmake.lua

New version of highs detected (package version: nil, last github version: v1.7.0)

Auto-update highs to v1.7.0

---

packages/m/mcut/xmake.lua

New version of mcut detected (package version: nil, last github version: v1.3.0)

Auto-update mcut to v1.3.0

---

packages/r/reproc/xmake.lua

New version of reproc detected (package version: nil, last github version: v14.2.5)

Auto-update reproc to v14.2.5

---

packages/l/libavif/xmake.lua

New version of libavif detected (package version: nil, last github version: v1.0.4)

Auto-update libavif to v1.0.4

---

packages/d/daw_header_libraries/xmake.lua

New version of daw_header_libraries detected (package version: nil, last github version: v2.102.0)

Auto-update daw_header_libraries to v2.102.0

---

packages/a/ada/xmake.lua

New version of ada detected (package version: nil, last github version: 2.7.7)

Auto-update ada to 2.7.7

---

packages/m/mdns/xmake.lua

New version of mdns detected (package version: nil, last github version: 1.4.3)

Auto-update mdns to 1.4.3

---

packages/l/libzip/xmake.lua

New version of libzip detected (package version: nil, last github version: v1.10.1)

Auto-update libzip to v1.10.1

---

packages/a/aws-c-http/xmake.lua

New version of aws-c-http detected (package version: nil, last github version: v0.8.1)

Auto-update aws-c-http to v0.8.1

---

packages/s/simdjson/xmake.lua

New version of simdjson detected (package version: nil, last github version: v3.8.0)

Auto-update simdjson to v3.8.0

---

packages/l/libremidi/xmake.lua

New version of libremidi detected (package version: nil, last github version: v4.5.0)

Auto-update libremidi to v4.5.0

---

packages/t/tracy/xmake.lua

New version of tracy detected (package version: nil, last github version: v0.10)

Auto-update tracy to v0.10

---

packages/o/ozz-animation/xmake.lua

New version of ozz-animation detected (package version: nil, last github version: 0.15.0)

Auto-update ozz-animation to 0.15.0

---

packages/o/onnxruntime/xmake.lua

onnxruntime supports CUDA 12 since version 1.17.0  
this PR adds the ability to specify the desired CUDA version while preserving backwards compatibility with the existing configs

add cuda 12 support for onnxruntime

---

packages/c/cargs/xmake.lua

New version of cargs detected (package version: nil, last github version: v1.1.0)

Auto-update cargs to v1.1.0

---

packages/r/redis-plus-plus/xmake.lua

New version of redis-plus-plus detected (package version: nil, last github version: 1.3.12)

Auto-update redis-plus-plus to 1.3.12

---

packages/g/glaze/xmake.lua

New version of glaze detected (package version: nil, last github version: v2.4.2)

Auto-update glaze to v2.4.2

---

packages/t/thread-pool/xmake.lua

New version of thread-pool detected (package version: nil, last github version: v4.1.0)

Auto-update thread-pool to v4.1.0

---

packages/g/glaze/xmake.lua

New version of glaze detected (package version: nil, last github version: v2.4.4)

Auto-update glaze to v2.4.4

---

packages/l/lunasvg/xmake.lua

New version of lunasvg detected (package version: nil, last github version: v2.3.9)

Auto-update lunasvg to v2.3.9

---

packages/d/dynareadout/xmake.lua

New version of dynareadout detected (package version: nil, last github version: 24.03)

Auto-update dynareadout to 24.03

---

packages/s/sentry-native/xmake.lua

New version of sentry-native detected (package version: nil, last github version: 0.7.2)

Auto-update sentry-native to 0.7.2

---

packages/r/robin-map/xmake.lua

New version of robin-map detected (package version: nil, last github version: v1.2.2)

Auto-update robin-map to v1.2.2

---

packages/c/chipmunk2d/xmake.lua

on macOS / iOS, if CP_USE_CGTYPES is not defined, it overrides CP_USE_DOUBLES value

chipmunk2d: Set CP_USE_CGTYPES if precision is set

---

packages/w/winreg/xmake.lua

New version of winreg detected (package version: nil, last github version: v6.2.0)

Auto-update winreg to v6.2.0

---

packages/m/mapbox_earcut/xmake.lua

New version of mapbox_earcut detected (package version: nil, last github version: 2.2.4)

Auto-update mapbox_earcut to 2.2.4

---

packages/j/joltphysics/xmake.lua

New version of joltphysics detected (package version: v4.0.2, last github version: v5.0.0)

Auto-update joltphysics to v5.0.0

---

packages/l/libdwarf/xmake.lua

New version of libdwarf detected (package version: nil, last github version: 0.9.2)

Auto-update libdwarf to 0.9.2

---

packages/m/mxml/xmake.lua

New version of mxml detected (package version: nil, last github version: 4.0.2)

Auto-update mxml to 4.0.2

---

packages/m/microsoft-proxy/xmake.lua

New version of microsoft-proxy detected (package version: nil, last github version: 2.3.0)

Auto-update microsoft-proxy to 2.3.0

---

packages/e/enet6/xmake.lua

New version of enet6 detected (package version: v6.0.2, last github version: v6.1.0)

Auto-update enet6 to v6.1.0

---

packages/s/scons/xmake.lua

New version of scons detected (package version: nil, last github version: 4.7.0)

Auto-update scons to 4.7.0

---

packages/p/pyincpp/xmake.lua

New version of pyincpp detected (package version: nil, last github version: v1.4.1)

Auto-update pyincpp to v1.4.1

---

packages/a/aws-c-auth/xmake.lua

New version of aws-c-auth detected (package version: nil, last github version: v0.7.17)

Auto-update aws-c-auth to v0.7.17

---

packages/r/rendergraph/xmake.lua

New version of rendergraph detected (package version: nil, last github version: v1.4.1)

Auto-update rendergraph to v1.4.1

---

packages/a/assimp/xmake.lua

New version of assimp detected (package version: v5.3.1, last github version: v5.4.0)

Auto-update assimp to v5.4.0

---

packages/l/libgit2/xmake.lua

New version of libgit2 detected (package version: nil, last github version: v1.8.0)

Auto-update libgit2 to v1.8.0

---

packages/c/c-blosc2/xmake.lua

New version of c-blosc2 detected (package version: nil, last github version: v2.14.3)

Auto-update c-blosc2 to v2.14.3

---

packages/f/frugally-deep/xmake.lua

New version of frugally-deep detected (package version: nil, last github version: v0.15.31)

Auto-update frugally-deep to v0.15.31

---

packages/s/sqlpp11/xmake.lua

New version of sqlpp11 detected (package version: nil, last github version: 0.64)

Auto-update sqlpp11 to 0.64

---

packages/c/cpp-httplib/xmake.lua

After 0.15.0 version, this library switch to openssl3

cpp-httplib: fix openssl

---

packages/v/vcglib/xmake.lua

New version of vcglib detected (package version: nil, last github version: 2023.12)

Auto-update vcglib to 2023.12

---

packages/m/msgpack-c/xmake.lua

New version of msgpack-c detected (package version: nil, last github version: 6.0.1)

Auto-update msgpack-c to 6.0.1

---

packages/k/kahip/xmake.lua

New version of kahip detected (package version: nil, last github version: v3.16)

Auto-update kahip to v3.16

---

packages/m/meson/xmake.lua

New version of meson detected (package version: nil, last github version: 1.4.0)

Auto-update meson to 1.4.0

---

packages/c/cpptrace/xmake.lua

New version of cpptrace detected (package version: nil, last github version: v0.5.2)

Auto-update cpptrace to v0.5.2

---

packages/r/reactiveplusplus/xmake.lua

Also fixed `package:version()` returning `nil` when requiring a specific git commit.

Update reactiveplusplus to v2.1.1

---

packages/a/aws-c-io/xmake.lua

New version of aws-c-io detected (package version: nil, last github version: v0.14.7)

Auto-update aws-c-io to v0.14.7

---

packages/l/libassert/xmake.lua

New version of libassert detected (package version: nil, last github version: v2.0.1)

Auto-update libassert to v2.0.1

---

packages/v/vulkan-utility-libraries/xmake.lua

New version of vulkan-utility-libraries detected (package version: nil, last github version: v1.3.281)

Auto-update vulkan-utility-libraries to v1.3.281

---

packages/y/yoga/xmake.lua

New version of yoga detected (package version: nil, last github version: v3.0.3)

Auto-update yoga to v3.0.3

---

packages/d/directx-headers/xmake.lua

New version of directx-headers detected (package version: nil, last github version: v1.613.1)

Auto-update directx-headers to v1.613.1

---

packages/j/jwt-cpp/xmake.lua

New version of jwt-cpp detected (package version: nil, last github version: v0.7.0)

Auto-update jwt-cpp to v0.7.0

---

packages/i/indicators/xmake.lua

New version of indicators detected (package version: nil, last github version: 2.3)

Auto-update indicators to 2.3

---

packages/c/cista/xmake.lua

New version of cista detected (package version: nil, last github version: v0.15)

Auto-update cista to v0.15

---

packages/a/aws-c-compression/xmake.lua

New version of aws-c-compression detected (package version: nil, last github version: v0.2.18)

Auto-update aws-c-compression to v0.2.18

---

packages/m/minizip-ng/xmake.lua

New version of minizip-ng detected (package version: nil, last github version: 4.0.5)

Auto-update minizip-ng to 4.0.5

---

packages/s/snitch/xmake.lua

New version of snitch detected (package version: nil, last github version: 1.2.4)

Auto-update snitch to 1.2.4

---

packages/l/libdeflate/xmake.lua

New version of libdeflate detected (package version: nil, last github version: v1.20)

Auto-update libdeflate to v1.20

---

packages/c/ck/xmake.lua

New version of ck detected (package version: nil, last github version: 0.7.2)

Auto-update ck to 0.7.2

---

packages/s/simdutf/xmake.lua

New version of simdutf detected (package version: nil, last github version: v5.2.4)

Auto-update simdutf to v5.2.4

---

packages/a/ada/xmake.lua

New version of ada detected (package version: nil, last github version: 2.7.8)

Auto-update ada to 2.7.8

---

packages/z/zeus_expected/xmake.lua

New version of zeus_expected detected (package version: nil, last github version: v1.0.1)

Auto-update zeus_expected to v1.0.1

---

packages/v/vvenc/xmake.lua

New version of vvenc detected (package version: nil, last github version: v1.11.1)

Auto-update vvenc to v1.11.1

---

packages/s/samurai/xmake.lua

New version of samurai detected (package version: nil, last github version: v0.12.0)

Auto-update samurai to v0.12.0

---

packages/r/rocksdb/xmake.lua

New version of rocksdb detected (package version: nil, last github version: v9.0.0)
- close: #3245

Auto-update rocksdb to v9.0.0

---

packages/c/csvparser/xmake.lua

New version of csvparser detected (package version: nil, last github version: 2.2.0)

Auto-update csvparser to 2.2.0

---

packages/s/stringzilla/xmake.lua

New version of stringzilla detected (package version: nil, last github version: v3.8.0)

Auto-update stringzilla to v3.8.0

---

packages/m/mariadb-connector-c/xmake.lua

New version of mariadb-connector-c detected (package version: 3.3.4, last github version: 3.3.9)

Auto-update mariadb-connector-c to 3.3.9

---

packages/k/kokkos-kernels/xmake.lua
packages/k/kokkos/xmake.lua

New version of kokkos-kernels detected (package version: nil, last github version: 4.3.00)

Auto-update kokkos-kernels to 4.3.00

---

packages/c/cpp-peglib/xmake.lua

New version of cpp-peglib detected (package version: nil, last github version: 1.8.8)

Auto-update cpp-peglib to 1.8.8

---

packages/a/actor-framework/xmake.lua

New version of actor-framework detected (package version: nil, last github version: 0.19.6)

Auto-update actor-framework to 0.19.6

---

packages/l/libxmake/xmake.lua

New version of libxmake detected (package version: nil, last github version: v2.8.9)

Auto-update libxmake to v2.8.9

---

packages/v/vk-bootstrap/xmake.lua

New version of vk-bootstrap detected (package version: nil, last github version: v1.3.282)

Auto-update vk-bootstrap to v1.3.282

---

packages/u/ucx/xmake.lua

New version of ucx detected (package version: nil, last github version: 1.16.0)

Auto-update ucx to 1.16.0

---

packages/n/nghttp2/xmake.lua

New version of nghttp2 detected (package version: nil, last github version: 1.61.0)

Auto-update nghttp2 to 1.61.0

---

packages/a/aws-c-common/xmake.lua

New version of aws-c-common detected (package version: nil, last github version: v0.9.15)

Auto-update aws-c-common to v0.9.15

---

packages/l/libfabric/xmake.lua

New version of libfabric detected (package version: nil, last github version: 1.20.2)

Auto-update libfabric to 1.20.2

---

packages/f/fast-cdr/xmake.lua

New version of fast-cdr detected (package version: nil, last github version: v2.2.1)

Auto-update fast-cdr to v2.2.1

---

packages/i/imgui-file-dialog/xmake.lua

New version of imgui-file-dialog detected (package version: nil, last github version: v0.6.7)

Auto-update imgui-file-dialog to v0.6.7

---

packages/y/yoga/xmake.lua

New version of yoga detected (package version: nil, last github version: v3.0.4)

Auto-update yoga to v3.0.4

---

packages/l/littlefs/xmake.lua

New version of littlefs detected (package version: nil, last github version: v2.9.2)

Auto-update littlefs to v2.9.2

---

packages/a/autodiff/xmake.lua

New version of autodiff detected (package version: nil, last github version: v1.1.2)

Auto-update autodiff to v1.1.2

---

packages/e/entt/xmake.lua

New version of entt detected (package version: v3.13.1, last github version: v3.13.2)

Auto-update entt to v3.13.2

---

packages/c/catch2/patches/3.5.4/windows_arm64.patch
packages/c/catch2/xmake.lua

New version of catch2 detected (package version: v3.5.3, last github version: v3.5.4)

Auto-update catch2 to v3.5.4

---

packages/c/c-ares/xmake.lua

New version of c-ares detected (package version: nil, last github version: 1.28.1)

Auto-update c-ares to 1.28.1

---

packages/o/onednn/xmake.lua

New version of onednn detected (package version: nil, last github version: v3.4.1)

Auto-update onednn to v3.4.1

---

packages/t/tree-sitter/xmake.lua

New version of tree-sitter detected (package version: nil, last github version: 0.22.5)

Auto-update tree-sitter to 0.22.5

---

packages/p/pyincpp/xmake.lua

New version of pyincpp detected (package version: nil, last github version: v1.6.0)

Auto-update pyincpp to v1.6.0

---

packages/g/glaze/xmake.lua

New version of glaze detected (package version: nil, last github version: v2.5.3)

Auto-update glaze to v2.5.3

---

packages/c/cuda-samples/xmake.lua

New version of cuda-samples detected (package version: nil, last github version: v12.4.1)

Auto-update cuda-samples to v12.4.1

---

packages/z/zeus_expected/xmake.lua

New version of zeus_expected detected (package version: nil, last github version: v1.1.0)

Auto-update zeus_expected to v1.1.0

---

packages/s/simdjson/xmake.lua

New version of simdjson detected (package version: nil, last github version: v3.9.1)

Auto-update simdjson to v3.9.1

---

packages/n/nanoflann/xmake.lua

New version of nanoflann detected (package version: nil, last github version: v1.5.5)

Auto-update nanoflann to v1.5.5

---

packages/l/libsais/xmake.lua

New version of libsais detected (package version: nil, last github version: v2.8.1)

Auto-update libsais to v2.8.1

---

packages/r/rocksdb/xmake.lua

Add a configure flag "rtti" for RocksDB to enable the RTTI build that is necessary for the MergeOperator API.

Add a "rtti" configure flag for rocksdb

---

packages/k/kuba-zip/xmake.lua

New version of kuba-zip detected (package version: nil, last github version: v0.3.2)

Auto-update kuba-zip to v0.3.2

---

packages/y/yomm2/xmake.lua

New version of yomm2 detected (package version: nil, last github version: v1.5.0)

Auto-update yomm2 to v1.5.0

---

packages/m/matio/xmake.lua

New version of matio detected (package version: nil, last github version: v1.5.27)

Auto-update matio to v1.5.27

---

packages/e/etl/xmake.lua

New version of etl detected (package version: nil, last github version: 20.38.11)

Auto-update etl to 20.38.11

---

packages/f/frugally-deep/xmake.lua

New version of frugally-deep detected (package version: nil, last github version: v0.16.0)

Auto-update frugally-deep to v0.16.0

---

packages/a/aws-c-common/xmake.lua

New version of aws-c-common detected (package version: nil, last github version: v0.9.17)

Auto-update aws-c-common to v0.9.17

---

packages/g/glslang/xmake.lua

glslang compiler binary has been renamed in https://github.com/KhronosGroup/glslang/releases/tag/12.3.0, a symlink exists but doesn't seem to work well on Windows

glslang: Update binary name when testing

---

packages/a/aws-c-cal/xmake.lua

New version of aws-c-cal detected (package version: nil, last github version: v0.6.11)

Auto-update aws-c-cal to v0.6.11

---

packages/s/s2n-tls/xmake.lua

New version of s2n-tls detected (package version: nil, last github version: v1.4.12)

Auto-update s2n-tls to v1.4.12

---

packages/u/ufbx/xmake.lua

New version of ufbx detected (package version: nil, last github version: v0.12.0)

Auto-update ufbx to v0.12.0

---

packages/r/rocksdb/xmake.lua

New version of rocksdb detected (package version: nil, last github version: v9.1.1)

Auto-update rocksdb to v9.1.1

---

packages/s/suitesparse/xmake.lua

New version of suitesparse detected (package version: nil, last github version: v7.7.0)

Auto-update suitesparse to v7.7.0

---

packages/a/aws-c-sdkutils/xmake.lua

New version of aws-c-sdkutils detected (package version: nil, last github version: v0.1.16)

Auto-update aws-c-sdkutils to v0.1.16

---

packages/l/llvm-arm/xmake.lua

add  llvm-arm 
A project dedicated to building LLVM toolchain for 32-bit Arm embedded targets.

add:llvm-arm

---

packages/z/zziplib/xmake.lua

New version of zziplib detected (package version: nil, last github version: v0.13.74)

Auto-update zziplib to v0.13.74

---

packages/y/yomm2/xmake.lua

New version of yomm2 detected (package version: nil, last github version: v1.5.1)

Auto-update yomm2 to v1.5.1

---

packages/h/h5cpp/xmake.lua

New version of h5cpp detected (package version: nil, last github version: v0.6.0)

Auto-update h5cpp to v0.6.0

---

packages/a/aws-crt-cpp/xmake.lua

New version of aws-crt-cpp detected (package version: nil, last github version: v0.26.8)

Auto-update aws-crt-cpp to v0.26.8

---

packages/m/mxml/xmake.lua

New version of mxml detected (package version: nil, last github version: 4.0.3)

Auto-update mxml to 4.0.3

---

packages/s/stringzilla/xmake.lua

New version of stringzilla detected (package version: nil, last github version: v3.8.4)

Auto-update stringzilla to v3.8.4

---

packages/o/openexr/xmake.lua

New version of openexr detected (package version: nil, last github version: v3.2.4)

Auto-update openexr to v3.2.4

---

packages/z/zeus_expected/xmake.lua

New version of zeus_expected detected (package version: nil, last github version: v1.1.1)

Auto-update zeus_expected to v1.1.1

---

packages/g/gmssl/xmake.lua

New version of gmssl detected (package version: nil, last github version: v3.1.1)

Auto-update gmssl to v3.1.1

---

packages/a/aws-c-mqtt/xmake.lua

New version of aws-c-mqtt detected (package version: nil, last github version: v0.10.4)

Auto-update aws-c-mqtt to v0.10.4

---

packages/q/quantlib/xmake.lua

New version of quantlib detected (package version: nil, last github version: 1.34)

Auto-update quantlib to 1.34

---

packages/h/haclog/xmake.lua

New version of haclog detected (package version: nil, last github version: v0.2.0)

Auto-update haclog to v0.2.0

---

packages/w/whisper.cpp/xmake.lua

New version of whisper.cpp detected (package version: nil, last github version: 1.5.5)

Auto-update whisper.cpp to 1.5.5

---

packages/l/llvm-mingw/xmake.lua

This pull request updates the xmake.lua file to include support for the latest version of llvm-mingw (version 20240417). This ensures that the project can be built and run using the latest version of llvm-mingw.

Update xmake.lua to include support for llvm-mingw version 20240417

---

packages/a/aws-c-auth/xmake.lua

New version of aws-c-auth detected (package version: nil, last github version: v0.7.18)

Auto-update aws-c-auth to v0.7.18

---

packages/a/aws-c-cal/xmake.lua

New version of aws-c-cal detected (package version: nil, last github version: v0.6.12)

Auto-update aws-c-cal to v0.6.12

---

packages/r/robin-map/xmake.lua

New version of robin-map detected (package version: nil, last github version: v1.3.0)

Auto-update robin-map to v1.3.0

---

packages/u/ufbx/xmake.lua

New version of ufbx detected (package version: nil, last github version: v0.13.0)

Auto-update ufbx to v0.13.0

---

packages/g/glfw3webgpu/xmake.lua

New version of glfw3webgpu detected (package version: nil, last github version: v1.2.0)

Auto-update glfw3webgpu to v1.2.0

---

packages/l/lzav/xmake.lua

New version of lzav detected (package version: nil, last github version: 4.0)

Auto-update lzav to 4.0

---

packages/d/dispenso/xmake.lua

New version of dispenso detected (package version: nil, last github version: v1.3.0)

Auto-update dispenso to v1.3.0

---

packages/s/simdutf/xmake.lua

New version of simdutf detected (package version: nil, last github version: v5.2.6)

Auto-update simdutf to v5.2.6

---

packages/l/littlefs/xmake.lua

New version of littlefs detected (package version: nil, last github version: v2.9.3)

Auto-update littlefs to v2.9.3

---

packages/a/aws-c-s3/xmake.lua

New version of aws-c-s3 detected (package version: nil, last github version: v0.5.7)

Auto-update aws-c-s3 to v0.5.7

---

packages/c/cello/xmake.lua
packages/l/libdicom/xmake.lua
packages/s/stringzilla/xmake.lua
packages/t/tiny-optional/xmake.lua
packages/t/tobiaslocker_base64/xmake.lua

https://github.com/xmake-io/xmake/issues/5048

fix limits for packages

---

packages/n/numactl/xmake.lua

New version of numactl detected (package version: nil, last github version: 2.0.18)

Auto-update numactl to 2.0.18

---

packages/v/vk-bootstrap/xmake.lua

New version of vk-bootstrap detected (package version: nil, last github version: v1.3.283)

Auto-update vk-bootstrap to v1.3.283

---

packages/l/libenvpp/xmake.lua

New version of libenvpp detected (package version: nil, last github version: v1.4.1)

Auto-update libenvpp to v1.4.1

---

packages/s/simde/xmake.lua

New version of simde detected (package version: nil, last github version: 0.8.2)
- close: #3791 
- close: #3481

Auto-update simde to 0.8.2

---

packages/o/openvr/xmake.lua

New version of openvr detected (package version: nil, last github version: v2.5.1)

Auto-update openvr to v2.5.1

---

packages/h/harfbuzz/xmake.lua

New version of harfbuzz detected (package version: nil, last github version: 8.4.0)

Auto-update harfbuzz to 8.4.0

---

packages/u/ufbx/xmake.lua

New version of ufbx detected (package version: nil, last github version: v0.14.0)

Auto-update ufbx to v0.14.0

---

packages/f/fast_double_parser/xmake.lua

New version of fast_double_parser detected (package version: v0.7.0, last github version: v0.8.0)

Auto-update fast_double_parser to v0.8.0

---

scripts/autoupdate.lua

Scope issue, should fix the nil version in messages like here: <https://github.com/xmake-io/xmake-repo/pull/3972>

Fix autoupdate package version nil

---

packages/b/blake3/xmake.lua

New version of blake3 detected (package version: nil, last github version: 1.5.1)

Auto-update blake3 to 1.5.1

---

packages/c/c-blosc2/xmake.lua

New version of c-blosc2 detected (package version: nil, last github version: v2.14.4)

Auto-update c-blosc2 to v2.14.4

---

packages/e/etl/xmake.lua

New version of etl detected (package version: nil, last github version: 20.38.13)

Auto-update etl to 20.38.13

---

packages/l/libcpuid/xmake.lua

New version of libcpuid detected (package version: v0.6.4, last github version: v0.6.5)

Auto-update libcpuid to v0.6.5

---

packages/w/wigxjpf/xmake.lua

The wigxjpf library is used for evaluating Wigner symbols, which is very useful for angular momentum coupling. The GNU-GSL library offers `gsl_sf_coupling_?j` functions, but they are inaccurate for very large angular momentum. This library use big integer techniques to give accurate result.

add wigxjpf

---

packages/d/daw_json_link/xmake.lua

New version of daw_json_link detected (package version: nil, last github version: v3.24.0)

Auto-update daw_json_link to v3.24.0

---

packages/l/libcpuid/xmake.lua

`native` would fail if we build on Windows ARM

libcpuid: support exclusively x86 archs on Windows

---

packages/l/libunwind/xmake.lua

New version of libunwind detected (package version: nil, last github version: v1.8.1)

Auto-update libunwind to v1.8.1

---

packages/f/fribidi/xmake.lua

New version of fribidi detected (package version: 1.0.13, last github version: 1.0.14)

Auto-update fribidi to 1.0.14

---

packages/h/hffix/xmake.lua

New version of hffix detected (package version: v1.4.0, last github version: v1.4.1)

Auto-update hffix to v1.4.1

---

packages/r/rapidfuzz/xmake.lua

New version of rapidfuzz detected (package version: v3.0.2, last github version: v3.0.4)

Auto-update rapidfuzz to v3.0.4

---

packages/k/kokkos-kernels/xmake.lua

New version of kokkos-kernels detected (package version: 4.3.00, last github version: 4.3.01)

Auto-update kokkos-kernels to 4.3.01

---

packages/c/cglm/xmake.lua

New version of cglm detected (package version: v0.9.2, last github version: v0.9.4)

Auto-update cglm to v0.9.4

---

packages/t/type_safe/xmake.lua

New version of type_safe detected (package version: v0.2.2, last github version: v0.2.4)

Auto-update type_safe to v0.2.4

---

packages/k/kangaru/xmake.lua

New version of kangaru detected (package version: v4.3.1, last github version: v4.3.2)

Auto-update kangaru to v4.3.2

---

packages/s/snitch/xmake.lua

New version of snitch detected (package version: 1.2.4, last github version: 1.2.5)

Auto-update snitch to 1.2.5

---

packages/d/daw_header_libraries/xmake.lua

New version of daw_header_libraries detected (package version: v2.102.0, last github version: v2.106.0)

Auto-update daw_header_libraries to v2.106.0

---

packages/g/gcem/xmake.lua

New version of gcem detected (package version: v1.17.0, last github version: v1.18.0)

Auto-update gcem to v1.18.0

---

packages/o/opencl-headers/xmake.lua

New version of opencl-headers detected (package version: v2023.12.14, last github version: v2024.05.08)

Auto-update opencl-headers to v2024.05.08

---

packages/s/sfml/xmake.lua

There is already a similar external source for OS X, but not for `pkgconfig` everywhere else.

sfml: use "sfml-all" in pkgconfig if not Windows

---

packages/c/cppcheck/xmake.lua

New version of cppcheck detected (package version: 2.13.4, last github version: 2.14.0)

Auto-update cppcheck to 2.14.0

---

packages/x/xerces-c/patches/patch-android.diff
packages/x/xerces-c/xmake.lua

Ref: https://github.com/apache/xerces-c/pull/56

Add patch for `Xerces-C` (Android NDK version < 26)

---

packages/a/aws-c-io/xmake.lua

New version of aws-c-io detected (package version: v0.14.7, last github version: v0.14.8)

Auto-update aws-c-io to v0.14.8

---

packages/v/vk-bootstrap/xmake.lua

New version of vk-bootstrap detected (package version: v1.3.284, last github version: v1.3.285)

Auto-update vk-bootstrap to v1.3.285

---

packages/w/whisper.cpp/xmake.lua

New version of whisper.cpp detected (package version: 1.5.5, last github version: 1.6.0)

Auto-update whisper.cpp to 1.6.0

---

packages/s/shaderc/xmake.lua

New version of shaderc detected (package version: v2024.0, last github version: v2024.1)

Auto-update shaderc to v2024.1

---

packages/s/simdjson/xmake.lua

New version of simdjson detected (package version: v3.9.1, last github version: v3.9.2)

Auto-update simdjson to v3.9.2

---

packages/l/libgit2/xmake.lua

New version of libgit2 detected (package version: v1.8.0, last github version: v1.8.1)

Auto-update libgit2 to v1.8.1

---

packages/s/s2n-tls/xmake.lua

New version of s2n-tls detected (package version: v1.4.12, last github version: v1.4.14)

Auto-update s2n-tls to v1.4.14

---

packages/a/aws-c-cal/xmake.lua

New version of aws-c-cal detected (package version: v0.6.12, last github version: v0.6.14)

Auto-update aws-c-cal to v0.6.14

---

packages/m/microsoft-proxy/xmake.lua

New version of microsoft-proxy detected (package version: 2.3.0, last github version: 2.4.0)

Auto-update microsoft-proxy to 2.4.0

---

packages/p/pyincpp/xmake.lua

Add v1.6.1 for pyincpp. This is the last version for v1 and requires C++17.

add version pyincpp v1.6.1

---

packages/g/gyp-next/xmake.lua

New version of gyp-next detected (package version: v0.16.2, last github version: v0.18.0)

Auto-update gyp-next to v0.18.0

---

packages/o/onednn/xmake.lua

New version of onednn detected (package version: v3.4.1, last github version: v3.4.2)

Auto-update onednn to v3.4.2

---

packages/u/uvwasi/xmake.lua

New version of uvwasi detected (package version: v0.0.20, last github version: v0.0.21)

Auto-update uvwasi to v0.0.21

---

packages/a/aws-c-common/xmake.lua

New version of aws-c-common detected (package version: v0.9.17, last github version: v0.9.19)

Auto-update aws-c-common to v0.9.19

---

packages/o/openmp/xmake.lua

The PR addresses request #4065.
The modifications are as follows:
* Added support for Fortran compilers ("fc")
* Added support of GFortran and Intel Fortran (classic)
Tested on Mac OS X (Apple, arm64, GFortran) and Linux (AMD, x86_64, GFortran).
Small example to test the package (`hello_mp.F90`)
```
program hello_mp
#ifdef _OPENMP
integer, external :: omp_get_num_threads, omp_get_thread_num
#endif
#ifdef _OPENMP
!$omp parallel
write(*, '(a,i0,a,i0)') 'Hello, ', omp_get_num_threads(), &
' threads are running and this thread ', omp_get_thread_num()
!$omp end parallel
#else
write(*,'(a)') 'Hello, this is a serial program'
#endif
end program hello_mp
```
Note that with GFortran, the extension needs to be in upper case (F90 instead of f90) to automatically enable C preprocssing, deactivated …

Added support of Fortran in OpenMP package

---

packages/t/trantor/xmake.lua

New version of trantor detected (package version: v1.5.17, last github version: v1.5.18)

Auto-update trantor to v1.5.18

---

packages/l/libxmake/xmake.lua

New version of libxmake detected (package version: v2.8.9, last github version: v2.9.1)

Auto-update libxmake to v2.9.1

---

packages/c/cutlass/xmake.lua

New version of cutlass detected (package version: v3.4.1, last github version: v3.5.0)

Auto-update cutlass to v3.5.0

---

packages/c/csvparser/xmake.lua

New version of csvparser detected (package version: 2.2.0, last github version: 2.2.1)

Auto-update csvparser to 2.2.1

---

packages/c/cpptrace/xmake.lua

New version of cpptrace detected (package version: v0.5.2, last github version: v0.5.4)

Auto-update cpptrace to v0.5.4

---

packages/a/aws-c-s3/xmake.lua

New version of aws-c-s3 detected (package version: v0.5.7, last github version: v0.5.9)

Auto-update aws-c-s3 to v0.5.9

---

packages/d/directx-headers/xmake.lua

New version of directx-headers detected (package version: v1.613.1, last github version: v1.614.0)

Auto-update directx-headers to v1.614.0

---

packages/n/ngtcp2/xmake.lua

New version of ngtcp2 detected (package version: 1.4.0, last github version: 1.5.0)

Auto-update ngtcp2 to 1.5.0

---

packages/h/hlslpp/xmake.lua

New version of hlslpp detected (package version: 3.4, last github version: 3.5)

Auto-update hlslpp to 3.5

---

packages/a/aws-c-auth/xmake.lua

New version of aws-c-auth detected (package version: v0.7.18, last github version: v0.7.22)

Auto-update aws-c-auth to v0.7.22

---

packages/f/fast_io/xmake.lua

Update Fast_io to version 2024.03.31
fast_io 在新版本修复了部分Bug，并且添加了fast_io::io命名空间避免命名冲突。
因此在添加了新版本后，额外修改了on_test部分的测试逻辑

Update fast_io to version 2024.03.31

---

packages/k/kokkos/xmake.lua

New version of kokkos detected (package version: 4.3.00, last github version: 4.3.01)

Auto-update kokkos to 4.3.01

---

packages/c/csvparser/xmake.lua

New version of csvparser detected (package version: 2.2.1, last github version: 2.2.2)

Auto-update csvparser to 2.2.2

---

packages/n/nghttp2/xmake.lua

New version of nghttp2 detected (package version: 1.62.0, last github version: 1.62.1)

Auto-update nghttp2 to 1.62.1

---

packages/z/zlib-ng/xmake.lua

New version of zlib-ng detected (package version: 2.1.5, last github version: 2.1.6)

Auto-update zlib-ng to 2.1.6

---

packages/x/xtensor-blas/xmake.lua

New version of xtensor-blas detected (package version: 0.20.0, last github version: 0.21.0)

Auto-update xtensor-blas to 0.21.0

---

packages/d/duckdb/xmake.lua

New version of duckdb detected (package version: v0.10.2, last github version: v0.10.3)

Auto-update duckdb to v0.10.3

---

packages/l/libxmake/xmake.lua

New version of libxmake detected (package version: v2.9.1, last github version: v2.9.2)

Auto-update libxmake to v2.9.2

---

packages/t/tbb/xmake.lua

Fixed parallel_for_each algorithm behavior for iterators defining iterator_concept trait instead of iterator_category.
Fixed the redefinition issue for std::min and std::max on Windows* OS (https://github.com/oneapi-src/oneTBB/issues/832).
Fixed the incorrect binary search order in TBBConfig.cmake.
https://github.com/oneapi-src/oneTBB/releases

Update tbb 2021.12.0

---

packages/p/pyincpp/xmake.lua

New version of pyincpp detected (package version: v2.3.0, last github version: v2.4.0)

Auto-update pyincpp to v2.4.0

---

packages/t/tree-sitter/xmake.lua

New version of tree-sitter detected (package version: 0.22.5, last github version: 0.22.6)

Auto-update tree-sitter to 0.22.6

---

packages/g/glog/xmake.lua

New version of glog detected (package version: v0.6.0, last github version: v0.7.0)

Auto-update glog to v0.7.0

---

packages/b/boost/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/4135#issuecomment-2130172364

improve boost #4135

---

packages/l/libassert/xmake.lua

New version of libassert detected (package version: v2.0.1, last github version: v2.0.2)

Auto-update libassert to v2.0.2

---

packages/u/ufbx/xmake.lua

New version of ufbx detected (package version: v0.14.0, last github version: v0.14.2)

Auto-update ufbx to v0.14.2

---

packages/a/aws-crt-cpp/xmake.lua

New version of aws-crt-cpp detected (package version: v0.26.8, last github version: v0.26.9)

Auto-update aws-crt-cpp to v0.26.9

---

packages/x/xpack/xmake.lua

New version of xpack detected (package version: v1.0.5, last github version: v1.0.6)

Auto-update xpack to v1.0.6

---

packages/s/symengine/xmake.lua

New version of symengine detected (package version: v0.11.2, last github version: v0.12.0)

Auto-update symengine to v0.12.0

---

packages/w/whisper.cpp/xmake.lua

New version of whisper.cpp detected (package version: 1.6.0, last github version: 1.6.2)

Auto-update whisper.cpp to 1.6.2

---

packages/j/json-c/xmake.lua

1. 删除了0.13: 因为0.13对CMake支持不够, 还需在xrepo中维护两套脚本 (CMake + autoconf)
2. 移除了对Win XP的检测 (需要测试?)

Upgrade json-c to 0.17

---

packages/s/sentry-native/xmake.lua

New version of sentry-native detected (package version: 0.7.2, last github version: 0.7.5)

Auto-update sentry-native to 0.7.5

---

packages/i/ittapi/xmake.lua

New version of ittapi detected (package version: v3.24.6, last github version: v3.24.7)

Auto-update ittapi to v3.24.7

---

packages/l/libsais/xmake.lua

New version of libsais detected (package version: v2.8.1, last github version: v2.8.2)

Auto-update libsais to v2.8.2

---

packages/a/astc-encoder/xmake.lua

New version of astc-encoder detected (package version: 4.7.0, last github version: 4.8.0)

Auto-update astc-encoder to 4.8.0

---

packages/t/thorvg/xmake.lua

New version of thorvg detected (package version: v0.13.5, last github version: v0.13.6)

Auto-update thorvg to v0.13.6

---

packages/h/hpx/xmake.lua

New version of hpx detected (package version: v1.9.1, last github version: v1.10.0)

Auto-update hpx to v1.10.0

---

packages/l/liboai/xmake.lua

New version of liboai detected (package version: 3.2.1, last github version: 4.0.1)

Auto-update liboai to 4.0.1

---

packages/m/minizip-ng/xmake.lua

New version of minizip-ng detected (package version: 4.0.5, last github version: 4.0.6)

Auto-update minizip-ng to 4.0.6

---

packages/y/yomm2/xmake.lua

New version of yomm2 detected (package version: v1.5.1, last github version: v1.5.2)

Auto-update yomm2 to v1.5.2

---

packages/e/emmylua_debugger/xmake.lua

New version of emmylua_debugger detected (package version: 1.7.1, last github version: 1.8.0)

Auto-update emmylua_debugger to 1.8.0

---

packages/h/harfbuzz/xmake.lua

New version of harfbuzz detected (package version: 8.4.0, last github version: 8.5.0)

Auto-update harfbuzz to 8.5.0

---

packages/o/onnx/xmake.lua

New version of onnx detected (package version: v1.16.0, last github version: v1.16.1)

Auto-update onnx to v1.16.1

---

packages/a/aws-crt-cpp/xmake.lua

New version of aws-crt-cpp detected (package version: v0.26.9, last github version: v0.26.11)

Auto-update aws-crt-cpp to v0.26.11

---

packages/d/duckdb/xmake.lua

New version of duckdb detected (package version: v0.10.3, last github version: v1.0.0)

Auto-update duckdb to v1.0.0

---

packages/e/etl/xmake.lua

New version of etl detected (package version: 20.38.13, last github version: 20.38.16)

Auto-update etl to 20.38.16

---

packages/s/samurai/xmake.lua

New version of samurai detected (package version: v0.12.0, last github version: v0.14.0)

Auto-update samurai to v0.14.0

---

packages/t/tiny-optional/xmake.lua

New version of tiny-optional detected (package version: v1.2.0, last github version: v1.2.1)

Auto-update tiny-optional to v1.2.1

---

packages/s/simdutf/xmake.lua

New version of simdutf detected (package version: v5.2.6, last github version: v5.2.8)

Auto-update simdutf to v5.2.8

---

packages/s/sonic-cpp/xmake.lua

New version of sonic-cpp detected (package version: 1.0.0, last github version: 1.0.1)

Auto-update sonic-cpp to 1.0.1
