xmake-io/xmake-repo

packages/l/libuv/xmake.lua

```bash
wget -q https://github.com/libuv/libuv/archive/v1.28.0.zip
shasum -a 256 v1.28.0.zip
```
```
e7b3caea3388a02f2f99e61f9a71ed3e3cbb88bbb4b0b630d609544099b40674  v1.28.0.zip
```

add libuv 1.28.0

---

packages/c/catch2/xmake.lua

add catch2

---

packages/c/concurrentqueue/xmake.lua

Add concurrentqueue

---

packages/f/fmt/xmake.lua

add c++ fmt lib

---

packages/c/cpp-taskflow/xmake.lua
packages/t/taskflow/xmake.lua

add cpp-taskflow lib

---

packages/s/spdlog/xmake.lua

update for spdlog

---

packages/f/fmt/xmake.lua

update for fmt

---

packages/d/doctest/xmake.lua

add doctest v2.3.6

---

packages/f/fmt/xmake.lua
packages/s/spdlog/xmake.lua

update spdlog and fmt

---

packages/p/protobuf-cpp/xmake.lua

add_versions 3.12.3 for protobuf-cpp

---

packages/r/raylib/xmake.lua

Add raylib 3.0.0

---

packages/l/libsdl_ttf/xmake.lua

Add libsdl_ttf

---

packages/l/libsdl_net/xmake.lua

Add libsdl_net

---

packages/l/libsdl_mixer/xmake.lua

Add libsdl_mixer

---

packages/l/libsdl_image/xmake.lua

Add libsdl_image

---

packages/l/libsdl_gfx/patches/1.0.4/add-x64-support.patch
packages/l/libsdl_gfx/xmake.lua

Adds libsdl_gfx with windows support

Add windows support for libsdl_gfx

---

packages/i/irrXML/xmake.lua

Adds the irrXML library which is necessary for assimp (#58)

Add irrXML

---

packages/a/assimp/xmake.lua

Add assimp

---

packages/g/glew/xmake.lua

fix static lib for glew

---

packages/s/spdlog/xmake.lua

spdlog: add version 1.8.0

---

packages/t/tinyxml2/xmake.lua

Adds the tinyxml2 xml parsing library

Add tinyxml2

---

packages/b/bullet3/xmake.lua

This adds the following to bullet3
+ Windows support
+ More unneccessary options are disabled
+ All required files are copied accordingly
+ Version 3.05
+ Fixes git checksum

Add windows support to bullet3 and more features

---

packages/g/glew/xmake.lua

This PR fixes the following
+ Adds test
+ Correct links when static linking and dynamic linking
+ glew32s and glew32
+ Correct Preprocessor Macros when static linking and dynamic linking
+ Correct syslinks

Fix links and add test to glew

---

.github/workflows/linux.yml
packages/g/glfw/xmake.lua

Fixes the following
+ Adds test
+ Correct libraries and defines for shared and static
+ Disables compilation of unneccesary options in linux

Fix links and add test to glfw

---

packages/i/imgui/xmake.lua

update imgui version to v1.79
------

Update imgui version to v1.79

---

packages/e/eigen/xmake.lua

Update eigen to 3.3.8

---

packages/b/blosc/xmake.lua

add package blosc

---

packages/c/cmake/xmake.lua

Update cmake to 3.18.4

---

packages/o/openexr/xmake.lua
packages/z/zlib/xmake.lua

zlib/xmake.lua is modified due to link errors. see [Compile zlib static library with -fPIC](https://github.com/conda-forge/zlib-feedstock/pull/4)

Add package openexr

---

packages/b/blosc/xmake.lua
packages/b/boost/xmake.lua
packages/o/openexr/xmake.lua
packages/t/tbb/xmake.lua

explanation for openexr: package openexr is composed of two parts and required by some other packages on both static and shared library.

add package tbb as well as some fixes to previous packages

---

packages/j/jsoncpp/xmake.lua

add jsoncpp repo ,mac test only

add jsoncpp

---

packages/t/tbb/xmake.lua

- 清除tbb中多余的中间文件
- windows下把dll路径添加到path

fix tbb path issue

---

packages/h/hopscotch-map/xmake.lua

Add hopscotch-map

---

packages/r/rapidjson/xmake.lua

Add rapidjson

---

packages/l/libsodium/xmake.lua

Add libsodium

---

packages/s/stackwalker/patches/1.20.0/debug_build.patch
packages/s/stackwalker/patches/1.20/debug_build.patch
packages/s/stackwalker/xmake.lua

From https://github.com/JochenKalmbach/StackWalker

Add stackwalker

---

packages/c/chipmunk2d/patches/7.0.3/android.patch
packages/c/chipmunk2d/xmake.lua

Add chipmunk2d

---

.github/workflows/mingw_macos.yml
packages/g/gnu-sed/xmake.lua
packages/l/libx11/xmake.lua
packages/l/libxtst/xmake.lua

add libxtst

---

packages/j/jsoncons/xmake.lua

Add jsoncons lib

---

packages/h/hpsocket/port/xmake.lua
packages/h/hpsocket/xmake.lua

add hpsocket

---

packages/a/angelscript/xmake.lua

add angelscript

---

packages/c/capstone/xmake.lua

add capstone

---

packages/h/http_parser/xmake.lua
packages/k/kcp/xmake.lua

add kcp and http-parser

---

packages/g/glslang/xmake.lua
packages/p/python/xmake.lua
packages/s/spirv-headers/xmake.lua
packages/s/spirv-tools/xmake.lua

add dlslang and spirv

---

packages/b/bzip2/xmake.lua
packages/f/fontconfig/xmake.lua
packages/l/libpng/xmake.lua

improve fontconfig

---

packages/c/chaiscript/xmake.lua

add chaiscript

---

packages/f/fltk/xmake.lua

Create xmake.lua for fltk

---

packages/w/wayland/xmake.lua

add wayland

---

packages/m/mimalloc/xmake.lua

improve mimalloc

---

packages/v/volk/xmake.lua

volk is a meta-loader for Vulkan, add it to xmake-repo
log: Add file xmake.lua in packages/v/volk/

feat: Add pacakge 'volk'

---

packages/i/ip2region/xmake.lua
packages/m/minhook/xmake.lua

add minhook and ip2region

---

packages/e/embree/xmake.lua
packages/f/fmt/xmake.lua
packages/m/metis/xmake.lua
packages/s/spdlog/xmake.lua

updated fmt (removed redundant configs; add windows runtime support)

add metis and embree

---

packages/g/glslang/xmake.lua
packages/l/libxcb/xmake.lua
packages/m/moltenvk/xmake.lua
packages/m/mpfr/xmake.lua
packages/s/spirv-tools/xmake.lua
packages/x/xcb-proto/xmake.lua

add mpfr and moltenvk

---

packages/h/hpsocket/port/xmake.lua
packages/h/hpsocket/xmake.lua

improve hpsocket and upgrade version to v5.7.3

improve hpsocket and upgrade version to v5.7.3

---

packages/v/vulkan-memory-allocator/xmake.lua

add package vulkan-memory-allocator with only a header

add vulkan-memory-allocator

---

packages/c/cgal/xmake.lua
packages/e/eigen/xmake.lua
packages/l/libigl/xmake.lua
packages/p/python/xmake.lua
packages/v/vulkan-headers/xmake.lua

- check required packages when installing python on linux
- update eigen to 3.3.9 (which fixed a major bug)

add cgal, libigl and fix some packages

---

packages/f/flatbuffers/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/73
May be closed?

add flatbuffers

---

packages/l/llhttp/xmake.lua

add llhttp

---

packages/b/boost/xmake.lua

Boost 1.75.0 updated:
https://www.boost.org/users/history/version_1_75_0.html

add boost 1.75.0

---

packages/l/libopus/patches/1.3.1/cmake.patch
packages/l/libopus/xmake.lua

Add libopus

---

packages/l/libogg/patches/1.3.4/macos_fix.patch
packages/l/libogg/xmake.lua
packages/l/libvorbis/xmake.lua

add libvorbis

---

packages/l/libflac/patches/1.3.3/cmake.patch
packages/l/libflac/xmake.lua

Add libflac

---

packages/l/libsndfile/xmake.lua

This is going to be fine...
From #203

Add libsndfile

---

packages/s/shaderwriter/xmake.lua

Add shaderwriter

---

packages/s/sentry-native/patches/0.4.4/zlib_fix.patch
packages/s/sentry-native/xmake.lua

From https://github.com/getsentry/sentry-native

Add sentry-native

---

.github/workflows/linux.yml

The default is gcc-7 and does not support C++17 :(

Set default compiler to gcc-9 on ubuntu-latest

---

packages/a/angelscript/xmake.lua

upgrade angelscript version to 2.35.0

upgrade angelscript version to 2.35.0

---

packages/l/libtool/xmake.lua
packages/l/libwebp/xmake.lua

improve libwebp

---

packages/l/libpng/xmake.lua
packages/l/libtiff/xmake.lua
packages/l/libwebp/xmake.lua

add mingw for libwebp

---

packages/n/nanovg/xmake.lua
packages/p/pugixml/xmake.lua

add pugixml and nanovg

---

packages/b/brynet/xmake.lua

Adds the networking library brynet

Add brynet

---

packages/s/sqlite3/xmake.lua

fix sqlite3

---

packages/m/mem/xmake.lua

Add mem package

---

.github/workflows/freebsd.yml
packages/g/giflib/xmake.lua
packages/l/libtiff/xmake.lua
packages/l/libwebp/xmake.lua
packages/z/zlib/xmake.lua
scripts/test.lua

add freebsd ci

---

packages/g/gamenetworkingsockets/port/xmake.lua
packages/g/gamenetworkingsockets/xmake.lua
packages/p/protobuf-cpp/xmake.lua

Fix protobuf-cpp and gamenetworkingsockets

---

packages/p/protobuf-c/xmake.lua

fix protobuf-c

---

packages/z/zlib/xmake.lua

rewrite zlib

---

packages/s/shaderwriter/xmake.lua

Add shaderwriter 1.0.0

---

.github/workflows/cross_musl.yml
packages/l/libpng/xmake.lua
packages/z/zlib/xmake.lua

fix libpng

---

packages/t/taskflow/xmake.lua

fix taskflow

---

packages/l/llvm/xmake.lua

add llvm for linux

---

packages/l/llvm-mingw/xmake.lua

add llvm-mingw

---

packages/m/muslcc/xmake.lua

add muslcc

---

packages/g/gnu-rm/xmake.lua

add gnu-rm toolchain

---

packages/l/libsodium/xmake.lua
packages/m/m4/xmake.lua

fix libsodium

---

packages/e/eudev/xmake.lua
packages/l/libusb/xmake.lua

improve and fix libusb

---

packages/l/libuv/xmake.lua

update and fix libuv

---

packages/l/libplist/xmake.lua

improve libplist

---

packages/m/mimalloc/xmake.lua

Add mimalloc version 1.7.0 and 2.0.0

---

packages/c/cef/xmake.lua

Support debug cef

---

packages/s/simdjson/port/xmake.lua
packages/s/simdjson/xmake.lua

This passes relevant CI on my fork. Please let me know if anything could be improved.

add simdjson

---

packages/t/tiltedcore/xmake.lua

Add v0.2.1 for tiltedcore

---

packages/s/sqlite3/xmake.lua

port sqlite3

---

.github/workflows/fedora.yml
packages/b/bzip2/xmake.lua
packages/e/expat/xmake.lua
packages/f/fontconfig/xmake.lua
packages/l/libuuid/xmake.lua
packages/l/libxft/xmake.lua
packages/u/util-linux/xmake.lua

add libxft

---

packages/g/godotheaders/xmake.lua

Adds the header-only Godot native interface library

Add godotheaders

---

.github/workflows/cross_musl.yml
packages/p/python/xmake.lua
packages/p/python2/xmake.lua

improve python

---

packages/l/libbpf/xmake.lua

add libbpf

---

packages/l/libcap/xmake.lua
packages/l/libelf/xmake.lua
packages/l/linux-tools/xmake.lua

add linux tools

---

packages/b/brotli/xmake.lua
packages/f/freetype/xmake.lua

improve freetype

---

packages/l/libcap/xmake.lua
packages/l/libelf/xmake.lua
packages/l/linux-tools/xmake.lua
packages/p/pcre2/xmake.lua

improve linux-tools

---

packages/a/argp-standalone/xmake.lua
packages/e/elfutils/patches/0.183/configure.patch
packages/e/elfutils/xmake.lua
packages/l/libelf/xmake.lua

improve libelf

---

packages/l/linux-tools/modules/bpftool.lua
packages/l/linux-tools/modules/libbpf.lua
packages/l/linux-tools/xmake.lua

improve linux tools

---

packages/n/ndk/xmake.lua

add android ndk

---

packages/l/libjpeg-turbo/xmake.lua

Improve libjpeg-turbo

---

packages/l/libfreenect2/xmake.lua

Improve freenect2

---

packages/c/cef/xmake.lua

Add missing resources

---

packages/s/sqlite3/xmake.lua

Update SQLite3 to 3.35.0

---

packages/i/imgui/xmake.lua

Update imgui to v1.82

---

packages/s/spdlog/xmake.lua

Fix wrong spdlog 1.8.5 hash

---

packages/f/fontconfig/xmake.lua
packages/l/libpng/xmake.lua
packages/n/ninja/xmake.lua
packages/s/skia/xmake.lua

improve skia

---

packages/l/libunwind/xmake.lua

add libunwind

---

packages/l/libjpeg/xmake.lua
packages/l/libtiff/xmake.lua

improve libtiff

---

packages/s/sqlite3/xmake.lua

sqlite3 3.35.0+400

---

packages/m/mimalloc/xmake.lua

1.7.1 and 2.0.1 of mimalloc

---

packages/c/catch2/xmake.lua

Catch2 v2.13.5

---

packages/c/cef/xmake.lua

CEF 90.5.3

---

packages/d/directxtk/xmake.lua

DirectxTK april 2021

---

packages/b/bullet3/xmake.lua

Bullet 3.09

---

packages/b/brotli/xmake.lua
packages/f/freetype/xmake.lua
packages/j/jasper/xmake.lua
packages/l/libraw/xmake.lua
packages/p/poppler/xmake.lua

jasper在windows上要求winsdk>=10.0.18362.0，ci上是10.0.17763.0会报错

add poppler and jasper

---

packages/s/shaderwriter/xmake.lua

Add shaderwriter 1.1.0.

---

packages/l/libsdl/xmake.lua

I added a on_fetch function which tries to use the sdl2-config tool and fallbacks on pkg-config
I also added an option to allow disable linking to SDL2main (which then automatically defines SDL_MAIN_HANDLED)

Improve libsdl package

---

packages/l/libsdl/xmake.lua

improve sdl with x

---

packages/g/glew/port/xmake.lua
packages/g/glew/xmake.lua

improve glew to support mingw

---

packages/f/faiss/xmake.lua
packages/l/libtorch/xmake.lua
packages/o/openblas/xmake.lua

CMake以及其他第三方库对openblas的命名约定都是openblas.lib(否则找不到)，故更名

update openblas and add faiss

---

packages/l/libmpdclient/xmake.lua

improve mdpclient to fix missing links

---

packages/l/libjpeg-turbo/xmake.lua
packages/p/pybind11/xmake.lua

pybind11设置了python不是binary，但没找到pythonlib的时候仍然返回已找到python，导致测试出问题

update some packages

---

packages/l/libsdl/xmake.lua

improve sdl to support bsd

---

.github/workflows/archlinux.yml
packages/l/linux-tools/modules/bpftool.lua

add archlinux ci

---

packages/l/lua-format/xmake.lua

add lua-format

---

packages/e/entt/xmake.lua
packages/f/flatbuffers/xmake.lua

update flatbuffers and entt

---

packages/i/imagemagick/xmake.lua

This needs to be tested on bsd and macosx before merging.
It should apparently work the exact same way as installing on Linux according to the docs, but I wanna be sure.
Edit: lol I forgot there are CIs for that.

add imagemagick package

---

packages/d/drogon/xmake.lua

add mysql as an optional dep, disable it if not used

update drogon package

---

packages/i/imagemagick/xmake.lua
packages/p/pkg-config/xmake.lua

This PR will update the `pkg-config` package to include BSD support, 
then update the `imagemagick` package to include BSD support.
This first commit only updates the `pkg-config` package, 
once it passes CI checks, I will work on the `imagemagick` package.

Update `pkg-config` and `imagemagick`

---

packages/b/bison/xmake.lua
packages/f/fmt/xmake.lua
packages/g/glib/xmake.lua
packages/l/libmpdclient/xmake.lua
packages/l/libxkbcommon/xmake.lua
packages/w/wayland/xmake.lua

improve libdir for meson

---

packages/p/pkgconf/xmake.lua

Currently still a draft, turns out it's installable on Windows too so I'll need to add Windows support to the pacakge.

add pkgconf package

---

packages/m/minimp3/xmake.lua

Add minimp3

---

packages/r/recastnavigation/port/xmake.lua
packages/r/recastnavigation/xmake.lua

Add recastnavigation

---

packages/l/libvorbis/xmake.lua

I think this could be improved by making separate xmake packages for vorbisenc and vorbisfile later (as they're separate packages for pkgconfig for example), but I'm not sure how to do that.

libvorbis: Add vorbisenc and vorbisfile support

---

packages/s/sqlite3/xmake.lua

Enable math functions in sqlite3

---

packages/g/gamenetworkingsockets/port/xmake.lua
packages/g/gamenetworkingsockets/xmake.lua

GameNetworkingSockets 1.3.0

---

packages/v/vulkan-hpp/xmake.lua

Adds Vulkan-Hpp. A C++ version of the Vulkan-Headers

Add Vulkan-Hpp

---

.github/workflows/windows.yml
packages/l/libtorch/xmake.lua

improve ci

---

packages/q/quickjs/xmake.lua

add quickjs

---

packages/b/benchmark/xmake.lua

fix benchmark

---

packages/c/capnproto/xmake.lua

Add capnproto

---

.github/workflows/archlinux.yml
packages/o/opencc/patches/1.1.2/fix-static.patch
packages/o/opencc/xmake.lua

Add OpenCC

---

packages/o/opencc/xmake.lua

fix static link to opencc

---

packages/m/marisa/port/CMakeLists.txt
packages/m/marisa/xmake.lua

add marisa-trie

---

packages/y/yaml-cpp/xmake.lua

enable yaml-cpp on mingw

---

packages/y/yasm/xmake.lua

add yasm for win

---

packages/o/opencv/xmake.lua

fix https://github.com/xmake-io/xmake-repo/issues/496

fix opencv

---

packages/l/lua/xmake.lua

add lua5.1.5

---

packages/o/opencl-clhpp/xmake.lua
packages/o/opencl/xmake.lua
packages/v/vexcl/xmake.lua

opencl具体实现要自己装gpu厂商的api，ci目前还没法测。本地windows测试可用，其他平台我这暂时没条件测

add opencl and vexcl

---

packages/l/luajit/port/xmake.lua
packages/l/luajit/xmake.lua

Add option to enable LuaJIT GC64 mode (`LUAJIT_ENABLE_GC64`).

add luajit gc64 option

---

.github/workflows/fedora.yml
packages/b/binutils/xmake.lua

fix binutils

---

packages/s/snappy/xmake.lua

Adds option to disable bzhi instructions in snappy.

add snappy bmi2 option

---

packages/b/blosc/xmake.lua
packages/g/gr/xmake.lua
packages/i/imath/xmake.lua
packages/o/openexr/xmake.lua
packages/o/openvdb/xmake.lua
packages/t/tbb/xmake.lua

openexr新版不再支持mingw；openvdb新版不再支持msvc /MT+shared的组合；这两种情况都已经提前报错了

update gr, openexr and openvdb

---

packages/p/protobuf-cpp/patches/3.17.3/field_access_listener.patch
packages/p/protobuf-cpp/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/530

update and fix protobuf

---

packages/f/freeglut/xmake.lua
packages/g/glfw/xmake.lua
packages/g/glu/xmake.lua
packages/g/glut/xmake.lua
packages/g/glx/xmake.lua
packages/o/opengl/xmake.lua
packages/p/pkg-config/xmake.lua

add opengl, glu and glut

---

packages/h/hwloc/xmake.lua
packages/x/xsimd/xmake.lua
packages/x/xtensor/xmake.lua
packages/x/xtl/xmake.lua

package描述文件里面似乎不能写add_vectorexts，所以暂时用add_cxxflags代替了

add hwloc, xtl, xsimd and xtensor

---

packages/r/raylib/xmake.lua

https://github.com/raysan5/raylib/releases/tag/3.7.0

update raylib 3.7.0

---

packages/b/box2d/xmake.lua

https://github.com/erincatto/box2d/releases/tag/v2.4.1

update box2d 2.4.1

---

packages/g/godotcpp/xmake.lua

Add version 3.3 to godotcpp

---

packages/o/opencv/xmake.lua

https://github.com/xmake-io/xmake/issues/1550
https://github.com/xmake-io/xmake-repo/pull/544

improve opencv

---

packages/l/libpng/xmake.lua

fix libpng for android armv7

---

.github/workflows/mingw_msys2.yml
packages/l/libusb/xmake.lua
packages/y/yasm/xmake.lua

add libusb for mingw32/64

---

packages/c/co/xmake.lua

- add version 2.0.1 for co
------

update xmake repo for co

---

packages/a/acl/xmake.lua
packages/a/attr/xmake.lua
packages/l/linux-headers/xmake.lua
packages/l/lz4/xmake.lua
packages/p/pkgconf/xmake.lua
packages/r/rsync/xmake.lua
packages/x/xxhash/xmake.lua
packages/z/zstd/xmake.lua

add and improve acl, attr and rsync

---

packages/a/automake/xmake.lua

update automake to support latest autoconf

---

.github/workflows/fedora.yml
packages/l/libice/xmake.lua
packages/l/libsm/xmake.lua
packages/o/ogre-next/patches/2.2.5/macosx.patch
packages/o/ogre-next/xmake.lua
packages/o/ogre/xmake.lua

macosx 上报错找不到符号sysctlbyname，我这没法调试

add ogre-next

---

packages/p/protobuf-cpp/xmake.lua

add protobuf-cpp 3.15.8

---

packages/a/assimp/patches/5.0.1/fix-mingw.patch
packages/a/assimp/xmake.lua
packages/f/freetype/xmake.lua

~~MinGW is normally able to use .lib files from MSVC (for C libraries)~~
In fact it cannot, maybe it was another version of MinGW. Anyway I fixed both of those packages with mingw (works with msys2 on my computer)

Add MinGW support for assimp and freetype

---

packages/p/protobuf-c/xmake.lua
packages/p/protobuf-cpp/xmake.lua

improve protobuf

---

packages/o/openssl/xmake.lua

- add openssl 1.1.1l 
- support static lib on windows

add openssl 1.1.1l & support static lib on windows

---

packages/d/devil/patches/1.8.0/jp2.patch
packages/d/devil/patches/1.8.0/static.patch
packages/d/devil/xmake.lua
packages/j/jasper/xmake.lua
packages/l/libjpeg-turbo/xmake.lua
packages/l/libmng/xmake.lua

devil的链接顺序出了问题：
devil依赖zlib、libjpeg、jasper，jasper又依赖zlib、libjpeg，正确的链接顺序应该是devil、jasper、libjpeg、zlib，但xmake test里面链接顺序是乱的，导致符号找不到

add libmng and devil

---

packages/k/kiwisolver/xmake.lua

Update Kiwisolver to 1.3.2

---

packages/f/freetype/xmake.lua

Fix freetype package

---

packages/f/freetype/patches/2.11.0/writing_system.patch
packages/f/freetype/xmake.lua

See https://gitlab.freedesktop.org/freetype/freetype/-/issues/1075

Freetype: Add patch for 2.11.0

---

packages/b/bzip2/patches/dllexport.patch
packages/b/bzip2/port/xmake.lua
packages/b/bzip2/xmake.lua

bzip2 didn't support dynamic build and didn't compile on mingw, so I remade it using a xmake.lua that should compile on every platform

Remake bzip2 using xmake.lua

---

packages/f/freetype/xmake.lua

I created a monster.
FindSomething.cmake worked on Windows but not on MinGW, so I added all include_dirs and libraries cmake options which fixed it.

Freetype: Fix package finding for MinGW

---

packages/l/libxml2/xmake.lua

improve libxml extsources

---

packages/l/libbacktrace/xmake.lua

- add a nice C/C++ [backtrace](https://github.com/ianlancetaylor/libbacktrace) library.

add package libbacktrace

---

packages/f/freetype/xmake.lua

Just found out there was a mistake with link order (zlib being used by png) and bzip2 cmake include config

Fix freetype for MinGW, again

---

packages/l/libjpeg/xmake.lua

improve libjpeg

---

packages/l/libsvm/xmake.lua

add libsvm

---

packages/l/libisl/xmake.lua

improve libisl

---

packages/c/co/xmake.lua

add v2.0.2 for co

---

packages/s/scnlib/xmake.lua

add scnlib

---

packages/c/ctre/xmake.lua

add ctre (Compile time regular expressions)

---

packages/p/pcre2/xmake.lua

fix pcre2 url

---

packages/a/atk/xmake.lua

I removed cairo to see if it works.

Add extsources to atk

---

packages/b/benchmark/xmake.lua
packages/b/binutils/xmake.lua

Maybe I can add commit one by one until it crashes to see how far I can go in one PR ?

Add extsources to benchmark

---

packages/t/toml++/xmake.lua

add toml++

---

packages/l/libgit2/xmake.lua

add libgit2

---

packages/l/libgcrypt/xmake.lua
packages/l/libgpg-error/xmake.lua
packages/l/libssh2/xmake.lua

Add libssh2

---

packages/j/jemalloc/patches/5.2.1/fix_nothrow_type.patch
packages/j/jemalloc/xmake.lua

Add jemalloc

---

packages/m/mio/xmake.lua
packages/p/parallel-hashmap/xmake.lua
packages/p/picojson/xmake.lua

add picojson, mio and hashmap

---

packages/q/quickjs/xmake.lua

quickjs:add missing header file,add bignum

quickjs:add missing header file,add bignum

---

packages/l/libspng/xmake.lua

add libspng

---

packages/i/imgui/xmake.lua
packages/i/imguizmo/xmake.lua

Sorry if i missed anything, it's my first time contributing.
I was obliged to changed the default includes file of imgui, if it's a problem let me know.

Add ImGuizmo and update ImGui

---

packages/c/cppcoro/xmake.lua

add cppcoro

---

packages/v/vulkan-validationlayers/xmake.lua

add android validation layers

---

packages/r/readerwriterqueue/xmake.lua

add readerwriterqueue

---

packages/l/libomp/xmake.lua
packages/o/openmp/xmake.lua

add openmp

---

packages/g/glslang/xmake.lua

Improve glslang

---

packages/s/shaderc/xmake.lua

Add shaderc

---

packages/e/e2fsprogs/xmake.lua

Add e2fsprogs to xmake repo

---

packages/e/e2fsprogs/xmake.lua

Enable libuuid in e2fsprogs

---

packages/l/libsdl/xmake.lua

fix sdl main

---

packages/o/openmp/xmake.lua

improve openmp

---

packages/l/libdivsufsort/xmake.lua

Add libdivsufsort

---

packages/b/bsdiff/port/Compat.h
packages/b/bsdiff/port/xmake.lua
packages/b/bsdiff/xmake.lua

Add bsdiff

---

packages/m/marl/xmake.lua

Add marl to xmake repo

---

packages/l/libtins/xmake.lua

add libtins

---

packages/z/zlib-ng/xmake.lua

Add zlib-ng

---

packages/t/texinfo/xmake.lua

add texinfo

---

.github/workflows/android.yml
packages/l/linux-headers/xmake.lua

improve linux-header to support driver modules

---

packages/l/libaco/xmake.lua

Add libaco

---

packages/p/pprint/xmake.lua

Add pprint

---

packages/o/optick/xmake.lua

Adds the API of the Profiler optick

Add optick

---

packages/l/liburing/xmake.lua
packages/l/libusbmuxd/xmake.lua
packages/x/xframe/xmake.lua

Add a whole bunch of libraries

---

packages/l/linux-headers/xmake.lua

support cross compilation for linux-headers

---

CONTRIBUTING.md
packages/b/boost/xmake.lua

those libs are presented on boost_1.77.0
Signed-off-by: yu bai <aiueclipse@mail.com>
The all libs can that required is got by execute `./b2 --show-libraries`.
------

add missing libs to boost/xmake.lua

---

packages/o/openssl/xmake.lua

improve openssl

---

packages/o/openblas/xmake.lua

Enable openmp for openblas

---

packages/h/hdf5/xmake.lua
packages/h/highfive/xmake.lua

Add highfive and improve hdf5

---

packages/o/openimageio/xmake.lua

utils such as igrep, idiff, iconvert are not very useful when using
openimageio as a library, therefore disable
------

Don't build openimageio utils

---

packages/l/libimobiledevice-glue/xmake.lua

Add libimobiledevice-glue

---

packages/l/libiconv/xmake.lua
packages/l/libidn2/xmake.lua
packages/l/libunistring/xmake.lua

这个地方libiconv的on_fetch写法不知道对不对，在find_package的时候要求有头文件存在

add libidn2

---

packages/a/automake/xmake.lua
packages/i/imgui-sfml/xmake.lua
packages/m/m4/xmake.lua
packages/s/sfml/xmake.lua

add imgui-sfml

---

packages/l/libimobiledevice/xmake.lua

Add libimobiledevice

---

packages/r/robotstxt/xmake.lua

Add robotstxt

---

packages/g/guetzli/xmake.lua

Add guetzli

---

packages/g/glib/xmake.lua
packages/l/libffi/xmake.lua

Add ext sources for glib/libffi

---

packages/c/crc32c/xmake.lua

Add crc32c

---

packages/w/wayland-protocols/xmake.lua

add wayland-protocols

---

packages/i/iso-codes/xmake.lua

add iso-codes

---

packages/l/libxml2/xmake.lua
packages/u/util-linux/xmake.lua

Add ext source for util-linux

---

packages/g/gdk-pixbuf/patches/2.42.6/macosx.patch
packages/g/gdk-pixbuf/xmake.lua
packages/g/glib/xmake.lua

Add gdk-pixbuf

---

packages/c/co/xmake.lua

add co v2.0.3

---

packages/t/toml11/xmake.lua
scripts/new.lua

add toml11

---

packages/s/sqlpp11/xmake.lua

Add sqlpp11

---

packages/a/assimp/xmake.lua

Assimp: Fix MinGW and update to 5.1.4

---

packages/m/mpmcqueue/xmake.lua

add mpmcqueue

---

packages/f/functionalplus/xmake.lua

add functionalplus

---

packages/r/raygui/xmake.lua
packages/r/raylib/xmake.lua

add raygui

---

packages/r/raylib/xmake.lua

improve raylib to support mac arm64

---

packages/c/cairo/xmake.lua
packages/f/fontconfig/xmake.lua
packages/g/gperf/xmake.lua
packages/h/harfbuzz/xmake.lua
packages/p/pixman/xmake.lua
packages/u/util-linux/xmake.lua

Enable fontconfig for cairo

---

packages/g/glib/patches/2.71.0/macosx.patch
packages/g/glib/xmake.lua

Fix glib apple framework dependency problem

---

packages/l/libsdl_image/xmake.lua

improve sdl_image

---

packages/m/miniaudio/xmake.lua

add miniaudio

---

packages/l/lz4/xmake.lua

Add ext source for lz4

---

packages/g/gdk-pixbuf/patches/2.42.6/macosx.patch
packages/g/gdk-pixbuf/xmake.lua

Fix gdk-pixbuf include dir

---

packages/noise-c/xmake.lua

add noise-c

---

packages/c/cocoyaxi/xmake.lua

Raname package co to cocoyaxi.

rename co to cocoyaxi

---

packages/p/promise-cpp/patches/2.1.3/cmake.patch
packages/p/promise-cpp/xmake.lua

add promise-cpp

---

packages/l/libpq/xmake.lua
packages/l/libpqxx/xmake.lua

add libpqxx

---

packages/t/toml++/xmake.lua

update toml++ v3.0.0

---

packages/l/libfiber/xmake.lua

add libfiber

---

packages/t/tinycrypt/xmake.lua

add tinycrypt

---

packages/l/libcpuid/xmake.lua

add libcpuid

---

packages/m/minilzo/xmake.lua

add minilzo

---

packages/m/msquic/xmake.lua

add msquic

---

packages/k/kompute/xmake.lua

add kompute

---

packages/d/debugbreak/xmake.lua

add debugbreak

---

packages/v/vulkan-headers/xmake.lua
packages/v/vulkan-memory-allocator/xmake.lua

support vulkan headers for android

---

packages/w/workflow/xmake.lua

add workflow

---

packages/f/fmt/xmake.lua
packages/f/fmtlog/xmake.lua

add fmtlog

---

packages/t/tbb/xmake.lua

support android for tbb

---

packages/i/imgui/xmake.lua

Update ImGui to v1.86

---

packages/w/workflow/xmake.lua

Workflow(无Android)

---

packages/s/shaderwriter/xmake.lua

Add shaderwriter 2.0.0.

---

packages/w/workflow/xmake.lua

update workflow from v0.9.9 to v0.9.10

---

packages/a/assimp/xmake.lua

with_pdb config was already broken, and enabling ASSIMP_INSTALL_PDB doesn't copy .pdb file to the right location so I had to copy it myself

assimp: fix .pdb installation

---

packages/g/gnu-rm/xmake.lua

add:gnu-rm 10.3-2021.10

---

packages/l/libwfkafka/xmake.lua
packages/z/zstd/xmake.lua

add libwfkafka

---

packages/o/onetbb/xmake.lua

add onetbb

---

packages/a/angelscript/xmake.lua

update angelscript to "2.35.1"

---

packages/a/asio/xmake.lua

update asio to "1.21.1"
------

update asio to "1.21.1"

---

packages/a/angelscript/xmake.lua
packages/a/armadillo/xmake.lua
packages/v/vulkan-memory-allocator/xmake.lua

update armadillo to 10.8.1

---

packages/o/openmesh/xmake.lua

update openmesh to "9.0"

---

packages/a/asmjit/xmake.lua

update asmjit to "9a92d2f"
------

update asmjit to "9a92d2f"

---

packages/l/librdkafka/xmake.lua

add rdkafka

---

packages/g/ghc_filesystem/xmake.lua

add ghc filesystem

---

packages/m/mongo-c-driver/xmake.lua
packages/m/mongo-cxx-driver/xmake.lua

1. new version 1.20.1 for mongo-c-dirver
2. add mongo-cxx-friver

update mongo-c-driver; add mongo-cxx-driver

---

packages/u/uvwasi/xmake.lua

add uvwasi

---

packages/s/sqlite3/xmake.lua

update sqlite3 to "3.37.200"

---

packages/n/ngtcp2/xmake.lua

add ngtcp2

---

packages/d/depot_tools/xmake.lua

add depot_tools

---

packages/t/tiltedcore/xmake.lua

Fix sha checksum for TiltedCore

---

packages/c/cef/patches/97.1.9/msvc_cpp20.patch
packages/c/cef/xmake.lua

CEF3 msvc C++20 fix

---

packages/c/cef/xmake.lua

I am an idiot

---

packages/i/isocline/xmake.lua

add isocline

---

packages/e/entt/xmake.lua

entt 3.9.0

---

packages/l/libdivide/xmake.lua

add libdivide

---

packages/g/gamenetworkingsockets/xmake.lua

gamenetworkingsockets 1.4.0

---

packages/n/nghttp3/xmake.lua

add nghttp3

---

packages/l/lua/xmake.lua

lua 5.4.4 & 5.4.3

---

packages/c/cereal/xmake.lua

Cereal 1.3.1

---

packages/f/folly/xmake.lua

Folly 2022.02.14

---

packages/m/mimalloc/xmake.lua

Update mimalloc to 2.0.5

---

packages/g/glog/xmake.lua

MinGW 和 BSD 编译过不了，没这个需求暂时不处理了。

glog: add platform android, iphoneos and cross.

---

packages/l/librdkafka/xmake.lua

improve librdkafka

---

packages/u/utf8proc/xmake.lua

正在尝试创建 apache arrow 包，这是其中一个依赖。
License 是 [MIT "expat" license](http://opensource.org/licenses/MIT)，不确定描述是否正确。

Add utf8proc

---

packages/p/pcre2/xmake.lua

pcre2: control jit option in description scope.

---

packages/l/librdkafka/xmake.lua

librdkafka: version 1.8.2-POST2, fix static lib build.

---

.github/workflows/ubuntu_clang.yml
packages/t/thrift/xmake.lua

目前仅支持 linux 和 macos，其他 platform 不太好搞。
flex 目前没有加 bsd，[windows](https://github.com/cyfdecyf/xmake-repo/runs/5415955599?check_suite_focus=true#step:5:132) 应该是没有编译出 lib。

add thrift

---

packages/n/nodeeditor/patches/2.1.3/fix_qt.patch
packages/n/nodeeditor/xmake.lua
packages/q/qt5base/xmake.lua

now that qt is a package, we can provide libraries using it

Add nodeeditor

---

packages/g/gyp-next/xmake.lua
packages/l/libcurl/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/1042

add gyp-next

---

packages/a/arrow/xmake.lua

在不增加其他库依赖的情况下，打开了 arrow 官方 cmake ninja-release preset 中开启的功能。这样的 config 会更加实用一点。

add apache arrow.

---

packages/t/tiltedcore/xmake.lua

TiltedCore v0.2.6

---

packages/l/libsdl/xmake.lua

Update libsdl to 2.0.20

---

packages/z/zstd/xmake.lua

按照 #1074 中的建议修改 pkgconfig 文件的名字。

zstd: change pkgconfig file name to libzstd.pc

---

packages/p/python/xmake.lua

add pic for python

---

packages/i/imgui/xmake.lua
packages/m/magnum-integration/xmake.lua

improve magnum

---

packages/a/assimp/patches/5.2.1/fix_zlib_filefunc_def.patch
packages/a/assimp/xmake.lua

update assimp to v5.2.3

---

packages/a/assimp/patches/5.2.3/cmake_static_crt.patch
packages/a/assimp/xmake.lua

See https://github.com/assimp/assimp/pull/4444

Fix assimp 5.2.3 with MTd and MDd runtimes

---

packages/x/xbyak/xmake.lua

xbyak 6.03

---

packages/o/opencv/xmake.lua

add apt install libopencv-dev to opencv/xmake.lua
------

add apt::libopencv-dev

---

packages/o/openssl/xmake.lua

The current openss install contains both `.so` and `.a` files on Linux.

openssl: fix shared and static.

---

packages/l/luajit/port/xmake.lua

fix luajit

---

packages/y/yyjson/xmake.lua

add yyjson 0.3.0 & 0.4.0

---

packages/m/magic_enum/xmake.lua

add magic_enum

---

packages/s/shaderwriter/xmake.lua

ShaderWriter: Update to version 2.2.0

---

packages/m/mapbox_variant/xmake.lua

Add mapbox_variant

---

packages/m/mapbox_eternal/patches/add_cstdint.patch
packages/m/mapbox_eternal/xmake.lua

Add mapbox_eternal

---

packages/f/frozen/xmake.lua

Add frozen

---

packages/c/cxxopts/xmake.lua

update(cxxopts): version 3.0.0

---

packages/z/zlibcomplete/xmake.lua

add zlibcomplete package

---

packages/l/lexy/xmake.lua

Add lexy package

---

packages/c/crashpad/xmake.lua

add crashpad

---

packages/e/entt/xmake.lua

entt 3.10.0

---

packages/v/vk-bootstrap/xmake.lua

Add support for Vulkan Bootstrapping Iibrary.

Adds vk-bootstrap

---

packages/v/vulkan-headers/xmake.lua

Adds a new version (v1.3.212) of vulkan headers.

Adds vulkan headers version

---

packages/l/libjpeg-turbo/xmake.lua

fix libjpeg

---

packages/l/libjpeg-turbo/xmake.lua

improve jpeg

---

packages/c/cryptopp/xmake.lua

cryptopp 8.5.0 & 8.6.0

---

packages/b/boost/xmake.lua
packages/f/folly/xmake.lua

Folly 2022.04.25

---

packages/a/aws-c-common/xmake.lua

new: aws-c-common package

---

packages/v/vulkan-headers/xmake.lua

vulkan-headers: remove platform limitation

---

packages/s/sfml/xmake.lua

SFML: fix links name on Linux/Windows

---

packages/r/raylib/xmake.lua

add mingw for raylib

---

packages/d/dbg-macro/xmake.lua

add dbg-macro

---

packages/a/aws-checksums/xmake.lua

Create `aws-checksums` package

new(packages/a/aws-checksums)

---

packages/l/libdeflate/xmake.lua
packages/l/libtiff/xmake.lua

Signed-off-by: neverfelly <neverfelly@gmail.com>
------

Fix build for libtiff&openimageio

---

packages/g/gpujpeg/xmake.lua

add gpujpeg

---

packages/f/ffmpeg/xmake.lua
packages/x/x264/xmake.lua

ffmpeg: Add support for pic compilation

---

packages/b/better-enums/xmake.lua

create better-enums package

---

packages/b/backward-cpp/patches/v1.6/fix_32bit_ssize_t_typedef.patch
packages/b/backward-cpp/patches/v1.6/link_to_imagehlp.patch
packages/b/backward-cpp/xmake.lua
packages/v/volk/xmake.lua
packages/v/vulkan-memory-allocator/xmake.lua

[Volk, Backward-cpp, VulkanMemoryAllocator] Add mingw support

---

packages/o/opencv/xmake.lua

fix opencv for mingw

---

packages/f/ffmpeg/xmake.lua

ffmpeg: Add support for shared compilation and fix license

---

packages/o/ordered_map/xmake.lua

Add ordered_map

---

packages/e/entt/xmake.lua

entt 3.10.1

---

packages/p/prometheus-cpp/xmake.lua

This PR creates the package for the `prometheus-cpp` library as per the title.

new(packages/p): create prometheus-cpp package

---

packages/s/spirv-headers/xmake.lua
packages/s/spirv-tools/xmake.lua

spirv-tools: update to 2022.2

---

packages/g/glslang/xmake.lua

glslang: add options to enable exceptions and rtti

---

packages/r/rendergraph/xmake.lua

RenderGraph: Update to v1.1.0

---

packages/s/shaderwriter/xmake.lua

ShaderWriter: Update to v2.3.0

---

packages/e/eabase/xmake.lua

fix eabase

---

packages/l/luajit/port/xmake.lua
packages/l/luajit/xmake.lua

revert luajit

---

packages/b/boost/xmake.lua

improve boost

---

packages/f/flecs/xmake.lua

Added new flecs package. For more infos check [here](https://github.com/SanderMertens/flecs).

create flecs package

---

packages/z/zycore-c/xmake.lua

add package: zycore-c, using as the dependency for package "zydis"
i've already run ci in my fork version. it works fine.

add package: zycore-c

---

packages/e/elfutils/xmake.lua

Improve elfutils

---

packages/z/zycore-c/xmake.lua

Zycore c add v1.1.0

---

packages/t/thrust/xmake.lua

remove redundant deps

---

packages/b/blend2d/xmake.lua

add blend2d

---

packages/g/git-crypt/xmake.lua

add git-crypt

---

.github/workflows/wasm_macos.yml
.github/workflows/wasm_ubuntu.yml
scripts/packages.lua
scripts/test.lua

Add wasm ci

---

packages/s/snmalloc/xmake.lua

add snmalloc

---

packages/b/boost/xmake.lua

enable mingw for boost

---

packages/l/littlefs/xmake.lua

add littlefs

---

packages/t/toml++/xmake.lua

update toml++ to v3.1.0

---

packages/i/imguizmo/xmake.lua

improve imguiemo

---

packages/i/imguizmo/xmake.lua

Add tests for Imguizmo

---

packages/d/demumble/xmake.lua

add demumble

---

packages/l/libwfkafka/xmake.lua
packages/w/workflow/xmake.lua

https://github.com/sogou/workflow/releases/tag/v0.10.2

Add workflow and libwfkafka v0.10.2

---

packages/m/managedc/xmake.lua

Managed C is a garbage collector for C

Added ManagedC

---

packages/i/imgui-sfml/xmake.lua

improve imgui-sfml

---

packages/o/openssl/fetch.lua

Issue: https://github.com/xmake-io/xmake-repo/issues/1315

fix openssl package nil crash on windows.

---

packages/o/onnxruntime/xmake.lua

https://github.com/microsoft/onnxruntime
使用预编译的onnxruntime。

onnxruntime

---

packages/o/onnxruntime/xmake.lua

添加gpu选项，目前可能只有在 windows 下可用，linux版本可能需要新增 [TensorRT ](https://github.com/NVIDIA/TensorRT) 包，才可通过测试。

onnxruntime gpu config

---

packages/m/mapbox_earcut/patches/2.2.3/mingw.patch
packages/m/mapbox_earcut/xmake.lua

Add (mapbox_earcut)[https://github.com/mapbox/earcut.hpp].
close #1327

Add mapbox_earcut

---

packages/c/cpr/xmake.lua

Make package cpr support MinGW@Windows

---

packages/m/marl/xmake.lua

add_versions 2022.3.02
More fixes and support.

google/marl  add_versions 2022.3.02

---

packages/l/libfswatch/xmake.lua

https://github.com/xmake-io/xmake/issues/2555

add libfswatch

---

packages/g/gamenetworkingsockets/port/xmake.lua
packages/g/gamenetworkingsockets/xmake.lua

Because of : https://github.com/ValveSoftware/GameNetworkingSockets/issues/243

GameNetworkingSockets: use openssl backend on windows 

---

packages/t/tiny-process-library/xmake.lua

Add tiny-process-library

---

packages/o/openssl/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/1355

improve openssl #1355

---

packages/s/sfml/xmake.lua

Fix sfml pthread link

---

packages/m/mariadb-connector-c/xmake.lua

improve mariadb dll

---

packages/s/sentry-native/xmake.lua

fix sentry-native

---

packages/f/fmt/xmake.lua

Added 9.0.0 version of fmt

---

packages/a/argparse/xmake.lua

Added argparse C++17 header only library (https://github.com/p-ranav/argparse)

Created argparse lib package

---

packages/d/doctest/xmake.lua

Added 2.4.9 version of doctest

---

packages/f/fast_float/patches/emscripten_fix.patch
packages/f/fast_float/xmake.lua

See https://github.com/fastfloat/fast_float/issues/136
Fixes compilation with emscripten

Fast float wasm

---

packages/k/kiwisolver/xmake.lua

Update kiwisolver to 1.4.4

---

packages/m/matlab/xmake.lua

add matlab package to adapt new find_matlab func

[add]:add matlab package

---

packages/l/libev/xmake.lua

improve libev

---

packages/j/json-schema-validator/xmake.lua

Aadd json-schema-validator package

---

packages/n/nodeeditor/patches/2.2.2/fix_qt.patch
packages/n/nodeeditor/xmake.lua

Update nodeeditor version

---

packages/s/shaderwriter/xmake.lua

ShaderWriter: Update to v2.4.0.

---

packages/l/libsdl/xmake.lua

libsdl: Update to 2.0.22

---

packages/t/thread-pool/xmake.lua

add thread-pool package

---

packages/c/clip/xmake.lua

Adds clip:
https://github.com/dacap/clip
"Library to copy/retrieve content to/from the clipboard/pasteboard."

add clip package

---

packages/x/xxhash/xmake.lua

update xxhash v0.8.1

---

packages/l/libcurl/xmake.lua

improve libcurl for macos

---

packages/y/yyjson/xmake.lua

Update yyjson 0.5.0 & 0.5.1

---

packages/c/cgal/xmake.lua
packages/l/libigl/xmake.lua

make libigl(and cgal) support mingw

---

packages/c/cumem/xmake.lua

------
Revision of merge request #1415

Added cumem

---

packages/b/btree/xmake.lua
packages/f/frozenca-btree/xmake.lua

add frozenca-btree

---

packages/g/gtk+4/xmake.lua

add gtk4 package

---

packages/d/directxtk/xmake.lua

https://github.com/xmake-io/xmake/issues/2714#issuecomment-1226666813

fix directxtk

---

packages/r/raylib/xmake.lua

update raylib 4.2.0

---

packages/f/fmt/xmake.lua

update fmt to 9.1.0

---

packages/a/asio/xmake.lua

 update asio to "1.24.0"

---

packages/f/folly/xmake.lua

update folly to v2022.08.29.00

update folly to v2022.08.29.00

---

packages/c/coost/xmake.lua

- Rename cocoyaxi to coost.
- Add coost v3.0.0.

rename cocoyaxi to coost and add coost v3.0.0

---

packages/i/imgui/port/xmake.lua
packages/i/imgui/xmake.lua

update imgui vulkan backend

---

packages/g/grpc/xmake.lua

add grpc@{linux, macosx, windows}

---

packages/m/magic_enum/xmake.lua

update magic_enum to v0.8.1

---

packages/l/libffi/xmake.lua
packages/o/openssl/xmake.lua

support bsd for libffi

---

packages/n/ninja/xmake.lua
packages/s/scons/xmake.lua

enable bsd for build tools

---

packages/r/reproc/xmake.lua

reproc package for "starting, stopping and communicating with external programs".

adds reproc package

---

packages/l/libhv/xmake.lua

update libhv to 1.2.6
already test the 1.2.6 source code with config in local machine.

update libhv to 1.2.6

---

packages/l/libffi/xmake.lua
packages/p/pcre/xmake.lua

enable cross for pcre and libffi

---

packages/l/libffi/xmake.lua

enable mingw for libffi

---

packages/t/tesseract/xmake.lua

Add Tesseract v5.2.0 and 5.0.1

Add Tesseract v5 versions

---

packages/f/fmt/xmake.lua
packages/s/spdlog/xmake.lua
packages/v/vulkan-hpp/xmake.lua

update `on_test` languages version

---

packages/u/uchardet/xmake.lua

add uchardet

---

packages/c/cppfront/xmake.lua

add cppfront

---

packages/m/mkl/xmake.lua

修复 mkl 指定 `threading=openmp` 安装失败的问题。
同时提供 `threading=gomp` 选项，使用 libgomp 作为 openmp runtime。
说明：使用 Intel openmp 时为何链接 `libomp` 而不是 `libiomp`？
- 从这个 Intel employee 的[回答](https://community.intel.com/t5/Intel-C-Compiler/Intel-OpenMP-vs-LLVM-OpenMP-runtimes/m-p/1126358#M33526)来看，llvm openmp 和 intel openmp 来自相同的代码
- Ubuntu 的 libiomp5 包也仅是依赖了 libomp5，并未提供实际的库文件
@xq114 方便的话麻烦 review 下这个 PR，非常感谢提供 mkl 这个包。
@waruqi 遇到个奇怪的问题，使用最新的 xmake，Ubuntu 和 Arch 上执行 `xrepo install -f threading=openmp mkl` 均无法设定 threading 选项，mkl 包的其他选项没问题。使用 lua 脚本指定 configs 可以生效。

mkl: fix threading=openmp, add threading=gomp.

---

packages/c/commonlibsse-ng/port/xmake.lua
packages/c/commonlibsse-ng/xmake.lua

Added `commonlibsse-ng` package, along with an xmake port.

[commonlibsse-ng] Add package

---

packages/g/glib/xmake.lua

enable cross for glib

---

packages/c/cmake/xmake.lua

CMake GitHub download url was wrong on Windows

Update cmake to 3.24.2 and fix Windows URL

---

packages/i/imgui/port/xmake.lua
packages/i/imgui/xmake.lua

\+ allow to enable multiple backends (there's no reason multiple backends can't be enabled)

imgui: Add support for sdl2 renderer

---

packages/p/poco/xmake.lua

update poco to 1.12.2

---

packages/g/glog/xmake.lua

update glog to 0.6.0

---

packages/c/coost/xmake.lua

fix links for coost

---

packages/l/libcurl/xmake.lua

improve mingw for curl

---

packages/l/libiconv/xmake.lua
packages/r/raygui/xmake.lua

improve mingw for libiconv

---

packages/h/hiredis/xmake.lua

fix hiredis

---

.github/workflows/windows.yml

add arm64 for windows

---

packages/e/effcee/xmake.lua

improve effcee

---

packages/f/ffmpeg/xmake.lua

improve ffmpeg

---

packages/a/abseil/xmake.lua

improve abseil

---

packages/g/glad/xmake.lua

improve glad

---

packages/o/openssl/xmake.lua

improve openssl for supporting windows arm64

---

packages/x/xege/xmake.lua

`xege`, or Easy Graphics Engine (EGE), is a graphics library in Windows. It implements most of the features of [BGI](https://en.wikipedia.org/wiki/Borland_Graphics_Interface). This library will be helpful for education.
`xege`，即简单图形引擎，是 Windows 上的一个图形库，实现了 [BGI](https://en.wikipedia.org/wiki/Borland_Graphics_Interface) 的大部分功能。该库在教育上非常有用。
*I've test the package under MSVC 17 and MinGW v10 (GCC 12).*

Add EGE library

---

packages/s/spdlog/xmake.lua

fix spdlog

---

packages/w/websocketpp/xmake.lua

add websocketpp

---

packages/i/imguizmo/xmake.lua

Update ImGuizmo version

---

packages/c/commonlibsse-ng/rules/plugin.lua
packages/c/commonlibsse-ng/xmake.lua

[commonlibsse-ng] Add package rule `plugin`

---

packages/s/sfml/xmake.lua

support component for sfml

---

packages/l/libpng/xmake.lua

improve libpng

---

packages/s/sentencepiece/xmake.lua

This library cannot be compiled in shared mode on Windows so I disabled it,
https://github.com/google/sentencepiece

Add Sentencepiece

---

packages/f/freetype/xmake.lua

add pkgconf

---

packages/p/pkgconf/xmake.lua

Improve pkgconf

---

packages/t/toml++/xmake.lua

Also fixes a wrong hash for v3.1.0

[toml++] Add `v3.2.0`

---

packages/c/catch2/xmake.lua

fix links for catch2

---

packages/d/d3d12-memory-allocator/xmake.lua

D3d12 memory allocator

---

packages/g/gdal/xmake.lua
packages/o/openjpeg/patches/2.5.0/build.patch
packages/o/openjpeg/xmake.lua
packages/p/proj/xmake.lua

add proj version and add gdal package

add proj version and add gdal package

---

packages/t/tracy/xmake.lua

**Tracy Profiler**
>A real time, nanosecond resolution, remote telemetry, hybrid frame and sampling profiler for games and other applications.
https://github.com/wolfpld/tracy

new package tracy

---

packages/p/protobuf-c/patches/1.3.1/342.patch
packages/p/protobuf-c/xmake.lua
packages/p/protobuf-cpp/xmake.lua

improve proto to support win arm

---

packages/g/gdal/xmake.lua

fix gdal compile on msvc debug mode
```
on_load("windows", function (package)
--fix gdal compile on msvc debug mode
if package:debug() then
package:config_set("cxxflags", "/FS")
package:config_set("cflags", "/FS")
end
end)
```

fix gdal compile on msvc debug mode

---

packages/d/dpp/port/xmake.lua
packages/d/dpp/xmake.lua

now developers can now enable or disable the voice support on the library

dpp: add config for voice support

---

packages/c/coost/xmake.lua

add backtrace

---

packages/d/dynareadout/xmake.lua

fix link order

---

packages/r/raw_pdb/xmake.lua

add raw_pdb

---

packages/h/hash-library/xmake.lua

add hash-library

---

packages/l/libsimdpp/xmake.lua

add libsimdpp

---

packages/d/discord/patches/2.5.6/add_include_cstdint_to_typeh.patch
packages/d/discord/patches/3.2.1/add_include_cstdint_to_typeh.patch
packages/d/discord/port/xmake.lua
packages/d/discord/xmake.lua

Improve discord sdk

---

packages/b/blake3/xmake.lua

blake3 is a secure and insanely fast cryptographic function

add blake3

---

packages/m/minifb/xmake.lua

add minifb

---

packages/l/libusb/xmake.lua

improve libusb

---

packages/s/shaderwriter/xmake.lua

ShaderWriter: Update to v2.5.0

---

packages/c/commonlibsse-ng/xmake.lua

Add `v3.6.0`, no further changes.

[commonlibsse-ng] Add `v3.6.0`

---

packages/q/quickcpplib/xmake.lua

add quickcpplib

---

packages/o/outcome/xmake.lua

Add Outcome

---

packages/n/ntkernel-error-category/port/xmake.lua
packages/n/ntkernel-error-category/xmake.lua

First needed library (XMake version) for #1631

Improve ntkernel-error-category

---

packages/l/libsdl/xmake.lua

Update libsdl to 2.26.0

---

packages/o/outcome/xmake.lua

improve outcome

---

packages/c/concurrencpp/xmake.lua

add concurrencpp

---

packages/s/simplethreadpool/xmake.lua
packages/t/threadpool/xmake.lua

add simplethreadpool package

---

.github/workflows/android.yml
.github/workflows/archlinux.yml
.github/workflows/cross_musl.yml
.github/workflows/deploy.yml
.github/workflows/fedora.yml
.github/workflows/iphoneos.yml
.github/workflows/macos.yml
.github/workflows/mingw_macos.yml
.github/workflows/monkey_linux.yml
.github/workflows/monkey_macos.yml
.github/workflows/monkey_windows.yml
.github/workflows/ubuntu.yml
.github/workflows/ubuntu_clang.yml
.github/workflows/wasm_ubuntu.yml
.github/workflows/windows.yml

enable action cache for xmake

---

packages/d/dynareadout/xmake.lua
packages/j/johnnyengine/xmake.lua
packages/l/libsdl_gfx/patches/1.0.4/add-x64-support.patch
packages/l/libsdl_gfx/xmake.lua

I just changed my username to **PucklaJ**. And therefore I wanted to reflect that in xmake-repo. This also completely removes the mention of my name in the patch of `libsdl_gfx`

Change mentions of PucklaMotzer09 -> PucklaJ, due to change of username

---

packages/t/termcolor/xmake.lua

add termcolor (https://github.com/ikalnytskyi/termcolor)

add termcolor

---

.github/workflows/wasm_ubuntu.yml
packages/b/bullet3/xmake.lua

Bullet3: Enable all platforms

---

packages/u/usd/xmake.lua

A new package [usd](https://github.com/PixarAnimationStudios/USD)
>Universal Scene Description (USD) is an efficient, scalable system for authoring, reading, and streaming time-sampled scene description for interchange between graphics applications.
Please note that the `usd` only support its dependency `tbb` with version `2020`
https://github.com/PixarAnimationStudios/USD/issues/1471

new package usd

---

packages/s/stb/xmake.lua

add missing stb_vorbis.c

---

packages/u/uriparser/xmake.lua

Added 0.9.6 and 0.9.7 versions to uriparser package

Add uriparser versions 0.9.6 and 0.9.7 to repo

---

packages/u/unordered_dense/xmake.lua

Added versions v1.4.0, v2.0.2, and v3.0.0

Add unordered_dense versions v1.4.0, v2.0.2, and v3.0.0

---

packages/c/cpuinfo/xmake.lua

Add cpuinfo

---

packages/i/imgui/port/xmake.lua
packages/i/imgui/xmake.lua

This PR closes #1687.
There's some duplicate code between the GLFW+OpenGL3 and SDL2+OpenGL3 configs - I didn't refactor this because I didn't want to affect existing code. Should this be cleaned up before merging?

Add SDL2+OpenGL3 backend to imgui

---

packages/c/cryptopp/xmake.lua

Adding cryptopp 8.7

---

packages/o/openssl3/fetch.lua
packages/o/openssl3/xmake.lua

Signed-off-by: Bradford Zhang <zyc@zyc.name>

add package openssl3

---

packages/n/nowide_standalone/xmake.lua

add package nowide

---

packages/l/libaesgm/xmake.lua
packages/p/pdfhummus/xmake.lua

add pdfhummus

---

packages/b/blake3/xmake.lua

Add Blake 1.3.3

---

packages/s/subprocess.h/xmake.lua

add subprocess.h

---

packages/j/json.h/xmake.lua

add json.h

---

packages/u/utf8.h/xmake.lua

add utf8.h

---

packages/l/libmill/xmake.lua

fix libmill

---

packages/l/libdill/xmake.lua

add libdill

---

packages/l/leveldb/xmake.lua
packages/l/libzip/xmake.lua

fix leveldb

---

packages/b/brpc/xmake.lua
packages/p/protobuf-cpp/xmake.lua

improve brpc

---

packages/i/iverilog/xmake.lua

add iverilog

---

packages/v/verilator/xmake.lua

improve verilator

---

packages/v/verilator/xmake.lua

add VERILATOR_ROOT env in verilator

---

packages/g/gcem/xmake.lua

Added new version for package gcem

---

packages/s/sparsepp/xmake.lua

add sparsepp

---

packages/m/mathfu/xmake.lua
packages/v/vectorial/xmake.lua

add mathfu and vectorial

---

packages/r/rpclib/xmake.lua

add rpclib

---

packages/f/fast_io/xmake.lua

Significantly faster input/output for C++20

add fast_io

---

packages/e/entt/xmake.lua

Update EnTT to v3.11.1

---

packages/o/olive.c/xmake.lua

add olive.c

---

packages/l/libwfkafka/xmake.lua
packages/w/workflow/xmake.lua

Use xmake in libwfkafka package

---

packages/r/rendergraph/xmake.lua

RenderGraph: Update to v1.2.0.

---

packages/c/cli11/xmake.lua
packages/g/ghc_filesystem/xmake.lua
packages/g/gmsh/xmake.lua

update ghc_filesystem, gmsh and cli11

---

packages/m/msdfgen/xmake.lua

https://github.com/Chlumsky/msdfgen

Add msdfgen

---

packages/u/usd/xmake.lua

- add new usd version v23.02
- fixed tbb link error when build usd with debug mode

[usd] add new version and fix tbb link error

---

packages/g/gumbo-parser/xmake.lua
packages/l/litehtml/xmake.lua

add litehtml

---

packages/l/libuuid/xmake.lua

Make libuuid available on android/ios

---

packages/f/fluxsort/xmake.lua
packages/q/quadsort/xmake.lua

add quadsort and fluxsort

---

.github/workflows/ubuntu_clang.yml
packages/l/lightgbm/xmake.lua

LightGBM v3.3.3 ~ v3.3.5 are special release used to prevent R package from being archived on CRAN. So v3.3.2 is the actual latest release for now.

lightgbm: add version v3.3.2

---

packages/a/apr/xmake.lua

improve apr

---

packages/b/bzip2/port/xmake.lua
packages/b/bzip2/xmake.lua

Fix bzip2 when cross-compiling from Windows

---

packages/b/boost/xmake.lua

improve boost with python

---

packages/v/vulkanscenegraph/xmake.lua

ci上没安装vulkansdk，这里安装不了；我本地测试是可以的

add vulkanscenegraph

---

.github/workflows/mingw_msys2.yml
packages/b/boost/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/1806

improve boost for mingw

---

packages/c/cpp-lazy/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/1814

Add package cpp-lazy

---

packages/t/toml++/xmake.lua

Adds version `v3.3.0` to `toml++`

[toml++] Add `v3.3.0`

---

packages/o/orangeduck_mpc/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/1819

add orangeduck mpc

---

packages/l/linenoise/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/1819

add linenoise

---

packages/b/brpc/patches/1.4.0/cmake.patch
packages/b/brpc/xmake.lua

* Add brpc version 1.4.0.
* Change the add_urls() parameter to the url of the release version.
------
* 添加brpc 1.4.0版本。
* 将add_urls()参数更改为发布版本的url。

Add brpc version 1.4.0 & improve add_urls

---

packages/l/libaio/xmake.lua

add libaio

---

packages/q/quake_triangle/xmake.lua
packages/t/tetgen/xmake.lua

add tetgen and quake_triangle

---

.github/CODEOWNERS
xmake.lua

remove root xmake.lua

---

packages/s/spdlog/xmake.lua

- Fixed typo: `SPDLOG_COMPILE_LIB` -> `SPDLOG_COMPILED_LIB`.
- Fixed `fmt_external` option
- Added `fmt_external_ho` option
- Added `SPDLOG_NO_EXCEPTIONS` define for `noexcept` option.
- Added `wchar` option.

[spdlog] Fix package issues

---

packages/c/commonlibsse-ng/port/xmake.lua
packages/c/commonlibsse-ng/xmake.lua

Set `spdlog`'s `header_only` option to false

[commonlibsse-ng] Edit `spdlog` dependency

---

packages/a/assimp/xmake.lua

use external zlib for assimp

---

packages/z/zig/xmake.lua

zig 0.10.1

---

packages/p/python/fetch.lua

https://github.com/xmake-io/xmake-repo/issues/1852#issuecomment-1441225355

fix python fetch

---

packages/o/openal-soft/xmake.lua

Restore Openal Soft on MinGW@macosx

---

packages/l/libsdl/xmake.lua

fix links in debug mode

---

packages/o/opencv/xmake.lua

Add tesseract option to opencv

---

packages/l/libwfkafka/xmake.lua
packages/w/workflow/xmake.lua

Fix libwfkafka's description.

---

packages/p/pocketpy/xmake.lua

C++17 header-only Python interpreter for game engines.

add pocketpy

---

packages/t/trompeloeil/xmake.lua

Adds the trompeloeil mocking library.

add trompeloeil

---

packages/u/uni_algo/xmake.lua

Unicode Algorithms Implementation for C/C++

add uni_algo

---

packages/d/directxshadercompiler/patches/disable_go_bindings.patch
packages/d/directxshadercompiler/xmake.lua

- update directx shader compiler to [v1.7.2212](https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.7.2212)
- add support for linux

Update directx shader compiler

---

packages/x/xerces-c/xmake.lua

update: update xerces-c to 3.2.4

update: update xerces-c to 3.2.4

---

packages/e/efsw/xmake.lua

Update efsw and enable iOS

---

packages/s/span-lite/xmake.lua

add span-lite

---

packages/l/libuuid/xmake.lua

improve uuid to support android on windows

---

packages/g/glslang/xmake.lua
packages/s/spirv-headers/xmake.lua
packages/s/spirv-tools/xmake.lua

Add all platforms for glslang and spirv-tools (and update)

---

packages/b/bullet3/xmake.lua

Update bullet3 to 3.25
