xmake-io/xmake-repo

packages/r/rmlui/xmake.lua

* fix RmlUi build error on macOS Apple M1 arch arm64
* https://github.com/xmake-io/xmake/issues/3469

add config CMAKE_OSX_ARCHITECTURES for RmlUi

---

packages/q/qt5base/xmake.lua
packages/q/qt5gui/xmake.lua

Now xmake/dev can automatically find Qt sdk from qt5base

improve qt5base

---

packages/r/rocksdb/xmake.lua

add rocksdb

---

packages/l/llvm/fetch.lua

improve llvm fetch

---

packages/s/snitch/xmake.lua

Lightweight C++20 testing framework.

add snitch

---

packages/l/llama.cpp/xmake.lua

add llama.cpp

---

packages/o/openssl/xmake.lua

disable tests for openssl

---

packages/c/c-ares/xmake.lua

rewrite c-ares

---

packages/u/utf8_range/xmake.lua

add utf8 range

---

packages/g/grpc/patches/1.51.3/disable-download-archive.patch
packages/g/grpc/patches/1.51.3/static-linking-in-linux.patch
packages/g/grpc/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/1910

improve grpc

---

packages/b/base-n/xmake.lua

add base-n

---

packages/s/sqlcipher/port/xmake.lua
packages/s/sqlcipher/xmake.lua

add sqlcipher

---

packages/v/vulkan-memory-allocator-hpp/xmake.lua

------
add hpp bindings of VulkanMemoryAllocator. According to [this issue](https://github.com/KhronosGroup/Vulkan-Hpp/issues/1501#issuecomment-1474750506) , it is better to work with Vulkan version < 1.3.234.

add vulkan-memory-allocator-hpp

---

packages/g/godotcpp/xmake.lua

Add godotcpp version 3.4.5/3.5/3.5.1/3.5.2.
source: https://github.com/godotengine/godot-cpp/tags

Update godotcpp version to 3.5.2

---

packages/g/glog/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/1924

add pthread for glog

---

packages/j/joltphysics/port/xmake.lua
packages/j/joltphysics/xmake.lua

fix debug_renderer and profile option and enable Windows ARM support

Improve JoltPhysics

---

packages/v/vulkan-hpp/xmake.lua

try to add andoird and iphone support to vulkan-hpp

---

packages/m/meson/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/1937

disable precompiled package for meson

---

packages/l/libkmod/port/config.h
packages/l/libkmod/port/endian-darwin.h
packages/l/libkmod/port/xmake.lua
packages/l/libkmod/xmake.lua

Add libkmod , a library for reading/manipulating kernel modules.

Add libkmod

---

packages/c/cpp-httplib/xmake.lua

Update cpp-http to 0.12.1

---

packages/d/dartsim/xmake.lua

add dartsim

---

packages/c/catch2/xmake.lua
packages/c/cxxopts/xmake.lua
packages/d/dbus/xmake.lua
packages/n/nativefiledialog-extended/xmake.lua

add nativefiledialog-extended

---

packages/h/hlslpp/xmake.lua

add c++ headeronly library hlslpp

add hlslpp

---

packages/v/vulkan-memory-allocator-hpp/xmake.lua

update vma-hpp version

---

packages/p/pulsar/xmake.lua

add pulsar

---

packages/n/nanobench/xmake.lua

Add nanobench

---

packages/c/convertutf/xmake.lua

Add [`convertutf`](https://github.com/xmake-mirror/convertutf)
Pre-requisite for `simpleini`

[convertutf] Add package

---

packages/s/simpleini/xmake.lua

Added [simpleini](https://github.com/brofield/simpleini)

[simpleini] Add package

---

packages/s/simpleini/xmake.lua

[simpleini] Fix `define` to `defines`

---

packages/c/commonlibsse-ng/rules/plugin.lua

Use `on_changed` to regenerate plugin support files only when necessary.

[commonlibsse-ng] Use `on_changed` for rule

---

packages/i/inja/xmake.lua

inja switch to c++17 after v3.4.0 https://github.com/pantor/inja/releases/tag/v3.4.0, that will cause `add_requires("inja master")`
so fix it

Update inja v3.4.0

---

packages/b/bullet3/xmake.lua

bullet3: Fix debug suffix

---

packages/l/lua/xmake.lua

add lua.hpp for cxx to include it

add lua.hpp for c++ easy to use

---

packages/l/libcurl/versions.lua
packages/l/libcurl/xmake.lua
packages/l/libpsl/xmake.lua
packages/m/meson/xmake.lua

https://github.com/orgs/xmake-io/discussions/3620#discussioncomment-5589748

add libpsl for libcurl

---

packages/s/s7/port/xmake.lua
packages/s/s7/xmake.lua

s7 provides an nightly tarball as official source download, which has a unstable hash. Maybe we should fork it at xmake-mirror
------

add s7 as binary tool and libary

---

packages/m/mysql/xmake.lua

update mysql ,add windows support

update mysql ,add windows support

---

packages/m/mysql/xmake.lua

Correctly distinguish between dynamic and static libraries

update mysql windows lib

---

packages/s/sqlpp11/xmake.lua

Update sqlpp11 to add mysql support

---

packages/b/boost/xmake.lua

remove dependency on msys for boost

---

packages/b/boost/xmake.lua

fix boost for macos

---

packages/m/mysql/xmake.lua

编译需要 vs 2019 ，但是翻了下文档，没看到有在 xmake.lua 里面设置vs版本的地方

update mysql to 8.0.31 and build from source

---

packages/p/python/xmake.lua

update win  python version to 3.11

---

packages/j/joltphysics/xmake.lua

Update JoltPhysics to 3.0.1

---

packages/l/libhv/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/1973
用的这个版本的mingw测试 https://github.com/mstorsjo/llvm-mingw/releases

add mingw support to libhv

---

packages/v/visit_struct/xmake.lua
packages/y/yaml_cpp_struct/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/2013

add yaml_cpp_struct

---

packages/c/cpuinfo/xmake.lua

Fix cpuinfo compilation on posix

---

packages/a/async_simple/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/2020

add async_simple

---

packages/a/abseil/xmake.lua
packages/g/grpc/xmake.lua

improve grpc tests

---

packages/r/redis-plus-plus/xmake.lua

* Add redis-plus-plus version 1.3.8
------
* 添加redis-plus-plus 1.3.8版本

Add redis-plus-plus version 1.3.8

---

packages/o/openpgl/xmake.lua

Intel(R) Open Path Guiding Library.

add openpgl

---

packages/c/cpp-peglib/xmake.lua

A single file C++ header-only PEG (Parsing Expression Grammars) library.

add cpp-peglib

---

packages/v/vc-ltl5/xmake.lua

Shared to msvcrt.dll or ucrtbase.dll and optimize the C/C++ application file size.

add VC-LTL5

---

packages/l/libopus/xmake.lua

Add libopus AVX settings

---

packages/f/fmt/xmake.lua

fmt: update to 10.0.0

---

packages/d/draco/xmake.lua

Add draco version 1.5.6

---

packages/c/cpr/xmake.lua

Added the two latest versions.

Add cpr 1.10.2 and 1.10.3

---

packages/v/vc-ltl5/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/2056

improve vc-ltl5

---

packages/r/raylib/xmake.lua

also update the on test according to the API change in 4.5.0
------

Update raylib to 4.5.0

---

packages/a/ada/xmake.lua

https://github.com/xmake-io/xmake/issues/3754

fix license

---

packages/c/commonlibsse-ng/port/xmake.lua
packages/c/commonlibsse-ng/xmake.lua

Add `v3.7.0` to `commonlibsse-ng`

[commonlibsse-ng] Add `v3.7.0`

---

packages/s/sqlitecpp/xmake.lua

SQLiteC++ (SQLiteCpp) is a smart and easy to use C++ SQLite3 wrapper.

add sqlitecpp

---

packages/x/x265/xmake.lua

I tried to add more ARM platforms support for but some reasons it will screw up detection, if anyone wants to fix it.

x265: Add support for more platforms

---

packages/y/yy-thunks/rules/link.lua

- Fix bug
- To run the Win2K program, we need to modify the minimum executable operating system version.

improve yy-thunks

---

packages/g/glslang/xmake.lua
packages/m/meson/xmake.lua
packages/s/spirv-headers/xmake.lua
packages/v/vulkan-headers/xmake.lua
packages/v/vulkan-loader/xmake.lua

Update Vulkan sdk packages to 1.3.246.1

---

packages/l/libffi/xmake.lua
packages/m/meson/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/2085

fix libffi and update meson

---

packages/c/cli11/xmake.lua

cli11: add pkgconfig extsource

---

packages/c/cglm/xmake.lua

Add cglm package

---

packages/a/aseprite-tga/xmake.lua

C++ library to read/write Truevision TGA/TARGA files.

add aseprite-tga

---

packages/w/wfrest/xmake.lua

Add wfrest

---

scripts/new.lua

- Add gitlab support
- Refactor scripts/new.lua

Add gitlab support in scripts/new.lua

---

packages/l/libaio/xmake.lua

improve libaio

---

packages/e/effolkronium-random/xmake.lua

Add `effolkronium-random` crossplatform random library

[effolkronium-random] Add package

---

packages/r/rsm-mmio/xmake.lua

Add `rsm-mmio` crossplatform memory mapped io library

[rsm-mmio] Add package

---

packages/r/rsm-binary-io/xmake.lua

Add `rsm-binary-io` crossplatform binary io library

[rsm-binary-io] Add package

---

packages/m/msgpack-c/xmake.lua

add mingw support to msgpack-c

---

packages/m/msgpack-cxx/xmake.lua

add mingw support to msgpack-cxx

---

packages/b/brynet/xmake.lua

这个pr里面用了大写开头就是从这里复制过去的
https://github.com/xmake-io/xmake-repo/pull/2163

fix brynet Ws2_32 to ws2_32

---

packages/r/rest_rpc/xmake.lua
packages/s/sqlite_orm/xmake.lua

modern C++(C++11), simple, easy to use rpc framework

add rest_rpc and sqlite_orm

---

packages/b/benchmark/xmake.lua

update to new version

---

packages/l/libcpuid/xmake.lua

Auto-update libcpuid to v0.6.3

---

packages/s/sentry-native/xmake.lua

Auto-update sentry-native to 0.6.3

---

packages/d/dr_wav/xmake.lua

Auto-update dr_wav to 0.13.10

---

packages/d/dr_mp3/xmake.lua

Auto-update dr_mp3 to 0.6.36

---

packages/d/dr_flac/xmake.lua

Auto-update dr_flac to 0.12.41

---

packages/f/fast_float/xmake.lua

Auto-update fast_float to v5.2.0

---

packages/l/libflac/patches/1.4.2/cmake.patch
packages/l/libflac/xmake.lua

Auto-update libflac to 1.4.2

---

packages/d/drogon/xmake.lua

update drogon syslinks

---

packages/f/fast_float/xmake.lua

There was a bug in the script which created #2190, I have fixed it.

Fix fast_float version hash

---

packages/l/lz4/xmake.lua

Auto-update lz4 to v1.9.4

---

packages/u/utfcpp/xmake.lua

New version of utfcpp detected (current version: v3.2.1, last version: v3.2.3)

Auto-update utfcpp to v3.2.3

---

.github/workflows/fedora.yml
packages/o/openal-soft/xmake.lua

New version of openal-soft detected (current version: 1.22.2, last version: 1.23.1)

Auto-update openal-soft to 1.23.1

---

packages/l/libflac/xmake.lua

Update libflac to v1.4.3

---

packages/f/flecs/patches/v3.2.4/freebsd_http_include.patch
packages/f/flecs/xmake.lua

Update flecs to v3.2.4

---

packages/r/redis-plus-plus/xmake.lua

* Add redis-plus-plus version 1.3.9
------
* 添加1.3.9版本

Add redis-plus-plus version 1.3.9

---

packages/r/rsm-autotoml/xmake.lua

Add `rsm-autotoml` header only package

[rsm-autotoml] Add package

---

packages/t/tinygltf/xmake.lua

Update tinygltf to v2.8.13

---

packages/c/coost/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/2238

Improve coost to modify vs runtime

---

packages/a/aqt/xmake.lua

Update aqt to v3.1.6

---

packages/a/assimp/xmake.lua
packages/m/minizip/xmake.lua

Fixes link errors when minizip is installed on the system
------

Assimp: Add minizip dependency

---

packages/g/grpc/xmake.lua

grpc: export bin path

---

packages/b/boost/xmake.lua

Added support for the clang-cl toolchain in boost.

boost: add boost package clang-cl toolchain support

---

packages/o/opencl/xmake.lua

Improve opencl

---

packages/a/autodiff/xmake.lua

autodiff: use tag name but not version name

---

packages/l/libpng/xmake.lua

libpng: update url and use tar.gz instead zip

---

packages/c/clblast/xmake.lua

Add clblast

---

packages/z/zlib/xmake.lua

zlib: add_urls from deb-src

---

packages/c/clblast/xmake.lua

Add cmake dep to clblast

---

packages/d/dxsdk/xmake.lua

dxsdk: Remove os check

---

packages/l/libaesgm/xmake.lua
packages/p/pdfhummus/xmake.lua
packages/p/pkgconf/xmake.lua

Add v4.5.7 version for pdfhummus

pdfhummus: add 4.5.7

---

packages/p/pdfhummus/xmake.lua

pdfhummus: add_versions 4.5.8

---

packages/d/dr_wav/xmake.lua

New version of dr_wav detected (package version: 0.13.10, last github version: 0.13.11)

Auto-update dr_wav to 0.13.11

---

packages/s/s7/port/xmake.lua
packages/s/s7/xmake.lua

s7: add_syslinks m

---

packages/p/pdfhummus/xmake.lua

pdfhummus: add syslinks

---

packages/p/pdfhummus/xmake.lua

pdfhummus: remove libstdc++ syslinks

---

packages/s/sockpp/patches/0.8.1/strerror.patch
packages/s/sockpp/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/2284

Add sockpp

---

packages/s/srell/xmake.lua

Add [`srell`](https://www.akenotsuki.com/misc/srell/en/) header-only package

[srell] Add package

---

packages/p/psimd/xmake.lua

Add [`psimd`](https://github.com/Maratyszcza/psimd) header-only simd package.

[psimd] Add package

---

packages/c/cgltf/xmake.lua

Add [`cgltf`](https://github.com/jkuhlmann/cgltf) header-only glTF loader/writer package.

[cgltf] Add package

---

packages/l/libwebp/xmake.lua

LibWebP added a `lib` prefix to the built libraries with this commit. https://github.com/webmproject/libwebp/commit/2498209ba9391b526e001f9fe01cba230dd9b10e
------

Fix libwebp MSVC lib prefix

---

packages/f/fdk-aac/xmake.lua

feat: add fdk-aac and wavpack

---

packages/e/elfutils/xmake.lua

improve elfutils #2313

---

packages/b/boost/xmake.lua

Add boost pch config

---

packages/m/mosquitto/patches/cmake.patch
packages/m/mosquitto/xmake.lua

add mosquitto to repo

---

packages/f/fdk-aac/xmake.lua
packages/l/libiconv/xmake.lua
packages/s/svt-av1/xmake.lua
packages/w/wavpack/xmake.lua

feat: add wavpack

---

packages/m/mint/xmake.lua

mint: fix link

---

packages/b/brpc/patches/1.5.0/cmake.patch
packages/b/brpc/xmake.lua

* Add brpc version 1.5.0.
------
* 添加brpc 1.5.0版本。

Add brpc version 1.5.0

---

packages/l/libwebp/xmake.lua

Fix libwebp link order

---

packages/p/polyhook2/xmake.lua

pollyhook2: add debug config

---

packages/l/libjpeg-turbo/xmake.lua

Add libjpeg turbo mingw

---

packages/g/gn/xmake.lua

Downloads a host-compatible gn package for mingw
------

Add mingw support to gn

---

packages/f/fontconfig/xmake.lua
packages/q/qt6base/xmake.lua
packages/q/qt6core/xmake.lua
packages/q/qt6gui/xmake.lua
packages/q/qt6lib/xmake.lua
packages/q/qt6network/xmake.lua
packages/q/qt6widgets/xmake.lua
packages/q/qtbase/xmake.lua

Add support for Qt6 (again)

---

packages/q/qtifw/xmake.lua

Add qt installer framework from aqt

---

packages/p/protobuf-cpp/xmake.lua

add protobuf-cpp 3.12.0

---

packages/p/pdfhummus/xmake.lua

Add 4.5.9 and 4.5.10 version for pdfhummus

---

packages/l/libpeconv/xmake.lua

add libpeconv

---

packages/q/qtifw/xmake.lua

Detect binarycreator on system path

---

packages/u/unity/xmake.lua
packages/u/unity_test/xmake.lua

* Simple Unit Testing for C: <https://github.com/ThrowTheSwitch/Unity>

Add c unity package

---

packages/c/celero/xmake.lua

update celero to  no patch version

---

packages/p/pdfhummus/xmake.lua

pdfhummus: use git tag

---

packages/p/protobuf-cpp/xmake.lua
packages/z/zeromq/xmake.lua

set_license("MPL-2.0")

---

packages/i/imgui/xmake.lua

update imgui to 1.89.8

---

packages/v/volk/xmake.lua
packages/v/vulkan-headers/xmake.lua

update volk and vulkan-headers

---

packages/f/freetype/xmake.lua

freetype: Add version 2.13.1 and fix git tag names

---

packages/u/universal_stacktrace/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/2413

add universal_stacktrace

---

packages/c/cpp-linenoise/xmake.lua

Add package cpp-linenoise

---

packages/d/dr_wav/xmake.lua

New version of dr_wav detected (package version: 0.13.11, last github version: 0.13.12)

Auto-update dr_wav to 0.13.12

---

packages/g/glslang/xmake.lua
packages/s/spirv-headers/xmake.lua
packages/v/vulkan-headers/xmake.lua
packages/v/vulkan-loader/xmake.lua

#2407 updated vulkan-headers and volk but did not update other vulkan packages causing issues, I added a warning to prevent it to happen in the future

Update Vulkan SDK packages

---

packages/o/ordered_map/xmake.lua

ordered_map: Copy natvis to include dir

---

packages/e/entt/xmake.lua

EnTT: Copy natvis to include dirs

---

packages/o/optick/xmake.lua

Improve optick and add version 1.4.0

---

packages/p/perlinnoise/xmake.lua

Add perlinnoise package

---

packages/l/llvm/xmake.lua

add:llvm add 16.0.6

---

packages/f/ftxui/xmake.lua

Add ftxui version 5.0.0

---

packages/u/universal_stacktrace/xmake.lua

enable ust on mingw

---

packages/h/half/xmake.lua

- add [`half`](https://half.sourceforge.net) floating point precision package

[half] add package

---

packages/m/miniball/xmake.lua

- add [`miniball`](https://people.inf.ethz.ch/gaertner/subdir/software/miniball.html) library

[miniball] add package

---

packages/a/assimp/xmake.lua

------
patch from https://www.github.com/assimp/assimp/pull/5183

fix assimp: Remove /WX from CMakeLists for MSVC

---

packages/a/autoconf-archive/xmake.lua

add autoconf-archive

---

packages/c/cpptrace/xmake.lua
packages/l/libassert/xmake.lua

- cpptrace: Fix download url.
- libassert: Convert sha256 to upper.

cpptrace: fix url

---

packages/e/emmylua_debugger/xmake.lua

add emmylua_debugger

---

packages/a/abseil/xmake.lua
packages/e/eigen/xmake.lua

add cross support to eigen
add cross mingw support to abseil

add mingw&cross support to eigen&abseil

---

packages/e/emscripten/xmake.lua

improve emcc

---

packages/c/cimgui/port/xmake.lua
packages/c/cimgui/xmake.lua

cimgui: add package

---

packages/l/lexbor/xmake.lua

lexbor: add package

---

packages/e/emscripten/xmake.lua

Add emscripten 3.1.25

---

packages/e/emscripten/xmake.lua

See https://doc.qt.io/qt-6.4/wasm.html , 3.1.4 is for Qt 6.4 WASM

Add emscripten 3.1.14

---

packages/t/tabulate/xmake.lua

- Use `tar.gz`.
- Use git tag for version.

tabulate: improve package

---

packages/e/emscripten/xmake.lua

Add emscripten 1.39.8

---

packages/z/zlmediakit/xmake.lua
packages/z/zltoolkit/xmake.lua

libzlmediakit: add package

---

packages/b/blosc/xmake.lua
packages/l/lz4/xmake.lua

和blosc的官方设置保持一致，解除openvdb中的warning

enable lz4 in blosc by default

---

packages/q/quill/xmake.lua

Add support for quill 3.3.1

---

packages/g/glfw3webgpu/xmake.lua

Added a package for glfw3webgpu, which allows one to get a WebGPU surface from a GLFW window.

added glfw3webgpu

---

packages/l/luabridge3/xmake.lua

Referenced the implementation of vcpkg:
https://github.com/microsoft/vcpkg/blob/master/ports/luabridge3/portfile.cmake
```
file(COPY "${SOURCE_PATH}/Source/LuaBridge" DESTINATION "${CURRENT_PACKAGES_DIR}/include/${PORT}")
```
the header file path is
```
#include "luabridge3/LuaBridge/LuaBridge.h"
```

add package Luabridge3

---

packages/l/lexy/xmake.lua

Bump lexy to release 2022.12.1

---

packages/d/dpp/xmake.lua

New version of dpp detected (package version: v10.0.24, last github version: v10.0.25)

Auto-update dpp to v10.0.25

---

packages/s/sdsl-lite/xmake.lua
packages/s/seqan3/xmake.lua

seqan3: add package

---

packages/l/libsdl/xmake.lua

Add Wayland support for SDL package

---

packages/i/imgui/port/xmake.lua
packages/i/imgui/xmake.lua

imgui learned a wgpu config

---

packages/l/libsdl/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/2553

improve libsdl

---

packages/m/matplotplusplus/xmake.lua

matplotplusplus: add_version v1.2.0

---

packages/m/matplotplusplus/xmake.lua

matplotplusplus: add_version v1.2.0 (#2565)

---

packages/m/mscharconv/xmake.lua

add header only package mscharconv

---

packages/k/kuba-zip/xmake.lua

Just a small PR to add version 0.2.6 to kuba-zip package

adding kuba-zip v0.2.6 version

---

packages/m/mpg123/xmake.lua

add package mpg123

---

packages/c/coost/xmake.lua

- coost: add new version v3.0.1

coost: add v3.0.1

---

packages/a/alsa-lib/xmake.lua

add alsa-lib

---

packages/l/lua/xmake.lua

add debug and release mode

---

packages/a/alsa-lib/xmake.lua
packages/l/libsndio/xmake.lua

add libsndio

---

packages/o/openal-soft/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/2580

add libsndio deps

---

packages/v/vulkan-hpp/xmake.lua

Update Vulkan-Hpp to v1.3.261

---

packages/i/imgui/xmake.lua

Update imgui to v1.89.9

---

packages/l/libarchive/xmake.lua

improve libarchive

---

packages/l/libsdl_ttf/xmake.lua

sdl_ttf cannot be installed without using precompiled.
I think xmake should disable symlink extraction (there's the same problem with sfml)
```
=> download https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.2/SDL2_ttf-2.20.2.tar.gz .. failed
C:\Program Files\xmake\winenv\bin\7z x -y SDL2_ttf-2.20.2.tar.gz -oC:\Users\lynix\AppData\Local\Temp\.xmake\230918\_B21627892EB948108F44065483A74B70.tar
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
Scanning the drive for archives:
1 file, 13161592 bytes (13 MiB)
Extracting archive: SDL2_ttf-2.20.2.tar.gz
--
Path = SDL2_ttf-2.20.2.tar.gz
Type = gzip
Headers Size = 10
Everything is Ok
Size:       42510336
Compressed: 13161592
C:\Program Files\xmake\winenv\bin\7z x -y …
```

libsdl_ttf: add .zip download sources on Windows

---

packages/s/spdlog/xmake.lua

spdlog: fix installation test on Linux

spdlog: fix installation test on Linux

---

packages/i/imgui/port/xmake.lua
packages/i/imgui/xmake.lua

imgui: add shared support

---

packages/l/libsndfile/xmake.lua

bump libsndfile

---

packages/t/trantor/xmake.lua

------
add trantor version 1.5.14

add trantor version 1.5.14

---

packages/o/opencl/xmake.lua

Add opencl test

---

packages/l/libevdev/xmake.lua

libevdev: add package

---

packages/c/clblast/xmake.lua
packages/o/opencl/xmake.lua

Add clblast tests

---

packages/l/lemon/xmake.lua

update lemon cxx=14

---

packages/u/utfcpp/xmake.lua

utfcpp: Add utf8cpp include dir

---

packages/f/fluidsynth/patches/find-intl.patch
packages/f/fluidsynth/xmake.lua
packages/g/glib/xmake.lua

add package fluidsynth

---

.github/workflows/wasm_ubuntu.yml
packages/a/assimp/xmake.lua

New version of assimp detected (package version: v5.2.5, last github version: v5.3.0)

Auto-update assimp to v5.3.1

---

packages/h/hiredis/xmake.lua

New version of hiredis detected (package version: v1.1.0, last github version: v1.2.0)

Auto-update hiredis to v1.2.0

---

packages/r/rtmidi/xmake.lua

fix compilation error of rtmidi under linux when libasound is installed

---

packages/z/zmqpb/xmake.lua

- add more types
- use bytes in proto message for wrapping
Details at https://github.com/SFGrenade/ZmqPb/compare/v0.1...v0.2

Add zmqpb v0.2

---

packages/c/cpp-httplib/xmake.lua

------
add cpp-httplib v0.14.0

add cpp-httplib v0.14.0

---

packages/e/enet6/xmake.lua

Add enet6 package

---

packages/e/enet6/xmake.lua

enet6: Add v6.0.1

---

packages/m/miniaudio/xmake.lua

add version 0.11.18 of miniaudio

add version 0.11.18 of miniaudio

---

packages/l/libsndfile/xmake.lua

New version of libsndfile detected (package version: 1.0.31, last github version: 1.2.2)

Auto-update libsndfile to 1.2.2

---

packages/e/enet6/xmake.lua

enet6: Add v6.0.2

---

packages/m/mingw-w64/xmake.lua

add new version of mingw toolchain

---

packages/q/qt6lib/xmake.lua

Add more versions of Qt 6.5 LTS for qt6lib

---

packages/l/linmath.h/xmake.lua
scripts/new.lua

https://github.com/xmake-io/xmake-repo/issues/2677

add linmath.h

---

packages/n/neargye-scope_guard/xmake.lua
packages/r/ricab-scope_guard/xmake.lua

Rename package: scope_guard -> neargye-scope_guard

ricab-scope_guard: add package

---

packages/l/libnet/xmake.lua

[libnet](https://github.com/libnet/libnet)

libnet: add version 1.2

---

packages/p/pugixml/xmake.lua

Refer to: https://github.com/xmake-io/xmake-repo/issues/2709

pugixml supports mingw

---

packages/s/sqlite3/xmake.lua

update sqlite3 to 3.43.0.200

---

packages/t/toml++/xmake.lua

update toml++ to 3.4.0

---

packages/t/tinyfiledialogs/xmake.lua

update tinyfiledialogs to 3.15.1

---

packages/v/verilator/xmake.lua

update verilator 5.015

---

packages/t/trantor/xmake.lua

trantor: find_package use config mode

---

packages/k/kiwisolver/xmake.lua

kiwisolver: mark as headeronly

---

packages/b/bcg729/xmake.lua

add bcg729 package

---

packages/z/zmqpb/xmake.lua

- changes interface, so additional test was added
- also removes fmt dependency

add zmqpb v0.3

---

packages/l/libccd/xmake.lua

add mingw,cross for libccd

---

packages/b/brpc/patches/1.6.1/cmake.patch
packages/b/brpc/xmake.lua

* Add brpc version 1.6.1
------
* 新增1.6.1版本

Add brpc version 1.6.1

---

packages/h/hedley/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/2792

hedley: add package

---

packages/b/boost/xmake.lua

Added Boost ICL and Interval to Boost xmake.lua

---

packages/x/xbyak/xmake.lua

- update `xbyak` to `v6.73`
- shorten description

xbyak: update

---

packages/d/dr_flac/xmake.lua

New version of dr_flac detected (package version: 0.12.41, last github version: 0.12.42)

Auto-update dr_flac to 0.12.42

---

packages/d/dr_wav/xmake.lua

New version of dr_wav detected (package version: 0.13.12, last github version: 0.13.13)

Auto-update dr_wav to 0.13.13

---

packages/a/abseil/xmake.lua

The optional cxx17 does not do anything and C++ 14 does not work with abseil

abseil: revert optional cxx17

---

packages/i/imgui/xmake.lua

update imgui to v1.90

---

packages/z/zmqpb/xmake.lua

Add zmqpb v0.4

---

packages/m/makeself/xmake.lua

add makeself

---

packages/i/immer/xmake.lua

update immer to 0.8.1

---

packages/s/simdjson/xmake.lua

update simdjson to 3.6.0

---

packages/l/libdeflate/xmake.lua

update libdeflate to 1.19

---

packages/b/brpc/patches/1.7.0/cmake.patch
packages/b/brpc/xmake.lua

Add brpc version 1.7.0

---

packages/c/cairo/xmake.lua
packages/g/gdk-pixbuf/xmake.lua
packages/g/glib/xmake.lua
packages/g/graphene/xmake.lua
packages/g/gtk4/xmake.lua
packages/h/harfbuzz/xmake.lua
packages/l/libdrm/xmake.lua
packages/l/libepoxy/xmake.lua
packages/l/libjpeg-turbo/xmake.lua
packages/l/libxi/xmake.lua
packages/n/nasm/xmake.lua
packages/p/pango/xmake.lua

add gtk4 build

---

packages/l/libsndio/xmake.lua

improve libsndio to support static library

---

.github/workflows/archlinux.yml
.github/workflows/fedora.yml
.github/workflows/ubuntu.yml
.github/workflows/ubuntu_clang.yml
packages/w/wxwidgets/xmake.lua

fix wxwidgets linux build

---

packages/c/cpptrace/xmake.lua

add mingw support to cpptrace

---

packages/u/utfcpp/xmake.lua

New version of utfcpp detected (package version: v4.0.2, last github version: v4.0.3)

Auto-update utfcpp to v4.0.3

---

packages/g/glslang/xmake.lua
packages/s/spirv-cross/xmake.lua
packages/s/spirv-headers/xmake.lua
packages/s/spirv-reflect/xmake.lua
packages/s/spirv-tools/xmake.lua
packages/v/volk/xmake.lua
packages/v/vulkan-headers/xmake.lua
packages/v/vulkan-hpp/xmake.lua
packages/v/vulkan-loader/xmake.lua

update to vulkan 1.3.168

---

packages/l/libgd/xmake.lua

libgd仓库一直在更新，只是两年没有发版本了
顺便放开mingw的支持

update libgd to latest commit

---

packages/a/attr/xmake.lua

improve attr

---

packages/c/catch2/xmake.lua

improve catch2

---

packages/a/abseil/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/2928

improve abseil links

---

packages/b/boost/xmake.lua

add boost for windows arm

---

packages/a/abseil/xmake.lua

fix abseil

---

packages/m/microsoft-detours/xmake.lua

fix microsoft-detours defines

---

packages/a/assimp/xmake.lua

https://github.com/xmake-io/xmake-repo/commit/15b61bf02c063ac1a2467616c9b7b896a884a7e5 broke minizip for assimp on Windows

assimp: Try to fix minizip

---

packages/a/assimp/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/2993

fix assimp for old version

---

packages/l/llvm/xmake.lua

added llvm 13.0.0, 15.0.7 support for x86_64 macOS

added llvm 13.0.0, 15.0.7 support for x86 macos

---

packages/l/libsdl/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/2997

improve sdl

---

packages/c/cmake/xmake.lua

FreeBSD CI always takes a lot of time to install cmake because it does not parallelize build
Edit: it doesn't seem to help

cmake: Update to 3.28.1 and enable parallel build on FreeBSD

---

packages/r/raylib/xmake.lua

Updated Raylib to 5.0

---

packages/e/expat/xmake.lua

open expat for android.
------

libexpat: open expat for android.

---

packages/i/imgui/xmake.lua

imgui: fix sdl test

---

packages/l/libcurl/xmake.lua

ibcurl: fix 'select TLS backend(s) or disable TLS with --without-ssl

---

packages/f/ffmpeg/xmake.lua

ffmpeg: fix ffmpeg compie failed for android

---

packages/g/glbinding/xmake.lua
packages/k/khrplatform/xmake.lua

Add glbinding package (and khrplatform)

---

packages/r/raygui/xmake.lua

Updated Raygui to the latest 4.0 version thanks

Updated Raygui to 4.0

---

packages/b/bullet3/xmake.lua

Fixes a compilation issue when compiling bullet3 as a debug package with MD vs_runtime

bullet3: Fix vs_runtime

---

packages/r/rendergraph/xmake.lua

[rendergraph] Update to v1.4.0.

---

.github/workflows/macos.yml
packages/f/ffmpeg/xmake.lua

Add macOS ARM64 CI and fix FFMpeg package for macOS ARM64

---

packages/l/libass/port/config.h.in

Fix libass packages

---

packages/o/openssl/xmake.lua

openssl: fix for macos ARM64

---

packages/a/asio/xmake.lua

Updated asio to 1.29.0

---

.github/workflows/sync.yml
scripts/automerge.lua

add automerge

---

packages/u/ultralight/xmake.lua
packages/w/wfrest/xmake.lua

This PR adds the `ultralight` package

Add ultralight package

---

packages/l/libflac/xmake.lua
packages/l/libogg/xmake.lua

improve patch path

---

packages/l/libyuv/xmake.lua

修复android平台libyuv默认链接so库，导致apk运行找不到libyuv.so.

libyuv: fix default shared lib usage for android

---

packages/l/libcurl/xmake.lua

libcurl: Fix missing dl link

---

packages/i/imgui/xmake.lua
packages/v/vk-bootstrap/xmake.lua

Update vk bootstrap and imgui

---

packages/l/libbpf/xmake.lua
packages/m/memorymapping/xmake.lua

Improve memorymapping

---

packages/t/tl_optional/xmake.lua

add tl_optional

---

packages/l/libsdl/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/3082
https://github.com/xmake-io/xmake-repo/issues/3139

Remove sdl subsystem

---

packages/g/glslang/xmake.lua
packages/s/spirv-headers/xmake.lua
packages/s/spirv-reflect/xmake.lua
packages/s/spirv-tools/xmake.lua
packages/v/volk/xmake.lua
packages/v/vulkan-headers/xmake.lua
packages/v/vulkan-hpp/xmake.lua
packages/v/vulkan-loader/xmake.lua
packages/v/vulkan-utility-libraries/xmake.lua
packages/v/vulkanscenegraph/xmake.lua

update vulkan related packages to v1.3.275

---

packages/l/lightningscanner/xmake.lua

New version of lightningscanner detected (package version: v1.0.0, last github version: v1.0.2)

Auto-update lightningscanner to v1.0.2

---

packages/w/whisper.cpp/xmake.lua

New version of whisper.cpp detected (package version: 1.4.2, last github version: 1.5.4)

Auto-update whisper.cpp to 1.5.4

---

packages/l/linalg/xmake.lua

Add support for the [linalg](https://github.com/sgorsten/linalg) package.

Add linalg

---

packages/n/nanovg/xmake.lua

nanovg: adds mingw platform

---

packages/v/vulkan-memory-allocator-hpp/xmake.lua

add modules support for vulkan-memory-allocator-hpp

---

packages/v/vulkan-headers/xmake.lua
packages/v/vulkan-hpp/xmake.lua

add module support for vulkan-hpp and vulkan-headers

---

packages/g/glm/xmake.lua

Add modules support for glm

---

packages/c/cxxopts/xmake.lua

same as https://github.com/xmake-io/xmake-repo/pull/3243

fix some packages tests for clang on Windows with msvc runtime

---

.github/workflows/mingw_msys2.yml
.github/workflows/windows.yml
packages/c/cosmocc/xmake.lua

enable windows for cosmocc

---

packages/o/ozz-animation/xmake.lua

New version of ozz-animation detected (package version: 0.14.2, last github version: 0.14.3)

Auto-update ozz-animation to 0.14.3

---

packages/l/libsdl/xmake.lua

See https://github.com/libsdl-org/SDL/issues/9031

libsdl: Fix compilation on mingw-w64

---

packages/i/imgui/xmake.lua

update imgui to v1.90.2

---

packages/c/cppcheck/xmake.lua

Add cppcheck

---

packages/o/onnxruntime/xmake.lua

Update xmake.lua (ONNX Runtime v1.17.0)

---

packages/p/parallel-hashmap/xmake.lua

Update parallel-hashmap to 1.3.12

---

packages/i/imgui/xmake.lua

update imgui to v1.90.3

---

packages/c/cpptrace/xmake.lua

update cpptrace to v0.4

---

packages/r/rmlui/xmake.lua

New version of rmlui detected (package version: 5.0, last github version: 5.1)

Auto-update rmlui to 5.1

---

packages/f/fcl/xmake.lua

fcl: make octomap optional

---

packages/e/enkits/xmake.lua

New version of enkits detected (package version: v1.10, last github version: v1.11)

Auto-update enkits to v1.11

---

packages/m/msys2-base/xmake.lua
packages/m/msys2/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/3310

Seperate msys2

---

packages/s/sqlite3/xmake.lua

[sqlite3] update to 3.45.1

---

packages/a/abseil/xmake.lua

[abseil] update to 20240116.1

---

packages/o/opencv/xmake.lua

Fix `includedirs` for opencv (homebrew)

---

packages/a/apr/xmake.lua

New version of apr detected (package version: 1.7.0, last github version: 1.7.4)

Auto-update apr to 1.7.4

---

packages/x/x264/xmake.lua

Compile x264 on Windows/MinGW using msys2

---

packages/l/libsdl/patches/2.30.0/fix_mingw.patch
packages/l/libsdl/xmake.lua

Fix libsdl patch

---

packages/o/opencv/xmake.lua

Fix the `sysincludedirs` for opencv (homebrew)

---

packages/b/boost/xmake.lua

add support for libc++ runtimes for boost

---

packages/c/cxxopts/xmake.lua

cxxopts: Fix 3.2.0 hash

---

packages/c/cxxopts/xmake.lua

update cxxopt to v3.2.1

---

packages/f/folly/xmake.lua

udpate folly to 2024.2.26

---

packages/g/glm/xmake.lua

update glm to 1.0.1

---

packages/d/directxtex/xmake.lua
packages/d/directxtk/xmake.lua

update directxtk to feb2024

---

packages/l/libunwind/xmake.lua

New version of libunwind detected (package version: v1.6.2, last github version: v1.7.2)

Auto-update libunwind to v1.7.2

---

packages/u/uvatlas/xmake.lua

update uvatlas to 2024.02

---

packages/s/sqlite3/xmake.lua

fix_sqlite3_encodings

---

packages/l/libntl/xmake.lua

Add libntl

---

packages/z/zig/xmake.lua

update zig to 0.11.0

---

packages/r/reproc/patches/0001-to-head.diff
packages/r/reproc/xmake.lua

Just the link order and multithreaded fixes for now. I've opened an issue asking for a point release in the reproc repo https://github.com/DaanDeMeyer/reproc/issues/109 to fix building with GCC 13.

reproc: add multithreaded option and fix link orders

---

packages/u/uni_algo/xmake.lua

New version of uni_algo detected (package version: v1.0.0, last github version: v1.2.0)

Auto-update uni_algo to v1.2.0

---

packages/c/cosmocc/xmake.lua

update cosmocc to 3.3.2

---

packages/g/gfortran/xmake.lua

gfortran: add more path on macos

---

packages/u/ucx/xmake.lua

New version of ucx detected (package version: 1.11.0, last github version: 1.15.0)

Auto-update ucx to 1.15.0

---

packages/k/kuba-zip/xmake.lua

New version of kuba-zip detected (package version: v0.2.6, last github version: v0.3.1)

Auto-update kuba-zip to v0.3.1

---

packages/d/depot_tools/xmake.lua

As the title says.
Part of the v8 fix operation.

depot_tools: Add version 2024.2.29@50de66

---

packages/t/tree-sitter/port/xmake.lua
packages/t/tree-sitter/xmake.lua

add library tree-sitter

---

packages/o/onnxruntime/xmake.lua

------
close: #3285
fix the ci error in #3282.

update onnxruntime to 1.17.1

---

.github/workflows/ubuntu_clang.yml
packages/f/fizz/xmake.lua
packages/f/folly/xmake.lua

add fizz & enable folly on macos arm

---

packages/d/dr_wav/xmake.lua

New version of dr_wav detected (package version: 0.13.13, last github version: 0.13.16)

Auto-update dr_wav to 0.13.16

---

packages/l/lightgbm/xmake.lua

New version of lightgbm detected (package version: 3.3.2, last github version: 4.2.0)

Auto-update lightgbm to 4.2.0

---

packages/e/emscripten/xmake.lua

update emsdk to 3.1.55

---

packages/f/fizz/xmake.lua
packages/l/liburing/xmake.lua

update liburing to 2.5

---

packages/m/mint/xmake.lua

New version of mint detected (package version: nil, last github version: 2024.1)

Auto-update mint to 2024.1

---

packages/w/webui/xmake.lua

New version of webui detected (package version: 2.3.0, last github version: 2.4.2)

Auto-update webui to 2.4.2

---

packages/w/wangle/xmake.lua

add wangle package

---

packages/f/fizz/xmake.lua
packages/f/folly/xmake.lua
packages/w/wangle/xmake.lua

[folly,fizz,wangle] update to 2024.03.04

---

packages/s/simdjson/xmake.lua

update simdjson to 3.7.0

---

packages/s/simdutf/xmake.lua

update simdutf to 4.0.9

---

packages/i/imath/xmake.lua

update imath to 3.1.11

---

.github/workflows/macos_x86_64.yml
packages/g/glaze/xmake.lua

update glaze to 2.2.0

---

packages/s/scnlib/xmake.lua

update scnlib to 2.0.2

---

packages/p/proxygen/xmake.lua

add proxygen

---

packages/g/ginkgo/xmake.lua

add ginkgo

---

packages/f/fbthrift/xmake.lua

add fbthrift

---

packages/r/re2/xmake.lua

update re2 to 2024.03.01

---

packages/s/stdexec/xmake.lua

add stdexec

---

packages/i/ixwebsocket/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/3436

ixwebsocket: update v11.4.5

---

packages/t/tgbot-cpp/xmake.lua

New version of tgbot-cpp detected (package version: nil, last github version: v1.7.3)

Auto-update tgbot-cpp to v1.7.3

---

packages/s/srtp/xmake.lua

New version of srtp detected (package version: nil, last github version: v2.6)

Auto-update srtp to v2.6

---

packages/r/rtm/xmake.lua

New version of rtm detected (package version: nil, last github version: v2.3.0)

Auto-update rtm to v2.3.0

---

packages/m/matplotplusplus/xmake.lua

New version of matplotplusplus detected (package version: nil, last github version: v1.2.1)

Auto-update matplotplusplus to v1.2.1

---

packages/f/ffmpeg/xmake.lua
packages/l/libiconv/port/xmake.lua
packages/x/x264/xmake.lua
packages/x/x265/xmake.lua

improve ffmpeg for windows

---

packages/e/elfutils/xmake.lua
packages/l/linux-headers/xmake.lua
packages/l/linux-tools/modules/bpftool.lua
packages/l/linux-tools/xmake.lua

update linux kernel 6.7.6

---

packages/f/fbthrift/xmake.lua
packages/f/fizz/xmake.lua
packages/f/folly/xmake.lua
packages/m/mvfst/xmake.lua
packages/p/proxygen/xmake.lua
packages/w/wangle/xmake.lua

update folly related to 3.11

---

.github/workflows/wasm_ubuntu.yml
packages/s/sqlite3/xmake.lua

------
------
* update sqlite from 3.45.1 to 3.45.2
* update wasm ci version from 11 to 14
* from the emsdk version so that it will always download the latest version

update sqlite3 to 3.45.2

---

packages/l/libredwg/xmake.lua

add libredwg package

---

packages/a/async_simple/xmake.lua

update async-simple to 1.3

---

packages/x/xbyak/xmake.lua

update xbyak to 7.06

---

packages/a/asmjit/xmake.lua

update asmjit to 2024.03.09

---

packages/b/bazel/xmake.lua

update bazel to 7.1.0

---

packages/l/libkmod/patches/31/basename.patch
packages/l/libkmod/xmake.lua

New version of libkmod detected (package version: v30, last github version: v31)

Auto-update libkmod to v31

---

packages/i/imgui/xmake.lua

Update imgui to 1.90.4

---

packages/r/rapidxml/xmake.lua
packages/x/xpack/xmake.lua

- add `rapidxml` library
- change `xpack` to use this package instead of the one included

rapidxml: add package

---

packages/x/xaudio2redist/xmake.lua

- add `xaudio2redist` redistributable library

xaudio2redist: add package

---

packages/l/libheif/xmake.lua

New version of libheif detected (package version: nil, last github version: 1.17.6)

Auto-update libheif to 1.17.6

---

packages/c/cppfront/xmake.lua

update cppfront to semver

---

packages/s/snappy/patches/1.1.10/cmake.patch
packages/s/snappy/xmake.lua

https://github.com/google/snappy/pull/169

improve snappy

---

packages/p/pulsar/xmake.lua

New version of pulsar detected (package version: nil, last github version: 3.5.0)

Auto-update pulsar to 3.5.0

---

packages/f/fbthrift/xmake.lua
packages/f/fizz/xmake.lua
packages/f/folly/xmake.lua
packages/m/mvfst/xmake.lua
packages/p/proxygen/xmake.lua
packages/w/wangle/xmake.lua

update folly to 3.18

---

packages/b/brpc/patches/1.8.0/cmake.patch
packages/b/brpc/xmake.lua

New version of brpc detected (package version: nil, last github version: 1.8.0)

Auto-update brpc to 1.8.0

---

packages/i/imgui/xmake.lua

https://github.com/xmake-io/xmake/issues/4859

imgui: fix sdl config

---

packages/g/glaze/xmake.lua

Added new version of glaze (v.2.3.1) with checksum.

Update glaze to v.2.3.1

---

packages/x/xsimd/xmake.lua
packages/x/xtensor/xmake.lua

New version of xtensor detected (package version: nil, last github version: 0.25.0)

Auto-update xtensor to 0.25.0

---

packages/l/libdwarf/xmake.lua

New version of libdwarf detected (package version: nil, last github version: 0.9.1)

Auto-update libdwarf to 0.9.1

---

packages/c/cpp-lazy/xmake.lua

Auto-update cpp-lazy to v8.0.0

---

packages/s/sparse-map/xmake.lua

add sparse-map package

---

packages/s/srt/xmake.lua

New version of srt detected (package version: nil, last github version: v1.5.3)

Auto-update srt to v1.5.3

---

packages/f/fbthrift/xmake.lua
packages/f/fizz/xmake.lua
packages/f/folly/xmake.lua
packages/m/mvfst/xmake.lua
packages/p/proxygen/xmake.lua
packages/w/wangle/xmake.lua

update folly related to 2024.03.25

---

packages/c/clip/xmake.lua

New version of clip detected (package version: nil, last github version: 1.8)

Auto-update clip to 1.8

---

.github/workflows/ubuntu_clang.yml
packages/o/onednn/xmake.lua

New version of onednn detected (package version: nil, last github version: v3.4)

Auto-update onednn to v3.4

---

packages/t/tinyexr/xmake.lua

add tinyexr v1.0.8

---

packages/p/pugixml/xmake.lua
packages/t/tmxlite/xmake.lua

Add tmxlite

---

packages/o/octomap/patches/1.10.0/cmake.patch
packages/o/octomap/xmake.lua

New version of octomap detected (package version: nil, last github version: v1.10.0)

Auto-update octomap to v1.10.0

---

packages/c/cpptrace/xmake.lua
packages/l/libassert/port/v1/xmake.lua
packages/l/libassert/xmake.lua

New version of libassert detected (package version: nil, last github version: v2.0.0)

Auto-update libassert to v2.0.0

---

packages/o/openssl/xmake.lua

temp fix
see https://github.com/xmake-io/xmake/pull/4903

openssl: Fix compilation for Android on Windows

---

packages/c/chipmunk2d/patches/7.0.3/android.patch
packages/c/chipmunk2d/xmake.lua

chipmunk2d: Fix Android static lib

---

packages/n/nghttp2/xmake.lua

New version of nghttp2 detected (package version: nil, last github version: 1.60.0)

Auto-update nghttp2 to 1.60.0

---

packages/f/fmtlog/xmake.lua

Add fmtlog version 2.2.1

---

packages/a/audiofile/xmake.lua

Add AudioFile package

---

packages/o/ozz-animation/xmake.lua

-Dozz_build_msvc_rt_dll option was missing. add it to support MSVC runtime config.

add msvc runtime configuration.

---

packages/o/ozz-animation/xmake.lua

fix the config after skimming this issue: https://github.com/xmake-io/xmake/issues/4477

fix: consider possible missing runtime config: MDd

---

packages/s/simdutf/xmake.lua

New version of simdutf detected (package version: nil, last github version: v5.2.2)

Auto-update simdutf to v5.2.2

---

packages/l/libtiff/xmake.lua

add brew extsources for libtiff

---

packages/p/protobuf-cpp/xmake.lua

protobuf-cpp url adjust

---

packages/a/abseil/xmake.lua
packages/g/grpc/xmake.lua
packages/p/protobuf-cpp/xmake.lua
packages/r/re2/xmake.lua

fix: abseil conflict in https://github.com/xmake-io/xmake-repo/issues/3705

fix: abseil conflict

---

packages/h/highfive/xmake.lua

New version of highfive detected (package version: v2.6.1, last github version: v2.9.0)

Auto-update highfive to v2.9.0

---

packages/c/cinatra/patches/0.8.9/windows-move.patch
packages/c/cinatra/xmake.lua

New version of cinatra detected (package version: nil, last github version: 0.8.9)

Auto-update cinatra to 0.8.9

---

packages/s/sqlitecpp/xmake.lua

New version of sqlitecpp detected (package version: nil, last github version: 3.3.1)

Auto-update sqlitecpp to 3.3.1

---

packages/z/zlog/patches/1.2.17/cmake.patch
packages/z/zlog/xmake.lua

close https://github.com/xmake-io/xmake-repo/issues/3748

zlog: add package

---

packages/o/openssl3/fetch.lua
packages/o/openssl3/xmake.lua

https://github.com/xmake-io/xmake/issues/4965

fix openssl3/fetch

---

packages/o/opencv/xmake.lua

add ffmpeg dep

---

packages/i/imgui/xmake.lua

Update imgui to v1.90.5

---

packages/p/plf_nanotimer/xmake.lua

Split this failing package out of https://github.com/xmake-io/xmake-repo/pull/3742

Add `plf_nanotimer` package

---

packages/p/pulsar/xmake.lua

New version of pulsar detected (package version: nil, last github version: 3.5.1)

Auto-update pulsar to 3.5.1

---

packages/l/libpsl/xmake.lua

New version of libpsl detected (package version: nil, last github version: 0.21.5)

Auto-update libpsl to 0.21.5

---

packages/x/xsimd/xmake.lua

New version of xsimd detected (package version: nil, last github version: 12.1.1)

Auto-update xsimd to 12.1.1

---

packages/x/xlsxio/xmake.lua

New version of xlsxio detected (package version: nil, last github version: 0.2.35)

Auto-update xlsxio to 0.2.35

---

packages/m/mjson/xmake.lua

New version of mjson detected (package version: nil, last github version: 1.2.7)

Auto-update mjson to 1.2.7

---

packages/a/asio/xmake.lua

update asio to 1.30.2

---

packages/s/sqlite3/xmake.lua

update sqlite3 to 3.45.3

---

packages/w/wavpack/xmake.lua

New version of wavpack detected (package version: nil, last github version: 5.7.0)

Auto-update wavpack to 5.7.0

---

packages/i/iowow/xmake.lua

New version of iowow detected (package version: nil, last github version: v1.4.18)

Auto-update iowow to v1.4.18

---

packages/b/bitsery/patches/5.2.3/cstdint-include.patch
packages/b/bitsery/xmake.lua

add bitsery

---

packages/n/nng/xmake.lua

add nng 1.7.3

---

packages/c/cmake/xmake.lua

update cmake to 3.29.2

---

packages/t/tracy/xmake.lua

Add configuration for tracy according to CMake options in https://github.com/wolfpld/tracy/blob/master/CMakeLists.txt

Add configs for tracy

---

packages/b/boringssl/patches/2022.06.13/cmake.patch
packages/b/boringssl/xmake.lua
packages/g/go/xmake.lua

Fix https://github.com/xmake-io/xmake-repo/issues/3816

boringssl: add version 2022.06.13

---

packages/a/abseil/xmake.lua

update abseil minor version

---

packages/c/clip/xmake.lua

New version of clip detected (package version: nil, last github version: 1.9)

Auto-update clip to 1.9

---

.github/workflows/mingw_macos.yml
packages/b/boost_sml/xmake.lua

New version of boost_sml detected (package version: nil, last github version: v1.1.11)

Auto-update boost_sml to v1.1.11

---

packages/u/uwebsockets/xmake.lua

add uWebSockets

---

packages/f/ffmpeg/xmake.lua

- Also enable mediacodec support on Android
- Try to compile on iOS
------

ffmpeg: Update to 7.0, enable iOS platform and add support for libdrm

---

.github/workflows/windows.yml
packages/s/spirv-cross/xmake.lua

https://github.com/xmake-io/xmake/issues/5020

improve links

---

packages/p/protobuf-cpp/xmake.lua

Fix linking protobuf-cpp

---

packages/c/cello/xmake.lua

close https://github.com/xmake-io/xmake-repo/issues/3678

cello: add package

---

packages/s/spdlog/xmake.lua

This pull request updates spdlog to version 1.14.0.

Update spdlog to v1.14.0

---

packages/r/rpmalloc/xmake.lua

New version of rpmalloc detected (package version: nil, last github version: 1.4.5)

Auto-update rpmalloc to 1.4.5

---

packages/g/gamenetworkingsockets/port/xmake.lua
packages/g/gamenetworkingsockets/xmake.lua
packages/o/openssl/fetch.lua
packages/p/protobuf-cpp/xmake.lua

As suggested by @waruqi in #3710 .

Fix gamenetworkingsockets abseil C++ version

---

packages/i/iguana/xmake.lua

- add_deps frozen
- Fix arm build(switch to c++20)

iguana: update to 1.0.4

---

packages/o/ormpp/xmake.lua
packages/s/spdlog/xmake.lua

Update ormpp to v0.1.2

---

packages/q/qmsetup/xmake.lua
packages/q/qtbase/xmake.lua
packages/q/qwindowkit/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/3889

add qwindowkit

---

packages/d/duckdb/xmake.lua

update duckdb v0.10.2

---

packages/p/pocketpy/xmake.lua

New version of pocketpy detected (package version: nil, last github version: v1.4.5)
- close: #3699
- close: #3376
- close: #3270
- close: #3199

Auto-update pocketpy to v1.4.5

---

packages/p/python/xmake.lua

When openssl is installed by brew, here's how it's installed:
```
openssl fetch:  { 
linkdirs = { 
"/opt/homebrew/Cellar/openssl@3/3.3.0", 
},
sysincludedirs = { 
"/opt/homebrew/Cellar/openssl@3/3.3.0/include", 
},
links = { 
"ssl",
"crypto", 
},
version = "3.3.0", 
}
```
the current code can't find it as it searches for a lib folder, I added a way to find openssl root compatible with that (checking if includedirs is in linkdirs)
tested here: https://github.com/NazaraEngine/ShaderLang/actions/runs/8909712957/job/24467551468
(it's failing because of another issue I'm still debugging)

Python: Add a way to find brew openssl

---

packages/s/spdlog/xmake.lua

update spdlog to 1.14.1

---

packages/g/glslang/xmake.lua
packages/s/shaderc/xmake.lua

- Use xrepo deps
- Remove python dep
- add_configs for exceptions
- Fix cross compilation in on_test

shaderc: improve deps

---

packages/a/alsa-lib/xmake.lua

alsa-lib: add syslinks pthread

---

packages/b/bgfx/rules/shaders.lua
packages/b/bgfx/xmake.lua

After https://github.com/bkaradzic/bgfx/pull/3005, ps_.../vs_.../cs_... have been changed to s_...

bgfx: fix rules

---

packages/s/shaderc/xmake.lua

close https://github.com/xmake-io/xmake-repo/issues/3937

shaderc: fix msvc runtimes

---

packages/x/xsimd/xmake.lua

New version of xsimd detected (package version: nil, last github version: 13.0.0)

Auto-update xsimd to 13.0.0

---

packages/d/directxshadercompiler/xmake.lua

------
add new version in windows plat.

Update directx shader compiler to 1.8.2403.2

---

packages/m/msdfgen/xmake.lua

New version of msdfgen detected (package version: nil, last github version: v1.11)

Auto-update msdfgen to v1.11

---

packages/g/glslang/xmake.lua
packages/s/spirv-headers/xmake.lua
packages/s/spirv-reflect/xmake.lua
packages/s/spirv-tools/xmake.lua
packages/v/vk-bootstrap/xmake.lua
packages/v/volk/xmake.lua
packages/v/vulkan-headers/xmake.lua
packages/v/vulkan-hpp/xmake.lua
packages/v/vulkan-loader/xmake.lua
packages/v/vulkan-utility-libraries/xmake.lua

update vulkan related packages to v1.3.280

---

packages/w/wixtoolset/xmake.lua

Add wixtoolset

---

packages/g/glslang/xmake.lua

add default resource limiit to glslang

---

packages/l/liburing/xmake.lua

update liburing to 2.6

---

packages/n/nmd/xmake.lua
packages/r/rcmp/xmake.lua

improve deps

---

packages/v/vulkan-hpp/xmake.lua

Remove vulkan-hpp warnings as errors

---

packages/c/croaring/xmake.lua

New version of croaring detected (package version: nil, last github version: v3.0.1)

Auto-update croaring to v3.0.1

---

packages/s/shaderc/xmake.lua
packages/s/spirv-headers/xmake.lua

- spirv-headers: disable test
- shaderc: fix binary only config

improve spirv-headers/shaderc

---

packages/i/icu4c/xmake.lua

icu4c: improve windows build

---

packages/i/imgui/xmake.lua

Update imgui to 1.90.6

---

packages/s/simsimd/xmake.lua

New version of simsimd detected (package version: v3.9.0, last github version: v4.3.1)

Auto-update simsimd to v4.3.1

---

packages/c/cpp-httplib/xmake.lua
scripts/packages.lua
scripts/test.lua

wait https://github.com/xmake-io/xmake/pull/5086

Add check support

---

packages/p/poco/xmake.lua

Add Poco version 1.13.3

---

packages/n/nghttp2/xmake.lua

update nghttp2 to 1.62.0

---

packages/m/msgpack-cxx/xmake.lua

udpate msgpack-cxx to 6.1.1

---

packages/m/mimalloc/xmake.lua

- add `CMAKE_BUILD_TYPE` to fix link crt error
- use `MI_INSTALL_TOPLEVEL` install cmake config files

mimalloc: fix install cmake config files

---

packages/p/pyincpp/xmake.lua

add version 2.3.0 and checks for pyincpp

add version 2.3.0 and checks for pyincpp

---

packages/w/wixtoolset/xmake.lua

Set kind for wixtoolset

---

packages/p/pyincpp/xmake.lua

more stringent checks on C++20 support

update xmake.lua: more stringent checks on C++20 support for pyincpp

---

packages/x/xtensor/xmake.lua

xtensor require a specific major version of their dependencies 
https://github.com/xtensor-stack/xtensor?tab=readme-ov-file#dependencies

Fix xtensor versions dependencies

---

packages/g/geos/xmake.lua

Use official GitHub repository releases URL instead

upgrade versions of `geos`

---

packages/t/thrift/xmake.lua

thrift: update version

---

packages/c/croaring/xmake.lua

New version of croaring detected (package version: v3.0.1, last github version: v4.0.0)

Auto-update croaring to v4.0.0

---

packages/p/python/xmake.lua
packages/t/tbb/xmake.lua

python 12.3
(if  not is_host("windows"))

Python123 

---

packages/p/python/xmake.lua

python: Add 3.12.3 for Windows

---

packages/s/stringbuilder/xmake.lua

Add `stringbuilder` package.

---

packages/p/plf_hive/xmake.lua

Split this failing package out of https://github.com/xmake-io/xmake-repo/pull/3742

Add `plf_hive` package

---

packages/v/vcglib/xmake.lua

add vcglib include dir

---

packages/r/raylib-cpp/xmake.lua

------
~The PR title will replace the internal commit message when merging, hopefully it's acceptable.~ Fixed via force-push.

Add package raylib-cpp

---

packages/t/tbb/fetch.lua

Oneapi has changed its pathes for tbb

Update fetching policy for TBB library

---

packages/s/sqlite3/xmake.lua

update sqlite3 to 3.46.0

---

packages/s/scnlib/xmake.lua

New version of scnlib detected (package version: 2.0.2, last github version: 2.0.3)

Auto-update scnlib to 2.0.3

---

packages/t/tracy/xmake.lua

improve tracy

---

packages/b/boost/xmake.lua

try fixing boost using clang toolchain build shared lib

---

packages/p/python/xmake.lua
packages/t/thorvg/xmake.lua

New version of thorvg detected (package version: v0.13.2, last github version: v0.13.5)

Auto-update thorvg to v0.13.5

---

packages/l/llvm/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/4158

Improve llvm urls

---

packages/b/boost/xmake.lua

Fix https://github.com/xmake-io/xmake-repo/issues/4180
patch ref: https://github.com/boostorg/build/commit/aaf14325ec8e3ca86be9afaa501bca68fcfea8b3

boost: fix v144 toolset

---

packages/o/onednn/xmake.lua

Update onednn 3.4.3

---

packages/z/zziplib/xmake.lua

New version of zziplib detected (package version: v0.13.74, last github version: v0.13.76)

Auto-update zziplib to v0.13.76

---

packages/c/cminpack/xmake.lua

------
The cminpack package has released a new version, and I kept the latest and some old versions. Test has also been done.

update cminpack versions

---

packages/a/aqt/xmake.lua
packages/q/qtbase/xmake.lua

https://github.com/xmake-io/xmake/issues/5168

rename vs runtimes

---

packages/g/glog/xmake.lua

https://github.com/xmake-io/xmake-repo/discussions/4221

fix glog & folly

---

packages/h/highway/xmake.lua

Update highway to 1.2.0

---

packages/q/quill/xmake.lua

close https://github.com/xmake-io/xmake-repo/issues/4212

quill: update to 4.3.0

---

packages/l/libhv/xmake.lua

Transfer debugging mode to cmake configuration in libhv package

Transfer debugging mode to cmake configuration in libhv package

---

packages/c/curl/xmake.lua
packages/l/libcurl/xmake.lua

add curl cli

---

packages/v/vcpkg/xmake.lua

add vcpkg tool

---

packages/w/workflow/xmake.lua

目前workflow的windows分支无法和主分支版本对应，先以windows分支最新commit加上对windows的支持
https://github.com/sogou/workflow/issues/1569

add windows support to workflow

---

packages/q/quirc/xmake.lua

QR codes are a type of high-density matrix barcodes, and [quirc](https://github.com/dlbeer/quirc) is a library for extracting and decoding them from images.

add quirc package

---

packages/f/ffmpeg/xmake.lua

ffmpeg: Add dl syslinks

---

.github/workflows/macos_x86_64.yml
packages/m/moltenvk/xmake.lua

New version of moltenvk detected (package version: nil, last github version: v1.2.8)

Auto-update moltenvk to v1.2.8

---

packages/b/boost/xmake.lua

fix https://github.com/xmake-io/xmake-repo/issues/4263
Windows platform doesn't need to deal with link order

boost: improve links

---

packages/c/cimg/xmake.lua

Update CImg from v3.2.6 to v3.3.6

Update CImg to 3.3.6

---

packages/z/zig/xmake.lua

Update zig to 0.13.0

---

packages/b/boost/xmake.lua

Boost: Better asan fix

---

packages/r/rapidhash/xmake.lua

add rapidhash library

---

packages/g/go/xmake.lua

There are important security fixes in v1.22.4.

Update go to 1.22.4

---

packages/m/mkl/fetch.lua

replace \\ with / for linux compatibility
------

Update MKL fetch.lua

---

packages/c/cpp-async/xmake.lua

Add cpp-async package

---

packages/t/tbb/fetch.lua

replace \\ with / for Linux path compatibility
------

Update TBB fetch.lua

---

packages/j/jsoncons/xmake.lua

Update jsoncons to 0.176.0

---

packages/v/vulkan-memory-allocator/xmake.lua

update VulkanMemoryAllocator to v3.1.0

---

packages/t/teascript/patches/0.14.0/macosx.patch
packages/t/teascript/xmake.lua

New version of teascript detected (package version: v0.13.0, last github version: v0.14.0)

Auto-update teascript to v0.14.0

---

packages/l/liboqs/xmake.lua

add liboqs package

---

packages/f/fizz/xmake.lua

improve fizz

---

packages/f/folly/xmake.lua
packages/w/wangle/xmake.lua

update wangle to 06.10

---

packages/f/fbthrift/xmake.lua

Update fbthrift to 06.10

---

packages/f/folly/xmake.lua
packages/p/proxygen/xmake.lua

Update proxygen to 06.10

---

packages/f/ffmpeg/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/3951

add pkg-config deps for ffmpeg

---

packages/l/libuv/xmake.lua

I mean, at some point, things need to stop randomly breaking and requiring nonsense solutions like checking if a function exists.

I don't know anymore

---

packages/c/cpptrace/xmake.lua

Fix cpptrace linux build

---

packages/x/x265/xmake.lua

fix https://github.com/xmake-io/xmake-repo/issues/4402

x265: fix syslinks

---

packages/m/mkl/xmake.lua

Update MKL 2024.2.0 static libraries and headers on Win and Linux

---

packages/l/libassert/xmake.lua

Update libassert to 2.1.0

---

packages/l/libpthread-stubs/xmake.lua
packages/l/libsdl/xmake.lua
packages/l/libx11/xmake.lua
packages/l/libxau/xmake.lua
packages/l/libxcb/xmake.lua
packages/l/libxdmcp/xmake.lua
packages/l/libxext/xmake.lua
packages/u/util-macros/xmake.lua
packages/x/xcb-proto/xmake.lua
packages/x/xorgproto/xmake.lua
packages/x/xtrans/xmake.lua

libsdl: Add support of x11 and wayland on FreeBSD

---

packages/f/fbthrift/xmake.lua
packages/f/fizz/xmake.lua
packages/f/folly/xmake.lua
packages/m/mvfst/xmake.lua
packages/p/proxygen/xmake.lua
packages/w/wangle/xmake.lua

update folly related to 06.24

---

packages/f/fatal/xmake.lua

add fatal package

---

packages/r/reflect-cpp/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/4466

reflect-cpp: remove cmake install

---

packages/b/boost/xmake.lua

fix https://github.com/xmake-io/xmake-repo/issues/4477

boost: fix llvm toolchain

---

packages/p/pcapplusplus/xmake.lua

需要等这个合并之后再触发测试
https://github.com/xmake-io/xmake-repo/pull/4492

Add pcapplusplus

---

packages/f/freeglut/xmake.lua

New version of freeglut detected (package version: v3.4.0, last github version: v3.6.0)

Auto-update freeglut to v3.6.0

---

packages/y/yoga/xmake.lua

update yoga to 3.1.0

---

packages/l/libopus/xmake.lua

update libopus latest to 1.5.2

update libopus to 1.5.2

---

packages/o/objfw/xmake.lua

Updated objfw

---

packages/m/magic_enum/xmake.lua

update magic_enum to 0.9.6

---

packages/r/rocksdb/xmake.lua

New version of rocksdb detected (package version: v9.1.1, last github version: v9.2.1)

Auto-update rocksdb to v9.2.1

---

packages/m/metalang99/xmake.lua

metalang99: add package

---

packages/f/fbthrift/xmake.lua
packages/f/fizz/xmake.lua
packages/f/folly/xmake.lua
packages/m/mvfst/xmake.lua
packages/p/proxygen/xmake.lua
packages/w/wangle/xmake.lua

update folly related to 07.01

---

packages/d/depot_tools/xmake.lua

fix depot_tools

---

packages/d/datatype99/xmake.lua

datatype99: add package

---

packages/i/interface99/xmake.lua

interface99: add package

---

packages/q/qtifw/xmake.lua

------
aqt中的qtifw只有4.7.0版本，因此无法从xmake安装qtifw

update qtifw to 4.7.0

---

packages/f/folly/xmake.lua
packages/g/glog/xmake.lua

try enable folly for windows

---

packages/a/assimp/xmake.lua

update assimp to v5.4.2

---

packages/a/assimp/xmake.lua

assimp: Fix 5.4.2 hash

---

packages/c/commata/xmake.lua

add commata packages

---

packages/f/fluidsynth/patches/2.3.3/find-intl.patch
packages/f/fluidsynth/patches/2.3.5/find-intl.patch
packages/f/fluidsynth/xmake.lua

------
更新fluidsynth到2.3.5，并修复链接错误。取代 #3854 。

upgrade fluidsynth and fix missing symbol in recent xmake

---

packages/f/fmt/xmake.lua

update fmt to 11.0.1

---

packages/l/libsodium/xmake.lua

Both libs were built leading to some issues

libsodium: Fix static and shared build

---

packages/f/fbthrift/xmake.lua
packages/f/fizz/xmake.lua
packages/f/folly/xmake.lua
packages/m/mvfst/xmake.lua
packages/p/proxygen/xmake.lua
packages/w/wangle/xmake.lua

update folly related to 07.08

---

packages/n/nlohmann_json/xmake.lua
packages/t/tinygltf/xmake.lua

New version of tinygltf detected (package version: v2.8.22, last github version: v2.9.2)

Auto-update tinygltf to v2.9.2

---

packages/y/yyjson/xmake.lua

update yyjson to 0.10.0

---

packages/n/node-api-headers/xmake.lua

Needed by https://github.com/xmake-io/xmake-repo/pull/4505

add node_api_headers package

---

packages/h/hyperscan/xmake.lua
packages/r/ragel/xmake.lua

add hyperscan package

---

packages/w/watcher/xmake.lua

* Before adding new features and new modules, please go to issues to submit the relevant feature description first. ✅
* Write good commit messages and use the same coding conventions as the rest of the project. ✅
* Please commit code to dev branch and we will merge into master branch in feature ✅
* Ensure your edited codes with four spaces instead of TAB. ✅
------

Update watcher to version 0.11.0

---

packages/m/meshoptimizer/xmake.lua

update meshoptimizer to v0.21

---

packages/b/blake3/port/xmake.lua
packages/b/blake3/xmake.lua

New version of blake3 detected (package version: 1.5.1, last github version: 1.5.2)

Auto-update blake3 to 1.5.2

---

packages/i/itlib/xmake.lua

New version of itlib detected (package version: v1.10.3, last github version: v1.11.0)

Auto-update itlib to v1.11.0

---

packages/f/fbthrift/xmake.lua
packages/f/fizz/xmake.lua
packages/f/folly/xmake.lua
packages/m/mvfst/xmake.lua
packages/p/proxygen/xmake.lua
packages/w/wangle/xmake.lua

[folly related] update to 07.15

---

packages/o/osip/xmake.lua

ospp中虽然没有这个包的要求，但这个包是exosip依赖的包，所以先添加该包的支持

add the osip repo
