- packages/e/etl/xmake.lua
New version of etl detected (package version: 20.38.16, last github version: 20.38.17)
> Auto-update etl to 20.38.17

- packages/f/folly/xmake.lua
Folly do not support glog 0.7.0 yet:
https://github.com/facebook/folly/issues/2171
> Use glog <0.7.0 for folly

- packages/a/ada/xmake.lua
New version of ada detected (package version: 2.7.8, last github version: 2.8.0)
> Auto-update ada to 2.8.0

- packages/c/csvparser/xmake.lua
New version of csvparser detected (package version: 2.2.2, last github version: 2.2.3)
> Auto-update csvparser to 2.2.3

- packages/c/cppcheck/xmake.lua
New version of cppcheck detected (package version: 2.13.4, last github version: 2.14.1)
> Auto-update cppcheck to 2.14.1

- packages/c/crossguid/xmake.lua
https://github.com/graeme-hill/crossguid/pull/67
原仓库不更新了，缺个头文件补一下
> fix crossguid build bug in gcc 13

- packages/q/quickjs/xmake.lua
fix https://github.com/xmake-io/xmake-repo/issues/4276
- crlf -> `0a240fdc13b31090bde7ebba10dacaabf42db0f580583b79af7cd53a0730a7c0`
- lf -> `e793d03b7c4db3741cfa3565f8fb1f6337afb31df33f4123c4050d65ffdd28a1`
Which is best?
> quickjs: fix patch checksum

- packages/t/tinygltf/xmake.lua
New version of tinygltf detected (package version: v2.8.21, last github version: v2.8.22)
> Auto-update tinygltf to v2.8.22

- packages/b/boost/xmake.lua
add nolzma and nozstd config option
default is true  which will disable using zstd and xz
if set as false it will add_deps xz/zstd then complie boost with the deps
> add nolzma and nozstd config option for boost.iostreams

- packages/m/msdfgen/xmake.lua
New version of msdfgen detected (package version: v1.11, last github version: v1.12)
> Auto-update msdfgen to v1.12

- packages/a/aws-c-http/xmake.lua
New version of aws-c-http detected (package version: v0.8.1, last github version: v0.8.2)
> Auto-update aws-c-http to v0.8.2

- packages/b/boost/xmake.lua
for boost lzma zstd 
测试函数从 int main() 改成 void test() 之后 忘记删除 return 0
删除多余的 return 0；
> remove void test return 0 statement

- packages/e/expected-lite/xmake.lua
New version of expected-lite detected (package version: v0.6.3, last github version: v0.8.0)
> Auto-update expected-lite to v0.8.0

- packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.4.14, last github version: v1.4.16)
> Auto-update s2n-tls to v1.4.16

- packages/p/pdfhummus/xmake.lua
New version of pdfhummus detected (package version: v4.6.3, last github version: v4.6.4)
> Auto-update pdfhummus to v4.6.4

- packages/m/meson/xmake.lua
New version of meson detected (package version: 1.4.0, last github version: 1.4.1)
> Auto-update meson to 1.4.1

- packages/o/onedpl/fetch.lua
- packages/o/onedpl/xmake.lua
tested with TBB backend
and it should work for omp backend
I wonder if TBB links/linkdirs should be explicitly added or these can be implicitly inferred after adding package deps ("openmp")?
> onedpl add fetch.lua

- packages/l/libsodium/xmake.lua
New version of libsodium detected (package version: 1.0.19, last github version: 1.0.20)
> Auto-update libsodium to 1.0.20

- packages/t/tiny-optional/xmake.lua
New version of tiny-optional detected (package version: v1.2.1, last github version: v1.3.1)
> Auto-update tiny-optional to v1.3.1

- packages/e/epoll-shim/xmake.lua
when reported by pkginfo, the epoll-shim include is not part of it
> Fix epoll-shim include dir

- packages/r/reflect-cpp/xmake.lua
New version of reflect-cpp detected (package version: v0.10.0, last github version: v0.11.1)
> Auto-update reflect-cpp to v0.11.1

- packages/l/libsais/xmake.lua
New version of libsais detected (package version: v2.8.2, last github version: v2.8.3)
> Auto-update libsais to v2.8.3

- packages/e/efsw/xmake.lua
New version of efsw detected (package version: 1.3.1, last github version: 1.4.0)
> Auto-update efsw to 1.4.0

- packages/n/ngtcp2/xmake.lua
New version of ngtcp2 detected (package version: 1.5.0, last github version: 1.6.0)
> Auto-update ngtcp2 to 1.6.0

- packages/c/cpptrace/xmake.lua
New version of cpptrace detected (package version: v0.6.0, last github version: v0.6.1)
> Auto-update cpptrace to v0.6.1

- packages/c/cgltf/xmake.lua
New version of cgltf detected (package version: v1.13, last github version: v1.14)
> Auto-update cgltf to v1.14

- packages/s/string-view-lite/xmake.lua
New version of string-view-lite detected (package version: v1.7.0, last github version: v1.8.0)
> Auto-update string-view-lite to v1.8.0

- packages/o/onednn/xmake.lua
New version of onednn detected (package version: v3.4.3, last github version: v3.5)
> Auto-update onednn to v3.5

- packages/d/dynareadout/xmake.lua
New version of dynareadout detected (package version: 24.03, last github version: 24.05)
> Auto-update dynareadout to 24.05

- packages/t/trantor/xmake.lua
New version of trantor detected (package version: v1.5.18, last github version: v1.5.19)
> Auto-update trantor to v1.5.19

- packages/i/ittapi/xmake.lua
New version of ittapi detected (package version: v3.24.7, last github version: v3.24.8)
> Auto-update ittapi to v3.24.8

- packages/m/minizip-ng/xmake.lua
New version of minizip-ng detected (package version: 4.0.6, last github version: 4.0.7)
> Auto-update minizip-ng to 4.0.7

- packages/c/c-ares/xmake.lua
New version of c-ares detected (package version: 1.30.0, last github version: 1.31.0)
> Auto-update c-ares to 1.31.0

- packages/s/simsimd/xmake.lua
New version of simsimd detected (package version: v4.3.1, last github version: v4.3.2)
> Auto-update simsimd to v4.3.2

- packages/a/aws-c-cal/xmake.lua
New version of aws-c-cal detected (package version: v0.6.14, last github version: v0.6.15)
> Auto-update aws-c-cal to v0.6.15

- packages/c/cpp-sort/xmake.lua
New version of cpp-sort detected (package version: 1.15.0, last github version: 1.16.0)
> Auto-update cpp-sort to 1.16.0

- packages/m/mujs/xmake.lua
New version of mujs detected (package version: 1.3.4, last github version: 1.3.5)
> Auto-update mujs to 1.3.5

- packages/c/c-blosc2/xmake.lua
New version of c-blosc2 detected (package version: v2.14.4, last github version: v2.15.0)
> Auto-update c-blosc2 to v2.15.0

- packages/s/samurai/xmake.lua
New version of samurai detected (package version: v0.14.0, last github version: v0.16.0)
> Auto-update samurai to v0.16.0

- packages/s/sentry-native/xmake.lua
New version of sentry-native detected (package version: 0.7.5, last github version: 0.7.6)
> Auto-update sentry-native to 0.7.6

- packages/c/cpptrace/xmake.lua
New version of cpptrace detected (package version: v0.6.1, last github version: v0.6.2)
> Auto-update cpptrace to v0.6.2

- packages/f/fribidi/xmake.lua
New version of fribidi detected (package version: 1.0.14, last github version: 1.0.15)
> Auto-update fribidi to 1.0.15

- packages/m/mathter/xmake.lua
New version of mathter detected (package version: v1.1.1, last github version: v1.1.2)
> Auto-update mathter to v1.1.2

- packages/m/matchit/xmake.lua
Detailed meta info see added `xmake.lua`.
- author: BowenFu
- home page: https://bowenfu.github.io/matchit.cpp/
- github repo: https://github.com/BowenFu/matchit.cpp.git
- description: A lightweight single-header pattern-matching library for C++17 with macro-free APIs.
> Add header only package `matchit`

- packages/e/emmylua_debugger/xmake.lua
New version of emmylua_debugger detected (package version: 1.8.0, last github version: 1.8.1)
> Auto-update emmylua_debugger to 1.8.1

- packages/t/thorvg/xmake.lua
New version of thorvg detected (package version: v0.13.6, last github version: v0.13.8)
> Auto-update thorvg to v0.13.8

- packages/c/cppcheck/xmake.lua
New version of cppcheck detected (package version: 2.14.1, last github version: 2.14.2)
> Auto-update cppcheck to 2.14.2

- packages/s/simdjson/xmake.lua
New version of simdjson detected (package version: v3.9.3, last github version: v3.9.4)
> Auto-update simdjson to v3.9.4

- packages/r/re-flex/xmake.lua
New version of re-flex detected (package version: v4.3.0, last github version: v4.4.0)
> Auto-update re-flex to v4.4.0

- packages/a/aws-c-io/xmake.lua
New version of aws-c-io detected (package version: v0.14.8, last github version: v0.14.9)
> Auto-update aws-c-io to v0.14.9

- packages/n/nsync/xmake.lua
New version of nsync detected (package version: 1.28.1, last github version: 1.29.1)
> Auto-update nsync to 1.29.1

- packages/t/toml11/xmake.lua
New version of toml11 detected (package version: v3.8.1, last github version: v4.0.1)
close: #4436
> Auto-update toml11 to v4.0.1

- packages/b/blosc/xmake.lua
New version of blosc detected (package version: v1.21.5, last github version: v1.21.6)
> Auto-update blosc to v1.21.6

- packages/l/lightgbm/xmake.lua
New version of lightgbm detected (package version: 4.3.0, last github version: 4.4.0)
> Auto-update lightgbm to 4.4.0

- packages/u/ucx/xmake.lua
New version of ucx detected (package version: 1.16.0, last github version: 1.17.0)
> Auto-update ucx to 1.17.0

- packages/p/pahomqttcpp/xmake.lua
New version of pahomqttcpp detected (package version: v1.3.2, last github version: v1.4.0)
> Auto-update pahomqttcpp to v1.4.0

- packages/b/b2/xmake.lua
New version of b2 detected (package version: 5.1.0, last github version: 5.2.1)
> Auto-update b2 to 5.2.1

- packages/a/arduinojson/xmake.lua
New version of arduinojson detected (package version: v7.0.4, last github version: v7.1.0)
> Auto-update arduinojson to v7.1.0

- packages/l/libsais/xmake.lua
New version of libsais detected (package version: v2.8.3, last github version: v2.8.4)
> Auto-update libsais to v2.8.4

- packages/a/ade/patches/0.1.2/cmake-mingw.patch
- packages/a/ade/xmake.lua
New version of ade detected (package version: v0.1.2d, last github version: v0.1.2)
> Auto-update ade to v0.1.2

- packages/n/nativefiledialog-extended/xmake.lua
New version of nativefiledialog-extended detected (package version: v1.1.1, last github version: v1.2.0)
> Auto-update nativefiledialog-extended to v1.2.0

- packages/c/csvparser/xmake.lua
New version of csvparser detected (package version: 2.2.3, last github version: 2.3.0)
> Auto-update csvparser to 2.3.0

- packages/a/aws-c-s3/xmake.lua
New version of aws-c-s3 detected (package version: v0.5.9, last github version: v0.6.0)
> Auto-update aws-c-s3 to v0.6.0

- packages/c/cgif/xmake.lua
New version of cgif detected (package version: v0.4.0, last github version: v0.4.1)
> Auto-update cgif to v0.4.1

- packages/r/rapidcsv/xmake.lua
New version of rapidcsv detected (package version: 8.82, last github version: 8.83)
> Auto-update rapidcsv to 8.83

- packages/a/aws-c-common/xmake.lua
New version of aws-c-common detected (package version: v0.9.19, last github version: v0.9.23)
> Auto-update aws-c-common to v0.9.23

- packages/l/libdwarf/xmake.lua
New version of libdwarf detected (package version: 0.9.2, last github version: 0.10.0)
> Auto-update libdwarf to 0.10.0

- packages/e/emmylua_debugger/xmake.lua
New version of emmylua_debugger detected (package version: 1.8.1, last github version: 1.8.2)
> Auto-update emmylua_debugger to 1.8.2

- packages/t/toml11/xmake.lua
New version of toml11 detected (package version: v4.0.1, last github version: v4.0.2)
> Auto-update toml11 to v4.0.2

- packages/f/fast-cdr/xmake.lua
New version of fast-cdr detected (package version: v2.2.1, last github version: v2.2.2)
> Auto-update fast-cdr to v2.2.2

- packages/n/nsync/xmake.lua
New version of nsync detected (package version: 1.29.1, last github version: 1.29.2)
> Auto-update nsync to 1.29.2

- packages/g/ginkgo/xmake.lua
New version of ginkgo detected (package version: v1.7.0, last github version: v1.8.0)
> Auto-update ginkgo to v1.8.0

- packages/p/protobuf-cpp/xmake.lua
New version of protobuf-cpp detected (package version: 27.0, last github version: 27.2)
close: #4282
> Auto-update protobuf-cpp to 27.2

- packages/r/reflect-cpp/xmake.lua
New version of reflect-cpp detected (package version: v0.11.1, last github version: v0.12.0)
> Auto-update reflect-cpp to v0.12.0

- packages/d/daw_json_link/xmake.lua
New version of daw_json_link detected (package version: v3.24.0, last github version: v3.24.1)
> Auto-update daw_json_link to v3.24.1

- packages/i/ittapi/xmake.lua
New version of ittapi detected (package version: v3.24.8, last github version: v3.25.1)
> Auto-update ittapi to v3.25.1

- packages/p/pocketpy/xmake.lua
New version of pocketpy detected (package version: v1.4.5, last github version: v1.4.6)
> Auto-update pocketpy to v1.4.6

- packages/l/libdwarf/xmake.lua
New version of libdwarf detected (package version: 0.10.0, last github version: 0.10.1)
> Auto-update libdwarf to 0.10.1

- packages/g/glaze/xmake.lua
New version of glaze detected (package version: v2.7.0, last github version: v2.9.5)
> Auto-update glaze to v2.9.5

- packages/d/daw_header_libraries/xmake.lua
New version of daw_header_libraries detected (package version: v2.106.0, last github version: v2.106.1)
> Auto-update daw_header_libraries to v2.106.1

- packages/t/tgbot-cpp/xmake.lua
New version of tgbot-cpp detected (package version: v1.7.3, last github version: v1.8)
> Auto-update tgbot-cpp to v1.8

- packages/r/raylib-cpp/xmake.lua
New version of raylib-cpp detected (package version: v5.0.1, last github version: v5.0.2)
> Auto-update raylib-cpp to v5.0.2

- packages/h/highs/xmake.lua
New version of highs detected (package version: v1.7.1, last github version: v1.7.2)
> Auto-update highs to v1.7.2

- packages/t/thorvg/xmake.lua
New version of thorvg detected (package version: v0.13.8, last github version: v0.14.1)
> Auto-update thorvg to v0.14.1

- packages/a/ada/xmake.lua
New version of ada detected (package version: v2.8.0, last github version: v2.9.0)
> Auto-update ada to v2.9.0

- packages/d/dartsim/xmake.lua
New version of dartsim detected (package version: v6.14.2, last github version: v6.14.4)
> Auto-update dartsim to v6.14.4

- packages/z/zlib-ng/xmake.lua
New version of zlib-ng detected (package version: 2.1.6, last github version: 2.2.1)
> Auto-update zlib-ng to 2.2.1

- packages/v/vk-bootstrap/xmake.lua
New version of vk-bootstrap detected (package version: v1.3.285, last github version: v1.3.289)
> Auto-update vk-bootstrap to v1.3.289

- packages/s/scons/xmake.lua
New version of scons detected (package version: 4.7.0, last github version: 4.8.0)
> Auto-update scons to 4.8.0

- packages/c/cargs/xmake.lua
New version of cargs detected (package version: v1.1.0, last github version: v1.2.0)
> Auto-update cargs to v1.2.0

- packages/u/uwebsockets/xmake.lua
New version of uwebsockets detected (package version: v20.62.0, last github version: v20.64.0)
> Auto-update uwebsockets to v20.64.0

- packages/m/mapbox_polylabel/xmake.lua
New version of mapbox_polylabel detected (package version: v2.0.0, last github version: v2.0.1)
> Auto-update mapbox_polylabel to v2.0.1

- packages/p/pdfhummus/xmake.lua
New version of pdfhummus detected (package version: v4.6.4, last github version: v4.6.6)
> Auto-update pdfhummus to v4.6.6

- packages/l/lunasvg/xmake.lua
New version of lunasvg detected (package version: v2.3.9, last github version: v2.4.0)
> Auto-update lunasvg to v2.4.0

- packages/c/clove-unit/xmake.lua
New version of clove-unit detected (package version: v2.4.4, last github version: v2.4.5)
> Auto-update clove-unit to v2.4.5

- packages/a/aws-crt-cpp/xmake.lua
New version of aws-crt-cpp detected (package version: v0.26.11, last github version: v0.27.2)
> Auto-update aws-crt-cpp to v0.27.2

- packages/z/zziplib/xmake.lua
New version of zziplib detected (package version: v0.13.76, last github version: v0.13.77)
> Auto-update zziplib to v0.13.77

- packages/d/date/xmake.lua
The maintainer recommends to use "live at head" - https://github.com/HowardHinnant/date/issues/828#issuecomment-2184283807
> date: fix links, change versioning

- packages/s/simdutf/xmake.lua
New version of simdutf detected (package version: v5.2.8, last github version: v5.3.0)
> Auto-update simdutf to v5.3.0

- packages/m/meson/xmake.lua
New version of meson detected (package version: 1.4.1, last github version: 1.4.2)
> Auto-update meson to 1.4.2

- packages/p/pahomqttcpp/xmake.lua
New version of pahomqttcpp detected (package version: v1.4.0, last github version: v1.4.1)
> Auto-update pahomqttcpp to v1.4.1

- packages/v/volk/xmake.lua
The package script file for `volk` library does not include a linkage specification, which will fail the linkage validation on latest xmake version:
```
error: package(volk): links not found!
=> install volk 1.3.283+0 .. failed
error: install failed!
```
See https://github.com/JX-Master/LunaSDK/actions/runs/9902626221/job/27356844358 for full log.
This pull request fixes this bug by adding a `on_load` callback function to explicitly specify the library as header-only, so that the linkage validation will not cause installation failure.
> Add `on_load` function to volk package script to fix installing error on latest xmake version.

- packages/f/flecs/xmake.lua
New version of flecs detected (package version: v3.2.11, last github version: v3.2.12)
> Auto-update flecs to v3.2.12

- packages/g/glaze/xmake.lua
This makes the glaze library multiplatform
> Make glaze multiplatform

- packages/n/node-api-headers/xmake.lua
New version of node-api-headers detected (package version: v1.1.0, last github version: v1.2.0)
> Auto-update node-api-headers to v1.2.0

- packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.4.16, last github version: v1.4.17)
> Auto-update s2n-tls to v1.4.17

- packages/v/vvenc/xmake.lua
New version of vvenc detected (package version: v1.11.1, last github version: v1.12.0)
> Auto-update vvenc to v1.12.0

- packages/r/rapidfuzz/xmake.lua
New version of rapidfuzz detected (package version: v3.0.4, last github version: v3.0.5)
> Auto-update rapidfuzz to v3.0.5

- packages/s/simdjson/xmake.lua
New version of simdjson detected (package version: v3.9.4, last github version: v3.9.5)
> Auto-update simdjson to v3.9.5

- packages/c/cgraph/xmake.lua
New version of cgraph detected (package version: v2.5.4, last github version: v2.6.0)
> Auto-update cgraph to v2.6.0

- packages/s/scnlib/xmake.lua
New version of scnlib detected (package version: v2.0.3, last github version: v3.0.1)
> Auto-update scnlib to v3.0.1

- packages/c/cserialport/xmake.lua
> add cserialport lib

- packages/b/binutils/xmake.lua
Fixes https://github.com/xmake-io/xmake/issues/5267
> add on_fetch to binutils package

- packages/t/trompeloeil/xmake.lua
New version of trompeloeil detected (package version: v47, last github version: v48)
> Auto-update trompeloeil to v48

- packages/l/libsvm/xmake.lua
New version of libsvm detected (package version: v332, last github version: v333)
> Auto-update libsvm to v333

- packages/a/aws-c-io/xmake.lua
New version of aws-c-io detected (package version: v0.14.9, last github version: v0.14.13)
> Auto-update aws-c-io to v0.14.13

- packages/b/binutils/xmake.lua
fix a typo I made in https://github.com/xmake-io/xmake-repo/pull/4636
> fix typo in binutils package

- packages/b/botan/xmake.lua
New version of botan detected (package version: 3.4.0, last github version: 3.5.0)
> Auto-update botan to 3.5.0

- packages/g/gdal/xmake.lua
New version of gdal detected (package version: 3.9.0, last github version: 3.9.1)
> Auto-update gdal to 3.9.1

- packages/o/onednn/xmake.lua
New version of onednn detected (package version: v3.5, last github version: v3.5.1)
> Auto-update onednn to v3.5.1

- packages/t/tracy/xmake.lua
New version of tracy detected (package version: v0.10, last github version: v0.11.0)
> Auto-update tracy to v0.11.0

- packages/a/aws-crt-cpp/xmake.lua
New version of aws-crt-cpp detected (package version: v0.27.2, last github version: v0.27.4)
> Auto-update aws-crt-cpp to v0.27.4

- packages/t/thorvg/xmake.lua
New version of thorvg detected (package version: v0.14.1, last github version: v0.14.2)
> Auto-update thorvg to v0.14.2

- packages/v/vk-bootstrap/xmake.lua
New version of vk-bootstrap detected (package version: v1.3.289, last github version: v1.3.290)
> Auto-update vk-bootstrap to v1.3.290

- packages/f/fastgltf/xmake.lua
New version of fastgltf detected (package version: v0.7.1, last github version: v0.7.2)
> Auto-update fastgltf to v0.7.2

- packages/c/croaring/xmake.lua
New version of croaring detected (package version: v4.0.0, last github version: v4.1.0)
> Auto-update croaring to v4.1.0

- packages/a/argparse/xmake.lua
New version of argparse detected (package version: 3.0, last github version: 3.1)
> Auto-update argparse to 3.1

- packages/q/quill/xmake.lua
New version of quill detected (package version: v4.5.0, last github version: v5.0.0)
> Auto-update quill to v5.0.0

- packages/t/toml11/xmake.lua
New version of toml11 detected (package version: v4.0.2, last github version: v4.0.3)
> Auto-update toml11 to v4.0.3

- packages/t/thorvg/xmake.lua
New version of thorvg detected (package version: v0.14.2, last github version: v0.14.3)
> Auto-update thorvg to v0.14.3

- packages/l/libheif/xmake.lua
New version of libheif detected (package version: 1.17.6, last github version: 1.18.0)
> Auto-update libheif to 1.18.0

- packages/p/pyincpp/xmake.lua
New version of pyincpp detected (package version: v2.4.0, last github version: v2.4.1)
> Auto-update pyincpp to v2.4.1

- packages/m/moltenvk/xmake.lua
New version of moltenvk detected (package version: v1.2.9, last github version: v1.2.10)
> Auto-update moltenvk to v1.2.10

- packages/o/oatpp-openssl/xmake.lua
I hope to add oatpp-openssl. Meanwhile, since the existing package oatpp only supports three platforms, as an extension library, it should only support three platforms.
> add oatpp-openssl

- packages/q/quill/xmake.lua
New version of quill detected (package version: v5.0.0, last github version: v5.1.0)
> Auto-update quill to v5.1.0

- packages/b/blake3/xmake.lua
New version of blake3 detected (package version: 1.5.2, last github version: 1.5.3)
> Auto-update blake3 to 1.5.3

- packages/a/aws-c-cal/xmake.lua
New version of aws-c-cal detected (package version: v0.7.1, last github version: v0.7.2)
> Auto-update aws-c-cal to v0.7.2

- packages/v/vcpkg/xmake.lua
New version of vcpkg detected (package version: 2024.05.24, last github version: 2024.07.12)
> Auto-update vcpkg to 2024.07.12

- packages/t/trantor/xmake.lua
New version of trantor detected (package version: v1.5.19, last github version: v1.5.20)
> Auto-update trantor to v1.5.20

- packages/c/c-ares/xmake.lua
New version of c-ares detected (package version: 1.31.0, last github version: 1.32.2)
> Auto-update c-ares to 1.32.2

- packages/n/nanoflann/xmake.lua
New version of nanoflann detected (package version: v1.5.5, last github version: v1.6.0)
> Auto-update nanoflann to v1.6.0

- packages/o/openexr/xmake.lua
Some of OpenEXR headers use global include notation and contain only file name, without the nested "OpenEXR" subdirectory. That approach require additional include directory to be added on the user side in order to get proper paths for such headers.
This pull request fixes the problem by adding nested "include/OpenEXR" include directory that will guarantee that these headers can be included properly.
> OpenEXR: fixed wrong includepaths

- packages/f/ffmpeg/xmake.lua
fixes this:
```
> move C:\Users\lynix\AppData\Local\.xmake\packages\f\ffmpeg\7.0\11eee8174e3342b5b90ed61ac467badc\lib\libavcodec.a to C:\Users\lynix\AppData\Local\.xmake\packages\f\ffmpeg\7.0\11eee8174e3342b5b90ed61ac467badc\lib\avcodec.lib
error: @programdir\core\base\os.lua:132: attempt to index a number value (local 'opt')
stack traceback:
[@programdir\core\base\os.lua:132]:
[@programdir\core\sandbox\modules\os.lua:109]:
[...make\repositories\xmake-repo\packages\f\ffmpeg\xmake.lua:259]: in function 'script'
[...dir\modules\private\action\require\impl\utils\filter.lua:114]: in function 'call'
[...\modules\private\action\require\impl\actions\install.lua:404]:
=> install ffmpeg 7.0 .. failed
```
> ffmpeg: Fix script with xmake dev

- packages/c/c-ares/xmake.lua
New version of c-ares detected (package version: 1.32.2, last github version: 1.32.3)
> Auto-update c-ares to 1.32.3

- packages/c/cpptrace/xmake.lua
New version of cpptrace detected (package version: v0.6.2, last github version: v0.6.3)
> Auto-update cpptrace to v0.6.3

- packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.4.17, last github version: v1.4.18)
> Auto-update s2n-tls to v1.4.18

- packages/c/ctre/xmake.lua
- packages/r/reflect-cpp/xmake.lua
New version of reflect-cpp detected (package version: v0.12.0, last github version: v0.13.0)
> Auto-update reflect-cpp to v0.13.0

- packages/d/dynareadout/xmake.lua
New version of dynareadout detected (package version: 24.05, last github version: 24.07)
> Auto-update dynareadout to 24.07

- packages/l/lz4/xmake.lua
New version of lz4 detected (package version: v1.9.4, last github version: v1.10.0)
> Auto-update lz4 to v1.10.0

- packages/f/fast_float/xmake.lua
New version of fast_float detected (package version: v6.1.1, last github version: v6.1.3)
> Auto-update fast_float to v6.1.3

- packages/r/rocksdb/xmake.lua
New version of rocksdb detected (package version: v9.3.1, last github version: v9.4.0)
> Auto-update rocksdb to v9.4.0

- packages/a/aws-c-common/xmake.lua
New version of aws-c-common detected (package version: v0.9.23, last github version: v0.9.24)
> Auto-update aws-c-common to v0.9.24

- packages/l/libfabric/xmake.lua
New version of libfabric detected (package version: 1.20.2, last github version: 1.22.0)
> Auto-update libfabric to 1.22.0

- packages/b/boost_ut/xmake.lua
New version of boost_ut detected (package version: v2.0.1, last github version: v2.1.0)
> Auto-update boost_ut to v2.1.0

- packages/m/msgpack-c/xmake.lua
New version of msgpack-c detected (package version: 6.0.1, last github version: 6.0.2)
> Auto-update msgpack-c to 6.0.2

- packages/c/cuda-samples/xmake.lua
New version of cuda-samples detected (package version: v12.4.1, last github version: v12.5)
> Auto-update cuda-samples to v12.5

- packages/t/toml11/xmake.lua
New version of toml11 detected (package version: v4.0.3, last github version: v4.1.0)
> Auto-update toml11 to v4.1.0

- packages/y/yoga/xmake.lua
AFAIK, you technically need `#include <cstdint>` for `std::uint64_t`, and at least my compiler really needs that to compile the snippet. Otherwise only a `package(yoga) Require at least C++20.` error message appears
> yoga: Add missing include <cstdint>

- packages/z/zlog/xmake.lua
New version of zlog detected (package version: 1.2.17, last github version: 1.2.18)
> Auto-update zlog to 1.2.18

- packages/a/aws-c-io/xmake.lua
New version of aws-c-io detected (package version: v0.14.13, last github version: v0.14.14)
> Auto-update aws-c-io to v0.14.14

- packages/f/fastgltf/xmake.lua
New version of fastgltf detected (package version: v0.7.2, last github version: v0.8.0)
> Auto-update fastgltf to v0.8.0

- packages/a/atomic_queue/xmake.lua
New version of atomic_queue detected (package version: v1.6.3, last github version: v1.6.4)
> Auto-update atomic_queue to v1.6.4

- packages/g/glaze/xmake.lua
New version of glaze detected (package version: v2.9.5, last github version: v3.1.7)
> Auto-update glaze to v3.1.7

- packages/l/libwfkafka/xmake.lua
New version of libwfkafka detected (package version: v0.11.4, last github version: v0.11.5)
> Auto-update libwfkafka to v0.11.5

- packages/c/c-blosc2/xmake.lua
New version of c-blosc2 detected (package version: v2.15.0, last github version: v2.15.1)
> Auto-update c-blosc2 to v2.15.1

- scripts/build_artifacts.lua
目前如果package不支持windows上全部arch就不会build，使得很多只支持windows x64的package没有缓存，这里修复这一问题
> relax conditions on building artifacts

- packages/d/directxmath/xmake.lua
DirectXMath can supports compilation on macosx. Made changes to the `xmake.lua` to allow compilation on macosx.
To test compilation on mac, I copied over this package and renamed it to `dxmath`
> Add macosx platform support to directxmath

- packages/c/croaring/xmake.lua
New version of croaring detected (package version: v4.1.0, last github version: v4.1.1)
> Auto-update croaring to v4.1.1

- packages/a/actor-framework/xmake.lua
New version of actor-framework detected (package version: 1.0.0, last github version: 1.0.1)
> Auto-update actor-framework to 1.0.1

- packages/o/onednn/xmake.lua
New version of onednn detected (package version: v3.5.1, last github version: v3.5.2)
> Auto-update onednn to v3.5.2

- packages/m/meson/xmake.lua
New version of meson detected (package version: 1.4.2, last github version: 1.5.1)
> Auto-update meson to 1.5.1

- packages/g/glfw/xmake.lua
warning: please use package:runtimes() or package:has_runtime() instead of package:config("vs_runtime")
Added the line `package:has_tool("cxx", "cl") since the "DUSE_MSVC_RUNTIME_LIBRARY_DLL" flag is only needed for msvc.
> fixed xmake warning for GLFW package

- packages/r/rapidcsv/xmake.lua
Due to https://github.com/xmake-io/xmake/issues/5357 we have to mark such libraries explicitly.
> Add missed headeronly option for rapidcsv

- packages/a/aws-c-io/xmake.lua
New version of aws-c-io detected (package version: v0.14.14, last github version: v0.14.16)
> Auto-update aws-c-io to v0.14.16

- packages/p/protobuf-cpp/xmake.lua
New version of protobuf-cpp detected (package version: 27.2, last github version: 27.3)
> Auto-update protobuf-cpp to 27.3

- packages/d/dlib/xmake.lua
New version of dlib detected (package version: v19.24.4, last github version: v19.24.5)
> Auto-update dlib to v19.24.5

- packages/y/yalantinglibs/xmake.lua
New version of yalantinglibs detected (package version: 0.3.5, last github version: 0.3.6)
> Auto-update yalantinglibs to 0.3.6

- packages/o/onednn/xmake.lua
New version of onednn detected (package version: v3.5.2, last github version: v3.5.3)
> Auto-update onednn to v3.5.3

- packages/c/c-ares/xmake.lua
New version of c-ares detected (package version: 1.32.3, last github version: 1.33.0)
> Auto-update c-ares to 1.33.0

- packages/a/antlr4-runtime/xmake.lua
New version of antlr4-runtime detected (package version: 4.13.1, last github version: 4.13.2)
> Auto-update antlr4-runtime to 4.13.2

- packages/t/tinyexr/xmake.lua
New version of tinyexr detected (package version: v1.0.8, last github version: v1.0.9)
> Auto-update tinyexr to v1.0.9

- packages/a/aws-c-io/xmake.lua
New version of aws-c-io detected (package version: v0.14.16, last github version: v0.14.18)
> Auto-update aws-c-io to v0.14.18

- packages/l/libavif/xmake.lua
New version of libavif detected (package version: v1.1.0, last github version: v1.1.1)
> Auto-update libavif to v1.1.1

- packages/r/re-flex/xmake.lua
New version of re-flex detected (package version: v4.4.0, last github version: v4.5.0)
> Auto-update re-flex to v4.5.0

- packages/d/dlib/xmake.lua
- packages/d/dpp/port/xmake.lua
- packages/d/dpp/xmake.lua
* Before adding new features and new modules, please go to issues to submit the relevant feature description first. [✔️]
* See #4823 
* Write good commit messages and use the same coding conventions as the rest of the project. [✔️]
*  Across the whole pull request conventional commits are used.
* Please commit code to dev branch and we will merge into master branch in feature [✔️]
* Ensure your edited codes with four spaces instead of TAB. [✔️]
* The EditorConfig plugin for Visual Studio Code managed these based in the public [EditorConfig file in this repo](https://github.com/xmake-io/xmake-repo/blob/dev/.editorconfig).
> DPP: De-const have_voice option and add coroutines support.

- packages/n/nativefiledialog-extended/xmake.lua
New version of nativefiledialog-extended detected (package version: v1.2.0, last github version: v1.2.1)
> Auto-update nativefiledialog-extended to v1.2.1

- packages/f/fast-cdr/xmake.lua
New version of fast-cdr detected (package version: v2.2.2, last github version: v2.2.3)
> Auto-update fast-cdr to v2.2.3

- packages/l/libbigwig/xmake.lua
- packages/z/zlib-ng/xmake.lua
1) Default value for zlib-ng library is "OFF":
https://github.com/zlib-ng/zlib-ng/blob/develop/CMakeLists.txt#L77
2) We have only one library which depends on "zlib-ng". Fixed config there.
> zlib-ng is non-compat by default

- packages/u/uwebsockets/xmake.lua
New version of uwebsockets detected (package version: v20.64.0, last github version: v20.65.0)
> Auto-update uwebsockets to v20.65.0

- packages/e/etl/xmake.lua
New version of etl detected (package version: 20.38.17, last github version: 20.39.1)
> Auto-update etl to 20.39.1

- packages/p/pdfio/xmake.lua
New version of pdfio detected (package version: v1.3.0, last github version: v1.3.1)
> Auto-update pdfio to v1.3.1

- packages/j/jsbsim/xmake.lua
New version of jsbsim detected (package version: v1.2.0, last github version: v1.2.1)
> Auto-update jsbsim to v1.2.1

- packages/l/libheif/xmake.lua
New version of libheif detected (package version: 1.18.0, last github version: 1.18.2)
> Auto-update libheif to 1.18.2

- packages/e/etl/xmake.lua
New version of etl detected (package version: 20.39.1, last github version: 20.39.2)
> Auto-update etl to 20.39.2

- packages/s/simdutf/xmake.lua
New version of simdutf detected (package version: v5.3.0, last github version: v5.3.4)
> Auto-update simdutf to v5.3.4

- packages/h/highfive/xmake.lua
New version of highfive detected (package version: v2.9.0, last github version: v2.10.0)
> Auto-update highfive to v2.10.0

- packages/d/daw_json_link/xmake.lua
New version of daw_json_link detected (package version: v3.24.1, last github version: v3.26.0)
> Auto-update daw_json_link to v3.26.0

- packages/b/boost/xmake.lua
More details on #4866
In summary, Added zlib and bzip2 configurations similar to how it's being done with lzma and, this is done to enable the use of those libraries within boost iostreams.
> Add zlib and bzip2 support to boost iostreams

- packages/o/onnx/xmake.lua
New version of onnx detected (package version: v1.16.1, last github version: v1.16.2)
> Auto-update onnx to v1.16.2

- packages/s/simdjson/xmake.lua
New version of simdjson detected (package version: v3.9.5, last github version: v3.10.0)
> Auto-update simdjson to v3.10.0

- packages/r/reflect-cpp/xmake.lua
New version of reflect-cpp detected (package version: v0.13.0, last github version: v0.14.0)
> Auto-update reflect-cpp to v0.14.0

- packages/l/libdeflate/xmake.lua
New version of libdeflate detected (package version: v1.20, last github version: v1.21)
> Auto-update libdeflate to v1.21

- packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.4.18, last github version: v1.5.0)
> Auto-update s2n-tls to v1.5.0

- packages/t/tinygltf/xmake.lua
New version of tinygltf detected (package version: v2.9.2, last github version: v2.9.3)
> Auto-update tinygltf to v2.9.3

- packages/q/quill/xmake.lua
New version of quill detected (package version: v5.1.0, last github version: v6.1.0)
> Auto-update quill to v6.1.0

- packages/j/joltphysics/xmake.lua
New version of joltphysics detected (package version: v5.0.0, last github version: v5.1.0)
> Auto-update joltphysics to v5.1.0

- packages/q/quantlib/xmake.lua
New version of quantlib detected (package version: 1.34, last github version: 1.35)
> Auto-update quantlib to 1.35

- packages/a/aws-c-auth/xmake.lua
New version of aws-c-auth detected (package version: v0.7.22, last github version: v0.7.25)
> Auto-update aws-c-auth to v0.7.25

- packages/v/vk-bootstrap/xmake.lua
New version of vk-bootstrap detected (package version: v1.3.290, last github version: v1.3.292)
> Auto-update vk-bootstrap to v1.3.292

- packages/z/zziplib/xmake.lua
New version of zziplib detected (package version: v0.13.77, last github version: v0.13.78)
> Auto-update zziplib to v0.13.78

- packages/u/ufbx/xmake.lua
New version of ufbx detected (package version: v0.14.2, last github version: v0.14.3)
> Auto-update ufbx to v0.14.3

- packages/v/vc-ltl5/xmake.lua
New version of vc-ltl5 detected (package version: 5.0.9, last github version: 5.1.1)
> Auto-update vc-ltl5 to 5.1.1

- packages/a/aws-c-http/xmake.lua
New version of aws-c-http detected (package version: v0.8.2, last github version: v0.8.7)
> Auto-update aws-c-http to v0.8.7

- packages/a/aws-c-common/xmake.lua
New version of aws-c-common detected (package version: v0.9.25, last github version: v0.9.27)
> Auto-update aws-c-common to v0.9.27

- packages/c/cpp-channel/xmake.lua
New version of cpp-channel detected (package version: v0.8.2, last github version: v0.8.3)
> Auto-update cpp-channel to v0.8.3

- packages/c/catch2/xmake.lua
New version of catch2 detected (package version: v3.6.0, last github version: v3.7.0)
> Auto-update catch2 to v3.7.0

- packages/c/c4core/xmake.lua
New version of c4core detected (package version: 0.2.1, last github version: 0.2.2)
> Auto-update c4core to 0.2.2

- packages/m/mini/xmake.lua
New version of mini detected (package version: 0.9.15, last github version: 0.9.16)
> Auto-update mini to 0.9.16

- packages/r/reflect-cpp/xmake.lua
New version of reflect-cpp detected (package version: v0.14.0, last github version: v0.14.1)
> Auto-update reflect-cpp to v0.14.1

- packages/c/cmark/xmake.lua
New version of cmark detected (package version: 0.31.0, last github version: 0.31.1)
> Auto-update cmark to 0.31.1

- packages/y/yalantinglibs/xmake.lua
New version of yalantinglibs detected (package version: 0.3.6, last github version: 0.3.7)
> Auto-update yalantinglibs to 0.3.7

- packages/t/thorvg/xmake.lua
New version of thorvg detected (package version: v0.14.3, last github version: v0.14.6)
> Auto-update thorvg to v0.14.6

- packages/l/libvips/patches/8.15.3/msvc-ssize_t.patch
- packages/l/libvips/xmake.lua
New version of libvips detected (package version: v8.15.2, last github version: v8.15.3)
> Auto-update libvips to v8.15.3

- packages/f/freeimage/patches/3.18.0/pluginbmp.patch
- packages/f/freeimage/xmake.lua
This is done by adding config option `rgb` to `FreeImage` for configuring between rgb and grb color formats
> Add support for rgb/grb config for FreeImage

- packages/t/toml11/xmake.lua
New version of toml11 detected (package version: v4.1.0, last github version: v4.2.0)
> Auto-update toml11 to v4.2.0

- packages/i/ittapi/xmake.lua
New version of ittapi detected (package version: v3.25.1, last github version: v3.25.2)
> Auto-update ittapi to v3.25.2

- packages/a/aws-crt-cpp/xmake.lua
New version of aws-crt-cpp detected (package version: v0.27.4, last github version: v0.27.5)
> Auto-update aws-crt-cpp to v0.27.5

- packages/p/polyscope/xmake.lua
New version of polyscope detected (package version: v2.2.1, last github version: v2.3)
> Auto-update polyscope to v2.3

- packages/f/flecs/xmake.lua
New version of flecs detected (package version: v4.0.0, last github version: v4.0.1)
> Auto-update flecs to v4.0.1

- packages/a/aws-c-event-stream/xmake.lua
New version of aws-c-event-stream detected (package version: v0.4.2, last github version: v0.4.3)
> Auto-update aws-c-event-stream to v0.4.3

- packages/c/cmake/xmake.lua
> cmake: update version to 3.30.2

- packages/j/json-glib/xmake.lua
json-glib 中在另一个环境中测试时有可能因为没有手动加addsyslinks("pthread") 而失败，所以此处加上
> json-glib: fix pthread link

- packages/s/sqlitecpp/xmake.lua
New version of sqlitecpp detected (package version: 3.3.1, last github version: 3.3.2)
> Auto-update sqlitecpp to 3.3.2

- packages/w/wfrest/xmake.lua
New version of wfrest detected (package version: v0.9.6, last github version: v0.9.7)
> Auto-update wfrest to v0.9.7

- packages/r/rocksdb/xmake.lua
New version of rocksdb detected (package version: v9.4.0, last github version: v9.5.2)
> Auto-update rocksdb to v9.5.2

- packages/s/suitesparse/xmake.lua
New version of suitesparse detected (package version: v7.7.0, last github version: v7.8.1)
> Auto-update suitesparse to v7.8.1

- packages/c/cpptrace/xmake.lua
New version of cpptrace detected (package version: v0.6.3, last github version: v0.7.0)
> Auto-update cpptrace to v0.7.0

- packages/b/benchmark/xmake.lua
New version of benchmark detected (package version: 1.8.5, last github version: 1.9.0)
> Auto-update benchmark to 1.9.0

- packages/l/libsvm/xmake.lua
New version of libsvm detected (package version: v333, last github version: v334)
> Auto-update libsvm to v334

- packages/a/aws-lc/xmake.lua
New version of aws-lc detected (package version: v1.32.0, last github version: v1.34.2)
> Auto-update aws-lc to v1.34.2

- packages/c/c-ares/xmake.lua
New version of c-ares detected (package version: 1.33.0, last github version: 1.33.1)
> Auto-update c-ares to 1.33.1

- packages/l/luau/xmake.lua
> Update luau to 0.638

- packages/c/cpp-semver/xmake.lua
New version of cpp-semver detected (package version: v0.3.3, last github version: v0.4.0)
> Auto-update cpp-semver to v0.4.0

- packages/p/pybind11/xmake.lua
New version of pybind11 detected (package version: v2.13.1, last github version: v2.13.5)
> Auto-update pybind11 to v2.13.5

- packages/l/libmaxminddb/xmake.lua
New version of libmaxminddb detected (package version: 1.10.0, last github version: 1.11.0)
> Auto-update libmaxminddb to 1.11.0

- packages/n/ngtcp2/xmake.lua
New version of ngtcp2 detected (package version: 1.6.0, last github version: 1.7.0)
> Auto-update ngtcp2 to 1.7.0

- packages/b/bitsery/xmake.lua
New version of bitsery detected (package version: v5.2.3, last github version: v5.2.4)
> Auto-update bitsery to v5.2.4

- packages/d/drogon/xmake.lua
Fix `config = { shared = true }` producing static lib.
In drogon 1.8.0 the CMake config `BUILD_DROGON_SHARED` was changed to `BUILD_SHARED_LIBS`
> drogon: fix shared build for version >=1.8.0

- packages/n/nghttp3/xmake.lua
New version of nghttp3 detected (package version: v1.4.0, last github version: v1.5.0)
> Auto-update nghttp3 to v1.5.0

- packages/c/cpp-httplib/xmake.lua
New version of cpp-httplib detected (package version: v0.16.2, last github version: v0.16.3)
> Auto-update cpp-httplib to v0.16.3

- packages/l/libdatrie/xmake.lua
pango在本地环境中测试时，发现需要依赖libthai，libthai依赖libdatrie，故先支持libdatrie
> add libdatrie repo

- packages/t/tree-sitter/port/xmake.lua
- packages/t/tree-sitter/xmake.lua
New version of tree-sitter detected (package version: 0.22.6, last github version: 0.23.0)
> Auto-update tree-sitter to 0.23.0

- packages/l/libthai/xmake.lua
pango中需要依赖libthai库，所以添加libthai的支持
> add repo libthai

- packages/e/etl/xmake.lua
New version of etl detected (package version: 20.39.2, last github version: 20.39.3)
> Auto-update etl to 20.39.3

- packages/c/cppfront/xmake.lua
New version of cppfront detected (package version: v0.7.2, last github version: v0.7.4)
> Auto-update cppfront to v0.7.4

- packages/g/gdal/xmake.lua
New version of gdal detected (package version: 3.9.1, last github version: 3.9.2)
> Auto-update gdal to 3.9.2

- packages/d/daw_json_link/xmake.lua
New version of daw_json_link detected (package version: v3.26.0, last github version: v3.28.3)
> Auto-update daw_json_link to v3.28.3

- packages/f/faker-cxx/xmake.lua
New version of faker-cxx detected (package version: v2.0.0, last github version: v3.0.0)
> Auto-update faker-cxx to v3.0.0

- packages/s/sentry-native/xmake.lua
New version of sentry-native detected (package version: 0.7.6, last github version: 0.7.9)
- close: #4915
- close: #4899 
- close: #4757
> Auto-update sentry-native to 0.7.9

- packages/k/kokkos-kernels/xmake.lua
- packages/k/kokkos/xmake.lua
New version of kokkos-kernels detected (package version: 4.3.01, last github version: 4.4.00)
> Auto-update kokkos-kernels to 4.4.00

- packages/t/tracy/xmake.lua
New version of tracy detected (package version: v0.11.0, last github version: v0.11.1)
> Auto-update tracy to v0.11.1

- packages/p/pdfhummus/xmake.lua
New version of pdfhummus detected (package version: v4.6.6, last github version: v4.6.7)
> Auto-update pdfhummus to v4.6.7

- packages/p/protobuf-cpp/xmake.lua
New version of protobuf-cpp detected (package version: 27.3, last github version: 28.0)
> Auto-update protobuf-cpp to 28.0

- packages/e/expat/xmake.lua
- packages/p/poco/xmake.lua
* Fix Poco libraries cannot compile with shared build on Windows
* Fix: Compiling Poco's xml module has some problems due to missing macros with the expat static library. Appending macros directly will cause to fail to compile Poco with a dynamic expat library. Change some previous code to be executed only when expat is a static library.
* Fix: Compiling Poco's foundation module has some problems due to missing macros with the pcre2 static library. Appending macros directly will cause to fail to compile Poco with a dynamic pcre2 library. Change some previous code to be executed only when pcre2 is a static library.
* Refine the Poco library modules so that you don't need to install the entire Poco library if you only need a small part of it.
* Provide the option of mariadb when using the …
> fix_poco_shared_build

- packages/j/json-glib/xmake.lua
New version of json-glib detected (package version: 1.9.2, last github version: 1.10.0)
> Auto-update json-glib to 1.10.0

- packages/d/dbus/xmake.lua
The dbus package is licensed under GPL-2.0-or-later and not MIT.
> Fix license for dbus

- packages/v/vulkansdk/xmake.lua
[#5531](https://github.com/xmake-io/xmake/issues/5531)
Fix vulkan-1.lib searching when platform is mingw.
> Fix vulkansdk searching for mingw platform

- packages/d/dlib/xmake.lua
New version of dlib detected (package version: v19.24.5, last github version: v19.24.6)
> Auto-update dlib to v19.24.6

- packages/s/soci/patches/v4.0.3/cmake_policy_fix.patch
- packages/s/soci/xmake.lua
> soci: fix deps

- packages/n/nghttp2/xmake.lua
New version of nghttp2 detected (package version: 1.62.1, last github version: 1.63.0)
> Auto-update nghttp2 to 1.63.0

- packages/l/libsvm/xmake.lua
New version of libsvm detected (package version: v334, last github version: v335)
> Auto-update libsvm to v335

- packages/f/frozen/xmake.lua
New version of frozen detected (package version: 1.1.1, last github version: 1.2.0)
> Auto-update frozen to 1.2.0

- packages/b/blake3/xmake.lua
New version of blake3 detected (package version: 1.5.3, last github version: 1.5.4)
> Auto-update blake3 to 1.5.4

- packages/a/at-spi2-core/xmake.lua
- packages/p/pango/xmake.lua
gtk3中需要依赖libatk-adapter。但目前只有atk的包，故添加at-spi2-core的包，包括atk，atspi, atk-bridge(包含atk-adapter)
> add at-spi2-core repo

- packages/a/aws-crt-cpp/xmake.lua
New version of aws-crt-cpp detected (package version: v0.27.5, last github version: v0.28.2)
> Auto-update aws-crt-cpp to v0.28.2

- packages/n/nanoflann/xmake.lua
New version of nanoflann detected (package version: v1.6.0, last github version: v1.6.1)
> Auto-update nanoflann to v1.6.1

- packages/a/aws-c-cal/xmake.lua
New version of aws-c-cal detected (package version: v0.7.2, last github version: v0.7.4)
> Auto-update aws-c-cal to v0.7.4

- packages/c/cpp-httplib/xmake.lua
New version of cpp-httplib detected (package version: v0.16.3, last github version: v0.17.0)
> Auto-update cpp-httplib to v0.17.0

- packages/p/pyincpp/xmake.lua
New version of pyincpp detected (package version: v2.4.1, last github version: v2.5.1)
> Auto-update pyincpp to v2.5.1

- packages/a/aws-c-compression/xmake.lua
New version of aws-c-compression detected (package version: v0.2.18, last github version: v0.2.19)
> Auto-update aws-c-compression to v0.2.19

- packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.5.0, last github version: v1.5.1)
> Auto-update s2n-tls to v1.5.1

- packages/g/go/xmake.lua
Add v1.22.7 and v1.23.1, which fixes CVE-2024-34155, CVE-2024-34156 and CVE-2024-34158.
> go: add new versions

- packages/d/daw_header_libraries/xmake.lua
New version of daw_header_libraries detected (package version: v2.106.1, last github version: v2.110.0)
> Auto-update daw_header_libraries to v2.110.0

- packages/b/bgfx/rules/shaders.lua
- packages/b/bgfx/xmake.lua
Fixes #5105
* Adds ".sc" as a supported extension for bgfx shaders;
* Adds support for vs_, fs, and cs_ prefixes for vertex, fragment, and compute shaders;
* Adds support for bin2c confguration (header generation)
> bgfx: fix shader compilation

- packages/b/bgfx/rules/shaders.lua
https://github.com/xmake-io/xmake-repo/pull/5106
> bgfx: rename header to array_name

- packages/k/kiwisolver/xmake.lua
New version of kiwisolver detected (package version: 1.4.5, last github version: 1.4.6)
> Auto-update kiwisolver to 1.4.6

- packages/f/fast_float/xmake.lua
New version of fast_float detected (package version: v6.1.4, last github version: v6.1.5)
> Auto-update fast_float to v6.1.5

- packages/a/assimp/xmake.lua
New version of assimp detected (package version: v5.4.2, last github version: v5.4.3)
> Auto-update assimp to v5.4.3

- packages/c/cpp-httplib/xmake.lua
New version of cpp-httplib detected (package version: v0.17.0, last github version: v0.17.3)
> Auto-update cpp-httplib to v0.17.3

- packages/q/quill/xmake.lua
New version of quill detected (package version: v6.1.2, last github version: v7.0.0)
> Auto-update quill to v7.0.0

- packages/c/cpp-peglib/xmake.lua
New version of cpp-peglib detected (package version: 1.8.8, last github version: 1.9.0)
> Auto-update cpp-peglib to 1.9.0

- packages/h/hlslpp/xmake.lua
New version of hlslpp detected (package version: 3.5, last github version: 3.5.1)
> Auto-update hlslpp to 3.5.1

- packages/c/cpp-dump/xmake.lua
New version of cpp-dump detected (package version: v0.6.0, last github version: v0.7.0)
> Auto-update cpp-dump to v0.7.0

- packages/a/aws-c-s3/xmake.lua
New version of aws-c-s3 detected (package version: v0.6.0, last github version: v0.6.5)
> Auto-update aws-c-s3 to v0.6.5

- packages/e/expat/xmake.lua
New version of expat detected (package version: 2.6.2, last github version: 2.6.3)
> Auto-update expat to 2.6.3

- packages/b/boost_reflect/xmake.lua
New version of boost_reflect detected (package version: v1.1.1, last github version: v1.2.3)
> Auto-update boost_reflect to v1.2.3

- packages/l/luau/xmake.lua
New version of luau detected (package version: 0.640, last github version: 0.642)
> Auto-update luau to 0.642

- packages/v/vk-bootstrap/xmake.lua
New version of vk-bootstrap detected (package version: v1.3.292, last github version: v1.3.295)
> Auto-update vk-bootstrap to v1.3.295

- packages/a/aws-c-auth/xmake.lua
New version of aws-c-auth detected (package version: v0.7.25, last github version: v0.7.29)
> Auto-update aws-c-auth to v0.7.29

- packages/m/mongoose/xmake.lua
New version of mongoose detected (package version: 7.14, last github version: 7.15)
> Auto-update mongoose to 7.15

- packages/d/directx-headers/xmake.lua
New version of directx-headers detected (package version: v1.614.0, last github version: v1.614.1)
> Auto-update directx-headers to v1.614.1

- packages/p/pulsar/xmake.lua
New version of pulsar detected (package version: 3.5.1, last github version: 3.6.0)
> Auto-update pulsar to 3.6.0

- packages/i/intx/xmake.lua
New version of intx detected (package version: v0.11.0, last github version: v0.12.0)
> Auto-update intx to v0.12.0

- packages/s/simdutf/xmake.lua
New version of simdutf detected (package version: v5.4.15, last github version: v5.5.0)
> Auto-update simdutf to v5.5.0

- packages/q/quill/xmake.lua
New version of quill detected (package version: v7.0.0, last github version: v7.1.0)
> Auto-update quill to v7.1.0

- packages/p/protobuf-cpp/xmake.lua
New version of protobuf-cpp detected (package version: 28.0, last github version: 28.1)
> Auto-update protobuf-cpp to 28.1

- packages/d/dlpack/xmake.lua
New version of dlpack detected (package version: v0.8, last github version: v1.0)
> Auto-update dlpack to v1.0

- packages/a/aws-checksums/xmake.lua
New version of aws-checksums detected (package version: v0.1.18, last github version: v0.1.19)
> Auto-update aws-checksums to v0.1.19

- packages/l/ls-hpack/xmake.lua
New version of ls-hpack detected (package version: v2.3.3, last github version: v2.3.4)
> Auto-update ls-hpack to v2.3.4

- packages/f/fast_float/xmake.lua
New version of fast_float detected (package version: v6.1.5, last github version: v6.1.6)
> Auto-update fast_float to v6.1.6

- packages/c/cmake/xmake.lua
> add ninja dep to cmake

- packages/s/sqlite_orm/xmake.lua
> add sqlite_orm version 1.9

- packages/u/uwebsockets/xmake.lua
New version of uwebsockets detected (package version: v20.65.0, last github version: v20.66.0)
> Auto-update uwebsockets to v20.66.0

- packages/s/stringzilla/xmake.lua
New version of stringzilla detected (package version: v3.9.5, last github version: v3.9.6)
> Auto-update stringzilla to v3.9.6

- packages/f/functionalplus/xmake.lua
New version of functionalplus detected (package version: v0.2.24, last github version: v0.2.25)
> Auto-update functionalplus to v0.2.25

- packages/j/jrtplib/xmake.lua
> add Jrtplib repo

- packages/f/fast-cdr/xmake.lua
New version of fast-cdr detected (package version: v2.2.3, last github version: v2.2.4)
> Auto-update fast-cdr to v2.2.4

- packages/u/urdfdom-headers/xmake.lua
New version of urdfdom-headers detected (package version: 1.1.1, last github version: 1.1.2)
> Auto-update urdfdom-headers to 1.1.2

- packages/p/pybind11/xmake.lua
New version of pybind11 detected (package version: v2.13.5, last github version: v2.13.6)
> Auto-update pybind11 to v2.13.6

- packages/n/node-api-headers/xmake.lua
New version of node-api-headers detected (package version: v1.2.0, last github version: v1.3.0)
> Auto-update node-api-headers to v1.3.0

- packages/c/cutlass/xmake.lua
New version of cutlass detected (package version: v3.5.0, last github version: v3.5.1)
> Auto-update cutlass to v3.5.1

- packages/u/urdfdom/xmake.lua
New version of urdfdom detected (package version: 4.0.0, last github version: 4.0.1)
> Auto-update urdfdom to 4.0.1

- packages/c/catch2/xmake.lua
New version of catch2 detected (package version: v3.7.0, last github version: v3.7.1)
> Auto-update catch2 to v3.7.1

- packages/l/lsquic/xmake.lua
New version of lsquic detected (package version: v4.0.9, last github version: v4.0.11)
> Auto-update lsquic to v4.0.11

- packages/l/libenvpp/xmake.lua
New version of libenvpp detected (package version: v1.4.1, last github version: v1.4.2)
> Auto-update libenvpp to v1.4.2

- packages/y/yalantinglibs/xmake.lua
New version of yalantinglibs detected (package version: 0.3.7, last github version: 0.3.8)
> Auto-update yalantinglibs to 0.3.8

- packages/f/flux/xmake.lua
> flux: add v0.4.0 version

- packages/t/trantor/xmake.lua
New version of trantor detected (package version: v1.5.20, last github version: v1.5.21)
> Auto-update trantor to v1.5.21

- packages/c/croaring/xmake.lua
New version of croaring detected (package version: v4.1.1, last github version: v4.1.5)
> Auto-update croaring to v4.1.5

- packages/a/arduinojson/xmake.lua
New version of arduinojson detected (package version: v7.1.0, last github version: v7.2.0)
> Auto-update arduinojson to v7.2.0

- packages/a/aws-c-common/xmake.lua
New version of aws-c-common detected (package version: v0.9.27, last github version: v0.9.28)
> Auto-update aws-c-common to v0.9.28

- packages/a/aws-c-common/xmake.lua
- packages/a/aws-checksums/xmake.lua
New version of aws-checksums detected (package version: v0.1.19, last github version: v0.1.20)
> Auto-update aws-checksums to v0.1.20

- packages/l/limonp/xmake.lua
New version of limonp detected (package version: v0.9.0, last github version: v1.0.0)
> Auto-update limonp to v1.0.0

- packages/m/md4qt/xmake.lua
New version of md4qt detected (package version: 2.8.1, last github version: 3.0.0)
> Auto-update md4qt to 3.0.0

- packages/l/libxmake/xmake.lua
New version of libxmake detected (package version: v2.9.4, last github version: v2.9.5)
> Auto-update libxmake to v2.9.5

- packages/e/elfutils/xmake.lua
> improve elfutils

- packages/i/imath/xmake.lua
New version of imath detected (package version: v3.1.11, last github version: v3.1.12)
> Auto-update imath to v3.1.12

- packages/w/winreg/xmake.lua
New version of winreg detected (package version: v6.2.0, last github version: v6.3.0)
> Auto-update winreg to v6.3.0

- packages/l/libassert/xmake.lua
New version of libassert detected (package version: v2.1.0, last github version: v2.1.1)
> Auto-update libassert to v2.1.1

- packages/g/geos/xmake.lua
New version of geos detected (package version: 3.12.1, last github version: 3.13.0)
> Auto-update geos to 3.13.0

- packages/a/apr/xmake.lua
New version of apr detected (package version: 1.7.4, last github version: 1.7.5)
> Auto-update apr to 1.7.5

- packages/a/aws-crt-cpp/xmake.lua
New version of aws-crt-cpp detected (package version: v0.28.2, last github version: v0.28.3)
> Auto-update aws-crt-cpp to v0.28.3

- packages/d/duckdb/xmake.lua
New version of duckdb detected (package version: v1.0.0, last github version: v1.1.1)
> Auto-update duckdb to v1.1.1

- packages/q/quickjs-ng/xmake.lua
New version of quickjs-ng detected (package version: v0.5.0, last github version: v0.6.1)
> Auto-update quickjs-ng to v0.6.1

- packages/c/coin-or-ipopt/xmake.lua
- packages/l/lapack/xmake.lua
- packages/m/mumps/xmake.lua
经过修改后重新提交coin-or-ipopt包
https://github.com/xmake-io/xmake-repo/pull/5326#issue-2544045052
关联此pr
> add coin-or-ipopt repo

- packages/c/cppjieba/xmake.lua
New version of cppjieba detected (package version: v5.2.0, last github version: v5.4.0)
> Auto-update cppjieba to v5.4.0

- packages/p/plutovg/xmake.lua
New version of plutovg detected (package version: v0.0.1, last github version: v0.0.6)
> Auto-update plutovg to v0.0.6

- packages/m/msgpack-c/xmake.lua
New version of msgpack-c detected (package version: 6.0.2, last github version: 6.1.0)
> Auto-update msgpack-c to 6.1.0

- packages/c/cppcheck/xmake.lua
New version of cppcheck detected (package version: 2.14.2, last github version: 2.15.0)
> Auto-update cppcheck to 2.15.0

- packages/v/vcpkg/xmake.lua
New version of vcpkg detected (package version: 2024.07.12, last github version: 2024.08.23)
> Auto-update vcpkg to 2024.08.23

- packages/q/quill/xmake.lua
New version of quill detected (package version: v7.1.0, last github version: v7.2.2)
> Auto-update quill to v7.2.2

- packages/a/aws-c-auth/xmake.lua
New version of aws-c-auth detected (package version: v0.7.29, last github version: v0.7.31)
> Auto-update aws-c-auth to v0.7.31

- packages/u/uwebsockets/xmake.lua
New version of uwebsockets detected (package version: v20.66.0, last github version: v20.67.0)
> Auto-update uwebsockets to v20.67.0

- packages/a/aws-c-mqtt/xmake.lua
New version of aws-c-mqtt detected (package version: v0.10.4, last github version: v0.10.6)
> Auto-update aws-c-mqtt to v0.10.6

- packages/j/jwt-cpp/xmake.lua
check package:config("picojson") before on_test
> fix jwt-cpp on_test

- packages/s/sentry-native/xmake.lua
New version of sentry-native detected (package version: 0.7.9, last github version: 0.7.10)
> Auto-update sentry-native to 0.7.10

- packages/g/gyp-next/xmake.lua
New version of gyp-next detected (package version: v0.18.1, last github version: v0.18.2)
> Auto-update gyp-next to v0.18.2

- packages/k/kiwisolver/xmake.lua
New version of kiwisolver detected (package version: 1.4.6, last github version: 1.4.7)
> Auto-update kiwisolver to 1.4.7

- packages/s/simdjson/xmake.lua
New version of simdjson detected (package version: v3.10.0, last github version: v3.10.1)
> Auto-update simdjson to v3.10.1

- packages/k/kdbindings/xmake.lua
New version of kdbindings detected (package version: v1.0.5, last github version: v1.1.0)
> Auto-update kdbindings to v1.1.0

- packages/f/fribidi/xmake.lua
New version of fribidi detected (package version: 1.0.15, last github version: 1.0.16)
> Auto-update fribidi to 1.0.16

- packages/l/libraqm/xmake.lua
New version of libraqm detected (package version: v0.10.1, last github version: v0.10.2)
> Auto-update libraqm to v0.10.2

- packages/m/meson/xmake.lua
New version of meson detected (package version: 1.5.1, last github version: 1.5.2)
> Auto-update meson to 1.5.2

- packages/f/flecs/xmake.lua
New version of flecs detected (package version: v4.0.1, last github version: v4.0.2)
> Auto-update flecs to v4.0.2

- packages/o/openexr/xmake.lua
New version of openexr detected (package version: v3.2.4, last github version: v3.3.0)
> Auto-update openexr to v3.3.0

- packages/c/cgraph/xmake.lua
New version of cgraph detected (package version: v2.6.0, last github version: v2.6.1)
> Auto-update cgraph to v2.6.1

- packages/s/stringzilla/xmake.lua
New version of stringzilla detected (package version: v3.9.6, last github version: v3.9.8)
> Auto-update stringzilla to v3.9.8

- packages/h/harfbuzz/xmake.lua
New version of harfbuzz detected (package version: 9.0.0, last github version: 10.0.1)
> Auto-update harfbuzz to 10.0.1

- packages/b/bison/xmake.lua
- **Windows**: Applied fix adapted from the flex package.
- **BSD**: Added m4 as a dependency.
> bison: fix Windows and BSD

- packages/q/quill/xmake.lua
New version of quill detected (package version: v7.2.2, last github version: v7.3.0)
> Auto-update quill to v7.3.0

- packages/v/vcpkg/xmake.lua
New version of vcpkg detected (package version: 2024.08.23, last github version: 2024.09.30)
> Auto-update vcpkg to 2024.09.30

- packages/o/openpgl/xmake.lua
New version of openpgl detected (package version: 0.6.0, last github version: 0.7.0)
> Auto-update openpgl to 0.7.0

- packages/h/hlslpp/xmake.lua
New version of hlslpp detected (package version: 3.5.1, last github version: 3.5.3)
> Auto-update hlslpp to 3.5.3

- packages/m/mini/xmake.lua
New version of mini detected (package version: 0.9.16, last github version: 0.9.17)
> Auto-update mini to 0.9.17

- packages/i/ittapi/xmake.lua
New version of ittapi detected (package version: v3.25.2, last github version: v3.25.3)
> Auto-update ittapi to v3.25.3

- packages/t/thrift/patches/0.21.0/cmake.patch
- packages/t/thrift/xmake.lua
New version of thrift detected (package version: v0.20.0, last github version: v0.21.0)
> Auto-update thrift to v0.21.0

- packages/l/libvips/xmake.lua
New version of libvips detected (package version: v8.15.3, last github version: v8.15.4)
> Auto-update libvips to v8.15.4

- packages/n/nghttp3/xmake.lua
New version of nghttp3 detected (package version: v1.5.0, last github version: v1.6.0)
> Auto-update nghttp3 to v1.6.0

- packages/s/symengine/xmake.lua
New version of symengine detected (package version: v0.12.0, last github version: v0.13.0)
> Auto-update symengine to v0.13.0

- .github/workflows/android_windows.yml
- .github/workflows/windows.yml
- .github/workflows/windows_v3.yml
> ci: upgrade al-cheb/configure-pagefile-action to fix warnings

- packages/a/atomic_queue/xmake.lua
New version of atomic_queue detected (package version: v1.6.4, last github version: v1.6.5)
> Auto-update atomic_queue to v1.6.5

- packages/t/trompeloeil/xmake.lua
New version of trompeloeil detected (package version: v48, last github version: v49)
> Auto-update trompeloeil to v49

- packages/s/simsimd/xmake.lua
New version of simsimd detected (package version: v5.4.4, last github version: v5.6.0)
> Auto-update simsimd to v5.6.0

- packages/t/tree-sitter/xmake.lua
New version of tree-sitter detected (package version: v0.23.0, last github version: v0.24.2)
> Auto-update tree-sitter to v0.24.2

- packages/l/libde265/xmake.lua
- Add git url
- Add `tools` config to build encoder/decoder.
- Fix ninja debug build on Windows.
> libde265: support some platform

- packages/x/x265/xmake.lua
- Add bitbucket tarball.
- Add configs
- tools: build x265 binary.
- high_bit_depth
- main12
- Fix ninja debug build on Windows.
- Fix Windows .pc file.
- Try to support other platform.
> x265: add 4.0 version

- packages/l/libuv/xmake.lua
New version of libuv detected (package version: v1.48.0, last github version: v1.49.0)
> Auto-update libuv to v1.49.0

- packages/k/keystone/xmake.lua
> add keystone

- packages/h/haclog/xmake.lua
New version of haclog detected (package version: v0.2.0, last github version: v0.4.0)
> Auto-update haclog to v0.4.0

- packages/l/lsquic/xmake.lua
New version of lsquic detected (package version: v4.0.11, last github version: v4.0.12)
> Auto-update lsquic to v4.0.12

- packages/s/simsimd/xmake.lua
New version of simsimd detected (package version: v5.6.0, last github version: v5.6.4)
> Auto-update simsimd to v5.6.4

- packages/k/keystone/xmake.lua
- Fix ninja debug build on Windows.
- Fix dll install.
- Android see https://github.com/xmake-io/xmake-repo/issues/5142
> keystone: fix windows dll install

- packages/p/pyincpp/xmake.lua
New version of pyincpp detected (package version: v2.5.1, last github version: v2.5.2)
> Auto-update pyincpp to v2.5.2

- packages/a/aws-c-mqtt/xmake.lua
New version of aws-c-mqtt detected (package version: v0.10.6, last github version: v0.10.7)
> Auto-update aws-c-mqtt to v0.10.7

- packages/h/hypre/xmake.lua
New version of hypre detected (package version: v2.31.0, last github version: v2.32.0)
> Auto-update hypre to v2.32.0

- packages/r/rapidcsv/xmake.lua
New version of rapidcsv detected (package version: 8.83, last github version: 8.84)
> Auto-update rapidcsv to 8.84

- packages/p/pegtl/xmake.lua
New version of pegtl detected (package version: 3.2.7, last github version: 3.2.8)
> Auto-update pegtl to 3.2.8

- packages/p/plutovg/xmake.lua
New version of plutovg detected (package version: v0.0.6, last github version: v0.0.7)
> Auto-update plutovg to v0.0.7

- packages/r/rocksdb/xmake.lua
New version of rocksdb detected (package version: v9.5.2, last github version: v9.6.1)
> Auto-update rocksdb to v9.6.1

- packages/e/enet6/xmake.lua
New version of enet6 detected (package version: v6.1.0, last github version: v6.1.2)
> Auto-update enet6 to v6.1.2

- packages/c/c-ares/xmake.lua
New version of c-ares detected (package version: 1.33.1, last github version: 1.34.1)
> Auto-update c-ares to 1.34.1

- packages/n/ngtcp2/xmake.lua
New version of ngtcp2 detected (package version: 1.7.0, last github version: 1.8.0)
> Auto-update ngtcp2 to 1.8.0

- packages/c/commata/xmake.lua
New version of commata detected (package version: v1.0.0, last github version: v1.0.1)
> Auto-update commata to v1.0.1

- packages/d/duckdb/xmake.lua
New version of duckdb detected (package version: v1.1.1, last github version: v1.1.2)
> Auto-update duckdb to v1.1.2

- packages/a/aws-c-http/xmake.lua
New version of aws-c-http detected (package version: v0.8.7, last github version: v0.8.10)
> Auto-update aws-c-http to v0.8.10

- packages/i/ipaddress/xmake.lua
- packages/v/vladimirshaleev-ipaddress/xmake.lua
https://github.com/VladimirShaleev/ipaddress/tree/main
A library for working and manipulating IPv4/IPv6 addresses and networks in modern C++.
This cross-platfrom header-only library (for C++11 and newer) is inspired by the [ipaddress API in Python](https://docs.python.org/3.12/library/ipaddress.html), from which it derives its name. It aims to be simpler to use due to its familiar interface. However, the C++ implementation takes a different approach: it uses static polymorphism through the strategy pattern instead of dynamic polymorphism to handle differences between IP versions (IPv4 and IPv6). This design choice eliminates the overhead of dynamic calls and virtual tables. For instance, an instance of the ipv4_address class will be represented by 4 bytes.
The library leverages modern C++ …
> add package ipaddress

- packages/o/onednn/xmake.lua
New version of onednn detected (package version: v3.5.3, last github version: v3.6)
> Auto-update onednn to v3.6

- packages/r/rocksdb/xmake.lua
New version of rocksdb detected (package version: v9.6.1, last github version: v9.7.2)
> Auto-update rocksdb to v9.7.2

- packages/f/fast-cdr/xmake.lua
New version of fast-cdr detected (package version: v2.2.4, last github version: v2.2.5)
> Auto-update fast-cdr to v2.2.5

- packages/a/alembic/xmake.lua
New version of alembic detected (package version: 1.8.6, last github version: 1.8.7)
> Auto-update alembic to 1.8.7

- packages/z/zlib-ng/xmake.lua
New version of zlib-ng detected (package version: 2.2.1, last github version: 2.2.2)
> Auto-update zlib-ng to 2.2.2

- packages/v/vladimirshaleev-ipaddress/xmake.lua
vladimirshaleev-ipaddress is a headeronly library.
The PR #5506 mistakenly forgot to export defines in xmake.
This PR fix the mistake.
> fix vladimirshaleev-ipaddress configs

- packages/w/watcher/xmake.lua
New version of watcher detected (package version: 0.11.0, last github version: 0.12.2)
> Auto-update watcher to 0.12.2

- packages/l/libenvpp/xmake.lua
New version of libenvpp detected (package version: v1.4.3, last github version: v1.4.4)
> Auto-update libenvpp to v1.4.4

- packages/h/highs/xmake.lua
New version of highs detected (package version: v1.7.2, last github version: v1.8.0)
> Auto-update highs to v1.8.0

- packages/f/fakeit/xmake.lua
New version of fakeit detected (package version: 2.4.0, last github version: 2.4.1)
> Auto-update fakeit to 2.4.1

- packages/e/etl/xmake.lua
New version of etl detected (package version: 20.39.3, last github version: 20.39.4)
> Auto-update etl to 20.39.4

- packages/c/cpp-rotor/xmake.lua
New version of cpp-rotor detected (package version: v0.30, last github version: v0.31)
> Auto-update cpp-rotor to v0.31

- packages/t/thorvg/xmake.lua
New version of thorvg detected (package version: v0.14.10, last github version: v0.15.1)
> Auto-update thorvg to v0.15.1

- packages/m/moltenvk/xmake.lua
New version of moltenvk detected (package version: v1.2.10, last github version: v1.2.11)
> Auto-update moltenvk to v1.2.11

- packages/n/ngtcp2/xmake.lua
New version of ngtcp2 detected (package version: 1.8.0, last github version: 1.8.1)
> Auto-update ngtcp2 to 1.8.1

- packages/u/ufbx/xmake.lua
New version of ufbx detected (package version: v0.14.3, last github version: v0.15.0)
> Auto-update ufbx to v0.15.0

- packages/l/libgit2/xmake.lua
New version of libgit2 detected (package version: v1.8.1, last github version: v1.8.2)
> Auto-update libgit2 to v1.8.2

- packages/m/meson/xmake.lua
New version of meson detected (package version: 1.5.2, last github version: 1.6.0)
> Auto-update meson to 1.6.0

- packages/l/libuv/xmake.lua
New version of libuv detected (package version: v1.49.1, last github version: v1.49.2)
> Auto-update libuv to v1.49.2

- packages/t/thorvg/xmake.lua
New version of thorvg detected (package version: v0.15.1, last github version: v0.15.2)
> Auto-update thorvg to v0.15.2

- packages/g/gyp-next/xmake.lua
New version of gyp-next detected (package version: v0.18.2, last github version: v0.18.3)
> Auto-update gyp-next to v0.18.3

- packages/u/upa-url/xmake.lua
New version of upa-url detected (package version: v1.0.0, last github version: v1.0.1)
> Auto-update upa-url to v1.0.1

- packages/l/libvips/xmake.lua
New version of libvips detected (package version: v8.15.4, last github version: v8.15.5)
> Auto-update libvips to v8.15.5

- packages/a/aws-c-io/xmake.lua
New version of aws-c-io detected (package version: v0.14.19, last github version: v0.15.0)
> Auto-update aws-c-io to v0.15.0

- packages/t/tree-sitter/xmake.lua
New version of tree-sitter detected (package version: v0.24.2, last github version: v0.24.3)
> Auto-update tree-sitter to v0.24.3

- packages/a/aws-checksums/xmake.lua
New version of aws-checksums detected (package version: v0.1.20, last github version: v0.2.0)
> Auto-update aws-checksums to v0.2.0

- packages/a/aws-c-event-stream/xmake.lua
New version of aws-c-event-stream detected (package version: v0.4.3, last github version: v0.5.0)
> Auto-update aws-c-event-stream to v0.5.0

- packages/c/cpp-httplib/xmake.lua
New version of cpp-httplib detected (package version: v0.17.3, last github version: v0.18.1)
> Auto-update cpp-httplib to v0.18.1

- packages/l/libdeflate/xmake.lua
New version of libdeflate detected (package version: v1.21, last github version: v1.22)
> Auto-update libdeflate to v1.22

- packages/l/lzav/xmake.lua
New version of lzav detected (package version: 4.0, last github version: 4.2)
> Auto-update lzav to 4.2

- packages/l/lzav/xmake.lua
Drop 4.2 version, see https://github.com/avaneev/lzav/issues/8
> lzav: add 4.3 version

- packages/v/vcpkg/xmake.lua
New version of vcpkg detected (package version: 2024.09.30, last github version: 2024.10.21)
> Auto-update vcpkg to 2024.10.21

- packages/a/aws-lc/xmake.lua
New version of aws-lc detected (package version: v1.34.2, last github version: v1.37.0)
> Auto-update aws-lc to v1.37.0

- packages/o/openexr/xmake.lua
New version of openexr detected (package version: v3.3.0, last github version: v3.3.1)
> Auto-update openexr to v3.3.1

- packages/a/aws-c-http/xmake.lua
New version of aws-c-http detected (package version: v0.8.10, last github version: v0.9.0)
> Auto-update aws-c-http to v0.9.0

- packages/p/pdfio/xmake.lua
New version of pdfio detected (package version: v1.3.1, last github version: v1.3.2)
> Auto-update pdfio to v1.3.2

- packages/a/aws-c-cal/xmake.lua
New version of aws-c-cal detected (package version: v0.7.4, last github version: v0.8.0)
> Auto-update aws-c-cal to v0.8.0

- packages/g/gdal/xmake.lua
New version of gdal detected (package version: 3.9.2, last github version: 3.9.3)
> Auto-update gdal to 3.9.3

- packages/a/alsa-lib/xmake.lua
- packages/l/libcanberra/xmake.lua
- packages/l/libtool/xmake.lua
- packages/m/magic_enum/xmake.lua
> add libcanberra repo

- packages/r/rocksdb/xmake.lua
New version of rocksdb detected (package version: v9.7.2, last github version: v9.7.3)
> Auto-update rocksdb to v9.7.3

- packages/a/ada/xmake.lua
New version of ada detected (package version: v2.9.1, last github version: v2.9.2)
> Auto-update ada to v2.9.2

- packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.5.5, last github version: v1.5.6)
> Auto-update s2n-tls to v1.5.6

- packages/y/yalantinglibs/xmake.lua
New version of yalantinglibs detected (package version: 0.3.8, last github version: 0.3.9)
> Auto-update yalantinglibs to 0.3.9

- packages/s/simsimd/xmake.lua
New version of simsimd detected (package version: v5.6.4, last github version: v5.9.6)
> Auto-update simsimd to v5.9.6

- packages/v/vvenc/xmake.lua
New version of vvenc detected (package version: v1.12.0, last github version: v1.12.1)
> Auto-update vvenc to v1.12.1

- packages/r/rapidfuzz/xmake.lua
New version of rapidfuzz detected (package version: v3.0.5, last github version: v3.1.1)
> Auto-update rapidfuzz to v3.1.1

- packages/u/uwebsockets/xmake.lua
New version of uwebsockets detected (package version: v20.67.0, last github version: v20.70.0)
> Auto-update uwebsockets to v20.70.0

- packages/d/daw_header_libraries/xmake.lua
New version of daw_header_libraries detected (package version: v2.110.0, last github version: v2.114.0)
> Auto-update daw_header_libraries to v2.114.0

- packages/a/aws-c-common/xmake.lua
New version of aws-c-common detected (package version: v0.9.28, last github version: v0.10.0)
> Auto-update aws-c-common to v0.10.0

- packages/w/winreg/xmake.lua
New version of winreg detected (package version: v6.3.0, last github version: v6.3.1)
> Auto-update winreg to v6.3.1

- packages/l/libgit2/xmake.lua
New version of libgit2 detected (package version: v1.8.2, last github version: v1.8.4)
> Auto-update libgit2 to v1.8.4

- packages/m/msgpack-cxx/xmake.lua
New version of msgpack-cxx detected (package version: 6.1.1, last github version: 7.0.0)
> Auto-update msgpack-cxx to 7.0.0

- packages/p/plutovg/xmake.lua
New version of plutovg detected (package version: v0.0.7, last github version: v0.0.8)
> Auto-update plutovg to v0.0.8

- packages/d/daw_header_libraries/xmake.lua
New version of daw_header_libraries detected (package version: v2.114.0, last github version: v2.114.1)
> Auto-update daw_header_libraries to v2.114.1

- packages/s/sentry-native/xmake.lua
New version of sentry-native detected (package version: 0.7.10, last github version: 0.7.11)
> Auto-update sentry-native to 0.7.11

- packages/a/aws-c-mqtt/xmake.lua
New version of aws-c-mqtt detected (package version: v0.10.7, last github version: v0.11.0)
> Auto-update aws-c-mqtt to v0.11.0

- packages/l/log4cplus/xmake.lua
New version of log4cplus detected (package version: 2.1.1, last github version: 2.1.2)
> Auto-update log4cplus to 2.1.2

- packages/p/plutovg/xmake.lua
New version of plutovg detected (package version: v0.0.8, last github version: v0.0.9)
> Auto-update plutovg to v0.0.9

- packages/m/matio/xmake.lua
New version of matio detected (package version: v1.5.27, last github version: v1.5.28)
> Auto-update matio to v1.5.28

- packages/u/utfcpp/xmake.lua
New version of utfcpp detected (package version: v4.0.5, last github version: v4.0.6)
> Auto-update utfcpp to v4.0.6

- packages/e/entt/xmake.lua
New version of entt detected (package version: v3.13.2, last github version: v3.14.0)
> Auto-update entt to v3.14.0

- packages/c/cppfront/xmake.lua
The URL for the v0.8.0 release of cppfront was added to the package file - c/cppfront/xmake.lua
> update cppfront package to v0.8.0 

- packages/o/onednn/xmake.lua
New version of onednn detected (package version: v3.6, last github version: v3.6.1)
> Auto-update onednn to v3.6.1

- packages/r/redis-plus-plus/xmake.lua
New version of redis-plus-plus detected (package version: 1.3.12, last github version: 1.3.13)
> Auto-update redis-plus-plus to 1.3.13

- packages/a/aws-c-auth/xmake.lua
New version of aws-c-auth detected (package version: v0.7.31, last github version: v0.8.0)
> Auto-update aws-c-auth to v0.8.0

- packages/m/miniaudio/build_defines.lua
- packages/m/miniaudio/xmake.lua
> miniaudio: Add support for split version and expose extra/nodes

- packages/a/aws-c-sdkutils/xmake.lua
New version of aws-c-sdkutils detected (package version: v0.1.19, last github version: v0.2.0)
> Auto-update aws-c-sdkutils to v0.2.0

- packages/a/aws-c-io/xmake.lua
- packages/s/s2n-tls/xmake.lua
New version of aws-c-io detected (package version: v0.15.0, last github version: v0.15.1)
> Auto-update aws-c-io to v0.15.1

- packages/w/watcher/xmake.lua
New version of watcher detected (package version: 0.12.2, last github version: 0.13.2)
> Auto-update watcher to 0.13.2

- packages/r/rocksdb/xmake.lua
New version of rocksdb detected (package version: v9.7.3, last github version: v9.7.4)
> Auto-update rocksdb to v9.7.4

- packages/a/aws-c-sdkutils/xmake.lua
New version of aws-c-sdkutils detected (package version: v0.2.0, last github version: v0.2.1)
> Auto-update aws-c-sdkutils to v0.2.1

- packages/a/aws-c-s3/xmake.lua
New version of aws-c-s3 detected (package version: v0.6.5, last github version: v0.7.0)
> Auto-update aws-c-s3 to v0.7.0

- packages/r/rhash/xmake.lua
New version of rhash detected (package version: 1.4.4, last github version: 1.4.5)
> Auto-update rhash to 1.4.5

- packages/c/c-ares/xmake.lua
New version of c-ares detected (package version: 1.34.1, last github version: 1.34.3)
> Auto-update c-ares to 1.34.3

- packages/a/asio/xmake.lua
MinGW disregards `#pragma comment(lib, "ws2.lib")`, causing link errors like `undefined symbol: __declspec(dllimport) WSACleanup`
Ref: https://github.com/search?q=repo%3Achriskohlhoff%2Fasio++comment%28lib&type=code
> asio: fix undefined symbol on MinGW

- packages/s/sentry-native/xmake.lua
New version of sentry-native detected (package version: 0.7.11, last github version: 0.7.12)
> Auto-update sentry-native to 0.7.12

- packages/m/meshoptimizer/xmake.lua
New version of meshoptimizer detected (package version: v0.21, last github version: v0.22)
> Auto-update meshoptimizer to v0.22

- packages/l/libssh2/xmake.lua
New version of libssh2 detected (package version: 1.11.0, last github version: 1.11.1)
> Auto-update libssh2 to 1.11.1

- packages/c/cli/xmake.lua
New version of cli detected (package version: v2.1.0, last github version: v2.2.0)
> Auto-update cli to v2.2.0

- packages/l/libvpx/xmake.lua
New version of libvpx detected (package version: v1.14.1, last github version: v1.15.0)
> Auto-update libvpx to v1.15.0

- packages/o/opencv/xmake.lua
Change the GTK package dependency from "gtk+3" to "gtk3" to match the correct package name
------
> Fix GTK package dependency name on Linux

- packages/s/scnlib/xmake.lua
New version of scnlib detected (package version: v3.0.1, last github version: v4.0.1)
> Auto-update scnlib to v4.0.1

- packages/t/tree-sitter/xmake.lua
New version of tree-sitter detected (package version: v0.24.3, last github version: v0.24.4)
> Auto-update tree-sitter to v0.24.4

- packages/g/gsl-lite/xmake.lua
New version of gsl-lite detected (package version: v0.41.0, last github version: v0.42.0)
> Auto-update gsl-lite to v0.42.0

- packages/m/magic_enum/xmake.lua
New version of magic_enum detected (package version: v0.9.6, last github version: v0.9.7)
> Auto-update magic_enum to v0.9.7

- packages/f/flecs/xmake.lua
New version of flecs detected (package version: v4.0.2, last github version: v4.0.3)
> Auto-update flecs to v4.0.3

- packages/h/highs/xmake.lua
New version of highs detected (package version: v1.8.0, last github version: v1.8.1)
> Auto-update highs to v1.8.1

- packages/a/aws-checksums/xmake.lua
New version of aws-checksums detected (package version: v0.2.0, last github version: v0.2.2)
> Auto-update aws-checksums to v0.2.2

- packages/s/soil2/xmake.lua
```lua
add_requires("soil2")
```
```c
#include <SOIL2/SOIL2.h>
```
> soil2: add package

- packages/d/dartsim/xmake.lua
New version of dartsim detected (package version: v6.14.5, last github version: v6.15.0)
> Auto-update dartsim to v6.15.0

- packages/p/pcapplusplus/xmake.lua
Recently added flag `--compile-no-warning-as-error` for cmake requires at least 3.24.0 version:
https://github.com/Kitware/CMake/blob/ddb7167a0c98b7598e6c0c02e36dac3fd6ec12be/Help/prop_tgt/COMPILE_WARNING_AS_ERROR.rst#L8
> Proper cmake version for pcapplusplus

- packages/n/node-addon-api/xmake.lua
New version of node-addon-api detected (package version: v8.0.0, last github version: v8.2.2)
> Auto-update node-addon-api to v8.2.2

- packages/a/aws-c-http/xmake.lua
New version of aws-c-http detected (package version: v0.9.0, last github version: v0.9.2)
> Auto-update aws-c-http to v0.9.2

- packages/o/openssl3/xmake.lua
关联 https://github.com/xmake-io/xmake-repo/issues/5773
为 OpenSSL3 添加一个config：“enable_md2”,默认值是 false，如果用户在引入时设置为 true，会在 ./config 时传递一个“enable-md2”（就是中横线，不是写错了）。
添加这个config的来源见 https://security.stackexchange.com/questions/173425/how-do-i-calculate-md2-hash-with-openssl
> ✨ feat: OpenSSL3 add md2

- packages/s/stringzilla/xmake.lua
New version of stringzilla detected (package version: v3.10.9, last github version: v3.10.10)
> Auto-update stringzilla to v3.10.10

- packages/p/prometheus-cpp/xmake.lua
New version of prometheus-cpp detected (package version: v1.2.4, last github version: v1.3.0)
> Auto-update prometheus-cpp to v1.3.0

- packages/s/simsimd/xmake.lua
New version of simsimd detected (package version: v5.9.6, last github version: v6.0.5)
> Auto-update simsimd to v6.0.5

- packages/q/quickjs-ng/xmake.lua
New version of quickjs-ng detected (package version: v0.6.1, last github version: v0.7.0)
> Auto-update quickjs-ng to v0.7.0

- packages/a/aws-c-cal/xmake.lua
New version of aws-c-cal detected (package version: v0.8.0, last github version: v0.8.1)
> Auto-update aws-c-cal to v0.8.1

- packages/l/lexbor/xmake.lua
New version of lexbor detected (package version: v2.3.0, last github version: v2.4.0)
> Auto-update lexbor to v2.4.0

- packages/d/daw_json_link/xmake.lua
New version of daw_json_link detected (package version: v3.28.3, last github version: v3.29.2)
> Auto-update daw_json_link to v3.29.2

- packages/o/opencl-headers/xmake.lua
New version of opencl-headers detected (package version: v2024.05.08, last github version: v2024.10.24)
> Auto-update opencl-headers to v2024.10.24

- packages/n/nghttp2/xmake.lua
New version of nghttp2 detected (package version: 1.63.0, last github version: 1.64.0)
> Auto-update nghttp2 to 1.64.0

- packages/r/re-flex/xmake.lua
New version of re-flex detected (package version: v4.5.0, last github version: v5.0.1)
> Auto-update re-flex to v5.0.1

- packages/o/openexr/xmake.lua
New version of openexr detected (package version: v3.3.1, last github version: v3.3.2)
> Auto-update openexr to v3.3.2

- packages/a/aws-c-common/xmake.lua
- packages/a/aws-c-io/xmake.lua
New version of aws-c-io detected (package version: v0.15.1, last github version: v0.15.3)
> Auto-update aws-c-io to v0.15.3

- packages/e/efsw/xmake.lua
New version of efsw detected (package version: 1.4.0, last github version: 1.4.1)
> Auto-update efsw to 1.4.1

- packages/s/simsimd/xmake.lua
New version of simsimd detected (package version: v6.0.5, last github version: v6.1.1)
> Auto-update simsimd to v6.1.1

- packages/n/ngtcp2/xmake.lua
New version of ngtcp2 detected (package version: 1.8.1, last github version: 1.9.0)
> Auto-update ngtcp2 to 1.9.0

- packages/a/arduinojson/xmake.lua
New version of arduinojson detected (package version: v7.2.0, last github version: v7.2.1)
> Auto-update arduinojson to v7.2.1

- packages/o/openexr/xmake.lua
- Unbundle dep(libdeflate).
- Add `tools` configs.
- Fix debug lib name (override `CMAKE_DEBUG_POSTFIX`).
- Improve test (will break old version?).
> openexr: support more platform

- packages/g/glaze/xmake.lua
> glaze: update to `v4.0.1`

- packages/o/openh264/xmake.lua
New version of openh264 detected (package version: v2.4.1, last github version: v2.5.0)
> Auto-update openh264 to v2.5.0

- packages/s/sentry-native/xmake.lua
New version of sentry-native detected (package version: 0.7.12, last github version: 0.7.15)
> Auto-update sentry-native to 0.7.15

- packages/c/cpr/xmake.lua
New version of cpr detected (package version: 1.10.5, last github version: 1.11.1)
> Auto-update cpr to 1.11.1

- packages/l/lzav/xmake.lua
New version of lzav detected (package version: 4.4, last github version: 4.5)
> Auto-update lzav to 4.5

- packages/e/expat/xmake.lua
New version of expat detected (package version: 2.6.3, last github version: 2.6.4)
> Auto-update expat to 2.6.4

- packages/z/zeus_expected/xmake.lua
New version of zeus_expected detected (package version: v1.1.1, last github version: v1.2.0)
> Auto-update zeus_expected to v1.2.0

- packages/l/libvips/xmake.lua
New version of libvips detected (package version: v8.15.5, last github version: v8.16.0)
> Auto-update libvips to v8.16.0

- packages/f/fast_float/xmake.lua
New version of fast_float detected (package version: v6.1.6, last github version: v7.0.0)
> Auto-update fast_float to v7.0.0

- packages/a/aws-crt-cpp/xmake.lua
New version of aws-crt-cpp detected (package version: v0.28.3, last github version: v0.29.5)
> Auto-update aws-crt-cpp to v0.29.5

- packages/l/libxmake/xmake.lua
New version of libxmake detected (package version: v2.9.5, last github version: v2.9.6)
> Auto-update libxmake to v2.9.6

- packages/n/nuklear/xmake.lua
New version of nuklear detected (package version: 4.12.0, last github version: 4.12.2)
> Auto-update nuklear to 4.12.2

- packages/a/aws-lc/xmake.lua
New version of aws-lc detected (package version: v1.39.0, last github version: v1.40.0)
> Auto-update aws-lc to v1.40.0

- packages/s/sqlite-vec/xmake.lua
New version of sqlite-vec detected (package version: 0.1.3, last github version: 0.1.6)
> Auto-update sqlite-vec to 0.1.6

- packages/p/plutosvg/xmake.lua
New version of plutosvg detected (package version: v0.0.2, last github version: v0.0.3)
> Auto-update plutosvg to v0.0.3

- packages/i/imguizmo/xmake.lua
When I install imguizmo, I am prompted to define the IMGUI_DEFINE_MATH_OPERATORS macro and include the header file imgui.h, otherwise the compilation will fail.
> define IMGUI_DEFINE_MATH_OPERATORS before include imgui.h

- packages/c/clove-unit/xmake.lua
New version of clove-unit detected (package version: v2.4.5, last github version: v2.4.6)
> Auto-update clove-unit to v2.4.6

- packages/s/simsimd/xmake.lua
New version of simsimd detected (package version: v6.1.1, last github version: v6.2.1)
> Auto-update simsimd to v6.2.1

- packages/c/cpp-peglib/xmake.lua
New version of cpp-peglib detected (package version: 1.9.0, last github version: 1.9.1)
> Auto-update cpp-peglib to 1.9.1

- packages/f/fmi/xmake.lua
New version of fmi detected (package version: v3.0.1, last github version: v3.0.2)
> Auto-update fmi to v3.0.2

- packages/a/antlr4-runtime/xmake.lua
- packages/a/antlr4/rules/lexer.lua
- packages/a/antlr4/rules/parser.lua
- Fix includedirs missing in compile_commadns.json.
- Fix path `xxx/./yyy`.
> antlr4: improve includedirs

- packages/k/kahip/xmake.lua
New version of kahip detected (package version: v3.16, last github version: v3.17)
> Auto-update kahip to v3.17

- packages/s/simdutf/xmake.lua
New version of simdutf detected (package version: v5.5.0, last github version: v5.6.3)
> Auto-update simdutf to v5.6.3

- packages/n/numactl/xmake.lua
New version of numactl detected (package version: 2.0.18, last github version: 2.0.19)
> Auto-update numactl to 2.0.19

- packages/s/samurai/xmake.lua
New version of samurai detected (package version: v0.16.0, last github version: v0.18.0)
> Auto-update samurai to v0.18.0

- packages/u/upa-url/xmake.lua
New version of upa-url detected (package version: v1.0.1, last github version: v1.0.2)
> Auto-update upa-url to v1.0.2

- packages/p/protobuf-cpp/xmake.lua
- Fixed `undefined symbol: __start_pb_defaults` when compiling with Clang (MinGW) on Windows by undefining PROTOBUF_DESCRIPTOR_WEAK_MESSAGES_ALLOWED. [#16844](https://github.com/protocolbuffers/protobuf/issues/16844)
- Fixed `undefined symbol: pthread_setspecific` by adding pthread to system link dependencies.
> protobuf-cpp: fix for MinGW and Clang on Windows

- packages/l/libenvpp/xmake.lua
New version of libenvpp detected (package version: v1.4.4, last github version: v1.5.1)
> Auto-update libenvpp to v1.5.1

- packages/a/amrex/xmake.lua
New version of amrex detected (package version: 24.09, last github version: 24.12)
> Auto-update amrex to 24.12

- packages/p/portable_build_tools/xmake.lua
New version of portable_build_tools detected (package version: v2.8, last github version: v2.8.1)
> Auto-update portable_build_tools to v2.8.1

- packages/g/gdal/xmake.lua
New version of gdal detected (package version: 3.9.3, last github version: 3.10.0)
> Auto-update gdal to 3.10.0

- packages/v/vk-bootstrap/xmake.lua
New version of vk-bootstrap detected (package version: v1.3.295, last github version: v1.3.302)
> Auto-update vk-bootstrap to v1.3.302

- packages/a/aws-c-s3/xmake.lua
New version of aws-c-s3 detected (package version: v0.7.1, last github version: v0.7.4)
> Auto-update aws-c-s3 to v0.7.4

- packages/b/benchmark/xmake.lua
New version of benchmark detected (package version: v1.9.0, last github version: v1.9.1)
> Auto-update benchmark to v1.9.1

- packages/a/alembic/xmake.lua
New version of alembic detected (package version: 1.8.7, last github version: 1.8.8)
> Auto-update alembic to 1.8.8

- packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.5.7, last github version: v1.5.9)
> Auto-update s2n-tls to v1.5.9

- packages/b/blake3/xmake.lua
New version of blake3 detected (package version: 1.5.4, last github version: 1.5.5)
> Auto-update blake3 to 1.5.5

- packages/l/libdwarf/xmake.lua
New version of libdwarf detected (package version: 0.11.0, last github version: 0.11.1)
> Auto-update libdwarf to 0.11.1

- packages/n/nanoflann/xmake.lua
New version of nanoflann detected (package version: v1.6.1, last github version: v1.6.2)
> Auto-update nanoflann to v1.6.2

- packages/l/libmem/xmake.lua
New version of libmem detected (package version: 5.0.2, last github version: 5.0.3)
> Auto-update libmem to 5.0.3

- packages/n/node-addon-api/xmake.lua
Running xrepo info node-addon-api throws
```
error: attempt to concatenate a nil value
```
> node-addon-api: fix xrepo info

- packages/a/aws-c-s3/xmake.lua
New version of aws-c-s3 detected (package version: v0.7.4, last github version: v0.7.5)
> Auto-update aws-c-s3 to v0.7.5

- packages/e/emmylua_debugger/xmake.lua
New version of emmylua_debugger detected (package version: 1.8.2, last github version: 1.8.3)
> Auto-update emmylua_debugger to 1.8.3

- packages/n/node-addon-api/xmake.lua
New version of node-addon-api detected (package version: v8.2.2, last github version: v8.3.0)
> Auto-update node-addon-api to v8.3.0

- packages/n/ngtcp2/xmake.lua
New version of ngtcp2 detected (package version: 1.9.0, last github version: 1.9.1)
> Auto-update ngtcp2 to 1.9.1

- packages/w/winreg/xmake.lua
New version of winreg detected (package version: v6.3.1, last github version: v6.3.2)
> Auto-update winreg to v6.3.2

- packages/y/yoga/xmake.lua
New version of yoga detected (package version: v3.1.0, last github version: v3.2.0)
> Auto-update yoga to v3.2.0

- packages/y/yalantinglibs/xmake.lua
New version of yalantinglibs detected (package version: 0.3.9, last github version: 0.3.11)
> Auto-update yalantinglibs to 0.3.11

- packages/o/onednn/xmake.lua
New version of onednn detected (package version: v3.6.1, last github version: v3.6.2)
> Auto-update onednn to v3.6.2

- packages/u/unordered_dense/xmake.lua
New version of unordered_dense detected (package version: v4.4.0, last github version: v4.5.0)
> Auto-update unordered_dense to v4.5.0

- packages/o/onedpl/xmake.lua
[oneDPL 2022.7.0 release](https://github.com/oneapi-src/oneDPL/releases/tag/oneDPL-2022.7.0-release)
New Features
Improved performance of the adjacent_find, all_of, any_of, copy_if, exclusive_scan, equal,
find, find_if, find_end, find_first_of, find_if_not, inclusive_scan, includes,
is_heap, is_heap_until, is_partitioned, is_sorted, is_sorted_until, lexicographical_compare,
max_element, min_element, minmax_element, mismatch, none_of, partition, partition_copy,
reduce, remove, remove_copy, remove_copy_if, remove_if, search, search_n,
stable_partition, transform_exclusive_scan, transform_inclusive_scan, unique, and unique_copy
algorithms with device policies.
Improved performance of sort, stable_sort and sort_by_key algorithms with device policies when using Merge
sort …
> Update onedpl 2022.7.0 and 2022.7.1 (sequentially)

- packages/s/simdjson/xmake.lua
New version of simdjson detected (package version: v3.10.1, last github version: v3.11.2)
> Auto-update simdjson to v3.11.2

- packages/h/harfbuzz/xmake.lua
New version of harfbuzz detected (package version: 10.0.1, last github version: 10.1.0)
> Auto-update harfbuzz to 10.1.0

- packages/p/portable_build_tools/xmake.lua
New version of portable_build_tools detected (package version: v2.8.1, last github version: v2.9.2)
> Auto-update portable_build_tools to v2.9.2

- packages/d/daw_header_libraries/xmake.lua
New version of daw_header_libraries detected (package version: v2.114.1, last github version: v2.118.0)
> Auto-update daw_header_libraries to v2.118.0

- packages/m/microsoft-proxy/xmake.lua
New version of microsoft-proxy detected (package version: 3.0.0, last github version: 3.1.0)
> Auto-update microsoft-proxy to 3.1.0

- packages/p/protobuf-cpp/xmake.lua
https://github.com/xmake-io/xmake/pull/5959
In windows/mingw plat & shared config, xmake will add `package:installdir("bin")` to PATH.
> protobuf-cpp: remove non-host protoc

- .github/workflows/ubuntu.yml
- packages/b/bison/xmake.lua
- packages/f/flex/xmake.lua
- packages/v/verilator/xmake.lua
A new packaging method: 
We can directly use `pacman::flex/bison` as `xmake::flex/bison` deps on msys2 subhost.
```lua
if is_subhost("msys") and xmake:version():ge("2.9.7") then
package:add("deps", "pacman::bison", {configs = {msystem = "msys"}})
end
```
- flex
- binary kind by default before, now `set_kind("library", {headeronly = true})`
- Copy `pacman::flex` header file `usr/include/FlexLexer.h` to `package:installdir("include")`
- Remove flex links.
- verilator
- Romove autotools build support.
> verilator: switch to cmake

- packages/u/uwebsockets/xmake.lua
New version of uwebsockets detected (package version: v20.70.0, last github version: v20.71.0)
> Auto-update uwebsockets to v20.71.0

- packages/v/vulkan-utility-libraries/xmake.lua
New version of vulkan-utility-libraries detected (package version: v1.3.290, last github version: v1.4.303)
> Auto-update vulkan-utility-libraries to v1.4.303

- packages/p/pocketpy/xmake.lua
New version of pocketpy detected (package version: v1.4.6, last github version: v2.0.3)
> Auto-update pocketpy to v2.0.3

- packages/l/liboqs/xmake.lua
New version of liboqs detected (package version: 0.11.0, last github version: 0.12.0)
> Auto-update liboqs to 0.12.0

- packages/j/json-glib/xmake.lua
New version of json-glib detected (package version: 1.10.0, last github version: 1.10.6)
> Auto-update json-glib to 1.10.6

- packages/l/libcurl/xmake.lua
See https://github.com/xmake-io/xmake-repo/pull/5892
------
> libcurl: Restore openssl by default on Linux/Android

- packages/a/aws-lc/xmake.lua
New version of aws-lc detected (package version: v1.40.0, last github version: v1.41.1)
> Auto-update aws-lc to v1.41.1

- packages/l/libcpuid/xmake.lua
New version of libcpuid detected (package version: v0.7.0, last github version: v0.7.1)
> Auto-update libcpuid to v0.7.1

- packages/a/aws-c-s3/xmake.lua
New version of aws-c-s3 detected (package version: v0.7.5, last github version: v0.7.7)
> Auto-update aws-c-s3 to v0.7.7

- packages/e/emmylua_debugger/xmake.lua
The `emmylua_debugger` project includes three main targets: `emmy_core`, `emmy_tool`, and `emmy_hook`.  
Most users primarily use `emmy_core` for debugging Lua code, while `emmy_tool` and `emmy_hook` are specific to Windows and have been unmaintained for a long time. Attempting to build these components may lead to issues such as:  
```
error C1083: Cannot open include file: 'mscoree.h': No such file or directory
```
To avoid unnecessary build errors, this PR introduces an option to opt-out of installing `emmy_tool` and `emmy_hook` by default.
> emmylua_debugger: add option to skip installing `emmy_tool` and `emmy_hook` on Windows

- packages/s/sentry-native/xmake.lua
New version of sentry-native detected (package version: 0.7.15, last github version: 0.7.16)
> Auto-update sentry-native to 0.7.16

- packages/l/libmem/xmake.lua
New version of libmem detected (package version: 5.0.3, last github version: 5.0.4)
> Auto-update libmem to 5.0.4

- packages/n/nlopt/xmake.lua
New version of nlopt detected (package version: v2.8.0, last github version: v2.9.1)
> Auto-update nlopt to v2.9.1

- packages/c/cgraph/xmake.lua
New version of cgraph detected (package version: v2.6.1, last github version: v2.6.2)
> Auto-update cgraph to v2.6.2

- packages/d/date/xmake.lua
This PR introduces the release version of `date`. However, there's an issue where versions based on the commit date always take precedence over the release versions. I'm unsure how to make the release version the default.
>  date: Add release version

- packages/a/aws-c-compression/xmake.lua
New version of aws-c-compression detected (package version: v0.2.19, last github version: v0.3.0)
> Auto-update aws-c-compression to v0.3.0

- packages/m/mongoose/xmake.lua
New version of mongoose detected (package version: 7.15, last github version: 7.16)
> Auto-update mongoose to 7.16

- packages/l/libzip/xmake.lua
New version of libzip detected (package version: v1.11.1, last github version: v1.11.2)
> Auto-update libzip to v1.11.2

- packages/m/meson/xmake.lua
New version of meson detected (package version: 1.6.0, last github version: 1.6.1)
> Auto-update meson to 1.6.1

- packages/b/boost_ut/xmake.lua
New version of boost_ut detected (package version: v2.1.0, last github version: v2.1.1)
> Auto-update boost_ut to v2.1.1

- packages/c/cpptrace/xmake.lua
New version of cpptrace detected (package version: v0.7.3, last github version: v0.7.4)
> Auto-update cpptrace to v0.7.4

- packages/p/protobuf-cpp/xmake.lua
New version of protobuf-cpp detected (package version: 28.1, last github version: 29.2)
> Auto-update protobuf-cpp to 29.2

- packages/c/cppjieba/xmake.lua
New version of cppjieba detected (package version: v5.4.0, last github version: v5.4.1)
> Auto-update cppjieba to v5.4.1

- packages/g/glaze/xmake.lua
New version of glaze detected (package version: v4.0.1, last github version: v4.2.2)
> Auto-update glaze to v4.2.2

- packages/s/samurai/xmake.lua
New version of samurai detected (package version: v0.18.0, last github version: v0.19.0)
> Auto-update samurai to v0.19.0

- packages/r/rocksdb/xmake.lua
New version of rocksdb detected (package version: v9.7.4, last github version: v9.9.3)
> Auto-update rocksdb to v9.9.3

- packages/o/onetbb/xmake.lua
```console
$ xmake f -c -y
checking for platform ... mingw
checking for architecture ... x86_64
checking for mingw directory ... C:/msys64/mingw64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.42.34435
=> install onetbb 2022.0.0 .. failed
patch(patches/2022.0.0/fix-mingw-compilation.patch): not found!
if you want to get more verbose errors, please see:
-> C:\Users\star\AppData\Local\.xmake\cache\packages\2412\o\onetbb\2022.0.0\installdir.failed\logs\install.txt
error: install failed!
```
> tbb: remove alias package

- packages/n/node-api-stub/xmake.lua
> Add node-api-stub

- packages/g/ginkgo/xmake.lua
New version of ginkgo detected (package version: v1.8.0, last github version: v1.9.0)
> Auto-update ginkgo to v1.9.0

- packages/s/simdutf/xmake.lua
New version of simdutf detected (package version: v5.6.3, last github version: v5.7.1)
> Auto-update simdutf to v5.7.1

- packages/c/c-ares/xmake.lua
New version of c-ares detected (package version: 1.34.3, last github version: 1.34.4)
> Auto-update c-ares to 1.34.4

- packages/l/libsdl_image/xmake.lua
New version of libsdl_image detected (package version: 2.8.2, last github version: 2.8.3)
> Auto-update libsdl_image to 2.8.3

- packages/c/cppcheck/xmake.lua
New version of cppcheck detected (package version: 2.15.0, last github version: 2.16.2)
> Auto-update cppcheck to 2.16.2

- packages/l/lunasvg/xmake.lua
New version of lunasvg detected (package version: v3.0.1, last github version: v3.1.0)
> Auto-update lunasvg to v3.1.0

- packages/b/barkeep/xmake.lua
New version of barkeep detected (package version: v0.1.3, last github version: v0.1.4)
> Auto-update barkeep to v0.1.4

- packages/w/wfrest/xmake.lua
New version of wfrest detected (package version: v0.9.7, last github version: v0.9.8)
> Auto-update wfrest to v0.9.8

- packages/e/exprtk/xmake.lua
Also added versions for tags: 0.0.1, 0.0.2.
Release notes: https://www.partow.net/programming/exprtk/exprtk_release_notes_v0.0.3.txt
> Update ExprTk to 0.0.3

- packages/u/ufbx/xmake.lua
New version of ufbx detected (package version: v0.15.0, last github version: v0.15.1)
> Auto-update ufbx to v0.15.1

- packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.5.9, last github version: v1.5.10)
> Auto-update s2n-tls to v1.5.10

- packages/s/sfml/xmake.lua
- Raised C++ requirement to C++17
- [Removed OpenAL shared library requirement](https://github.com/SFML/SFML/blob/master/changelog.md#general)
- The default constructors `sf::Sound::Sound()`, `sf::Text::Text()`, and `sf::Sprite::Sprite()` were [removed.](https://github.com/SFML/SFML/blob/master/migration.md#removal-of-default-constructors)
- Changed default library type from shared to static
- When using X11 as the backend on Linux, libxi-dev is a newly [required dependency.](https://www.sfml-dev.org/tutorials/3.0/getting-started/migrate/#linux-dependencies)
> SFML: update to 3.0.0

- packages/l/lief/xmake.lua
Possible issue is dealing with repeated fmt library symbols of fmtlib_bundled.obj....
Yet it looks like it need some refactor or change so let me know.
> update LIEF to 0.16

- packages/k/kiwisolver/xmake.lua
New version of kiwisolver detected (package version: 1.4.7, last github version: 1.4.8)
> Auto-update kiwisolver to 1.4.8

- packages/f/fmt/xmake.lua
New version of fmt detected (package version: 11.0.2, last github version: 11.1.0)
> Auto-update fmt to 11.1.0

- packages/d/dr_mp3/xmake.lua
New version of dr_mp3 detected (package version: 0.6.39, last github version: 0.6.40)
> Auto-update dr_mp3 to 0.6.40

- packages/t/tree-sitter/xmake.lua
New version of tree-sitter detected (package version: v0.24.4, last github version: v0.24.5)
> Auto-update tree-sitter to v0.24.5

- packages/p/pdfio/xmake.lua
New version of pdfio detected (package version: v1.3.2, last github version: v1.4.0)
> Auto-update pdfio to v1.4.0

- packages/s/simdutf/xmake.lua
New version of simdutf detected (package version: v5.7.1, last github version: v5.7.2)
> Auto-update simdutf to v5.7.2

- packages/s/simsimd/xmake.lua
New version of simsimd detected (package version: v6.2.1, last github version: v6.2.3)
> Auto-update simsimd to v6.2.3

- packages/q/quickjs-ng/xmake.lua
New version of quickjs-ng detected (package version: v0.7.0, last github version: v0.8.0)
> Auto-update quickjs-ng to v0.8.0

- packages/p/pffft/port/xmake.lua
- packages/p/pffft/xmake.lua
[ x ] Im confused how to deal with option here... 
[ ] License itself does not seem into repo. (Like License file is seems to be used to store into conan, and being stored into vcpkg repo itself)...
[ x ] Maybe there is better url to use.
[ ] De-bundle fftpack & if there is need & possible (most likely this is abandoned & modified bundled dependency)? Quite funny to see it still stored there (https://chromium.googlesource.com/chromium/src/+/c1086af075699b05612673ef0005b0d3e0817a04/third_party/pffft/src & here https://healpix.jpl.nasa.gov/html/libfftpack/dirs.html) (Most likely file header stores LICENSE itself.)
If everything is ok feel free to merge, if there is need edit feel free to edit.
> new port pffft

- packages/c/c-blosc2/xmake.lua
New version of c-blosc2 detected (package version: v2.15.1, last github version: v2.15.2)
> Auto-update c-blosc2 to v2.15.2

- packages/u/units/xmake.lua
New version of units detected (package version: v2.3.3, last github version: v2.3.4)
> Auto-update units to v2.3.4

- packages/t/tree-sitter/xmake.lua
New version of tree-sitter detected (package version: v0.24.5, last github version: v0.24.6)
> Auto-update tree-sitter to v0.24.6

- packages/n/ngtcp2/xmake.lua
New version of ngtcp2 detected (package version: 1.9.1, last github version: 1.10.0)
> Auto-update ngtcp2 to 1.10.0

- packages/c/cpp-httplib/xmake.lua
New version of cpp-httplib detected (package version: v0.18.1, last github version: v0.18.3)
> Auto-update cpp-httplib to v0.18.3

- packages/s/snitch/xmake.lua
New version of snitch detected (package version: 1.2.5, last github version: 1.3.1)
> Auto-update snitch to 1.3.1
