packages/c/cmake/xmake.lua

add cmake 3.30.1

---

packages/l/libavif/xmake.lua
packages/l/libyuv/xmake.lua

New version of libavif detected (package version: v1.0.4, last github version: v1.1.0)

Auto-update libavif to v1.1.0

---

packages/f/fmt/xmake.lua

update fmt to 11.0.2

---

packages/b/boost/patches/1.85.0/fix-v144.patch
packages/b/boost/xmake.lua

Improve https://github.com/xmake-io/xmake-repo/pull/4182
Ref: https://github.com/bfgroup/b2/pull/394

boost: improve patch

---

packages/g/glm/xmake.lua

Fix https://github.com/xmake-io/xmake-repo/issues/4711

glm: fix headeronly kind

---

packages/e/exosip/xmake.lua

add exosip repo

---

packages/o/oatpp/xmake.lua

This pull request updates oatpp to version 1.4.0. Please note that this is a preview version as the milestone for the official release is not yet completed https://github.com/oatpp/oatpp/milestone/5

Update oatpp to 1.4.0 (Preview Version)

---

packages/r/rttr/xmake.lua

Fix https://github.com/xmake-io/xmake-repo/issues/4742

rttr: add latest version

---

packages/c/crashpad/xmake.lua

add macosx support for crashpad

---

packages/g/glslang/xmake.lua
packages/s/spirv-headers/xmake.lua
packages/s/spirv-reflect/xmake.lua
packages/s/spirv-tools/xmake.lua
packages/v/vk-bootstrap/xmake.lua
packages/v/volk/xmake.lua
packages/v/vulkan-headers/xmake.lua
packages/v/vulkan-hpp/xmake.lua
packages/v/vulkan-loader/xmake.lua
packages/v/vulkan-utility-libraries/xmake.lua
packages/v/vulkan-validationlayers/xmake.lua

update vulkan related libraries to v1.3.290.0

---

packages/p/patchelf/xmake.lua

add patchelf

---

packages/h/hidapi/xmake.lua
packages/l/libusb/xmake.lua

Fix https://github.com/xmake-io/xmake-repo/issues/4749

hidapi: support mingw

---

packages/b/benchmark/xmake.lua

update benchmark to 1.8.5

---

packages/a/aqt/xmake.lua

and drop support for signed versions as they're no longer produced

aqt: Add version 3.1.17

---

packages/i/imgui/xmake.lua

update imgui to v1.91.0

---

packages/x/xerces-c/xmake.lua

~~linux clang检查系统库似乎有问题，暂时先去掉了显式依赖`package:add("deps", "libiconv", {system = true})`~~
Wait for: #4708

add options for xerces-c

---

packages/u/usockets/port/xmake.lua
packages/u/usockets/xmake.lua

usockets: support openssl3

---

packages/s/stringzilla/xmake.lua

Support Stringzilla 3.0 C++ bindings.

---

packages/f/fmtlog/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/4806

fmtlog: set fmt version to 10

---

packages/f/fbgemm/patches/0.8.0/dep-unbundle.patch
packages/f/fbgemm/patches/0.8.0/msvc-omp.patch
packages/f/fbgemm/xmake.lua

New version of fbgemm detected (package version: v0.7.0, last github version: v0.8.0)

Auto-update fbgemm to v0.8.0

---

packages/f/fmt/xmake.lua

https://github.com/fmtlib/fmt/issues/3721

fmt: Set license

---

packages/i/itlib/xmake.lua

New version of itlib detected (package version: v1.11.0, last github version: v1.11.1)

Auto-update itlib to v1.11.1

---

packages/b/brpc/xmake.lua

New version of brpc detected (package version: 1.8.0, last github version: 1.10.0)

Auto-update brpc to 1.10.0

---

packages/c/cppfront/xmake.lua

New version of cppfront detected (package version: v0.7.0, last github version: v0.7.2)

Auto-update cppfront to v0.7.2

---

packages/r/rapidjson/xmake.lua

Fix rapidjson

---

packages/b/brynet/xmake.lua

brynet: fix header only kind

---

packages/a/abseil/xmake.lua

update abseil to 20240722.0

---

packages/p/python/xmake.lua

fix python for linux

---

packages/g/gdal/xmake.lua

update gdal test

---

.github/workflows/ubuntu_clang.yml
packages/o/openblas/xmake.lua

------
------
Fix the clang CI issue identified in #4699.

update openblas & upgrade clang ci

---

packages/s/sqlite3/xmake.lua

sqlite add "safe_mode" config

---

packages/b/boost/xmake.lua

update boost package:config("vs_runtime") to package:has_runtime

update boost package:config("vs_runtime") to package:has_runtime

---

packages/z/zmqpb/xmake.lua

- it's also headeronly now
adjust repo link, since i renamed it

add ZmqPb v0.10.2

---

packages/s/squirrel/xmake.lua

In response to #3127, this adds the Squirrel scripting language

Squirrel: Add new package

---

packages/g/gtest/xmake.lua

update gtest to 1.15.2

---

packages/c/cpp-httplib/xmake.lua

Update cpp-httplib to 0.16.2

---

packages/d/dyncall/xmake.lua

add package dyncall

---

packages/s/sqlite3/xmake.lua

update sqlite3 to 3.46.1

---

packages/f/fmt/xmake.lua

https://github.com/xmake-io/xmake/pull/5466

fix has_tool for fmt

---

packages/j/joltphysics/xmake.lua

fix joltphysics

---

packages/c/catch2/xmake.lua

fix catch2

---

packages/i/isocline/xmake.lua

isocline: remove limits

---

packages/b/boost/xmake.lua

------
------
> No new libraries.

update boost to 1.86.0

---

.github/workflows/android.yml
.github/workflows/android_windows.yml
packages/f/fast_float/xmake.lua

update fast_float to 6.1.4 & update android CI

---

packages/j/json-glib/patches/1.9.2/add_brace_to_json_scanner.patch
packages/j/json-glib/xmake.lua

这个库时libgda需要依赖的库，所以先提前支持，以便libgda集成

add json_glib repo

---

packages/g/godotcpp4/xmake.lua

Update godotcpp4 to 4.3

---

packages/l/libsdl/xmake.lua

------
------
related to https://github.com/xmake-io/xmake-repo/pull/4953

fix sdl android build

---

packages/c/centurion/xmake.lua

centurion: add package

---

packages/l/libdwarf/xmake.lua

update libdwarf to 0.11.0

---

packages/w/wil/xmake.lua

wil: update version to v1.0.240803.1

---

packages/i/iso-codes/xmake.lua
packages/l/libgda/xmake.lua

add repo libgda

---

packages/c/csvparser/xmake.lua

fix csvparser for xmake 2.9.4

---

packages/g/go/xmake.lua

- add v1.22.6 and v1.23.0
- support Windows-arm64

go: upgrade and add windows-arm64 support

---

.github/workflows/windows.yml
packages/s/simdutf/xmake.lua

------
------
- Upgrade simdutf to version 5.3.11.
- Remove temporary debug CI script to significantly reduce overall CI time.

update simdutf to 5.3.11

---

packages/p/pcre2/xmake.lua

update pcre2 to 10.44

---

packages/r/rapidjson/xmake.lua
packages/w/wren/xmake.lua

This adds the Wren scripting language to the repo.
**Links**
- https://github.com/wren-lang/wren
- https://wren.io/
**Popularity**
- Over 6k stars on Github
- over 500 forks on Github

Wren: add package

---

packages/p/pixman/xmake.lua

- Remove 404 github url
- Remove 0.40.0 version (4 years ago)

pixman: add 0.43.4 version & remove limit plat

---

packages/l/liburing/xmake.lua

update liburing to 2.7

---

packages/s/simdutf/xmake.lua

New version of simdutf detected (package version: v5.3.11, last github version: v5.4.15)

Auto-update simdutf to v5.4.15

---

packages/c/cimg/xmake.lua

CImg: add version 3.4.1

---

packages/a/ada/xmake.lua

update ada-url to 2.9.1

---

packages/l/lunasvg/xmake.lua
packages/p/plutovg/xmake.lua

New version of lunasvg detected (package version: v2.4.0, last github version: v2.4.1)

Auto-update lunasvg to v2.4.1

---

packages/v/vulkan-validationlayers/xmake.lua

Fix for vulkan not finding validation layers at runtime.
I'm not sure if I did it right, but it worked for me.
Also, this is my first pull request, so I apologize if something is wrong.

vulkan-validationlayers: fixing the detection of layers at runtime

---

packages/c/c-vector/xmake.lua

A simple vector library for C that can store any type.
193 stars and 21 forks on github

add c-vector

---

packages/f/fpng/xmake.lua

New version of fpng detected (package version: v1.0.1, last github version: v1.0.6)

Auto-update fpng to v1.0.6

---

packages/l/libwebsockets/xmake.lua

Drop v4.1.6 version (4 years ago)

libwebsockets: add v4.3.3 version

---

packages/j/jsoncons/xmake.lua

Update jsoncons to 0.177.0

---

packages/c/cosmocc/xmake.lua

https://github.com/xmake-io/xmake/issues/5552

fix cosmoc++

---

packages/c/cosmocc/xmake.lua

improve cosmocc

---

packages/c/cimg/xmake.lua

* add v.3.4.2
* fix the homepage link

CImg: add new version & fix the homepage link

---

packages/p/pyincpp/xmake.lua

pyincpp: add the missing license

---

packages/c/catch2/xmake.lua

Fixes https://github.com/xmake-io/xmake-repo/issues/5144

Fix catch2 v2.x install failures

---

packages/l/libxmake/xmake.lua

New version of libxmake detected (package version: v2.9.2, last github version: v2.9.4)

Auto-update libxmake to v2.9.4

---

.github/workflows/cross_musl.yml
packages/a/async_simple/xmake.lua

update cross toolchain

---

packages/i/imgui-sfml/xmake.lua

imgui-sfml: add the license

---

packages/c/croncpp/xmake.lua

croncpp: add package

---

packages/p/pcapplusplus/xmake.lua

New version of pcapplusplus detected (package version: v23.09, last github version: v24.09)

Auto-update pcapplusplus to v24.09

---

packages/i/imgui/xmake.lua

Just a small PR to add version 1.91.1 (normal and docking) to imgui package

adding imgui v1.91.1

---

packages/q/qmsetup/xmake.lua
packages/s/syscmdline/xmake.lua

- Unbundle dep(syscmdline)
- Drop 2024.04.23 version and add 2024.09.02 version
- Fix ninja build in debug mode

qmsetup: fix library kind

---

packages/g/glad/patches/0.1.36/utf8.patch
packages/g/glad/xmake.lua

localize glad patch

---

packages/l/libvpx/xmake.lua

fix libvpx grammar problem

---

packages/o/osqp/patches/0.6.3/cmake.patch
packages/o/osqp/xmake.lua
packages/q/qdldl/xmake.lua

- Drop 0.6.2 (2021)
- Unbundled dep(qdldl)

osqp: add v0.6.3 version

---

packages/d/dataframe/xmake.lua

dataframe: update version

---

packages/y/yxml/xmake.lua

```lua
add_requires("yxml")
```
```c++
#include <yxml.h>
```

yxml: add package

---

packages/f/frozen/xmake.lua
packages/l/lief/patches/0.15.1/algorithm.patch
packages/l/lief/xmake.lua
packages/s/spdlog/xmake.lua
packages/t/tl_expected/xmake.lua

- Add 0.15.1 version
- Add exceptions config
- Enable all platform
deps package
- frozen/tl_expected: Switch to cmake install
- spdlog: Fix `CMAKE_BUILD_TYPE`

lief: improve deps

---

packages/l/libxml2/configs.lua
packages/l/libxml2/xmake.lua
packages/x/xz/xmake.lua

- Drop 2.10.3 version
- Add version
- v2.13.4
- v2.12.9
- v2.11.9
- Add all cmake option
- python test maybe fail.

libxml2: rework

---

packages/u/upa-url/xmake.lua

```lua
add_requires("upa-url")
```
```c++
#include <upa/url.h>
```

upa-url: add package

---

packages/j/jsoncpp/xmake.lua

jsoncpp: update to 1.9.6

---

packages/p/portaudio/xmake.lua

libportaudio.a would have link error when not linked to libasound

portaudio: add libasound syslink

---

packages/l/lapack/xmake.lua

add lapack repo

---

packages/c/cosmocc/xmake.lua

update cosmocc to version 3.9.2
add a new mirror for cosmocc

update cosmocc to version 3.9.2

---

packages/m/mmloader/xmake.lua

```lua
add_requires("mmloader", {configs = {shellcode = true}})
```
```c++
#include <mmLoader/mmLoader.h>
#include <mmloader/mmLoaderShellCode-[x64|Win32]-[Debug|Release].h>
```

mmloader: add package

---

packages/g/gfx-timsort/xmake.lua
packages/t/timsort/xmake.lua

```lua
add_requires("gfx-timsort")
```
```c++
#include <gfx/timsort.hpp>
```

gfx-timsort: add package

---

packages/l/libvips/patches/8.15.3/msvc-ssize_t.patch
packages/l/libvips/xmake.lua

https://github.com/libvips/libvips/issues/4088

libvips: improve patch

---

packages/c/cnl/xmake.lua

```lua
add_requires("cnl")
```
```c++
#include <cnl/all.h>
```

cnl: add package

---

packages/l/libfixmath/xmake.lua
packages/l/libfixmatrix/xmake.lua

```lua
add_requires("libfixmath")
add_requires("libfixmatrix")
```
```c++
#include <libfixmath/fix16.h>
#include <libfixmath/fix16.hpp>
#include <libfixmatrix/fixmatrix.hpp>
```

libfixmatrix: add package

---

packages/f/fpm/xmake.lua

```lua
add_requires("fpm")
```
```c++
#include <fpm/fixed.hpp>
#include <fpm/math.hpp>
#include <fpm/ios.hpp>
```

fpm: add package

---

packages/p/physfs/xmake.lua

```lua
add_requires("physfs")
```
```c++
#include <physfs.h>
```

physfs: add package

---

packages/x/x264/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/5344

x264: add v2024.02.27 version

---

packages/w/wirehair/xmake.lua

```lua
add_requires("wirehair")
```
```c++
#include <wirehair/wirehair.hpp>
```

wirehair: add package

---

packages/n/nifly/xmake.lua

- add [`nifly`](https://github.com/ousnius/nifly) library

nifly: add package

---

packages/z/zimg/xmake.lua

zimg: update to 3.0.5

---

packages/c/croaring/xmake.lua

New version of croaring detected (package version: v4.1.5, last github version: v4.1.7)

Auto-update croaring to v4.1.7

---

packages/q/qoa/xmake.lua

```lua
add_requires("qoa")
```
```c++
#include <qoa.h>
```

qoa: add package

---

packages/g/glaze/xmake.lua

Update glaze to v3.6.0

---

packages/l/libdom/port/xmake.lua
packages/l/libdom/xmake.lua
packages/l/libwapcaplet/port/xmake.lua
packages/l/libwapcaplet/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/5377
```lua
add_requires("libdom")
add_requires("libwapcaplet")
```
```c++
#include <dom/dom.h>
#include <libwapcaplet/libwapcaplet.h>
```

libdom: add package

---

packages/i/itlib/xmake.lua

New version of itlib detected (package version: v1.11.1, last github version: v1.11.4)

Auto-update itlib to v1.11.4

---

packages/c/cppast/xmake.lua

Update cppast and limit llvm version

---

packages/s/sqlite-vec/xmake.lua

```lua
add_requires("sqlite-vec")
```
```c++
#include <sqlite-vec.h>
```

sqlite-vec: add package

---

packages/p/pycdc/port/xmake.lua
packages/p/pycdc/xmake.lua

pycdc: add 2024.08.12 version

---

packages/l/linalg/xmake.lua

Change the hash to lower case to avoid unmached checksum error.

linalg: fix checksum

---

packages/s/spirv-reflect/xmake.lua

spirv-reflect support android

---

packages/o/openh264/xmake.lua

Add macos compilation support for openh264

openh264: Add macos compilation support

---

packages/d/dataframe/xmake.lua

New version of dataframe detected (package version: 3.2.0, last github version: 3.3.0)

Auto-update dataframe to 3.3.0

---

packages/i/imgui-filebrowser/xmake.lua

```lua
add_requires("imgui-filebrowser")
```
```c++
#include <imgui.h>
#include <imfilebrowser.h>
```

imgui-filebrowser: add package

---

packages/c/cimg/xmake.lua

CImg: add v3.4.3

---

packages/a/aws-c-cal/xmake.lua
packages/a/aws-c-common/xmake.lua
packages/a/aws-c-io/xmake.lua
packages/s/s2n-tls/xmake.lua

New version of aws-c-io detected (package version: v0.14.18, last github version: v0.14.19)

Auto-update aws-c-io to v0.14.19

---

packages/l/libebur128/xmake.lua

```lua
add_requires("libebur128")
```
```c++
#include <ebur128.h>
```

libebur128: add package

---

packages/l/libuv/xmake.lua

update libuv to 1.49.1

---

packages/f/ffts/xmake.lua

```lua
add_requires("ffts")
```
```c++
#include <ffts/ffts.h>
```

ffts: add package

---

packages/l/libenvpp/xmake.lua

New version of libenvpp detected (package version: v1.4.2, last github version: v1.4.3)

Auto-update libenvpp to v1.4.3

---

packages/l/ls-qpack/patches/2.5.5/cmake.patch
packages/l/ls-qpack/xmake.lua
packages/p/pkg-config/xmake.lua

New version of ls-qpack detected (package version: v2.5.4, last github version: v2.5.5)

Auto-update ls-qpack to v2.5.5

---

packages/l/libxml2/xmake.lua
packages/l/libxslt/xmake.lua

libxslt: rework

---

packages/t/tidy-html5/xmake.lua

```lua
add_requires("tidy-html5")
```
```c++
#include <tidy.h>
```

tidy-html5: add package

---

packages/n/nanomsg/xmake.lua

```lua
add_requires("nanomsg")
```
```c
#include <nanomsg/nn.h>
```

nanomsg: add package

---

packages/o/openxlsx/xmake.lua

```lua
add_requires("openxlsx")
```
```c++
#include <OpenXLSX/OpenXLSX.hpp>
```

openxlsx: add package

---

packages/s/stringzilla/xmake.lua

* update stringzilla to v3.10.0
* fix not copying stringzillia.hpp to include and build error when enable cpp

update stringzilla to v3.10.0

---

packages/s/stringzilla/xmake.lua

StringZilla: update to v3.10.5

---

packages/e/emio/xmake.lua

New version of emio detected (package version: 0.7.0, last github version: 0.8.0)

Auto-update emio to 0.8.0

---

packages/z/zmqpb/xmake.lua

this fixes a runtime error i had on windows

add zmqpb v0.10.3

---

packages/k/klib/port/rand48.c
packages/k/klib/port/unistd.h
packages/k/klib/port/xmake.lua
packages/k/klib/xmake.lua

```lua
add_requires("klib[url,thread,open]")
```
```c
#include <kalloc.h>
```

klib: add package

---

packages/l/libssh/xmake.lua

```lua
add_requires("libssh[zlib,backend=openssl]")
```
```c++
#include <libssh/libssh.h>
```

libssh: add package

---

packages/u/unicorn/xmake.lua

```lua
add_requires("unicorn[logging,tracer,archs=[x86,aarh64]]")
```
More archs see
https://github.com/unicorn-engine/unicorn/blob/d568885d64c89db5b9a722f0c1bef05aa92f84ca/CMakeLists.txt#L70
```c++
#include <unicorn/unicorn.h>
```

unicorn: rework

---

packages/m/magic_enum/xmake.lua

Add magic enum module support

---

packages/l/libxkbcommon/xmake.lua
packages/m/minifb/xmake.lua

version: 2022.11.12 -> 2023.09.21

minifb: support more platforms

---

packages/m/meet/xmake.lua

------
ps: `xmake l scripts/test.lua -v -D meet` 运行测试没问题

add meet lib repo

---

packages/g/gsound/xmake.lua

add gsound repo

---

packages/s/sqlite3/xmake.lua

update sqlite3 to 3.47.0

---

packages/a/asio/xmake.lua

update asio to 1.32.0

---

packages/e/eigen/xmake.lua

后面的检测应该没必要，是我之前改fortran compiler错误的时候disable太多东西了
https://github.com/xmake-io/xmake-repo/issues/5597 看到了，还是得加上

fix eigen incorrectly disabling unsupported

---

packages/l/lighthook/xmake.lua
packages/m/meet/xmake.lua

add lighthook lib repo.
Single-header, minimalistic, cross-platform hook library written in pure C 
git: https://github.com/SamuelTulach/LightHook

add lighthook lib repo.

---

packages/v/vulkan-memory-allocator-hpp/xmake.lua

[vulkan-memory-allocator-hpp] fix module support

---

packages/c/cjson/xmake.lua

Sorry for re-opening the PR. I accidentally deleted my fork.
This PR already includes changes from @star-hengxing 's work in #5611

cJSON: update to v1.7.18

---

packages/b/bddisasm/xmake.lua

```lua
add_requires("bddisasm[isagenerator, vsnprintf, memset, no_mnemonics, tools]")
```
```c++
#include <bddisasm/bddisasm.h>
```

bddisasm: add package

---

packages/s/stringzilla/xmake.lua

Also updated the description (synched with its homepage).

StringZilla: update to v3.10.7

---

packages/o/openmp/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/5610

improve to fetch openmp #5610

---

packages/b/barkeep/xmake.lua

```lua
add_requires("barkeep[fmt]")
```
```c++
#include <barkeep/barkeep.h>
```

barkeep: add package

---

packages/i/icu4c/xmake.lua

close https://github.com/xmake-io/xmake-repo/issues/5647
No way to pass ucrt flags for msbuild from the command line, only patch vcxproj or custom vcxproj.
Current icu vcxproj will pass `-D_DEBUG` macro when `build_type=debug`. If `M[T/D]d` runtime is enabled, force to use debug package.

icu4c: improve ucrt

---

packages/d/dartsim/xmake.lua

Closes https://github.com/xmake-io/xmake-repo/pull/5268

dart 6.14.5

---

packages/j/joltphysics/xmake.lua

joltphysics: Add version 5.2.0

---

packages/m/manif/xmake.lua
packages/t/tl_optional/xmake.lua

```lua
add_requires("manif")
```
```c
#include <manif/manif>
```
tl_optional: switch to cmake.

manif: add package

---

packages/b/boost/b2/install.lua
packages/b/boost/b2/load.lua
packages/b/boost/cmake/install.lua
packages/b/boost/cmake/load.lua

close https://github.com/xmake-io/xmake-repo/issues/5669

boost: fix b2 when enable iostreams deps

---

packages/m/microsoft-gsl/xmake.lua

microsoft-gsl: add v4.1.0 version

---

packages/s/stringzilla/xmake.lua

StringZilla: update to v3.10.8

---

packages/m/microsoft-kuku/xmake.lua

```lua
add_requires("microsoft-kuku[c_api]")
```
```c++
#include <kuku/kuku.h>
#include <kuku/c/kuku_ref.h>
```

microsoft-kuku: add package

---

packages/c/cpu-features/xmake.lua
packages/c/cpu_features/xmake.lua

- Add alias package.
- Support more platform.

cpu_features: add v0.9.0 version

---

packages/p/plutosvg/xmake.lua
packages/p/plutovg/xmake.lua

```lua
add_requires("plutosvg")
```
```c
#include <plutosvg/plutosvg.h>
```

plutosvg: add package

---

packages/m/microsoft-seal/patches/4.1.2/cmake-config-zstd.patch
packages/m/microsoft-seal/patches/4.1.2/find-zstd.patch
packages/m/microsoft-seal/xmake.lua

```lua
add_requires("microsoft-seal[zlib,zstd,ms_gsl,hexl]")
```
```c++
#include <seal/seal.h>
```

microsoft-seal: add package

---

packages/h/hexl/patches/1.2.5/cmake-find-easyloggingpp.patch
packages/h/hexl/xmake.lua

```lua
add_requires("hexl[experimental]")
```
```c++
#include <hexl/hexl.hpp>
```

hexl: add package

---

packages/s/spdlog/xmake.lua

Update spdlog to v1.15.0

---

packages/f/flatbuffers/xmake.lua

flatbuffers: support more platform

---

packages/z/zpp_bits/xmake.lua

```lua
add_requires("zpp_bits")
```
```c++
#include <zpp_bits.h>
```

zpp_bits: add package

---

packages/f/fftw/xmake.lua

Fix test with non-double precision

fftw: support more platform

---

packages/j/jnipp/xmake.lua
packages/o/openjdk/fetch.lua
packages/o/openjdk/xmake.lua

- Improve on_fetch.
- Default binary kind.
- Use microsoft precompiled binary.

openjdk: improve download link

---

packages/p/python/xmake.lua

wondering how to update download links for windows...

Update python 3.13 and 3.11.9 (for linux)

---

packages/c/cppzmq/xmake.lua
packages/z/zeromq/patches/4.3.5/mingw.patch
packages/z/zeromq/xmake.lua

- Switch to cmake.
- Add curve config.

zeromq: support more platform

---

packages/c/catch2/xmake.lua

fix clang-cl ldflag

---

packages/l/liburing/xmake.lua

update liburing to 2.8

---

packages/a/alembic/xmake.lua

alembic: support more platform

---

packages/b/boost/fetch.lua

https://github.com/xmake-io/xmake-repo/issues/5817

fix boost fetch

---

packages/a/arkari/xmake.lua

close https://github.com/xmake-io/xmake-repo/issues/5815
```lua
add_requires("arkari")
set_toolchains("llvm@arkari")
```

arkari: add package

---

packages/a/actor-framework/xmake.lua

New version of actor-framework detected (package version: 1.0.1, last github version: 1.0.2)

Auto-update actor-framework to 1.0.2

---

packages/f/flatbuffers/xmake.lua
packages/l/log4cplus/xmake.lua
packages/m/microsoft-apsi/xmake.lua
packages/m/microsoft-seal/xmake.lua

```lua
add_requires("microsoft-apsi[log4cplus,cppzmq]")
```
```c++
#include <apsi/sender.h>
```

microsoft-apsi: add package

---

packages/m/msvc/xmake.lua
packages/p/portable_build_tools/xmake.lua

add msvc package

---

packages/m/msvc/xmake.lua

add installtips for msvc

---

packages/c/cppfront/xmake.lua

cppfront - support arm macos

---

packages/s/sqlite3/xmake.lua

update sqlite3 to 3.47.1

---

packages/s/srt/xmake.lua

New version of srt detected (package version: v1.5.3, last github version: v1.5.4)

Auto-update srt to v1.5.4

---

packages/m/memorymodulepp/xmake.lua

add memorymodulepp

---

packages/o/onedpl/xmake.lua

Update onedpl 2022.6.0rc1

---

packages/a/abseil/xmake.lua
packages/p/protobuf-cpp/xmake.lua
packages/z/zmqpb/xmake.lua

- abseil
- Fix syslinks
- protobuf
- Add config
- rtti
- lite (libprotobuf-lite)
- upb (libupb)
- Add component
- utf8_range
- protobuf
- protobuf-lite
- protoc
- upb
- Add library test

protobuf-cpp: support more platform

---

packages/c/cpptrace/xmake.lua
packages/l/libdwarf/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/5844#issuecomment-2507253941

cpptrace: fix libdwarf & zstd

---

packages/j/jsoncons/xmake.lua

- Add cmake config (default: true)
- Drop old version v0.158.0

jsoncons: add v0.178.0 version

---

packages/q/qengine/xmake.lua

```lua
add_requires("qengine")
```
```c++
#include <qengine/engine/qengine.hpp>
```

qengine: add package

---

packages/r/reflect-cpp/xmake.lua

Update reflect-cpp to v0.16.0

---

packages/b/boxfort/xmake.lua

```lua
add_requires("boxfort[arena_reopen_shm,arena_file_backed]")
```
```c
#include <boxfort.h>
```

boxfort: add package

---

packages/a/audiofile/xmake.lua

New version of audiofile detected (package version: 1.1.1, last github version: 1.1.2)

Auto-update audiofile to 1.1.2

---

packages/s/snmalloc/xmake.lua

New version of snmalloc detected (package version: 0.6.2, last github version: 0.7.0)

Auto-update snmalloc to 0.7.0

---

packages/b/boost/cmake/install.lua
packages/b/boost/cmake/load.lua
packages/b/boost/xmake.lua
packages/m/mailio/xmake.lua

New version of mailio detected (package version: 0.23.0, last github version: 0.24.1)

Auto-update mailio to 0.24.1

---

packages/t/tbb/patches/2022.0.0/fix-mingw-compilation.patch
packages/t/tbb/xmake.lua

See if the package can pass ci
------

Update tbb 2022.0

---

packages/f/flatcc/xmake.lua

```lua
add_requires("flatcc")
```
```c
#include <flatcc/flatcc_builder.h>
```

flatcc: add package

---

packages/n/nanoarrow/xmake.lua

```lua
add_requires("nanoarrow[ipc,device,cuda]")
```
```c
#include <nanoarrow/nanoarrow.h>
```

nanoarrow: add package

---

packages/i/ispc/xmake.lua

Update ISPC to 1.25.3

---

packages/i/itstool/xmake.lua
packages/l/libxml2/xmake.lua

The package does not work by default but setting the libxml2 dep to shared makes it work

itstool: Support bsd

---

packages/j/jxrlib/patches/mingw.patch
packages/j/jxrlib/patches/missing-declarations.patch
packages/j/jxrlib/port/xmake.lua
packages/j/jxrlib/xmake.lua

```lua
add_requires("jxrlib")
```
```c
#include <JXRTest.h>
// or
#include <jxrlib/JXRTest.h>
```

jxrlib: add package

---

.github/workflows/android_windows.yml
.github/workflows/windows.yml
.github/workflows/windows_v3.yml
scripts/test.lua

https://github.com/xmake-io/xmake-repo/pull/5922

Improve to test packages

---

packages/s/sqlite3/xmake.lua

update sqlite3 to 3.47.2

---

packages/i/imgui/xmake.lua

imgui: Enable all platforms

---

packages/o/openssl/xmake.lua
packages/o/openssl3/xmake.lua

support iphoneos for openssl

---

packages/b/boost/fetch.lua
packages/b/boost/test.lua

修复 boost 包的测试函数在 exception 关闭时失败的问题

[boost] fix test.lua

---

scripts/test.lua

fix test.lua for info test

---

packages/p/protobuf-cpp/xmake.lua

Resolve the issue reported in #5877

protobuf-cpp: Fix Windows build for versions <= 3.19.4

---

scripts/test.lua

https://github.com/xmake-io/xmake-repo/pull/5953#issuecomment-2541642373

fix test.lua cd

---

packages/m/magic_enum/xmake.lua

Patch includedirs to support:
```c++
#include <magic_enum.hpp>
#include <magic_enum/magic_enum.hpp>
```

magic_enum: compatible with includedirs

---

packages/p/plfit/xmake.lua

```lua
add_reuires("plfit[sse,openmp]")
```
```c
#include <plfit/plfit.h>
```

plfit: add package

---

packages/a/annoy/xmake.lua

```lua
add_requires("annoy")
```
```c++
#include <annoy/annoylib.h>
```

annoy: add package

---

packages/c/clay/xmake.lua

```lua
add_requires("clay")
```
```c
#include <clay.h>
```

clay: add package

---

packages/n/nghttp3/xmake.lua
packages/s/sfparse/xmake.lua

New version of nghttp3 detected (package version: v1.6.0, last github version: v1.7.0)

Auto-update nghttp3 to v1.7.0

---

packages/h/hookmanager/xmake.lua

+ **一个以`lighthook` `minhook` `detours` （后续可能添加更多）其中一个作为hook实现的hook管理框架**

Add HookManager Lib Repo

---

packages/h/hookmanager/xmake.lua

- update to 0.3.3
- 更新到0.3.3 - 修复0.3.2头文件不能跨cpp引用的问题

Update The HookManager Version To V0.3.3

---

packages/v/vvenc/xmake.lua

New version of vvenc detected (package version: v1.12.1, last github version: v1.13.0)

Auto-update vvenc to v1.13.0

---

packages/d/dr_wav/xmake.lua

New version of dr_wav detected (package version: 0.13.16, last github version: 0.13.17)

Auto-update dr_wav to 0.13.17

---

packages/d/dr_flac/xmake.lua

New version of dr_flac detected (package version: 0.12.42, last github version: 0.12.43)

Auto-update dr_flac to 0.12.43

---

packages/l/lief/xmake.lua

Update LIEF 0.16.1

---

packages/s/sfml/xmake.lua

SFML: Fix msvc runtime when using MTd without debug

---

packages/f/fmt/xmake.lua

update fmt to 11.1.1

---

packages/f/flatbuffers/xmake.lua

Update flatbuffers to v24.12.23

---

packages/l/lief/xmake.lua

Update LIEF to 0.16.2

---

packages/c/cimg/xmake.lua

CImg: update to v3.5.0

---

packages/v/vulkan-memory-allocator/xmake.lua

Update vulkan-memory-allocator to 3.2.0.

Update vulkan-memory-allocator to 3.2.0

---

packages/c/cunit/xmake.lua

Feel free to change & merge. IDK if lic is correct. Its either LGPL-2.0 or LGPL-2.1 I think. https://archlinux.org/packages/extra/x86_64/cunit/ as I believe this fork kept same license.

New package: cunit

---

packages/m/miniz/xmake.lua

Update miniz to 3.0.2

---

packages/m/miniz/xmake.lua

Make shared build possible, rely over existing CMakeLists.txt

revise miniz

---

packages/e/easy_profiler/xmake.lua

Fixes https://github.com/xmake-io/xmake-repo/issues/6115
Since it's my very first pr, feel free to correct me!

Add easy_profiler package

---

packages/l/libgit2/xmake.lua

Update libgit2 to 1.9.0

---

packages/l/libgit2cpp/xmake.lua

```lua
add_requires("libgit2cpp[boost]")
```
```c++
#include <git2cpp/repo.h>
```

libgit2cpp: add package

---

packages/t/tlsf/xmake.lua

Add https://github.com/mattconte/tlsf  memory allocator.

Add tlsf package

---

packages/l/littlefs/xmake.lua

New version of littlefs detected (package version: v2.9.3, last github version: v2.10.1)

Auto-update littlefs to v2.10.1

---

packages/d/dipp/xmake.lua

for #6154, unfortunately it uses C++20 and C++23 features for the time being.

Add dipp package

---

packages/o/offsetallocator/xmake.lua

Add https://github.com/sebbbi/OffsetAllocator

Add offsetAllocator package

---

packages/f/fmt/xmake.lua

update fmt to 11.1.2

---

packages/s/sqlite3/xmake.lua

update sqlite3 to 3.48.0

---

packages/d/dlss/xmake.lua

Add  https://github.com/NVIDIA/DLSS

Add dlss package

---

packages/l/lwlog/xmake.lua

```lua
add_requires("lwlog")
```
```c++
#include <lwlog.h>
```

lwlog: add package

---

.github/workflows/ubuntu_arm64.yml

https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview

Add hosted arm64 ci

---

packages/u/utf8proc/xmake.lua

for poco's dep 
https://github.com/xmake-io/xmake-repo/pull/6177

Update utf8proc and install to all plat

---

packages/c/cmake/xmake.lua

https://github.com/xmake-io/xmake/pull/6101

improve cmake for ninja

---

packages/f/faker-cxx/xmake.lua

New version of faker-cxx detected (package version: v3.0.0, last github version: v4.0.1)

Auto-update faker-cxx to v4.0.1

---

packages/l/lastools/port/xmake.lua
packages/l/lastools/xmake.lua

close https://github.com/xmake-io/xmake-repo/issues/6204
```lua
add_requires("lastools[cmake,tools]")
```
```c++
#include <LASlib/lasreader.hpp>
#include <LASlib/laswriter.hpp>
```

lastools: add package

---

packages/r/reckless/xmake.lua

Add https://github.com/mattiasflodin/reckless

Add reckless log

---

packages/g/gcem/xmake.lua

Remove platform requirements for gcem

---

packages/s/stc/xmake.lua

New version of stc detected (package version: v4.2, last github version: v5.0)

Auto-update stc to v5.0

---

packages/k/kuba-zip/xmake.lua

New version of kuba-zip detected (package version: v0.3.2, last github version: v0.3.3)

Auto-update kuba-zip to v0.3.3

---

packages/c/cimg/xmake.lua

CImg: update to v3.5.2

---

packages/r/reactiveplusplus/xmake.lua

New version of reactiveplusplus detected (package version: v2.1.1, last github version: v2.2.2)

Auto-update reactiveplusplus to v2.2.2

---

packages/m/minja/xmake.lua

```c++
#include <minja/minja.hpp>
```

minja: add package

---

packages/i/itlib/xmake.lua

New version of itlib detected (package version: v1.11.4, last github version: v1.11.5)

Auto-update itlib to v1.11.5

---

packages/f/fmt/xmake.lua

update fmt to 11.1.3

---

packages/l/libfswatch/xmake.lua

New version of libfswatch detected (package version: 1.17.1, last github version: 1.18.2)

Auto-update libfswatch to 1.18.2

---

packages/l/libmaxminddb/xmake.lua

New version of libmaxminddb detected (package version: 1.11.0, last github version: 1.12.2)

Auto-update libmaxminddb to 1.12.2

---

packages/l/liboai/xmake.lua

- Add license.
- Improve version name.
- Remove deleted version.

liboai: Add license

---

packages/v/vc-ltl5/xmake.lua

See https://github.com/Chuyu-Team/VC-LTL5/releases/tag/v5.1.1

vc-ltl5: add deps for windows xp version

---

packages/l/libxmake/xmake.lua

libxmake: disable readline

---

packages/c/capstone/xmake.lua

New version of capstone detected (package version: 5.0.3, last github version: 5.0.5)

Auto-update capstone to 5.0.5

---

packages/l/libxmake/patches/2.9.8/prefix.patch
packages/l/libxmake/xmake.lua

libxmake: fix lni

---

packages/i/idna/xmake.lua

idna: add 0.2.0 version

---

packages/s/sqlite3/xmake.lua

update sqlite3 to 3.49.0

---

packages/p/pahomqttcpp/xmake.lua

New version of pahomqttcpp detected (package version: v1.4.1, last github version: v1.5.0)

Auto-update pahomqttcpp to v1.5.0

---

packages/l/libpng/xmake.lua

Update libpng to 1.6.46

---

packages/l/libsdl3_image/xmake.lua

Add libsdl3_image

---

packages/k/kotlin-native/xmake.lua

add kotlin-native

---

packages/d/dlss/xmake.lua

New version of dlss detected (package version: v3.7.20, last github version: v310.1.0)

Auto-update dlss to v310.1.0

---

packages/z/zint/xmake.lua

```lua
add_requires("zint[png]")
```
```c
#include <zint.h>
```

zint: add package

---

packages/s/streamvbyte/xmake.lua

New version of streamvbyte detected (package version: v1.0.0, last github version: v2.0.0)

Auto-update streamvbyte to v2.0.0

---

packages/c/cpr/xmake.lua

close https://github.com/xmake-io/xmake-repo/issues/5703

cpr: support clang-cl toolchain

---

packages/a/aws-lc/xmake.lua

New version of aws-lc detected (package version: v1.41.1, last github version: v1.45.0)

Auto-update aws-lc to v1.45.0

---

packages/i/implot3d/xmake.lua

```lua
add_requires("implot3d")
```
```c++
#include <implot3d.h>
```

implot3d: add package

---

packages/w/watcher/xmake.lua

New version of watcher detected (package version: 0.13.2, last github version: 0.13.5)

Auto-update watcher to 0.13.5

---

packages/a/aurora-au/xmake.lua

```lua
add_requires("aurora-au")
```
```c++
#include <au/units/meters.hh>
```

aurora-au: add package

---

packages/k/kotlin-native/xmake.lua
packages/o/openjdk/xmake.lua

add msys platform for kotlin-native

---

packages/s/sqlite3/xmake.lua

update sqlite3 to 3.49.1

---

packages/d/dataframe/xmake.lua

New version of dataframe detected (package version: 3.3.0, last github version: 3.4.0)

Auto-update dataframe to 3.4.0

---

packages/m/meson/xmake.lua

Update meson to 1.7.0

---

packages/t/taskflow/xmake.lua

update taskflow to v3.9.0

---

packages/p/poly2tri/xmake.lua

https://repology.org/project/poly2tri/versions
```cpp
#include <poly2tri/poly2tri.h>
```
Maybe I should ```FILES_MATCHING PATTERN "*.h"``` during headers installation.

add new package poly2tri

---

packages/e/etl/xmake.lua

etl: update to v20.40.0

---

packages/f/flatbuffers/xmake.lua

update flatbuffers to v25.2.10

---

packages/l/lcms/xmake.lua

update lcms to 2.17

---

packages/h/harfbuzz/xmake.lua

update harfbuzz to 10.3.0

---

packages/p/plutosvg/xmake.lua

update plutosvg to 0.0.6

---

packages/s/safetyhook/xmake.lua

```cpp
#include <safetyhook.hpp>
```

add new package safetyhook

---

packages/u/uwebsockets/xmake.lua

Update uwebsockets to v20.74.0

---

packages/g/gelldur-eventbus/xmake.lua

Add gelldur-eventbus v3.1.2

---

packages/l/libebur128/xmake.lua

Add windows plat for libebur128

---

packages/f/fixed-containers/xmake.lua

Add fixed-containers

---

packages/n/nsis/xmake.lua

improve check nsis

---

.github/workflows/ubuntu_arm64.yml
packages/m/mnn/xmake.lua

update mnn to 3.0.5

---

packages/c/cpptrace/xmake.lua

update cpptrace to v0.8.2

---

packages/a/async_simple/xmake.lua

Should help to https://github.com/xmake-io/xmake-repo/pull/6464

async_simple Fix linux arm64

---

packages/t/tbox/xmake.lua

Update tbox to v1.7.6

---

packages/i/iguana/xmake.lua

update iguana to 1.0.7

---

packages/c/cinatra/xmake.lua

update cinatra to 0.9.5

---

packages/f/fast_float/xmake.lua

update fast_float to v8.0.0

---

packages/l/libkeyfinder/xmake.lua

Add libkeyfinder 2.2.8

---

packages/g/gamenetworkingsockets/port/xmake.lua
packages/g/gamenetworkingsockets/xmake.lua

Remove OpenSSL dependency for GNS on windows

---

packages/s/sokol-tools/xmake.lua

Add sokol-tools

---

packages/l/liquid-dsp/xmake.lua

Add liquid-dsp v1.7.0

---

packages/m/muparserx/xmake.lua

Add muparserx v4.0.12

---

packages/p/plfit/xmake.lua

New version of plfit detected (package version: 1.0.0, last github version: 1.0.1)

Auto-update plfit to 1.0.1

---

packages/g/glad/xmake.lua

```
add_requires("glad[loader]")
```

glad: add loader config

---

packages/o/ormpp/xmake.lua

现在的包描述,当如下引用 master 的时候会报错
```
add_requires("ormpp master", {configs={sqlite3=true}})
```
```
PS C:\Users\Administrator\temp\testormpp> x f -c -v -D
checking for platform ... windows
checking for architecture ... x64
checking for cl.exe ... C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.43.34808
checkinfo: cannot runv(nim.exe --version), No such file or directory
checking for nim ... no
checkinfo: cannot runv(nim.exe --version), No such file or directory
checking for nim ... no
checking for git ... ok
checkinfo: BusyBox v1.38.0-FRP-5579-g5749feb35 (2025-02-08 12:49:06 UTC)
Usage: gzip [-cfkdt123456789] [FILE]... …
```

make ormpp support git version

---

packages/a/aws-c-io/xmake.lua

Update aws-c-io to 0.17.0

---

packages/g/ggml/xmake.lua
packages/l/llama.cpp/xmake.lua

```lua
add_requires("ggml[openmp,cuda,vulkan]")
```
```c
#include <ggml.h>
```

ggml: add package

---

packages/n/nodesoup/xmake.lua

```lua
add_requires("nodesoupp[cmake=n]")
```
- Support shared build.
- Improve test.

nodesoup: support cmake build

---

packages/m/matplotplusplus/xmake.lua

New version of matplotplusplus detected (package version: v1.2.1, last github version: v1.2.2)

Auto-update matplotplusplus to v1.2.2

---

packages/f/fbgemm/patches/1.1.0/dep-unbundle.patch
packages/f/fbgemm/xmake.lua

New version of fbgemm detected (package version: v0.8.0, last github version: v1.1.0)

Auto-update fbgemm to v1.1.0

---

packages/t/tbox/xmake.lua

improve tbox to support cosmocc

---

packages/m/mxml/xmake.lua

New version of mxml detected (package version: 4.0.3, last github version: 4.0.4)

Auto-update mxml to 4.0.4

---

packages/a/aws-c-auth/xmake.lua
packages/a/aws-c-compression/xmake.lua
packages/a/aws-c-http/xmake.lua
packages/a/aws-c-s3/xmake.lua
packages/a/aws-c-sdkutils/xmake.lua

New version of aws-c-s3 detected (package version: v0.7.7, last github version: v0.7.12)

Auto-update aws-c-s3 to v0.7.12

---

packages/i/imgui/port/xmake.lua
packages/i/imgui/xmake.lua

try to add libsdl3 backend to imgui
#6327

Imgui backend libsdl3

---

packages/l/libmobi/xmake.lua

```lua
add_requires("libmobi[encryption,xmlwriter,libxml2,zlib,tools]")
```
```c
#include <mobi.h>
```

libmobi: add package

---

packages/r/radeonrays/xmake.lua

```lua
add_requires("radeonrays[dx12,vulkan,embedded]")
```
```c
#include <radeonrays.h>
#include <radeonrays_dx.h>
#include <radeonrays_vlk.h>
```
close https://github.com/xmake-io/xmake-repo/issues/6164

radeonrays: add package

---

.github/workflows/android.yml
packages/h/harfbuzz/xmake.lua

harfbuzz: switch to meson on Android/BSD and add 10.4.0

---

packages/n/nng/xmake.lua

upgrade nng version to 1.10.1

---

packages/r/raylib/xmake.lua

raylib: add wasm platform

---

packages/o/obfusheader.h/xmake.lua

```lua
add_requires("obfusheader.h")
```
```c++
#include <obfusheader.h>
```

obfusheader.h: add package

---

packages/d/datatype99/xmake.lua
packages/m/metalang99/xmake.lua

Its dependency also need be update: metalang99 v1.13.3 -> v1.13.5

datatype99: update to v1.6.5

---

packages/f/flatbuffers/xmake.lua
packages/l/libmysofa/xmake.lua
packages/s/steam-audio/patch.lua
packages/s/steam-audio/xmake.lua

```lua
add_requires("steam-audio[fft=pffft,mkl,embree,radeonrays]")
```
```c++
#include <phonon.h>
```
close https://github.com/xmake-io/xmake-repo/issues/6049

steam-audio: add package

---

packages/l/linux-syscall-support/xmake.lua

Update `linux-syscall-support` to `v2024.02.01`

linux-syscall-support: update to v2024.02.01

---

packages/o/osip/xmake.lua

This PR extends package `osip` to support Windows OS by `msbuild` `.sln`
Feel free to edit this PR code.
https://repology.org/project/osip/versions

osip: add windows support

---

packages/x/xapian-core/xmake.lua
packages/x/xapian/xmake.lua

https://repology.org/project/xapian-core/versions

Add xapian-core

---

packages/v/volk/xmake.lua

volk: Use cmake to build

---

packages/l/libmd/xmake.lua

libmd: add plats, update to 1.1.0

---

packages/l/libkdtree/xmake.lua

Add libkdtree

---

packages/e/elfutils/patches/0.190/configure.patch
packages/e/elfutils/xmake.lua

Resolves https://github.com/xmake-io/xmake-repo/pull/3183

Update elfutils to 0.190

---

packages/h/hpsocket/port/xmake.lua
packages/h/hpsocket/xmake.lua

Resolves https://github.com/xmake-io/xmake-repo/pull/3444 & Resolves https://github.com/xmake-io/xmake-repo/pull/5207
Note: https://developercommunity.visualstudio.com/t/error-LNK2001:-Unresolved-outer-characte/10786093?sort=active

Test hpsocket

---

packages/t/tinyspline/xmake.lua

Resolves https://github.com/xmake-io/xmake-repo/pull/3358

Add tinyspline

---

packages/l/libice/xmake.lua
packages/l/libsm/xmake.lua
packages/l/libx11/xmake.lua
packages/l/libxau/xmake.lua
packages/l/libxaw/xmake.lua
packages/l/libxcb/xmake.lua
packages/l/libxcursor/xmake.lua
packages/l/libxdamage/xmake.lua
packages/l/libxdmcp/xmake.lua
packages/l/libxfixes/xmake.lua
packages/l/libxft/xmake.lua
packages/l/libxi/xmake.lua
packages/l/libxkbcommon/xmake.lua
packages/l/libxmu/xmake.lua
packages/l/libxpm/xmake.lua
packages/l/libxshmfence/xmake.lua
packages/l/libxt/xmake.lua
packages/l/libxtst/xmake.lua
packages/l/libxv/xmake.lua
packages/l/libxvmc/xmake.lua
packages/l/libxxf86vm/xmake.lua
packages/x/xcb-proto/xmake.lua
packages/x/xcb-util-cursor/xmake.lua
packages/x/xcb-util-errors/xmake.lua
packages/x/xcb-util-image/xmake.lua
packages/x/xcb-util-keysyms/xmake.lua
packages/x/xcb-util-renderutil/xmake.lua
packages/x/xcb-util-wm/xmake.lua
packages/x/xcb-util/xmake.lua
packages/x/xtrans/xmake.lua

update x11/xcb/xkb libraries

---

packages/j/jthread/xmake.lua

jthread: Add more plats

---

packages/c/cpr/xmake.lua

Resolves https://github.com/xmake-io/xmake-repo/pull/4635
Please note that removed pthread for mingw maybe is mistake.

cpr: Add more plats

---

packages/j/jrtplib/xmake.lua

jrtplib: Add more plats

---

packages/k/khaledhosny-ots/xmake.lua

`build (ubuntu-latest, armeabi-v7a, r22, 30)`
../src/cmap.h:8:10: fatal error: 'vector' file not found
`build (arm64-v8a, r27, 30)`
43 | #   error <clocale> tried including <locale.h> but didn't find libc++'s <locale.h> header. \

khaledhosny-ots: Add new package

---

packages/s/snappy/xmake.lua

Update snappy to 1.2.2

---

packages/w/webthing-cpp/xmake.lua

Resolves https://github.com/xmake-io/xmake-repo/pull/6644

Try resolve https://github.com/xmake-io/xmake-repo/pull/6644

---

packages/w/webui/port/xmake.lua
packages/w/webui/xmake.lua

Resolves https://github.com/xmake-io/xmake-repo/pull/6727

webui: add new config

---

packages/w/webui/xmake.lua

Fixup webui

---

packages/l/libsais/xmake.lua

Related to https://github.com/xmake-io/xmake-repo/pull/4818 https://github.com/xmake-io/xmake-repo/pull/5936 https://github.com/xmake-io/xmake-repo/pull/6377

libsais: Update to v2.8.7

---

packages/l/libremidi/xmake.lua

New version of libremidi detected (package version: v4.5.0, last github version: v5.1.0)

Auto-update libremidi to v5.1.0

---

packages/a/ada/xmake.lua

ada: update to v3.2.2

---

packages/l/libbsd/xmake.lua

libbsd: update to 0.12.2

---

packages/c/cimgui/port/xmake.lua
packages/c/cimgui/xmake.lua
packages/i/imgui/port/xmake.lua
packages/i/imgui/xmake.lua

Remove vulkansdk dependency from imgui

---

packages/c/criterion/patch.lua
packages/c/criterion/xmake.lua
packages/l/libgit2/xmake.lua
packages/n/nanopb/xmake.lua

Resolves https://github.com/xmake-io/xmake-repo/pull/6482
https://reviews.freebsd.org/D30842

criterion: Add new package

---

packages/s/sheenbidi/xmake.lua

Resolves https://github.com/xmake-io/xmake-repo/pull/5643

sheenbidi: update to v2.8

---

packages/s/shadowhook/xmake.lua

shadowhook: add package

---

packages/v/vulkan-validationlayers/xmake.lua

Fix env variable for Vulkan validation layers

---

packages/e/entt/xmake.lua

Fix entt v3.14.0's patch hash

---

packages/g/glslang/xmake.lua
packages/s/spirv-headers/xmake.lua
packages/s/spirv-reflect/xmake.lua
packages/s/spirv-tools/xmake.lua
packages/v/volk/xmake.lua
packages/v/vulkan-headers/xmake.lua
packages/v/vulkan-hpp/xmake.lua
packages/v/vulkan-loader/xmake.lua
packages/v/vulkan-tools/xmake.lua
packages/v/vulkan-utility-libraries/xmake.lua
packages/v/vulkan-validationlayers/xmake.lua

Update vulkan packages to 1.4.309

---

packages/l/libassert/xmake.lua

add use_external_magic_enum config option to libassert

---

packages/g/glbinding/xmake.lua

New version of glbinding detected (package version: v3.3.0, last github version: v3.4.0)

Auto-update glbinding to v3.4.0

---

packages/g/gtest/xmake.lua

Update gtest to v1.16.0

---

packages/d/dlfcn-win32/xmake.lua

New version of dlfcn-win32 detected (package version: v1.4.1, last github version: v1.4.2)

Auto-update dlfcn-win32 to v1.4.2

---

packages/l/libcbor/xmake.lua

New version of libcbor detected (package version: v0.11.0, last github version: v0.12.0)

Auto-update libcbor to v0.12.0

---

packages/o/openal-soft/xmake.lua

New version of openal-soft detected (package version: 1.23.1, last github version: 1.24.3)

Auto-update openal-soft to 1.24.3

---

packages/m/msgpack23/xmake.lua

```lua
add_requires("msgpack23")
```
```c++
#include <msgpack23/msgpack23.h>
```

msgpack23: add package

---

packages/y/yas/xmake.lua

upgrade yas

---

packages/b/bzip2/xmake.lua

bzip2 Add download mirror

---

packages/b/boost_pfr/xmake.lua

Added Boost.pfr, a light-weight reflection library.

boost_pfr: add package

---

packages/d/dlpack/xmake.lua

dlpack: update to v1.1

---

packages/i/imath/xmake.lua
packages/o/openexr/patches/3.3.3/mingw32.patch
packages/o/openexr/xmake.lua

New version of openexr detected (package version: v3.3.2, last github version: v3.3.3)

Auto-update openexr to v3.3.3

---

packages/p/proj/patches/6.3.1/fix-dl.patch
packages/p/proj/patches/6.3.1/fixes.patch
packages/p/proj/xmake.lua

proj: add older version

---

packages/w/wayland-protocols/xmake.lua

wayland-protocols: update to v1.43

---

packages/l/lockfree/xmake.lua

```lua
add_requires("lockfree")
```
```c++
#include <lockfree/lockfree.hpp>
```

lockfree: add package

---

packages/s/socket-io-client/xmake.lua
packages/w/websocketpp/xmake.lua

```
3>ClCompile:
sio_socket.cpp
3>C:\Users\Administrator\AppData\Local\.xmake\cache\packages\2504\s\socket-io-client\2024.07.17\source\socket-io-client\src\internal\sio_client_impl.h(39,10): error
C1083: Cannot open include file: 'boost/asio/io_service.hpp': No such file or directory [C:\Users\Administrator\AppData\Local\.xmake\cache\packages\2504\s\socket 
-io-client\2024.07.17\source\socket-io-client\build_8d2e0fba\sioclient.vcxproj]
(compiling source file '../src/sio_client.cpp')
4>ClCompile:
sio_socket.cpp
4>C:\Users\Administrator\AppData\Local\.xmake\cache\packages\2504\s\socket-io-client\2024.07.17\source\socket-io-client\src\internal\sio_client_impl.h(39,10): error
C1083: Cannot open include file: 'boost/asio/io_service.hpp': No such file or directory …
```

socket-io-client: add package

---

packages/i/itlib/xmake.lua

New version of itlib detected (package version: v1.11.5, last github version: v1.11.7)

Auto-update itlib to v1.11.7

---

packages/n/nazarautils/rules/compiler_setup.lua
packages/n/nazarautils/xmake.lua

Add nazarautils

---

packages/u/upa-url/xmake.lua

New version of upa-url detected (package version: v1.2.0, last github version: v2.0.0)

Auto-update upa-url to v2.0.0

---

packages/s/stringzilla/xmake.lua

* Ensure your edited codes with four spaces instead of TAB
------
* 为了规范化提交日志的格式，commit消息，不要用中文，请用英文描述

StringZilla: update to v3.12.4

---

packages/r/reaction/xmake.lua

```lua
add_requires("reaction")
```
```c++
#include <reaction/reaction.h>
```

reaction: add package

---

packages/c/cpptrace/xmake.lua

(cpptrace) update to 0.8.3

---

packages/m/magic_enum/xmake.lua

(magic_enum) fix error when version is nill

---

packages/s/stringzilla/xmake.lua

StringZilla: update to v3.12.5

---

packages/a/astc-encoder/xmake.lua

New version of astc-encoder detected (package version: 4.8.0, last github version: 5.2.0)

Auto-update astc-encoder to 5.2.0

---

packages/s/safetyhook/xmake.lua

safetyhook: update to 0.6.6

---

packages/l/libogg/xmake.lua

libogg: update to 1.3.5

---

packages/d/duckdb/xmake.lua

This is a bug fix release for various issues discovered after we released 1.2.1. There are no new major features, just bug fixes. Database files created by DuckDB versions all the way back to v0.9.* can be read by this version.
------

Update duckdb 1.2.2

---

packages/o/osip/xmake.lua

>https://www.gnu.org/software/osip/
>>If the above links does not work, new versions of osip can be found [there](http://www.antisip.com/download/)

osip: add mirror

---

packages/a/ada/xmake.lua

ada: update to v3.2.3

---

packages/g/glslang/xmake.lua

fixes and closes https://github.com/xmake-io/xmake-repo/issues/6898

glslang: expose MachineIndependent headers

---

packages/o/openjdk/fetch.lua
packages/o/openjdk/xmake.lua

```lua
add_requires("openjdk", {system = true, kind = "library"})
```

openjdk: improve on_fetch for ubuntu

---

packages/r/robin-hood-hashing/xmake.lua
packages/v/vulkan-validationlayers/xmake.lua

vulkan-validationlayers: Fixed not being found on linux

---

packages/a/acl-dev/xmake.lua

acl-dev: update to 3.6.3

---

packages/u/ultralight/xmake.lua

TODO:
I dont know how to fix. 
Either limit by distro?
Or wait for https://gitlab.gnome.org/GNOME/at-spi2-core/-/archive/AT_SPI2_CORE_2_53_90/at-spi2-core-AT_SPI2_CORE_2_53_90.tar.gz .. ok 
https://github.com/xmake-io/xmake-repo/pull/6530 going to be fixed I guess.
Either some ext_source?

ultralight: update to 1.4.0-beta

---

packages/r/rust/xmake.lua
packages/r/rustup-init/xmake.lua
packages/r/rustup/xmake.lua

Adds a new package called "rust" that acts as the official rust toolchains

Adding rust toolchain

---

packages/u/ultralight/xmake.lua

ultralight: update to 1.4.0

---

packages/w/wayland-protocols/xmake.lua

wayland-protocols: update to v1.44

---

packages/a/automake/xmake.lua

automake: update to 1.17

---

packages/l/libtool/xmake.lua

libtool: update to 2.5.4

---

packages/c/cmake/xmake.lua

cmake: update to 4.0.1

---

packages/m/meson/xmake.lua

meson: update to 1.8.0

---

packages/e/easyhook/patches/v2.7.7097+0/fix-build.patch
packages/e/easyhook/xmake.lua

easyhook: new port

---

packages/l/lzma/xmake.lua

(because: [discord](https://discord.com/channels/785173387962089492/785369106199216130/1366866949920919653))
LZMA SDK 19.00 does not implement POSIX threads, so `_7ZIP_ST` is defined and multithreading functionality is not available on non-Windows platforms.

lzma: re-add 19.00

---

packages/v/vulkan-memory-allocator/xmake.lua

(vulkan-memory-allocator) update to 3.2.1

---

packages/p/python/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/7052

disable precompiled for python/win

---

packages/u/unicorn/xmake.lua

unicorn: update to 2.1.3

---

packages/f/flatcc/xmake.lua

trying to solve the error occurred when installing nanoarrow[ipc]
------

Update flatcc git ver

---

packages/z/zydis/xmake.lua

New version of zydis detected (package version: v4.1.0, last github version: v4.1.1)

Auto-update zydis to v4.1.1

---

packages/b/box2d/patches/3.1.0/cmake.patch
packages/b/box2d/xmake.lua

New version of box2d detected (package version: v3.0.0, last github version: v3.1.0)

Auto-update box2d to v3.1.0

---

packages/c/cxxopts/patches/missing-gcc15-header.patch
packages/c/cxxopts/xmake.lua

cxxopts: Fix compilation with gcc15

---

packages/w/winpixevent/xmake.lua

winpixevent: add package

---

packages/y/yaml-cpp/patches/missing-gcc15-header.diff
packages/y/yaml-cpp/xmake.lua

https://bugs.gentoo.org/937412

yaml-cpp: Fix compilation with gcc15

---

packages/w/woff2/patches/missing-gcc15-header.diff
packages/w/woff2/xmake.lua

https://github.com/google/woff2/pull/176

woff2: Fix compilation with gcc15

---

packages/y/yasm/patches/fix-bool-gcc15.diff
packages/y/yasm/patches/upd-min-cmake.diff
packages/y/yasm/xmake.lua

https://github.com/yasm/yasm/issues/283#issuecomment-2661108816
https://github.com/yasm/yasm/pull/287/files

yasm: fix gcc 15 build `std=c23`

---

.github/workflows/mingw_macos.yml
packages/m/mcfgthread/xmake.lua

2.1.1 version require https://github.com/xmake-io/xmake/pull/6408 & https://github.com/xmake-io/xmake/pull/6410

mcfgthread: add 2.1.1

---

packages/l/libxkbcommon/xmake.lua

(libxkbcommon) fix package when using x11

---

packages/l/libjpeg-turbo/xmake.lua

(libjpeg-turbo) fix runtime checking

---

packages/l/libxkbcommon/xmake.lua

quick fix for little fail from https://github.com/xmake-io/xmake-repo/pull/7100

(libxkbcommon) table.ipair => ipairs

---

packages/n/nanobind/xmake.lua

Update nanobind 2.7.0

---

packages/x/xtl/xmake.lua

xtl: update to v0.8.0

---

packages/l/libdivide/xmake.lua

libdivide: update to v5.2.0

---

packages/m/mbedtls/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/7127

mbedtls: fix url

---

packages/z/zmqpb/xmake.lua

since none of the deps are marked as such

zmqPb is not windows-native only

---

packages/r/replxx/xmake.lua

replxx: add package

---

packages/v/vulkanscenegraph/xmake.lua

version update and version-dependent config additions.

vulkanscenegraph: add v1.1.10

---

packages/p/pcapplusplus/xmake.lua

https://github.com/seladb/PcapPlusPlus/issues/1713
能有效减小程序体积

add compile time log level setting to pcapplusplus

---

packages/g/glfw3webgpu/xmake.lua

glfw3webgpu: update to v1.3.0-alpha

---

packages/a/ace/xmake.lua

todo: tao_idl for linux/os x in next pr

ace: add BSD/Linux/OS X platform

---

packages/j/jansson/xmake.lua

New version of jansson detected (package version: 2.14, last github version: 2.14.1)

Auto-update jansson to 2.14.1

---

packages/x/xgrammar/port/xmake.lua
packages/x/xgrammar/xmake.lua

Source code [here](https://github.com/mlc-ai/xgrammar). Hope this could be helpful for LLM developers.
It's my first time writing an xmake package, following the steps in [this article](https://zhuanlan.zhihu.com/p/651108523). I'm still learning, so any suggestions or feedback to help improve the code would be greatly appreciated!
------
* …

Add xgrammar package

---

packages/s/sqlite3/xmake.lua

update sqlite3 to 3.49.2

---

packages/u/usrsctp/xmake.lua
packages/w/wineditline/patches/2.208/build.diff
packages/w/wineditline/xmake.lua

https://github.com/msys2/MINGW-packages/blob/7a04b83222059ad648d6bcded62d5540b34ddf96/mingw-w64-wineditline/PKGBUILD#L3

wineditline: add new package

---

packages/v/vladimirshaleev-ipaddress/xmake.lua

New version of vladimirshaleev-ipaddress detected (package version: v1.1.0, last github version: v1.2.0)

Auto-update vladimirshaleev-ipaddress to v1.2.0

---

packages/a/ace/xmake.lua
packages/k/kokyu/xmake.lua

kokyu: add new package

---

packages/s/sqlite3-lemon/xmake.lua

https://archlinux.org/packages/core/x86_64/lemon/
TODO: limit platforms.

sqlite3-lemon: add new package

---

packages/l/luasocket/xmake.lua

Yet I do not know how to fix linux linkdir.

luasocket: new package

---

packages/l/libomp/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/7206
adds OpenMP support for android NDK

libomp: add android

---

packages/g/glfw3webgpu/xmake.lua

Since v1.3.0-alpha changed some defines, I have added them.
------

glfw3webgpu: Add defines depending on platform

---

packages/m/meson/xmake.lua

meson: Fix 1.8.1 file hash

---

.github/workflows/macos_arm64.yml
.github/workflows/macos_x86_64.yml
packages/s/screen_capture_lite/xmake.lua
packages/u/uasm/patches/fix-bool.diff
packages/u/uasm/patches/fix-build.diff
packages/u/uasm/patches/fix-esc-seq.diff
packages/u/uasm/patches/uint64-fix.diff
packages/u/uasm/ports/osx64.mak
packages/u/uasm/xmake.lua

1. How to support Mac OS @ MinGW, since Windows @ MinGW works? Is it expect Mac OS to be supported platform (it looks like Mac OS @ MinGW is just rely over Mac OS solution I guess, but why it does not use MinGW)?
2. I still believe Github CI log should show us compiled program test output though (for Mac OS), for some reason Github CI often truncate output of on_test... I often misunderstand why it does not provide on_test output, but outputs `OK`, in theory it is working because expected return code of executed program is met.

uasm: add package

---

packages/o/openmp/xmake.lua

fix https://github.com/xmake-io/xmake-repo/issues/7231

openmp: add cuda support

---

packages/t/tinymcp/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/10#issuecomment-2922385618
> Model Context Protocol SDK for C++
> https://github.com/Qihoo360/TinyMCP

tinymcp: new package

---

packages/l/lsp-framework/patches/1.0.1/fix-install.diff
packages/l/lsp-framework/patches/1.0.1/fix-missing-ios.diff
packages/l/lsp-framework/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/10#issuecomment-2923102205
> LSP framework written in C++
> https://github.com/leon-bckl/lsp-framework

lsp-framework: new package

---

packages/g/glosshook/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/10#issuecomment-2906373249
>Android Hook Library GlossHook
>https://github.com/XMDS/GlossHook

glosshook: new package

---

packages/l/libyaml/xmake.lua

https://github.com/xmake-io/xmake/discussions/6515

libyaml: add_extsources pkgconfig::yaml-0.1

---

packages/m/msdf-atlas-gen/xmake.lua
packages/m/msdfgen/xmake.lua

msdf-atlas-gen: new package

---

packages/l/lief/xmake.lua

lief: update to 0.16.6

---

packages/c/cpu-features/xmake.lua

New version of cpu-features detected (package version: v0.9.0, last github version: v0.10.0)

Auto-update cpu-features to v0.10.0

---

packages/t/ta-lib/xmake.lua

update ta-lib homepage

---

packages/l/libjq/xmake.lua

update libjq to 1.8.0

---

packages/e/etl/xmake.lua

etl: update to v20.41.4

---

packages/l/lodepng/xmake.lua

adds cpp config for `lodepng` package
https://github.com/xmake-io/xmake-repo/issues/7298

lodepng: add cpp config

---

packages/f/ftxui/port/xmake.lua
packages/f/ftxui/xmake.lua

ftxui: Add modules support

---

packages/l/libhv/xmake.lua

libhv debundle nlohmann_json 
https://github.com/xmake-io/xmake-repo/issues/7288

libhv: debundle nlohmann_json

---

packages/s/sqlite3/xmake.lua

Sqlite3: update to v3.50.1

---

packages/q/qjson/xmake.lua

qjson: add new package

---

packages/b/base64-terrakuh/xmake.lua
packages/b/base64/xmake.lua

Needs for `cpp-mcp` https://github.com/hkr04/cpp-mcp

base64-terrakuh: add new package

---

packages/c/cpp-mcp/patches/2025.05.24/install.diff
packages/c/cpp-mcp/xmake.lua
packages/p/pkgconf/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/10#issuecomment-2963104322

cpp-mcp: add new package

---

packages/c/cpptrace/xmake.lua

cpptrace: update to v1.0.0

---

packages/b/blobify/xmake.lua

blobify: add package

---

packages/l/libharu/xmake.lua

libharu: update to 2.4.5

---

packages/s/snowhouse/xmake.lua

snowhouse: add new package

---

packages/l/libnpy-matajoh/patches/v1.5.3/fix.diff
packages/l/libnpy-matajoh/xmake.lua

libnpy-matajoh: new package

---

packages/l/libgit2/xmake.lua

libgit2: update to 1.9.1

---

packages/o/openjpeg/xmake.lua

openjpeg: update to 2.5.3

---

packages/w/wayland-protocols/xmake.lua

wayland-protocols: update to v1.45

---

packages/j/json.h/xmake.lua

json.h: update to 2024.07.19

---

packages/m/mapbox_earcut/xmake.lua

https://github.com/mapbox/earcut.hpp/pull/120

mapbox_earcut: fix GCC15

---

packages/p/phnt/xmake.lua

phnt: update to 2025.05.25

---

packages/w/webdriverxx/patches/2025.03.20/picojson.diff
packages/w/webdriverxx/xmake.lua

webdriverxx: update to 2025.03.20

---

.github/workflows/android.yml
.github/workflows/android_windows.yml
packages/a/aws-lc/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/7413#issuecomment-2982434429

add ndk cache for ci

---

packages/l/libtcod/patches/2.1.1/debundle.diff
packages/l/libtcod/xmake.lua
packages/u/utf8proc/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/10#issuecomment-2975601644
I create issue https://github.com/libtcod/libtcod/issues/163 & PR https://github.com/libtcod/libtcod/pull/164
1. Improve utf8proc by adding cmake support
2. Add libtcod package

libtcod: add package

---

packages/h/hwinfo/xmake.lua

hwinfo: add new package

---

packages/a/abseil/xmake.lua

patch during on_install to one of the source file to include `__APPLE__` platform macro detection
------

fix: abseil macos broken build

---

packages/i/ispc/xmake.lua

Update ISPC to V1.27.0

---

packages/l/liblemon/patches/1.3.1/cmake-add-runtime-install-destination.patch
packages/l/liblemon/patches/1.3.1/cpp17-compat-remove-register-keyword.patch
packages/l/liblemon/xmake.lua

Supposed to be part of OpenMVG dependencies.

liblemon: add package

---

packages/a/abseil/xmake.lua

fix(abseil): compile error for abseil 20250512.1 in macosx

---

packages/a/alsa-lib/xmake.lua

alsa-lib: add missing m links

---

packages/s/safetyhook/xmake.lua

safetyhook: update to v0.6.7

---

packages/f/fcpw/xmake.lua

fcpw: update to v1.2.0

---

packages/l/libsndio/xmake.lua

fix libsndio

---

packages/s/stringbuilder/xmake.lua

stringbuilder: fix GCC15

---

packages/w/w64devkit/xmake.lua

w64devkit: update to 2.3.0

---

packages/s/swisseph/xmake.lua

swisseph: add more plats

---

packages/c/cmidi2/xmake.lua

cmidi2: update to 2025.06.25

---

packages/c/cpp-async/xmake.lua

cpp-async: update to v1.2.0

---

packages/p/ppqsort/xmake.lua

ppqsort: add package

---

packages/r/re2/xmake.lua

re2: update to 2025-06-26b

---

packages/e/eabase/patches/2.09.05/add-arm64-windows.patch
packages/e/eabase/xmake.lua

eabase: add more platforms

---

packages/w/workflow/xmake.lua

Add workflow v0.11.9.

---

packages/b/bass24/xmake.lua

Maybe first package to be used as `iOS Framework` so far.
I dont know what license here.

bass24: new package

---

packages/f/flecs/xmake.lua

Update flecs to 4.1.0

---

packages/c/coin-or-coinutils/xmake.lua
packages/c/coin-or-osi/xmake.lua

https://anaconda.org/IBMDecisionOptimization/cplex
gurobi looks somewhat closed source dep that requires lic key to use.
https://anaconda.org/MOSEK/mosek
I think soplex package should be improved, but that would require to make gmp package to work on windows.
Glpk has some c20/c23 problem so it wont be built.

coin-or-osi: add new package

---

packages/r/rapidcsv/xmake.lua

rapidcsv: update to v8.87

---

packages/i/idna/xmake.lua

idna: update to 0.3.4

---

packages/q/qoi/xmake.lua

qoi: update to 2025.06.18

---

packages/o/optional-lite/xmake.lua

optional-lite: update to v3.6.0

---

packages/c/croaring/xmake.lua

New version of croaring detected (package version: v4.1.7, last github version: v4.3.5)

Auto-update croaring to v4.3.5

---

packages/l/libdisplay-info/xmake.lua

libdisplay-info: add package

---

packages/a/audiofile/xmake.lua

audiofile: update to v1.1.3

---

packages/s/sfml/xmake.lua

sfml: update to 3.0.1

---

packages/i/imgui-color-text-edit/xmake.lua

https://github.com/BalazsJako/ImGuiColorTextEdit/issues/158

imgui-color-text-edit: fix imgui version

---

packages/l/lunasvg/xmake.lua

New version of lunasvg detected (package version: v3.2.0, last github version: v3.3.0)

Auto-update lunasvg to v3.3.0

---

packages/a/angelscript/port/xmake.lua
packages/a/angelscript/xmake.lua
packages/a/asbind20/xmake.lua

asbind20: add package

---

packages/t/trantor/xmake.lua

See https://github.com/xmake-io/xmake-repo/pull/7504

trantor: fix find openssl

---

packages/k/kittymemory/xmake.lua

kittymemory: add new package

---

packages/s/simdutf/xmake.lua

New version of simdutf detected (package version: v7.3.2, last github version: v7.3.3)

Auto-update simdutf to v7.3.3

---

packages/o/oboe/xmake.lua

oboe: add new package

---

packages/l/libplist/xmake.lua

New version of libplist detected (package version: 2.6.0, last github version: 2.7.0)

Auto-update libplist to 2.7.0

---

packages/x/xtensor/xmake.lua

New version of xtensor detected (package version: 0.25.0, last github version: 0.26.0)

Auto-update xtensor to 0.26.0

---

packages/b/bddisasm/xmake.lua

New version of bddisasm detected (package version: v2.2.0, last github version: v3.0.0)

Auto-update bddisasm to v3.0.0

---

packages/a/asbind20/xmake.lua

asbind20: update to 1.7.0

---

packages/l/libyuv/patches/1913/cmake.patch
packages/l/libyuv/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/7676

libyuv: add 1913 version

---

packages/s/speex/patches/1.2.1/filter-subdirs.patch
packages/s/speex/patches/1.2.1/fix-ac-compile-ifelse.patch
packages/s/speex/xmake.lua

I assume it is part of pulseaudio.

speex: add new package

---

packages/s/samurai/xmake.lua
packages/x/xtensor/xmake.lua

New version of samurai detected (package version: v0.23.0, last github version: v0.25.1)

Auto-update samurai to v0.25.1

---

packages/f/function2/xmake.lua

New version of function2 detected (package version: 4.2.4, last github version: 4.2.5)

Auto-update function2 to 4.2.5

---

packages/l/libflac/patches/1.5.0/fix-cmake-in.patch
packages/l/libflac/xmake.lua
packages/l/libsdl2/patches/2.32.2/fix-arm64.patch
packages/l/libsdl2/xmake.lua
packages/l/libsdl2_mixer/xmake.lua

Validate and repair FLAC::FLAC.
Part of pulseaudio PR.
https://github.com/xmake-io/xmake-repo/pull/7695

libsdl2_mixer: add FLAC option and validate FLAC::FLAC CMakeConfig

---

packages/h/h3/patches/v4.3.0/fix-m-lib.diff
packages/h/h3/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/10#issuecomment-3116454151

h3: add new package

---

packages/o/openssl3/xmake.lua

https://discourse.cmake.org/t/findopenssl-cmake-does-not-search-lib64-directory/9429

openssl3: fix find by cmake

---

packages/p/plutovg/xmake.lua

New version of plutovg detected (package version: v1.1.0, last github version: v1.3.0)

Auto-update plutovg to v1.3.0

---

packages/g/glfw3webgpu/xmake.lua

glfw3webgpu: add defines on package loading

---

packages/s/simdutf/xmake.lua

New version of simdutf detected (package version: v7.3.3, last github version: v7.3.4)

Auto-update simdutf to v7.3.4

---

packages/a/amgcl/xmake.lua

New version of amgcl detected (package version: 1.4.4, last github version: 1.4.5)

Auto-update amgcl to 1.4.5

---

packages/c/cdt/xmake.lua

New version of cdt detected (package version: 1.4.1, last github version: 1.4.4)

Auto-update cdt to 1.4.4

---

packages/a/async_simple/xmake.lua

New version of async_simple detected (package version: 1.3, last github version: 1.4)

Auto-update async_simple to 1.4

---

packages/x/xz/xmake.lua

fix xz build with asan:y

---

packages/c/cppitertools/xmake.lua

cppitertools: update to v2.3

---

packages/p/protobuf-cpp/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/7846

protobuf-cpp: fix build with c++ language

---

packages/s/stringzilla/xmake.lua

stringzilla: update to v3.12.6

---

packages/e/emscripten/xmake.lua

update emcc 4.0.12

---

packages/g/go/xmake.lua

go: support more platforms

---

packages/i/implot/xmake.lua

https://github.com/epezent/implot/issues/632

implot: fix build

---

packages/z/zig/xmake.lua

zig: update to v0.15.1

---

packages/c/concerto-core/xmake.lua

concerto-core

---

packages/c/cimg/xmake.lua

CImg: update to v3.6.0

---

packages/l/libavif/xmake.lua

https://github.com/xmake-io/xmake-repo/issues/7955

libavif: fix deps

---

packages/l/libbpf/xmake.lua

Reverts xmake-io/xmake-repo#7975

Revert "libbpf: try to fix build"

---

packages/u/usd/xmake.lua

New version of usd detected (package version: v25.05.01, last github version: v25.08)

Auto-update usd to v25.08

---

packages/e/elfutils/patches/0.183/libelf-map.patch
packages/e/elfutils/patches/0.189/libelf-map.patch
packages/e/elfutils/xmake.lua

elfutils: fix Android

---

packages/l/lz4/xmake.lua

https://github.com/xmake-io/xmake-repo/pull/7999 require

lz4: add cmake support

---

packages/c/c-blosc2/xmake.lua

New version of c-blosc2 detected (package version: v2.21.0, last github version: v2.21.1)

Auto-update c-blosc2 to v2.21.1

---

packages/l/librats/xmake.lua

New version of librats detected (package version: 0.1.5, last github version: 0.2.1)

Auto-update librats to 0.2.1

---

packages/p/poselib/xmake.lua

New version of poselib detected (package version: v2.0.4, last github version: v2.0.5)

Auto-update poselib to v2.0.5

---

packages/m/muslcc/xmake.lua

fix muslcc

---

packages/e/etl/xmake.lua

etl: update to v20.43.1

---

packages/d/dlib/xmake.lua

dlib: png config was used incorrectly in place of jpg

---

packages/e/emock/patches/v0.9.0/fix_mingw_and_install.diff
packages/e/emock/patches/v0.9.0/support_multiplat_and_fix_install.diff
packages/e/emock/xmake.lua

#8065
further work: its dependence `cpputest`. I start school tomorrow, maybe in a day or two

emock: Add new package

---

packages/l/libopus/patches/1.5.2/add-sse4.1-flag-when-using-clang-cl.patch
packages/l/libopus/xmake.lua

- Fix git tag version
- Fix clang-cl, refer https://github.com/conan-io/conan-center-index/pull/28300
- Add extsources
- Fix `OPUS_PACKAGE_VERSION`

libopus: fix clang-cl build

---

packages/e/etl/xmake.lua

etl: update to v20.43.4

---

packages/w/workflow/xmake.lua

New version of workflow detected (package version: v0.11.9, last github version: v0.11.11)

Auto-update workflow to v0.11.11

---

packages/d/dr_wav/xmake.lua

New version of dr_wav detected (package version: 0.13.17, last github version: 0.14.1)

Auto-update dr_wav to 0.14.1

---

packages/l/libselinux/xmake.lua
packages/l/libsemanage/xmake.lua
packages/l/libsepol/xmake.lua

selinux: fix pkg-config.

---

packages/c/cista/xmake.lua

cista: fix build

---

packages/f/freetype/xmake.lua

freetype: update to 2.14.1 and fix issue with shared dep on Windows

---

CONTRIBUTING.md
README.md
README_zh.md

Update README and CONTRIBUTING

---

packages/n/ncnn/xmake.lua

- add `c_api` config
- `protobuf-cpp`: only used by `tools` which are disabled, so remove
- `glslang`: only used when enabling vulkan support, so `add_deps` moved to `on_load`

ncnn: improve and update

---

packages/h/hyperscan/xmake.lua

hyperscan: fix boost dependency config

---

packages/s/seqan3/xmake.lua

seqan3: fix build

---

packages/c/cpp-jwt/xmake.lua

New version of cpp-jwt detected (package version: v1.5, last github version: v1.5.1)

Auto-update cpp-jwt to v1.5.1

---

packages/a/abseil/xmake.lua

abseil: update to 20250814.1

---

packages/d/dbus-cxx/xmake.lua
packages/l/libuv/xmake.lua

https://github.com/aui-framework/aui/pull/635
Drop `libuv-static.pc`/`libuv.pc` provided by libuv `CMakeLists.txt`, keep only `libuv.pc` that is being generated by XMake to repair existing .pc.

dbus-cxx: add package

---

packages/g/glgpuselect/xmake.lua

Update glgpuselect package: add version 0.1.3

---

packages/x/xproperty/xmake.lua

#8306 
```
error: @programdir/core/sandbox/modules/os.lua:273: CMake Error at CMakeLists.txt:39 (find_package):
```

xproperty: update to 0.12.1

---

packages/b/brpc/patches/1.14.1/cmake.patch
packages/b/brpc/xmake.lua

Fixes #8033
Fixes #7211 
Fixes #6254 
Fixes #5651

brpc: fix build

---

packages/m/mariadb-connector-c/xmake.lua

Fixes #4550 
Fixes #5317 
Fixes #5710 
Fixes #5756 
Fixes #6358 
Fixes #7498 
Fixes #8325

mariadb-connector-c: fix build

---

packages/a/arrayfire/xmake.lua

waiting for 
- https://github.com/xmake-io/xmake/issues/6680
- https://github.com/xmake-io/xmake-repo/pull/7824

arrayfire: add package.

---

packages/c/cpptrace/xmake.lua

Add libunwind support to cpptrace

---

packages/p/polyscope/xmake.lua

update polyscope v.2.5.0 version

update polyscope v2.5.0
