packages/a/amqp-cpp/xmake.lua
New version of amqp-cpp detected (package version: v4.3.26, last github version: v4.3.27)
=> Auto-update amqp-cpp to v4.3.27

packages/h/highfive/xmake.lua
New version of highfive detected (package version: v2.10.0, last github version: v2.10.1)
=> Auto-update highfive to v2.10.1

packages/g/gyp-next/xmake.lua
New version of gyp-next detected (package version: v0.18.3, last github version: v0.19.1)
=> Auto-update gyp-next to v0.19.1

packages/h/highs/xmake.lua
New version of highs detected (package version: v1.8.1, last github version: v1.9.0)
=> Auto-update highs to v1.9.0

packages/p/polyscope/xmake.lua
Polyscope Officially Support ImGui Version is 1.90.4
It has Compilation Error When Using Latest ImGui=1.91.6
So, In this Commit, Limit ImGui Version to 1.90.4 For Polyscope > 2.2.0
=> Limit ImGui <=1.90.4 to Polyscope > 2.2.0

packages/x/xxhash/xmake.lua
New version of xxhash detected (package version: v0.8.2, last github version: v0.8.3)
=> Auto-update xxhash to v0.8.3

packages/x/x265/xmake.lua
- Improve numa deps.
- Add vmaf config.
- Remove unused code.
=> x265: improve numa deps

packages/l/libsdl_image/xmake.lua
New version of libsdl_image detected (package version: 2.8.3, last github version: 2.8.4)
=> Auto-update libsdl_image to 2.8.4

packages/s/simdjson/xmake.lua
New version of simdjson detected (package version: v3.11.2, last github version: v3.11.3)
=> Auto-update simdjson to v3.11.3

packages/c/cutlass/xmake.lua
New version of cutlass detected (package version: v3.5.1, last github version: v3.6.0)
=> Auto-update cutlass to v3.6.0

packages/g/grpc/xmake.lua
New version of grpc detected (package version: v1.68.2, last github version: v1.69.0)
=> Auto-update grpc to v1.69.0

packages/t/ta-lib/port/xmake.lua, packages/t/ta-lib/xmake.lua
=> add ta-lib

packages/j/jsoncons/xmake.lua
New version of jsoncons detected (package version: v0.178.0, last github version: v1.0.0)
=> Auto-update jsoncons to v1.0.0

packages/b/boost/libs.lua
asio depends on date_time, but date_time depends on container, exception, regex.
Without this fix, boost asio fails to use in project:
```log
error: In file included from tcp_server/connection.cpp:2:
In file included from tcp_server/connection.hpp:5:
In file included from /Users/yhsb/.xmake/packages/b/boost/1.87.0/ca26f133eba24e8295bc2dae086e8311/include/boost/asio.hpp:33:
In file included from /Users/yhsb/.xmake/packages/b/boost/1.87.0/ca26f133eba24e8295bc2dae086e8311/include/boost/asio/basic_deadline_timer.hpp:27:
In file included from /Users/yhsb/.xmake/packages/b/boost/1.87.0/ca26f133eba24e8295bc2dae086e8311/include/boost/asio/detail/deadline_timer_service.hpp:31:
In file included from /Users/yhsb/.xmake/packages/b/boost/1.87.0/ca26f133eba24e8295bc2dae086e8311/include/boost/asio/detail …
```
=> Fix boost asio build

packages/x/xsimd/xmake.lua
New version of xsimd detected (package version: 13.0.0, last github version: 13.1.0)
=> Auto-update xsimd to 13.1.0

packages/a/aws-c-common/xmake.lua
New version of aws-c-common detected (package version: v0.10.3, last github version: v0.10.6)
=> Auto-update aws-c-common to v0.10.6

packages/a/annoy/xmake.lua
New version of annoy detected (package version: v1.17.2, last github version: v1.17.3)
=> Auto-update annoy to v1.17.3

packages/p/plutosvg/xmake.lua
New version of plutosvg detected (package version: v0.0.3, last github version: v0.0.4)
=> Auto-update plutosvg to v0.0.4

packages/p/pyincpp/xmake.lua
New version of pyincpp detected (package version: v2.5.2, last github version: v2.6.0)
=> Auto-update pyincpp to v2.6.0

packages/z/zxing-cpp/xmake.lua
New version of zxing-cpp detected (package version: v2.2.1, last github version: v2.3.0)
=> Auto-update zxing-cpp to v2.3.0

packages/a/aws-crt-cpp/xmake.lua
New version of aws-crt-cpp detected (package version: v0.29.5, last github version: v0.29.8)
=> Auto-update aws-crt-cpp to v0.29.8

packages/l/libdeflate/xmake.lua
New version of libdeflate detected (package version: v1.22, last github version: v1.23)
=> Auto-update libdeflate to v1.23

packages/f/ffmpeg/xmake.lua
- Fix msys2 make build.
- Fix msvc ucrt.
- Remove unsupported flags for android r27.
- Fix windows cross-compilation
=> ffmpeg: Fix build on msys2

packages/n/nuklear/xmake.lua
New version of nuklear detected (package version: 4.12.2, last github version: 4.12.3)
=> Auto-update nuklear to 4.12.3

packages/l/libgit2/xmake.lua
- Use openssl3 on wasm plat.
- Remove unused code on windows plat.
=> libgit2: Support wasm

packages/c/cunit/xmake.lua
try to build shared cunit
Yet, need create export surface if something missing that needs ```CU_EXPORT``` before function definition. I dont know what exactly could be missing so let me know if that needs, like ```wxWidget.h``` functions or some struct in ```TestDB.h```, hence it is relying over static preprocessor during static lib build, not ```define CU_EXPORT declspec(dllimport)``` but ```define CU_EXPORT```
Since it is already placed where it is expected to be, but yet I do not believe it is good to do so, though just decide to keep it static only or not, any decision is good.
<details><summary>dumpbin /EXPORTS cunit.lib</summary>
<p>
dumpbin /EXPORTS cunit.lib
Microsoft (R) COFF/PE Dumper Version 14.33.31629.0
Copyright (C) Microsoft Corporation.  All rights reserved.
Dump of file …
=> try to build shared cunit

packages/s/sentry-native/xmake.lua
New version of sentry-native detected (package version: 0.7.16, last github version: 0.7.17)
=> Auto-update sentry-native to 0.7.17

packages/l/libwfkafka/xmake.lua
New version of libwfkafka detected (package version: v0.11.5, last github version: v0.11.7)
=> Auto-update libwfkafka to v0.11.7

packages/x/xxhash/xmake.lua
- Add new config
- cmake
- dispatch
- Generate `libxxhash.pc` instead of `xxhash.pc` when xmake build.
=> xxhash: Support shared build

packages/c/cnats/patches/3.9.1/fix-cmake-mingw.patch, packages/c/cnats/xmake.lua
New version of cnats detected (package version: v3.8.2, last github version: v3.9.2)
=> Auto-update cnats to v3.9.2

packages/l/libsdl_image/xmake.lua
just noticed that it didn't install on my machine because of sha mismatch, should've been caught by CI before though
=> fix libsdl_image 2.8.4 sha256

packages/l/libtorch/xmake.lua
pytorch introduces NVTX3 as a git submodule since pytorch 2.4.1. Therefore, we do not need to add NVTX as deps any more since v2.4.1.
从2.4.1版本开始，pytorch开始将NVTX以Git submodule的形式引入，因此无需再将NVTX作为deps。
=> libtorch: remove nvtx dependency since v2.5.0

packages/s/sse2neon/xmake.lua
New version of sse2neon detected (package version: v1.7.0, last github version: v1.8.0)
=> Auto-update sse2neon to v1.8.0

packages/b/barkeep/xmake.lua
New version of barkeep detected (package version: v0.1.4, last github version: v0.1.5)
=> Auto-update barkeep to v0.1.5

packages/j/jsoncons/xmake.lua
New version of jsoncons detected (package version: v1.0.0, last github version: v1.1.0)
=> Auto-update jsoncons to v1.1.0

packages/a/aws-c-sdkutils/xmake.lua
New version of aws-c-sdkutils detected (package version: v0.2.1, last github version: v0.2.2)
=> Auto-update aws-c-sdkutils to v0.2.2

packages/s/spectra/xmake.lua
New version of spectra detected (package version: v1.0.1, last github version: v1.1.0)
=> Auto-update spectra to v1.1.0

packages/q/qt6base/xmake.lua, packages/q/qt6lib/xmake.lua
https://github.com/xmake-io/xmake-repo/issues/6189
Tested build on Apple M4:
```sh
checking for platform ... macosx
checking for architecture ... arm64
checking for Xcode directory ... %s
checking for Codesign Identity of Xcode ... no
=> install qt6base 6.8.0 .. ok
=> install qt6core 6.8.0 .. ok
=> install qt6network 6.8.0 .. ok
=> install qt6gui 6.8.0 .. ok
=> install qt6widgets 6.8.0 .. ok
[ 28%]: compiling.qt.moc main_window.hpp
[ 42%]: cache compiling.debug main.cpp
[ 57%]: cache compiling.debug main_window.cpp
[ 71%]: compiling.qt.qrc resources.qrc
[ 85%]: linking.debug qt-app
[100%]: generating.qt.app qt-app.app
create ok!
compile_commands.json updated!
[100%]: build ok, spent 7.001s
```
=> Enable Qt6 for macOS arm64

packages/o/oniguruma/xmake.lua
New version of oniguruma detected (package version: v6.9.9, last github version: v6.9.10)
=> Auto-update oniguruma to v6.9.10

packages/c/cutlass/xmake.lua
New version of cutlass detected (package version: v3.6.0, last github version: v3.7.0)
=> Auto-update cutlass to v3.7.0

packages/c/catch2/xmake.lua
New version of catch2 detected (package version: v3.7.1, last github version: v3.8.0)
=> Auto-update catch2 to v3.8.0

packages/c/cpp-httplib/xmake.lua
New version of cpp-httplib detected (package version: v0.18.3, last github version: v0.18.5)
=> Auto-update cpp-httplib to v0.18.5

packages/h/harfbuzz/xmake.lua
New version of harfbuzz detected (package version: 10.1.0, last github version: 10.2.0)
=> Auto-update harfbuzz to 10.2.0

packages/v/verilator/xmake.lua
New version of verilator detected (package version: v5.016, last github version: v5.032)
=> Auto-update verilator to v5.032

packages/r/reflect-cpp/patches/0.16.0/cmake.patch, packages/r/reflect-cpp/xmake.lua
=> fix reflect-cpp compilation when msgpack is enabled

packages/v/verilator/xmake.lua
添加 verilator v5.024 和 v5.032 支持
https://github.com/verilator/verilator/commit/f56f3182176c967d9f14861e38563177ab2295f0 添加了 VERILATOR_ROOT  环境变量的检查，如果与脚本所在目录不符合会报错，将条件替换为 true 跳过检查
=> fix: bypass verilator root check

packages/o/orc/xmake.lua
New version of orc detected (package version: v2.0.3, last github version: v2.1.0)
=> Auto-update orc to v2.1.0

packages/l/libzip/xmake.lua
New version of libzip detected (package version: v1.11.2, last github version: v1.11.3)
=> Auto-update libzip to v1.11.3

packages/c/cpp-rotor/xmake.lua
New version of cpp-rotor detected (package version: v0.31, last github version: v0.32)
=> Auto-update cpp-rotor to v0.32

packages/a/arduinojson/xmake.lua
New version of arduinojson detected (package version: v7.2.1, last github version: v7.3.0)
=> Auto-update arduinojson to v7.3.0

packages/i/ittapi/xmake.lua
New version of ittapi detected (package version: v3.25.3, last github version: v3.25.4)
=> Auto-update ittapi to v3.25.4

packages/q/qt-tools/xmake.lua, packages/q/qt6lib/xmake.lua, packages/q/qtbase/xmake.lua
This PR improves cross-compilation workflows by introducing a new `qt-tools` package, which provides the essential host tools required for building Qt applications in cross-compilation environments.
For a simple Qt Widgets application created using the command:
```bash
xmake create -l c++ -t qt.widgetapp
```
Update the `xmake.lua` file as follows:
```diff
add_rules("mode.debug", "mode.release")
+ add_requires("qt6widgets")
target("test")
add_rules("qt.widgetapp")
+   add_packages("qt6widgets")
add_headerfiles("src/*.h")
add_files("src/*.cpp")
add_files("src/mainwindow.ui")
-- Add files with Q_OBJECT meta (only for qt.moc)
add_files("src/mainwindow.h")
```
To build the project for MinGW on Linux, run:
```bash
xmake f -c -vD -p mingw
```
This command will automatically install all required …
=> Qt: enhance cross-compilation support for desktop platforms

packages/d/dispenso/xmake.lua
New version of dispenso detected (package version: v1.3.0, last github version: v1.4.0)
=> Auto-update dispenso to v1.4.0

packages/u/ufbx/xmake.lua
Install the files under the "extra" folder for convenient use in C++ project and others.
=> ufbx: install extra files to includedir

packages/b/box2d/xmake.lua
- This change fixes box2d build when using commit hash as package version
=> Fix box2d build when using commit hash as version

packages/y/yoga/xmake.lua
New version of yoga detected (package version: v3.2.0, last github version: v3.2.1)
=> Auto-update yoga to v3.2.1

packages/a/aws-c-sdkutils/xmake.lua
New version of aws-c-sdkutils detected (package version: v0.2.2, last github version: v0.2.3)
=> Auto-update aws-c-sdkutils to v0.2.3

packages/c/cgns/xmake.lua
New version of cgns detected (package version: v4.4.0, last github version: v4.5.0)
=> Auto-update cgns to v4.5.0

packages/f/frugally-deep/xmake.lua
New version of frugally-deep detected (package version: v0.16.0, last github version: v0.16.2)
=> Auto-update frugally-deep to v0.16.2

packages/r/reflect-cpp/xmake.lua
New version of reflect-cpp detected (package version: v0.16.0, last github version: v0.17.0)
=> Auto-update reflect-cpp to v0.17.0

packages/l/libassert/xmake.lua
New version of libassert detected (package version: v2.1.2, last github version: v2.1.4)
=> Auto-update libassert to v2.1.4

packages/l/libxmake/xmake.lua
New version of libxmake detected (package version: v2.9.6, last github version: v2.9.7)
=> Auto-update libxmake to v2.9.7

packages/t/tinygltf/xmake.lua
New version of tinygltf detected (package version: v2.9.3, last github version: v2.9.5)
=> Auto-update tinygltf to v2.9.5

packages/p/protobuf-cpp/xmake.lua
New version of protobuf-cpp detected (package version: 29.2, last github version: 29.3)
=> Auto-update protobuf-cpp to 29.3

packages/l/libuv/xmake.lua
New version of libuv detected (package version: v1.49.2, last github version: v1.50.0)
=> Auto-update libuv to v1.50.0

packages/b/bzip3/xmake.lua
New version of bzip3 detected (package version: 1.4.0, last github version: 1.5.1)
=> Auto-update bzip3 to 1.5.1

packages/c/cpp-rotor/xmake.lua
New version of cpp-rotor detected (package version: v0.32, last github version: v0.33)
=> Auto-update cpp-rotor to v0.33

packages/t/tinyexr/xmake.lua
New version of tinyexr detected (package version: v1.0.9, last github version: v1.0.10)
=> Auto-update tinyexr to v1.0.10

packages/t/toml11/xmake.lua
New version of toml11 detected (package version: v4.2.0, last github version: v4.3.0)
=> Auto-update toml11 to v4.3.0

packages/s/sol2/patches/3.3.0/optional.patch, packages/s/sol2/xmake.lua
Small PR to add a patch in sol3 3.3.0 to fix an issue with clang19 because the dev seems to have abandonned the project. Have been tested on one of my project, compiles fine now.
The issue have been reported multiple times and have been fixed in the dev branch but the dev does not seem to prepare a new release (https://github.com/ThePhD/sol2/issues/1658). Patch file have been yoinked from [here](https://github.com/seechew/conan-center-index/blob/26b58b13be06adc58603df4d0b5e96eaabc576ec/recipes/sol2/all/patches/0001-Fix-emplace.patch).
=> Adding patch for sol2 3.3.0

packages/a/aws-c-cal/xmake.lua
New version of aws-c-cal detected (package version: v0.8.1, last github version: v0.8.3)
=> Auto-update aws-c-cal to v0.8.3

packages/g/google-cloud-cpp/xmake.lua
New version of google-cloud-cpp detected (package version: v2.33.0, last github version: v2.34.0)
=> Auto-update google-cloud-cpp to v2.34.0

packages/p/pdfhummus/xmake.lua
New version of pdfhummus detected (package version: v4.6.7, last github version: v4.6.8)
=> Auto-update pdfhummus to v4.6.8

packages/c/cppfront/xmake.lua
New version of cppfront detected (package version: v0.8.0, last github version: v0.8.1)
=> Auto-update cppfront to v0.8.1

packages/l/libpthread-stubs/xmake.lua, packages/l/libsdl3/xmake.lua, packages/l/libx11/xmake.lua, packages/l/libxau/xmake.lua, packages/l/libxcb/xmake.lua, packages/l/libxdmcp/xmake.lua, packages/l/libxext/xmake.lua, packages/u/util-macros/xmake.lua, packages/w/wayland/xmake.lua, packages/x/xcb-proto/xmake.lua, packages/x/xorgproto/xmake.lua, packages/x/xtrans/xmake.lua
#6156 
I took the libsdl package and removed all deprecated stuff, I may have missed some things though.
=> Add libsdl3

packages/p/pahomqttc/xmake.lua
New version of pahomqttc detected (package version: v1.3.13, last github version: v1.3.14)
=> Auto-update pahomqttc to v1.3.14

packages/l/libxmake/xmake.lua
=> xmake 2.9.8

packages/l/lief/xmake.lua
New version of lief detected (package version: 0.16.2, last github version: 0.16.3)
=> Auto-update lief to 0.16.3

packages/a/ada/xmake.lua
New version of ada detected (package version: v2.9.2, last github version: v3.0.1)
https://www.yagiz.co/release-of-ada-v3
=> Auto-update ada to v3.0.1

packages/a/aws-c-compression/xmake.lua
New version of aws-c-compression detected (package version: v0.3.0, last github version: v0.3.1)
=> Auto-update aws-c-compression to v0.3.1

packages/l/libbigwig/xmake.lua
New version of libbigwig detected (package version: 0.4.7, last github version: 0.4.8)
=> Auto-update libbigwig to 0.4.8

packages/c/cpp-httplib/xmake.lua
New version of cpp-httplib detected (package version: v0.18.5, last github version: v0.18.6)
=> Auto-update cpp-httplib to v0.18.6

packages/a/aws-c-event-stream/xmake.lua
New version of aws-c-event-stream detected (package version: v0.5.0, last github version: v0.5.1)
=> Auto-update aws-c-event-stream to v0.5.1

packages/l/liburing/xmake.lua
liburing builds for static and shared without any way to configuring so remove lib files based on the shared config
=> Patch liburing shared/static

packages/c/cpptrace/xmake.lua
New version of cpptrace detected (package version: v0.7.4, last github version: v0.7.5)
=> Auto-update cpptrace to v0.7.5

packages/c/cpp-httplib/xmake.lua
New version of cpp-httplib detected (package version: v0.18.6, last github version: v0.18.7)
=> Auto-update cpp-httplib to v0.18.7

packages/s/simdutf/xmake.lua
New version of simdutf detected (package version: v5.7.2, last github version: v6.2.0)
=> Auto-update simdutf to v6.2.0

packages/n/node-api-headers/xmake.lua
New version of node-api-headers detected (package version: v1.4.0, last github version: v1.5.0)
=> Auto-update node-api-headers to v1.5.0

packages/s/scnlib/xmake.lua
Currently, scnlib failed to compile and run with fast_float 7.0.0 and above. See [their issue](https://github.com/eliaskosunen/scnlib/pull/136). We hereby manually limit the version of fast_float in scnlib's dependencies.
=> lock scnlib's fast_float dependency to below 7.0.0

packages/w/webui/xmake.lua
WebUI 在 Linux 上需要链接 pthread 和 libdl，这些在高版本 gcc 上会自动链接，但在低版本 gcc(<=8) 上需要手动链接。
=> fix: syslink missing on linux in webui.

packages/r/rocksdb/xmake.lua
New version of rocksdb detected (package version: v9.9.3, last github version: v9.10.0)
=> Auto-update rocksdb to v9.10.0

packages/s/sentry-native/xmake.lua
New version of sentry-native detected (package version: 0.7.17, last github version: 0.7.20)
=> Auto-update sentry-native to 0.7.20

packages/s/samurai/xmake.lua
New version of samurai detected (package version: v0.19.0, last github version: v0.21.1)
=> Auto-update samurai to v0.21.1

packages/p/portable_build_tools/xmake.lua
New version of portable_build_tools detected (package version: v2.9.2, last github version: v2.10)
=> Auto-update portable_build_tools to v2.10

packages/d/directx-headers/xmake.lua
New version of directx-headers detected (package version: v1.614.1, last github version: v1.615.0)
=> Auto-update directx-headers to v1.615.0

packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.5.10, last github version: v1.5.12)
=> Auto-update s2n-tls to v1.5.12

packages/a/aws-c-http/xmake.lua
New version of aws-c-http detected (package version: v0.9.2, last github version: v0.9.3)
=> Auto-update aws-c-http to v0.9.3

packages/l/libfabric/xmake.lua
New version of libfabric detected (package version: 1.22.0, last github version: 2.0.0)
=> Auto-update libfabric to 2.0.0

packages/t/ta-lib/xmake.lua
New version of ta-lib detected (package version: 0.6.2, last github version: 0.6.4)
=> Auto-update ta-lib to 0.6.4

packages/s/sol2/xmake.lua
New version of sol2 detected (package version: v3.3.0, last github version: v3.3.1)
=> Auto-update sol2 to v3.3.1

packages/m/microsoft-proxy/xmake.lua
As is a header-only library, nothing needs to be done, except for a new `add_versions()` line.
=> update microsoft-proxy to 3.2.0

packages/e/extra-cmake-modules/xmake.lua
This package is required as a dependency for certain CMake-based projects.
=> extra-cmake-modules: add package

packages/c/cgltf/xmake.lua
New version of cgltf detected (package version: v1.14, last github version: v1.15)
=> Auto-update cgltf to v1.15

packages/v/vk-bootstrap/xmake.lua
New version of vk-bootstrap detected (package version: v1.3.302, last github version: v1.4.307)
=> Auto-update vk-bootstrap to v1.4.307

packages/l/ls-qpack/xmake.lua
New version of ls-qpack detected (package version: v2.6.0, last github version: v2.6.1)
=> Auto-update ls-qpack to v2.6.1

packages/f/flecs/xmake.lua
New version of flecs detected (package version: v4.0.3, last github version: v4.0.4)
=> Auto-update flecs to v4.0.4

packages/z/zxing-cpp/xmake.lua
- Don't clone submodules (zint) for git url.
- Add new configs:
- reader
- writer
- Improve cmake option.
- Fix `c_api` config build and test
=> zxing-cpp: Improve 2.3.0 version build

packages/b/boost_ut/xmake.lua
New version of boost_ut detected (package version: v2.1.1, last github version: v2.3.0)
=> Auto-update boost_ut to v2.3.0

packages/s/snmalloc/xmake.lua
New version of snmalloc detected (package version: 0.7.0, last github version: 0.7.1)
=> Auto-update snmalloc to 0.7.1

packages/f/fast-cdr/xmake.lua
New version of fast-cdr detected (package version: v2.2.5, last github version: v2.2.6)
=> Auto-update fast-cdr to v2.2.6

packages/f/fmtlog/xmake.lua
New version of fmtlog detected (package version: v2.2.2, last github version: v2.3.0)
=> Auto-update fmtlog to v2.3.0

packages/p/paul_thread_pool/xmake.lua
New version of paul_thread_pool detected (package version: 0.6.2, last github version: 0.7.0)
=> Auto-update paul_thread_pool to 0.7.0

packages/l/libsdl2_mixer/xmake.lua
New version of libsdl2_mixer detected (package version: 2.8.0, last github version: 2.8.1)
=> Auto-update libsdl2_mixer to 2.8.1

packages/q/quill/xmake.lua
New version of quill detected (package version: v8.0.0, last github version: v8.1.1)
=> Auto-update quill to v8.1.1

packages/g/glaze/xmake.lua
New version of glaze detected (package version: v4.2.2, last github version: v4.4.2)
=> Auto-update glaze to v4.4.2

packages/j/jsoncons/xmake.lua
New version of jsoncons detected (package version: v1.1.0, last github version: v1.2.0)
=> Auto-update jsoncons to v1.2.0

packages/c/c-blosc2/xmake.lua
New version of c-blosc2 detected (package version: v2.15.2, last github version: v2.16.0)
=> Auto-update c-blosc2 to v2.16.0

packages/o/ozz-animation/xmake.lua
New version of ozz-animation detected (package version: 0.15.0, last github version: 0.16.0)
=> Auto-update ozz-animation to 0.16.0

packages/l/libsdl2_image/xmake.lua
New version of libsdl2_image detected (package version: 2.8.4, last github version: 2.8.5)
=> Auto-update libsdl2_image to 2.8.5

packages/p/plutosvg/xmake.lua
New version of plutosvg detected (package version: v0.0.4, last github version: v0.0.5)
=> Auto-update plutosvg to v0.0.5

packages/g/glaze/xmake.lua
New version of glaze detected (package version: v4.4.2, last github version: v4.4.3)
=> Auto-update glaze to v4.4.3

packages/a/amrex/xmake.lua
New version of amrex detected (package version: 24.12, last github version: 25.02)
=> Auto-update amrex to 25.02

packages/l/libpng/xmake.lua
New version of libpng detected (package version: v1.6.46, last github version: v1.6.47)
=> Auto-update libpng to v1.6.47

packages/l/lunasvg/xmake.lua
New version of lunasvg detected (package version: v3.1.0, last github version: v3.2.0)
=> Auto-update lunasvg to v3.2.0

packages/c/c4core/xmake.lua
New version of c4core detected (package version: 0.2.2, last github version: 0.2.5)
=> Auto-update c4core to 0.2.5

packages/n/nanoflann/xmake.lua
New version of nanoflann detected (package version: v1.6.2, last github version: v1.7.0)
=> Auto-update nanoflann to v1.7.0

packages/l/libsdl2_ttf/xmake.lua
New version of libsdl2_ttf detected (package version: 2.22.0, last github version: 2.24.0)
=> Auto-update libsdl2_ttf to 2.24.0

packages/a/argparse/xmake.lua
New version of argparse detected (package version: 3.1, last github version: 3.2)
=> Auto-update argparse to 3.2

packages/a/aws-c-mqtt/xmake.lua
New version of aws-c-mqtt detected (package version: v0.11.0, last github version: v0.12.1)
=> Auto-update aws-c-mqtt to v0.12.1

packages/c/cglm/xmake.lua
New version of cglm detected (package version: v0.9.4, last github version: v0.9.6)
=> Auto-update cglm to v0.9.6

packages/n/node-addon-api/xmake.lua
New version of node-addon-api detected (package version: v8.3.0, last github version: v8.3.1)
=> Auto-update node-addon-api to v8.3.1

packages/w/webui/xmake.lua
在 [WebUI 2.5.0](https://github.com/webui-dev/webui) 中，在 Windows 上编译 WebUI 需要添加额外的 syslinks：ws2_32, ole32，否则会出错：
```
error: ...xmake\repositories\xmake-repo\packages\w\webui\xmake.lua:52: ...e-cache\core\sandbox\modules\import\core\tool\linker.lua:75: .\.xmake-cache\modules\core\tools\link.lua:175:    Creating library C:\Users\RUNNER~1\AppData\Local\Temp\.xmake\250219\_42B3F84178514750872955E65EB6BE80.lib and object C:\Users\RUNNER~1\AppData\Local\Temp\.xmake\250219\_42B3F84178514750872955E65EB6BE80.exp
webui.lib(webui.c.obj) : error LNK2019: unresolved external symbol __imp_CoTaskMemFree referenced in function TitleChanged_Invoke
C:\Users\RUNNER~1\AppData\Local\Temp\.xmake\250219\_42B3F84178514750872955E65EB6BE80.b : fatal error LNK1120: 1 unresolved externals
stack traceback:
[C]: in …
```
=> Fix syslink missing in webui 2.5.0

packages/c/cgif/xmake.lua
New version of cgif detected (package version: v0.4.1, last github version: v0.5.0)
=> Auto-update cgif to v0.5.0

packages/d/daw_header_libraries/xmake.lua
New version of daw_header_libraries detected (package version: v2.118.0, last github version: v2.123.2)
=> Auto-update daw_header_libraries to v2.123.2

packages/a/aws-c-common/xmake.lua
New version of aws-c-common detected (package version: v0.10.6, last github version: v0.11.1)
=> Auto-update aws-c-common to v0.11.1

packages/c/cuda-samples/xmake.lua
New version of cuda-samples detected (package version: v12.5, last github version: v12.8)
=> Auto-update cuda-samples to v12.8

packages/r/re-flex/xmake.lua
New version of re-flex detected (package version: v5.0.1, last github version: v5.2.2)
=> Auto-update re-flex to v5.2.2

packages/m/miniaudio/xmake.lua
New version of miniaudio detected (package version: 0.11.21, last github version: 0.11.22)
=> Auto-update miniaudio to 0.11.22

packages/p/pahomqttcpp/xmake.lua
New version of pahomqttcpp detected (package version: v1.5.0, last github version: v1.5.1)
=> Auto-update pahomqttcpp to v1.5.1

packages/c/cwt-cucumber/xmake.lua
https://cucumber.io/
```cpp
#include <cwt-cucumber/cucumber.hpp>
```
I kept trying to ```add_cxxflags("clang::-fexperimental-library", {force = true})``` within package scope so macos would succeed.
As last logs showup it is maybe missing link to ```libc++experimental.a```. I do not know good solution there, hence existing CI machine clang++13 macosx maybe miss library ```c++experimental```, as per it is not being specified like syslink/link there https://github.com/MorganCaron/Script/blob/08403631fe52876b3d89fc2fb760ef25a0f6f725/xmake.lua#L13 for some reason.
Maybe https://github.com/orgs/Homebrew/discussions/4429 *However, passing the path to homebrew llvm's own libdir gives the expected results:* could help in this case.
Yet I just decide to avoid that flag and do not support it. …
=> Add new package cwt-cucumber 2.5

packages/f/ffmpeg/xmake.lua
This PR attempts to ~~correct the `shared` field and~~ (solved by https://github.com/xmake-io/xmake/commit/4abb777fb6cdca3bfeebfd2ae2b2f4a2d4089dad) improve the version parsing logic. However, since `ffmpeg` does not adhere to a common pattern for version strings, there may still be cases where the version is inaccurate.
=> ffmpeg: improve version parsing logic

packages/s/sqlite_orm/xmake.lua
New version of sqlite_orm detected (package version: v1.9, last github version: v1.9.1)
=> Auto-update sqlite_orm to v1.9.1

packages/t/tiny-optional/xmake.lua
New version of tiny-optional detected (package version: v1.3.1, last github version: v1.4.0)
=> Auto-update tiny-optional to v1.4.0

packages/d/double-conversion/xmake.lua
New version of double-conversion detected (package version: v3.3.0, last github version: v3.3.1)
=> Auto-update double-conversion to v3.3.1

packages/l/libwebsockets/xmake.lua
New version of libwebsockets detected (package version: v4.3.3, last github version: v4.3.4)
=> Auto-update libwebsockets to v4.3.4

packages/u/ucx/xmake.lua
New version of ucx detected (package version: 1.17.0, last github version: 1.18.0)
=> Auto-update ucx to 1.18.0

packages/s/stringzilla/xmake.lua
New version of stringzilla detected (package version: v3.11.3, last github version: v3.12.1)
=> Auto-update stringzilla to v3.12.1

packages/n/nuklear/xmake.lua
New version of nuklear detected (package version: 4.12.3, last github version: 4.12.4)
=> Auto-update nuklear to 4.12.4

packages/k/kahip/xmake.lua
New version of kahip detected (package version: v3.17, last github version: v3.18)
=> Auto-update kahip to v3.18

packages/l/libjpeg-turbo/xmake.lua
New version of libjpeg-turbo detected (package version: 3.0.4, last github version: 3.1.0)
=> Auto-update libjpeg-turbo to 3.1.0

packages/l/lapack/xmake.lua
New version of lapack detected (package version: v3.12.0, last github version: v3.12.1)
=> Auto-update lapack to v3.12.1

packages/x/xsimd/xmake.lua
New version of xsimd detected (package version: 13.1.0, last github version: 13.2.0)
=> Auto-update xsimd to 13.2.0

packages/z/zstd/xmake.lua
New version of zstd detected (package version: v1.5.6, last github version: v1.5.7)
=> Auto-update zstd to v1.5.7

packages/p/plutovg/xmake.lua
New version of plutovg detected (package version: v0.0.12, last github version: v0.0.13)
=> Auto-update plutovg to v0.0.13

packages/o/openssl/xmake.lua
#6079 added the restriction that perl must be installed on the system (on_check runs before installation of strawberry-perl).
Fix #6496
=> openssl: Fix build on Windows without perl

packages/h/hlslpp/xmake.lua
New version of hlslpp detected (package version: 3.5.3, last github version: 3.6)
=> Auto-update hlslpp to 3.6

packages/m/microsoft-gsl/xmake.lua
New version of microsoft-gsl detected (package version: v4.1.0, last github version: v4.2.0)
=> Auto-update microsoft-gsl to v4.2.0

packages/l/lzav/xmake.lua
New version of lzav detected (package version: 4.5, last github version: 4.7)
=> Auto-update lzav to 4.7

packages/a/arduinojson/xmake.lua
New version of arduinojson detected (package version: v7.3.0, last github version: v7.3.1)
=> Auto-update arduinojson to v7.3.1

packages/f/fmt/xmake.lua
New version of fmt detected (package version: 11.1.3, last github version: 11.1.4)
=> Auto-update fmt to 11.1.4

packages/r/re-flex/xmake.lua
New version of re-flex detected (package version: v5.2.2, last github version: v5.3.0)
=> Auto-update re-flex to v5.3.0

packages/a/amrex/xmake.lua
New version of amrex detected (package version: 25.02, last github version: 25.03)
=> Auto-update amrex to 25.03

packages/v/verilator/xmake.lua
New version of verilator detected (package version: v5.032, last github version: v5.034)
=> Auto-update verilator to v5.034

packages/u/unity_test/xmake.lua
New version of unity_test detected (package version: v2.6.0, last github version: v2.6.1)
=> Auto-update unity_test to v2.6.1

packages/c/cpr/xmake.lua
New version of cpr detected (package version: 1.11.1, last github version: 1.11.2)
=> Auto-update cpr to 1.11.2

packages/n/nghttp3/xmake.lua
New version of nghttp3 detected (package version: v1.7.0, last github version: v1.8.0)
=> Auto-update nghttp3 to v1.8.0

packages/o/openh264/xmake.lua
New version of openh264 detected (package version: v2.5.0, last github version: v2.6.0)
=> Auto-update openh264 to v2.6.0

packages/l/libfswatch/xmake.lua
New version of libfswatch detected (package version: 1.18.2, last github version: 1.18.3)
=> Auto-update libfswatch to 1.18.3

packages/a/aws-lc/xmake.lua
New version of aws-lc detected (package version: v1.45.0, last github version: v1.48.1)
=> Auto-update aws-lc to v1.48.1

packages/s/sentry-native/xmake.lua
New version of sentry-native detected (package version: 0.7.20, last github version: 0.8.1)
=> Auto-update sentry-native to 0.8.1

packages/t/tgbot-cpp/xmake.lua
New version of tgbot-cpp detected (package version: v1.8, last github version: v1.9)
=> Auto-update tgbot-cpp to v1.9

packages/s/spdlog/xmake.lua
1. Add spdlog's control macros SPDLOG_WCHAR_FILENAMES and SPDLOG_UTF8_TO_WCHAR_CONSOLE to xrepo's package management
2. Remove the restriction of shared build for spdlog on Windows platform.
=> add_more control macro for spdlog

packages/m/minizip-ng/xmake.lua
New version of minizip-ng detected (package version: 4.0.7, last github version: 4.0.8)
=> Auto-update minizip-ng to 4.0.8

packages/g/glpk/port/xmake.lua, packages/g/glpk/xmake.lua
- build system
- linux & macosx -> autotools
- other platform -> xmake
- Support features
ref: https://github.com/microsoft/vcpkg/blob/da78c7eb8881444fbc9e2176400e9a9f4b325692/ports/glpk/portfile.cmake
=> glpk: improve build

packages/b/blake3/xmake.lua
New version of blake3 detected (package version: 1.5.5, last github version: 1.6.1)
=> Auto-update blake3 to 1.6.1

packages/d/dlib/xmake.lua
New version of dlib detected (package version: v19.24.6, last github version: v19.24.8)
=> Auto-update dlib to v19.24.8

packages/s/safetyhook/xmake.lua
New version of safetyhook detected (package version: v0.6.4, last github version: v0.6.5)
=> Auto-update safetyhook to v0.6.5

packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.5.12, last github version: v1.5.14)
=> Auto-update s2n-tls to v1.5.14

packages/w/wavpack/xmake.lua
New version of wavpack detected (package version: 5.7.0, last github version: 5.8.1)
=> Auto-update wavpack to 5.8.1

packages/c/cserialport/xmake.lua
New version of cserialport detected (package version: v4.3.1, last github version: v4.3.2)
=> Auto-update cserialport to v4.3.2

packages/s/sobjectizer/xmake.lua
New version of sobjectizer detected (package version: 5.8.0, last github version: 5.8.4)
=> Auto-update sobjectizer to 5.8.4

packages/t/toml11/xmake.lua
New version of toml11 detected (package version: v4.3.0, last github version: v4.4.0)
=> Auto-update toml11 to v4.4.0

packages/t/tree-sitter/xmake.lua
New version of tree-sitter detected (package version: v0.24.6, last github version: v0.25.3)
=> Auto-update tree-sitter to v0.25.3

packages/o/onednn/xmake.lua
New version of onednn detected (package version: v3.6.2, last github version: v3.7.1)
=> Auto-update onednn to v3.7.1

packages/l/lightgbm/xmake.lua
New version of lightgbm detected (package version: 4.4.0, last github version: 4.5.0)
=> Auto-update lightgbm to 4.5.0

packages/l/lightgbm/xmake.lua
New version of lightgbm detected (package version: 4.4.0, last github version: 4.6.0)
=> Auto-update lightgbm to 4.6.0

packages/q/quickjs-ng/xmake.lua
New version of quickjs-ng detected (package version: v0.8.0, last github version: v0.9.0)
=> Auto-update quickjs-ng to v0.9.0

packages/a/aws-c-common/xmake.lua
New version of aws-c-common detected (package version: v0.11.1, last github version: v0.11.3)
=> Auto-update aws-c-common to v0.11.3

packages/r/rapidfuzz/xmake.lua
New version of rapidfuzz detected (package version: v3.1.1, last github version: v3.3.2)
=> Auto-update rapidfuzz to v3.3.2

packages/s/samurai/xmake.lua
New version of samurai detected (package version: v0.21.1, last github version: v0.22.0)
=> Auto-update samurai to v0.22.0

packages/a/aws-c-auth/xmake.lua
New version of aws-c-auth detected (package version: v0.8.0, last github version: v0.8.6)
=> Auto-update aws-c-auth to v0.8.6

packages/g/gfx-timsort/xmake.lua
New version of gfx-timsort detected (package version: v3.0.0, last github version: v3.0.1)
=> Auto-update gfx-timsort to v3.0.1

packages/c/cpp-httplib/xmake.lua
New version of cpp-httplib detected (package version: v0.18.7, last github version: v0.19.0)
=> Auto-update cpp-httplib to v0.19.0

packages/f/frugally-deep/xmake.lua
New version of frugally-deep detected (package version: v0.16.2, last github version: v0.17.1)
=> Auto-update frugally-deep to v0.17.1

packages/g/gdal/xmake.lua
New version of gdal detected (package version: 3.10.0, last github version: 3.10.2)
=> Auto-update gdal to 3.10.2

packages/a/abseil/xmake.lua
Use package's `cxx_standard` version in `on_test` since it fails with `cxx_standard=20` because of `<compare>` (`std::partial_ordering`, `std::weak_ordering`, and so on)
Logs of failed `on_test`:
```
> checking for c++ snippet(test)
checkinfo: ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:84: @programdir/modules/core/tools/gcc.lua:966: In file included from /tmp/.xmake1000/250315/_655EF772B73E4B43A7AB303658501B4D.cpp:4:
In file included from /home/akylzhan/.xmake/packages/a/abseil/b3b568d9/5469470edd9647118f0bc7cd962dde3a/include/absl/strings/numbers.h:50:
In file included from /home/akylzhan/.xmake/packages/a/abseil/b3b568d9/5469470edd9647118f0bc7cd962dde3a/include/absl/numeric/int128.h:41:
/home/akylzhan/.xmake/packages/a/abseil/b3b568d9/5469470edd9647118f0bc7cd962dde3a/inc …
```
=> Abseil: use cxx_standard in on_test

packages/p/pahomqttcpp/xmake.lua
New version of pahomqttcpp detected (package version: v1.5.1, last github version: v1.5.2)
=> Auto-update pahomqttcpp to v1.5.2

packages/c/cnats/xmake.lua
New version of cnats detected (package version: v3.9.2, last github version: v3.10.1)
=> Auto-update cnats to v3.10.1

packages/w/wintoast/xmake.lua
New version of wintoast detected (package version: v1.3.0, last github version: v1.3.1)
=> Auto-update wintoast to v1.3.1

packages/w/wayland/xmake.lua
https://gitlab.freedesktop.org/wayland/wayland is currently down for about a week, breaking all package installation, I added a proxy link
=> wayland: add proxy URL

packages/l/libjq/xmake.lua
If msys, does it need to be? Or keep as is.
```
if is_subhost("msys") then
add_deps("autotools")
else
add_deps("autoconf", "automake", "libtool")
end
-- assert(not (package:is_plat("mingw") and package:is_subhost("msys")), "package(libjq): does not support windows@mingw.")
```
Seems it some sort of bug for msys. :/ IDK what can be done upon that. 
https://github.com/jqlang/jq/wiki/Cross-compilation it seems mingw-w64 can *cross-build* for windows.
```
checkinfo: cannot runv(autoreconf --version), No such file or directory
checking for autoreconf ... no
error: @programdir\modules\package\tools\autoconf.lua:515: autoreconf not found!
```
Shy version.
=> Test libjq

packages/c/c-blosc2/xmake.lua
New version of c-blosc2 detected (package version: v2.16.0, last github version: v2.17.0)
=> Auto-update c-blosc2 to v2.17.0

packages/n/nlopt/xmake.lua
New version of nlopt detected (package version: v2.9.1, last github version: v2.10.0)
=> Auto-update nlopt to v2.10.0

packages/a/aws-c-cal/xmake.lua
New version of aws-c-cal detected (package version: v0.8.3, last github version: v0.8.7)
=> Auto-update aws-c-cal to v0.8.7

packages/t/tinycbor/port/xmake.lua, packages/t/tinycbor/xmake.lua
New version of tinycbor detected (package version: v0.6.0, last github version: v0.6.1)
=> Auto-update tinycbor to v0.6.1

packages/l/lsquic/xmake.lua
New version of lsquic detected (package version: v4.0.12, last github version: v4.2.0)
=> Auto-update lsquic to v4.2.0

packages/l/libassert/xmake.lua
New version of libassert detected (package version: v2.1.4, last github version: v2.1.5)
=> Auto-update libassert to v2.1.5

packages/u/upa-url/xmake.lua
New version of upa-url detected (package version: v1.0.2, last github version: v1.2.0)
=> Auto-update upa-url to v1.2.0

packages/a/aws-lc/xmake.lua
New version of aws-lc detected (package version: v1.48.1, last github version: v1.48.5)
=> Auto-update aws-lc to v1.48.5

packages/j/jsoncons/xmake.lua
New version of jsoncons detected (package version: v1.2.0, last github version: v1.3.0)
=> Auto-update jsoncons to v1.3.0

packages/l/lzav/xmake.lua
New version of lzav detected (package version: 4.7, last github version: 4.9)
=> Auto-update lzav to 4.9

packages/s/simsimd/xmake.lua
New version of simsimd detected (package version: v6.2.3, last github version: v6.4.0)
=> Auto-update simsimd to v6.4.0

packages/s/srtp/xmake.lua
New version of srtp detected (package version: v2.6, last github version: v2.7)
=> Auto-update srtp to v2.7

packages/a/abseil/xmake.lua
New version of abseil detected (package version: 20250127.0, last github version: 20250127.1)
=> Auto-update abseil to 20250127.1

packages/r/reflect-cpp/xmake.lua
New version of reflect-cpp detected (package version: v0.17.0, last github version: v0.18.0)
=> Auto-update reflect-cpp to v0.18.0

packages/m/melon/xmake.lua
Windows has not DLL build support.
MinGW32/64 or UCRT would not work, but Clang64 is working. I do not know upon Mac OS X MinGW-W64 so Ill place up placeholder there.
```lua
if is_subhost("macosx") then
raise("package(melon) is unsupported on Mac OS X subhost.")
end
```
=> Test melon

packages/s/sqrat/xmake.lua
Feel free to change PR code. This is very much likely header-only lib, so I ve placed headeronly option.
Limit WASM & iPhoneOS since dep squirrel does not support WASM & iPhoneOS.
Resolves https://github.com/xmake-io/xmake-repo/pull/3129 by https://github.com/xmake-io/xmake-repo/pull/4874 & https://github.com/xmake-io/xmake-repo/pull/6667
=> Test sqrat

packages/t/think-cell-library/xmake.lua
```cpp
#include <tc/>
```
b2 does not support WASM.
Release tag on GitHub is not x.y.z it's like x.y in case of this header only library.
=> Test think-cell-library

packages/a/aws-c-http/xmake.lua
New version of aws-c-http detected (package version: v0.9.4, last github version: v0.9.5)
=> Auto-update aws-c-http to v0.9.5

packages/m/mnn/xmake.lua
New version of mnn detected (package version: 3.0.5, last github version: 3.1.1)
=> Auto-update mnn to 3.1.1

packages/q/qcbor/xmake.lua
New version of qcbor detected (package version: v1.4.1, last github version: v1.5.1)
=> Auto-update qcbor to v1.5.1

packages/i/imgui/port/xmake.lua, packages/i/imgui/xmake.lua
看了包里只有 sdl3 与 sdl3_render 配置，但却缺少了以`sdl3gpu`为后端相关的头文件与cpp。所以增加了 `sdl3_gpu` 配置以供引入对应的文件。
=> [imgui] add sdl3 `gpu` backend

packages/s/sfgui/port/xmake.lua, packages/s/sfgui/xmake.lua
Feel free to change this PR.
SFML 3 supports "windows", "linux", "macosx", "mingw".
Dunno upon error here for MinGW... Would be nice to avoid ```defines = not package:config("shared") and "SFGUI_STATIC" or nil```
https://stackoverflow.com/questions/48661676/sfml-undefined-reference-to-imp
_imp___ZN2sf6StringC1EPKcRKSt6locale <=> sf::String::String(const char*, const std::locale&) ?
Resolves https://github.com/xmake-io/xmake-repo/pull/2122
=> Test sfgui

packages/j/joltphysics/xmake.lua
New version of joltphysics detected (package version: v5.2.0, last github version: v5.3.0)
=> Auto-update joltphysics to v5.3.0

packages/n/node-addon-api/xmake.lua
`node-addon-api` 目前的配置只允许在 linux 平台上使用，但根据其官方 [README.md](https://github.com/nodejs/node-addon-api)，并没有相关限制
=> Allow node-addon-api to be used on non-Linux platforms

packages/v/vvenc/xmake.lua
New version of vvenc detected (package version: v1.13.0, last github version: v1.13.1)
=> Auto-update vvenc to v1.13.1

packages/w/woff2/xmake.lua
```xmake
if is_plat("windows") then
add_configs("shared", {description = "Build shared library.", default = false, type = "boolean", readonly = true})
end
```
mingw@macosx https://stackoverflow.com/questions/8878676/compile-error-g-error-trying-to-exec-cc1plus-execvp-no-such-file-or-dir ?
https://github.com/xmake-io/xmake/issues/5191
Exactly 
```
x86_64-w64-mingw32-g++: fatal error: cannot execute 'cc1plus': posix_spawnp: No such file or directory
```
=> Test woff2

packages/g/google-cloud-cpp/xmake.lua
New version of google-cloud-cpp detected (package version: v2.34.0, last github version: v2.36.0)
=> Auto-update google-cloud-cpp to v2.36.0

packages/l/libfabric/xmake.lua
New version of libfabric detected (package version: 2.0.0, last github version: 2.1.0)
=> Auto-update libfabric to 2.1.0

packages/c/cpp-rotor/xmake.lua
New version of cpp-rotor detected (package version: v0.33, last github version: v0.34)
=> Auto-update cpp-rotor to v0.34

packages/p/portable_build_tools/xmake.lua
New version of portable_build_tools detected (package version: v2.10, last github version: v2.10.2)
=> Auto-update portable_build_tools to v2.10.2

packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.5.14, last github version: v1.5.15)
=> Auto-update s2n-tls to v1.5.15

packages/q/quill/xmake.lua
New version of quill detected (package version: v8.1.1, last github version: v8.2.0)
=> Auto-update quill to v8.2.0

packages/s/screen_capture_lite/xmake.lua
New version of screen_capture_lite detected (package version: 17.1.1368, last github version: 17.1.1369)
=> Auto-update screen_capture_lite to 17.1.1369

packages/t/tinyexr/xmake.lua
New version of tinyexr detected (package version: v1.0.10, last github version: v1.0.12)
=> Auto-update tinyexr to v1.0.12

packages/l/libavif/xmake.lua, packages/l/libyuv/xmake.lua
New version of libavif detected (package version: v1.1.1, last github version: v1.2.1)
=> Auto-update libavif to v1.2.1

packages/r/rapidcsv/xmake.lua
New version of rapidcsv detected (package version: v8.84, last github version: v8.85)
=> Auto-update rapidcsv to v8.85

packages/f/flecs/xmake.lua
New version of flecs detected (package version: v4.0.4, last github version: v4.0.5)
=> Auto-update flecs to v4.0.5

packages/g/gyp-next/xmake.lua
New version of gyp-next detected (package version: v0.19.1, last github version: v0.20.0)
=> Auto-update gyp-next to v0.20.0

packages/s/sfml/xmake.lua
Setting the `SFML_USE_SYSTEM_DEPS` to `TRUE` when compiling with mingw on linux gives me this error :
```
In file included from /home/simon/.xmake/cache/packages/2503/s/sfml/3.0.0/source/extlibs/headers/miniaudio/miniaudio.h:3754,
from /home/simon/.xmake/cache/packages/2503/s/sfml/3.0.0/source/src/SFML/Audio/AudioDevice.hpp:34,
from /home/simon/.xmake/cache/packages/2503/s/sfml/3.0.0/source/src/SFML/Audio/Listener.cpp:28:
/usr/include/stdint.h:90:33: error: conflicting declaration ‘typedef long unsigned int uintptr_t’
90 | typedef unsigned long int       uintptr_t;
|                                 ^~~~~~~~~
In file included from /usr/share/mingw-w64/include/crtdefs.h:10,
from /usr/share/mingw-w64/include/stddef.h:7,
from /usr/lib/gcc/x86_64-w64-mingw32/12-posix/include/stddef.h:1,
from …
```
=> Fix SFML mingw cross compiling

packages/e/expat/xmake.lua
New version of expat detected (package version: 2.6.4, last github version: 2.7.1)
=> Auto-update expat to 2.7.1

packages/l/leancrypto/xmake.lua
New version of leancrypto detected (package version: v1.2.0, last github version: v1.3.0)
=> Auto-update leancrypto to v1.3.0

packages/e/emio/xmake.lua
New version of emio detected (package version: 0.8.0, last github version: 0.9.0)
=> Auto-update emio to 0.9.0

packages/o/onednn/xmake.lua
New version of onednn detected (package version: v3.7.1, last github version: v3.7.2)
=> Auto-update onednn to v3.7.2

packages/p/plutovg/xmake.lua
New version of plutovg detected (package version: v0.0.13, last github version: v1.0.0)
=> Auto-update plutovg to v1.0.0

packages/k/kokkos-kernels/xmake.lua
New version of kokkos-kernels detected (package version: 4.4.00, last github version: 4.6.00)
=> Auto-update kokkos-kernels to 4.6.00

packages/r/rocksdb/xmake.lua
New version of rocksdb detected (package version: v9.10.0, last github version: v9.11.2)
=> Auto-update rocksdb to v9.11.2

packages/m/mongoose/xmake.lua
New version of mongoose detected (package version: 7.16, last github version: 7.17)
=> Auto-update mongoose to 7.17

packages/m/mujs/xmake.lua
New version of mujs detected (package version: 1.3.5, last github version: 1.3.6)
=> Auto-update mujs to 1.3.6

packages/n/nuklear/xmake.lua
New version of nuklear detected (package version: 4.12.5, last github version: 4.12.6)
=> Auto-update nuklear to 4.12.6

packages/p/protobuf-cpp/xmake.lua
New version of protobuf-cpp detected (package version: 29.3, last github version: 30.2)
=> Auto-update protobuf-cpp to 30.2

packages/s/sentry-native/xmake.lua
New version of sentry-native detected (package version: 0.8.1, last github version: 0.8.3)
=> Auto-update sentry-native to 0.8.3

packages/s/spdlog/xmake.lua
New version of spdlog detected (package version: v1.15.1, last github version: v1.15.2)
=> Auto-update spdlog to v1.15.2

packages/f/fast_float/xmake.lua
New version of fast_float detected (package version: v8.0.0, last github version: v8.0.2)
=> Auto-update fast_float to v8.0.2

packages/e/entt/xmake.lua
New version of entt detected (package version: v3.14.0, last github version: v3.15.0)
=> Auto-update entt to v3.15.0

packages/c/cppcheck/xmake.lua
New version of cppcheck detected (package version: 2.16.2, last github version: 2.17.1)
=> Auto-update cppcheck to 2.17.1

packages/a/aws-c-s3/xmake.lua
New version of aws-c-s3 detected (package version: v0.7.12, last github version: v0.7.14)
=> Auto-update aws-c-s3 to v0.7.14

packages/c/c-blosc2/xmake.lua
New version of c-blosc2 detected (package version: v2.17.0, last github version: v2.17.1)
=> Auto-update c-blosc2 to v2.17.1

packages/h/highs/xmake.lua
New version of highs detected (package version: v1.9.0, last github version: v1.10.0)
=> Auto-update highs to v1.10.0

packages/f/fast-cdr/xmake.lua
New version of fast-cdr detected (package version: v2.2.6, last github version: v2.3.0)
=> Auto-update fast-cdr to v2.3.0

packages/g/glaze/xmake.lua
New version of glaze detected (package version: v4.4.3, last github version: v5.0.2)
=> Auto-update glaze to v5.0.2

packages/l/libsdl3/xmake.lua
New version of libsdl3 detected (package version: 3.2.8, last github version: 3.2.10)
=> Auto-update libsdl3 to 3.2.10

packages/e/entt/xmake.lua
Reverts xmake-io/xmake-repo#6795
For unknown reason, the https://github.com/skypjack/entt/commit/0a3c2cc4006157241665c6ccefc8b9676c1c752e.patch is rollbacked. A few hours ago, its sha256 is `3e791f9869d1b387444d435cad9b1515db5befe706ed5dca71ee733a583da84e`, but it is recovered to `3f059d322244d64233ff2f37e9c80c8b28d92bf5b1bbef39e95cbc4d9ef0b132` again.
=> Revert "Fix entt v3.14.0's patch hash"

packages/c/cli11/xmake.lua
New version of cli11 detected (package version: v2.4.2, last github version: v2.5.0)
=> Auto-update cli11 to v2.5.0

packages/f/ftxui/xmake.lua
New version of ftxui detected (package version: v5.0.0, last github version: v6.0.2)
=> Auto-update ftxui to v6.0.2

packages/b/b2/xmake.lua
New version of b2 detected (package version: 5.2.1, last github version: 5.3.0)
=> Auto-update b2 to 5.3.0

packages/m/microsoft-proxy/xmake.lua
New version of microsoft-proxy detected (package version: 3.2.1, last github version: 3.3.0)
=> Auto-update microsoft-proxy to 3.3.0

packages/c/capstone/xmake.lua
New version of capstone detected (package version: 5.0.5, last github version: 5.0.6)
=> Auto-update capstone to 5.0.6

packages/c/cutlass/xmake.lua
New version of cutlass detected (package version: v3.7.0, last github version: v3.8.0)
=> Auto-update cutlass to v3.8.0

packages/m/mini/xmake.lua
New version of mini detected (package version: 0.9.17, last github version: 0.9.18)
=> Auto-update mini to 0.9.18

packages/z/zasm/xmake.lua
Since downstream users can reference packages using commit hash, using commit hash to determine versions is more precise.
=> zasm: Improve determining versions

packages/t/tinyexpr/xmake.lua
给 `tinyexpr` 添加了两个配置选项： `pow_from_right` 和 `natural_log`。
=> Add config options for tinyexpr.

packages/t/trantor/xmake.lua
New version of trantor detected (package version: v1.5.22, last github version: v1.5.23)
=> Auto-update trantor to v1.5.23

packages/n/nghttp2/xmake.lua
New version of nghttp2 detected (package version: 1.64.0, last github version: 1.65.0)
=> Auto-update nghttp2 to 1.65.0

packages/t/tinyxml2/xmake.lua
New version of tinyxml2 detected (package version: 10.0.0, last github version: 11.0.0)
=> Auto-update tinyxml2 to 11.0.0

packages/v/vk-bootstrap/xmake.lua
New version of vk-bootstrap detected (package version: v1.4.307, last github version: v1.4.311)
=> Auto-update vk-bootstrap to v1.4.311

packages/b/botan/xmake.lua
The original botan library used a minimal install, which resulted in a lack of many header files. This commit now passes "minimal" as an option to control whether to use a minimal or full build
minimal build:
```
allocator.h
api.h
assert.h
buf_comp.h
build.h
compiler.h
concepts.h
database.h
data_src.h
exceptn.h
hex.h
mem_ops.h
mutex.h
rng.h
secmem.h
strong_type.h
sym_algo.h
symkey.h
types.h
version.h
```
full build:
```
aead.h          build.h                der_enc.h          ed448.h        mac.h                  p11_rsa.h     pk_ops_fwd.h     sphincsplus.h       tls.h                            types.h
allocator.h     certstor_flatfile.h    dh.h               elgamal.h      mceliece.h             p11_types.h   pk_ops.h         sp_parameters.h     tls_handshake_msg.h              uuid.h …
```
=> botan: add minimal as option

packages/m/meshoptimizer/xmake.lua
New version of meshoptimizer detected (package version: v0.22, last github version: v0.23)
=> Auto-update meshoptimizer to v0.23

packages/c/c-ares/xmake.lua
Since the official download link for c-ares is no longer available, it has been removed.
=> c-ares: Delete deprecated urls

packages/c/cmake/xmake.lua
```
Run xmake-io/github-action-setup-xmake@v1
Selected xmake branch master (commit: 9a4136c5)
Selected xmake v2.9.9 (commit: 40815a0e)
Warning: No cached files found at path "D:\a\xmake-repo\xmake-repo\.xmake-cache".
download xmake branch master
downloading from https://github.com/xmake-io/xmake/releases/download/v2.9.9/xmake-master.win64.exe
Error: Unexpected HTTP response: 404
```
Github CI recent issue? Looks like appeared since auto-update 6 h ago.
=> cmake: update to 4.0.0

packages/e/emmylua_debugger/xmake.lua
New version of emmylua_debugger detected (package version: 1.8.3, last github version: 1.8.4)
=> Auto-update emmylua_debugger to 1.8.4

packages/l/libremidi/xmake.lua
New version of libremidi detected (package version: v5.1.0, last github version: v5.2.0)
=> Auto-update libremidi to v5.2.0

packages/v/vk-bootstrap/xmake.lua
New version of vk-bootstrap detected (package version: v1.4.311, last github version: v1.4.312)
=> Auto-update vk-bootstrap to v1.4.312

packages/b/blake3/xmake.lua
New version of blake3 detected (package version: 1.6.1, last github version: 1.8.1)
=> Auto-update blake3 to 1.8.1

packages/s/scons/xmake.lua
New version of scons detected (package version: 4.8.0, last github version: 4.9.1)
=> Auto-update scons to 4.9.1

packages/w/websocketpp/xmake.lua
Hash of patch changed on next day for some reason.
```
checkinfo: ...amdir/core/sandbox/modules/import/core/tool/compiler.lua:84: @programdir/modules/core/tools/gcc.lua:980: /home/runner/.xmake/packages/w/websocketpp/0.8.2/2e65daa25197460ab878866d27c4d816/include/websocketpp/transport/asio/connection.hpp:89:24: error: no type named 'io_service' in namespace 'websocketpp::lib::asio'
89 |     typedef lib::asio::io_service * io_service_ptr;
|             ~~~~~~~~~~~^
/home/runner/.xmake/packages/w/websocketpp/0.8.2/2e65daa25197460ab878866d27c4d816/include/websocketpp/transport/asio/connection.hpp:91:40: error: no member named 'io_service' in namespace 'websocketpp::lib::asio'
91 |     typedef lib::shared_ptr<lib::asio::io_service::strand> strand_ptr;
| …
```
=> websocketpp: adapt to new versions of boost

packages/j/jsbsim/xmake.lua
New version of jsbsim detected (package version: v1.2.1, last github version: v1.2.2)
=> Auto-update jsbsim to v1.2.2

packages/g/geos/xmake.lua
New version of geos detected (package version: 3.13.0, last github version: 3.13.1)
=> Auto-update geos to 3.13.1

packages/b/boost_sml/xmake.lua
New version of boost_sml detected (package version: v1.1.11, last github version: v1.1.12)
=> Auto-update boost_sml to v1.1.12

packages/p/protobuf-c/xmake.lua
New version of protobuf-c detected (package version: 1.5.1, last github version: 1.5.2)
=> Auto-update protobuf-c to 1.5.2

packages/r/redis-plus-plus/xmake.lua
New version of redis-plus-plus detected (package version: 1.3.13, last github version: 1.3.14)
=> Auto-update redis-plus-plus to 1.3.14

packages/a/aws-c-common/xmake.lua
New version of aws-c-common detected (package version: v0.12.0, last github version: v0.12.2)
=> Auto-update aws-c-common to v0.12.2

packages/c/catch2/xmake.lua
New version of catch2 detected (package version: v3.8.0, last github version: v3.8.1)
=> Auto-update catch2 to v3.8.1

packages/t/taywee_args/xmake.lua
New version of taywee_args detected (package version: 6.4.6, last github version: 6.4.7)
=> Auto-update taywee_args to 6.4.7

packages/l/llvm/xmake.lua
llvm 18.1.1 on windows cannot be used as library because it lacks a lot of files.
Change its source to `llvm/llvm-project/releases/download/llvmorg-18.1.1/clang+llvm-18.1.1-x86_64-pc-windows-msvc.tar.xz` to get full header files and libraries.
=> Change the source of llvm 18.1.1 on windows

packages/z/zlib-ng/xmake.lua
New version of zlib-ng detected (package version: 2.2.2, last github version: 2.2.4)
=> Auto-update zlib-ng to 2.2.4

packages/a/avir/xmake.lua
New version of avir detected (package version: 3.0, last github version: 3.1)
=> Auto-update avir to 3.1

packages/c/cwt-cucumber/xmake.lua
New version of cwt-cucumber detected (package version: 2.5, last github version: 2.6)
=> Auto-update cwt-cucumber to 2.6

packages/s/steam-audio/patch.lua, packages/s/steam-audio/xmake.lua
New version of steam-audio detected (package version: v4.6.0, last github version: v4.6.1)
=> Auto-update steam-audio to v4.6.1

packages/n/ngtcp2/xmake.lua
New version of ngtcp2 detected (package version: 1.10.0, last github version: 1.11.0)
=> Auto-update ngtcp2 to 1.11.0

packages/l/libxmake/xmake.lua
New version of libxmake detected (package version: v2.9.8, last github version: v2.9.9)
=> Auto-update libxmake to v2.9.9

packages/k/kokkos/xmake.lua
New version of kokkos detected (package version: 4.4.00, last github version: 4.6.00)
=> Auto-update kokkos to 4.6.00

packages/a/anari/xmake.lua
New version of anari detected (package version: v0.12.1, last github version: v0.13.1)
=> Auto-update anari to v0.13.1

packages/g/glbinding/xmake.lua
New version of glbinding detected (package version: v3.4.0, last github version: v3.5.0)
=> Auto-update glbinding to v3.5.0

packages/l/libwebsockets/xmake.lua
New version of libwebsockets detected (package version: v4.3.4, last github version: v4.3.5)
=> Auto-update libwebsockets to v4.3.5

packages/n/ngtcp2/xmake.lua
New version of ngtcp2 detected (package version: 1.11.0, last github version: 1.12.0)
=> Auto-update ngtcp2 to 1.12.0

packages/c/c4core/xmake.lua
New version of c4core detected (package version: 0.2.5, last github version: 0.2.6)
=> Auto-update c4core to 0.2.6

packages/s/simsimd/xmake.lua
New version of simsimd detected (package version: v6.4.0, last github version: v6.4.1)
=> Auto-update simsimd to v6.4.1

packages/l/libdwarf/xmake.lua
New version of libdwarf detected (package version: 0.11.1, last github version: 0.12.0)
=> Auto-update libdwarf to 0.12.0

packages/b/boost_ut/xmake.lua
New version of boost_ut detected (package version: v2.3.0, last github version: v2.3.1)
=> Auto-update boost_ut to v2.3.1

.github/workflows/windows_arm64.yml
https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview
=> Add native windows arm64 ci

packages/b/boost_di/xmake.lua
New version of boost_di detected (package version: v1.3.0, last github version: v1.3.2)
=> Auto-update boost_di to v1.3.2

packages/e/embree/xmake.lua
New version of embree detected (package version: v4.3.3, last github version: v4.4.0)
=> Auto-update embree to v4.4.0

packages/a/aws-lc/xmake.lua
New version of aws-lc detected (package version: v1.48.5, last github version: v1.49.1)
=> Auto-update aws-lc to v1.49.1

packages/s/sonic-cpp/xmake.lua
New version of sonic-cpp detected (package version: 1.0.1, last github version: 1.0.2)
=> Auto-update sonic-cpp to 1.0.2

packages/g/glaze/xmake.lua
New version of glaze detected (package version: v5.0.2, last github version: v5.1.0)
=> Auto-update glaze to v5.1.0

packages/i/idna/xmake.lua
New version of idna detected (package version: 0.3.2, last github version: 0.3.3)
=> Auto-update idna to 0.3.3

packages/b/boost_reflect/xmake.lua
New version of boost_reflect detected (package version: v1.2.4, last github version: v1.2.6)
=> Auto-update boost_reflect to v1.2.6

packages/a/aws-c-mqtt/xmake.lua
New version of aws-c-mqtt detected (package version: v0.12.1, last github version: v0.12.3)
=> Auto-update aws-c-mqtt to v0.12.3

packages/l/liboqs/xmake.lua
New version of liboqs detected (package version: 0.12.0, last github version: 0.13.0)
=> Auto-update liboqs to 0.13.0

packages/l/libflac/patches/1.5.0/android_fseek.diff, packages/l/libflac/patches/1.5.0/cmake.patch, packages/l/libflac/xmake.lua, packages/l/libogg/xmake.lua
I don't know how to fix shared `Wasm` build, `static` works. Most of time it is `static` only in case of `wasm` build.
For android need to pass `CMP0057` into `libogg` instead.
=> libflac: update to 1.5.0

packages/i/ittapi/xmake.lua
New version of ittapi detected (package version: v3.25.4, last github version: v3.25.5)
=> Auto-update ittapi to v3.25.5

packages/s/simdjson/xmake.lua
New version of simdjson detected (package version: v3.12.2, last github version: v3.12.3)
=> Auto-update simdjson to v3.12.3

packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.5.15, last github version: v1.5.17)
=> Auto-update s2n-tls to v1.5.17

packages/c/commata/xmake.lua
New version of commata detected (package version: v1.0.1, last github version: v1.1.0)
=> Auto-update commata to v1.1.0

packages/x/xz/patches/5.2.13/fix-unknown-cmake-command.patch, packages/x/xz/patches/xz-cve-2025-31115.patch, packages/x/xz/xmake.lua
- update to 5.8.1
- add patch for [cve-2025-31115](https://nvd.nist.gov/vuln/detail/CVE-2025-31115)
- all platform support (use cmake instead of autoconf)
=> xz: update to 5.8.1

packages/s/simdutf/xmake.lua
New version of simdutf detected (package version: v6.2.0, last github version: v6.5.0)
=> Auto-update simdutf to v6.5.0

packages/l/libsdl3_ttf/xmake.lua
`.tar.gz` archives are about half the size of `.zip` files
=> libsdl3_ttf: download smaller `.tar.gz` archives instead of `.zip`

packages/z/zint/xmake.lua
New version of zint detected (package version: 2.14.0, last github version: 2.15.0)
=> Auto-update zint to 2.15.0

packages/m/meson/xmake.lua
New version of meson detected (package version: 1.7.0, last github version: 1.7.2)
=> Auto-update meson to 1.7.2

packages/d/daw_json_link/xmake.lua
New version of daw_json_link detected (package version: v3.29.2, last github version: v3.30.2)
=> Auto-update daw_json_link to v3.30.2

packages/a/amrex/xmake.lua
New version of amrex detected (package version: 25.03, last github version: 25.04)
=> Auto-update amrex to 25.04

packages/l/libiconv/xmake.lua, packages/l/libvips/xmake.lua
New version of libvips detected (package version: v8.16.0, last github version: v8.16.1)
=> Auto-update libvips to v8.16.1

packages/s/simsimd/xmake.lua
New version of simsimd detected (package version: v6.4.1, last github version: v6.4.3)
=> Auto-update simsimd to v6.4.3

packages/c/cutlass/xmake.lua
New version of cutlass detected (package version: v3.8.0, last github version: v3.9.0)
=> Auto-update cutlass to v3.9.0

packages/h/hiredis/xmake.lua
New version of hiredis detected (package version: v1.2.0, last github version: v1.3.0)
=> Auto-update hiredis to v1.3.0

packages/z/zycore-c/xmake.lua
New version of zycore-c detected (package version: v1.5.0, last github version: v1.5.2)
=> Auto-update zycore-c to v1.5.2

packages/v/verilator/xmake.lua
New version of verilator detected (package version: v5.034, last github version: v5.036)
=> Auto-update verilator to v5.036

packages/a/aws-c-s3/xmake.lua
New version of aws-c-s3 detected (package version: v0.7.14, last github version: v0.7.15)
=> Auto-update aws-c-s3 to v0.7.15

.github/workflows/freebsd.yml, packages/l/lzma/xmake.lua
- update to 24.09.
- all platform support.
- drop 19.00, because it cannot be compiled on some platforms.
=> lzma: update to 24.09

packages/c/cppjieba/xmake.lua
New version of cppjieba detected (package version: v5.4.1, last github version: v5.5.0)
=> Auto-update cppjieba to v5.5.0

packages/l/lzav/xmake.lua
New version of lzav detected (package version: 4.9, last github version: 4.19)
=> Auto-update lzav to 4.19

packages/f/ftxui/xmake.lua
New version of ftxui detected (package version: v6.0.2, last github version: v6.1.1)
=> Auto-update ftxui to v6.1.1

packages/l/libelf/xmake.lua
https://github.com/xmake-io/xmake-repo/pull/7022#issuecomment-2842433195
=> libelf: use `add_resources` instead of `http.download`

packages/d/dirent/xmake.lua
New version of dirent detected (package version: 1.24, last github version: 1.25)
=> Auto-update dirent to 1.25

packages/l/libusb/xmake.lua
New version of libusb detected (package version: v1.0.27, last github version: v1.0.28)
=> Auto-update libusb to v1.0.28

packages/l/lief/patches/0.16.5/cstdint.patch, packages/l/lief/xmake.lua
New version of lief detected (package version: 0.16.4, last github version: 0.16.5)
=> Auto-update lief to 0.16.5

packages/l/libffi/xmake.lua
New version of libffi detected (package version: 3.4.7, last github version: 3.4.8)
=> Auto-update libffi to 3.4.8

packages/s/samurai/xmake.lua
New version of samurai detected (package version: v0.22.0, last github version: v0.23.0)
=> Auto-update samurai to v0.23.0

packages/a/aws-c-auth/xmake.lua
New version of aws-c-auth detected (package version: v0.8.7, last github version: v0.9.0)
=> Auto-update aws-c-auth to v0.9.0

packages/y/yy-thunks/xmake.lua
New version of yy-thunks detected (package version: 1.1.6, last github version: 1.1.7)
=> Auto-update yy-thunks to 1.1.7

packages/g/glaze/xmake.lua
New version of glaze detected (package version: v5.1.0, last github version: v5.1.2)
=> Auto-update glaze to v5.1.2

packages/j/jsoncons/xmake.lua
New version of jsoncons detected (package version: v1.3.0, last github version: v1.3.2)
=> Auto-update jsoncons to v1.3.2

packages/p/pybind11/xmake.lua, packages/p/python/xmake.lua
The current `rule("python.library")` works well with `pybind11`, but it may drop the `-lnanobind` flag when used with `nanobind`, leading to `undefined reference` link errors.
This PR moves the logic specific to `pybind11` from `rule("python.library")` into the `pybind11` package. This change ensures better compatibility with `nanobind` while maintaining the intended behavior for `pybind11`.
After this change, we can safely remove the following lines, allowing `rule("python.library")` to work with `nanobind`:
https://github.com/xmake-io/xmake/blob/2774ecbc0961e1e2b1f995d8937b44c2c90e11c6/xmake/rules/python/xmake.lua#L45-L67
=> pybind11: relocate macOS workaround for `pybind11` from `rule("python.library")` to package

packages/l/libsais/xmake.lua
New version of libsais detected (package version: v2.8.7, last github version: v2.10.0)
=> Auto-update libsais to v2.10.0

packages/d/doctest/xmake.lua
New version of doctest detected (package version: 2.4.11, last github version: 2.4.12)
=> Auto-update doctest to 2.4.12

packages/g/google-cloud-cpp/xmake.lua
New version of google-cloud-cpp detected (package version: v2.36.0, last github version: v2.37.0)
=> Auto-update google-cloud-cpp to v2.37.0

packages/r/robin-map/xmake.lua
New version of robin-map detected (package version: v1.3.0, last github version: v1.4.0)
=> Auto-update robin-map to v1.4.0

packages/p/polyscope/xmake.lua
New version of polyscope detected (package version: v2.3, last github version: v2.4.0)
=> Auto-update polyscope to v2.4.0

packages/b/boost/libs.lua
Due to 
[https://github.com/boostorg/locale/commit/258e95940248d9a113939f61b6ca2549c4c70e0b](url)
From boost 1.88, Boost::charconv is add as a PRIVATE dependency of Boost::locale
=> Update boost libs.lua

packages/a/aws-c-event-stream/xmake.lua
New version of aws-c-event-stream detected (package version: v0.5.1, last github version: v0.5.4)
=> Auto-update aws-c-event-stream to v0.5.4

packages/a/aws-c-cal/xmake.lua
New version of aws-c-cal detected (package version: v0.8.7, last github version: v0.9.0)
=> Auto-update aws-c-cal to v0.9.0

packages/a/arduinojson/xmake.lua
New version of arduinojson detected (package version: v7.3.1, last github version: v7.4.1)
=> Auto-update arduinojson to v7.4.1

packages/o/orc/xmake.lua
New version of orc detected (package version: v2.1.1, last github version: v2.1.2)
=> Auto-update orc to v2.1.2

packages/b/botan/xmake.lua
New version of botan detected (package version: 3.7.1, last github version: 3.8.1)
=> Auto-update botan to 3.8.1

packages/a/atomic_queue/xmake.lua
New version of atomic_queue detected (package version: v1.6.5, last github version: v1.6.9)
=> Auto-update atomic_queue to v1.6.9

packages/m/maddy/xmake.lua
New version of maddy detected (package version: 1.3.0, last github version: 1.5.0)
=> Auto-update maddy to 1.5.0

packages/g/gsl-lite/xmake.lua
New version of gsl-lite detected (package version: v0.42.0, last github version: v0.43.0)
=> Auto-update gsl-lite to v0.43.0

packages/g/gettext/xmake.lua, packages/l/libiconv/port/xmake.lua
=> (gettext) add version 0.22.5 0.23.1 0.24.1 and 0.25 and fix libiconv

packages/f/ftxui/xmake.lua
New version of ftxui detected (package version: v6.1.1, last github version: v6.1.9)
=> Auto-update ftxui to v6.1.9

packages/a/aws-c-http/xmake.lua
New version of aws-c-http detected (package version: v0.10.0, last github version: v0.10.1)
=> Auto-update aws-c-http to v0.10.1

packages/l/libsais/xmake.lua
New version of libsais detected (package version: v2.10.0, last github version: v2.10.1)
=> Auto-update libsais to v2.10.1

packages/u/ufbx/xmake.lua
New version of ufbx detected (package version: v0.15.1, last github version: v0.18.2)
=> Auto-update ufbx to v0.18.2

packages/a/aws-lc/xmake.lua
New version of aws-lc detected (package version: v1.49.1, last github version: v1.51.2)
=> Auto-update aws-lc to v1.51.2

packages/c/cpp-httplib/xmake.lua
New version of cpp-httplib detected (package version: v0.20.0, last github version: v0.20.1)
=> Auto-update cpp-httplib to v0.20.1

packages/l/libcpuid/xmake.lua
New version of libcpuid detected (package version: v0.7.1, last github version: v0.8.0)
=> Auto-update libcpuid to v0.8.0

packages/n/ncurses/xmake.lua, packages/r/readline/patches/8.2.13/mingw_fd_set.patch, packages/r/readline/xmake.lua
This PR improves platform support for `readline`.
**Side Note: Impact of `CFLAGS` on `autotools` Optimization Levels**
A noteworthy behavior was identified with `autotools`-based builds:
Setting the `CFLAGS` environment variable overrides the default compiler flags that `autoconf` would otherwise establish. Critically, if these user-supplied `CFLAGS` lack optimization specifications (e.g., `-O2`), the build process defaults to the compiler's base optimization level, typically `-O0`.
This is distinct from CMake's approach, where build-type-specific flags (e.g., `CMAKE_C_FLAGS_RELEASE`) are additive to `CMAKE_C_FLAGS`, generally ensuring optimized release builds. The `autotools` behavior can inadvertently result in packages being built without intended optimizations if `CFLAGS` is set.
=> readline: extend platform support

packages/l/libdeflate/xmake.lua
New version of libdeflate detected (package version: v1.23, last github version: v1.24)
=> Auto-update libdeflate to v1.24

packages/a/abseil/xmake.lua
New version of abseil detected (package version: 20250127.1, last github version: 20250512.0)
=> Auto-update abseil to 20250512.0

packages/s/simdutf/xmake.lua
New version of simdutf detected (package version: v6.5.0, last github version: v7.0.0)
=> Auto-update simdutf to v7.0.0

packages/a/ace/xmake.lua
Maybe one day `tao` would be packaged as binary tool, so another way to build `.idl` files would be possible.
This PR ports `ace` dependency of `tao` for Windows OS using MSVC.
=> ace: add package

packages/o/onnx/patches/1.18.0/cmake-abseil.patch, packages/o/onnx/xmake.lua
New version of onnx detected (package version: v1.17.0, last github version: v1.18.0)
=> Auto-update onnx to v1.18.0

packages/d/d3d12-memory-allocator/xmake.lua
New version of d3d12-memory-allocator detected (package version: v2.0.1, last github version: v3.0.1)
=> Auto-update d3d12-memory-allocator to v3.0.1

packages/l/libigl/xmake.lua
New version of libigl detected (package version: v2.5.0, last github version: v2.6.0)
=> Auto-update libigl to v2.6.0

packages/c/cuda-samples/xmake.lua
New version of cuda-samples detected (package version: v12.8, last github version: v12.9)
=> Auto-update cuda-samples to v12.9

packages/s/spdlog/xmake.lua
New version of spdlog detected (package version: v1.15.2, last github version: v1.15.3)
=> Auto-update spdlog to v1.15.3

packages/a/aws-c-common/xmake.lua
New version of aws-c-common detected (package version: v0.12.2, last github version: v0.12.3)
=> Auto-update aws-c-common to v0.12.3

packages/a/ace/xmake.lua, packages/t/tao_idl/xmake.lua
```
tao_idl -h
tao_idl: usage: tao_idl [[flag|file] ...] [-- file ...]
Legal flags:
-h | --help | -u       Print this list and exit successfully
-A...                  local implementation-specific escape
-Cw                    Warning if identifier spellings differ only in case (default is error)
-Ce                    Error if identifier spellings differ only in case (default)
-ae                    Error if anonymous type is seen (default)
-aw                    Warning if anonymous type is seen (default is error)
-as                    Silences the anonymous type diagnostic (default is error)
-d | --dump            Prints a dump of the AST and exits
-Dname[=value]         defines name for preprocessor
-E                     runs preprocessor only, prints on stdout
-Idir …
```
=> tao_idl: add package

packages/s/sol2/xmake.lua
New version of sol2 detected (package version: v3.3.1, last github version: v3.5.0)
=> Auto-update sol2 to v3.5.0

packages/l/libde265/xmake.lua
New version of libde265 detected (package version: 1.0.15, last github version: 1.0.16)
=> Auto-update libde265 to 1.0.16

packages/l/libvpx/xmake.lua
New version of libvpx detected (package version: v1.15.0, last github version: v1.15.1)
=> Auto-update libvpx to v1.15.1

packages/p/plutosvg/xmake.lua
New version of plutosvg detected (package version: v0.0.6, last github version: v0.0.7)
=> Auto-update plutosvg to v0.0.7

packages/f/fbgemm/xmake.lua
New version of fbgemm detected (package version: v1.1.2, last github version: v1.2.0)
=> Auto-update fbgemm to v1.2.0

packages/q/qdldl/xmake.lua
New version of qdldl detected (package version: v0.1.7, last github version: v0.1.8)
=> Auto-update qdldl to v0.1.8

packages/d/dlib/xmake.lua
New version of dlib detected (package version: v19.24.8, last github version: v19.24.9)
=> Auto-update dlib to v19.24.9

packages/l/libdicom/xmake.lua
New version of libdicom detected (package version: v1.1.0, last github version: v1.2.0)
=> Auto-update libdicom to v1.2.0

packages/m/mhook/xmake.lua
- Drop 2.5.1 version.
- Use xmake instead of cmake for building
=> mhook: update to latest version

packages/m/mongoose/xmake.lua
New version of mongoose detected (package version: 7.17, last github version: 7.18)
=> Auto-update mongoose to 7.18

packages/z/zziplib/xmake.lua
New version of zziplib detected (package version: v0.13.78, last github version: v0.13.79)
=> Auto-update zziplib to v0.13.79

packages/p/picobench/xmake.lua
New version of picobench detected (package version: 2.07, last github version: 2.08)
=> Auto-update picobench to 2.08

packages/k/kokkos/xmake.lua
New version of kokkos detected (package version: 4.6.00, last github version: 4.6.01)
=> Auto-update kokkos to 4.6.01

packages/p/plutovg/xmake.lua
New version of plutovg detected (package version: v1.0.0, last github version: v1.1.0)
=> Auto-update plutovg to v1.1.0

packages/a/aws-c-io/xmake.lua
New version of aws-c-io detected (package version: v0.18.1, last github version: v0.19.1)
=> Auto-update aws-c-io to v0.19.1

packages/c/cxxopts/xmake.lua
New version of cxxopts detected (package version: v3.2.1, last github version: v3.3.1)
=> Auto-update cxxopts to v3.3.1

packages/l/libavif/xmake.lua
New version of libavif detected (package version: v1.2.1, last github version: v1.3.0)
=> Auto-update libavif to v1.3.0

packages/r/reflect-cpp/xmake.lua
New version of reflect-cpp detected (package version: v0.18.0, last github version: v0.19.0)
=> Auto-update reflect-cpp to v0.19.0

packages/l/limonp/xmake.lua
New version of limonp detected (package version: v1.0.0, last github version: v1.0.1)
=> Auto-update limonp to v1.0.1

packages/a/aws-checksums/xmake.lua
New version of aws-checksums detected (package version: v0.2.3, last github version: v0.2.7)
=> Auto-update aws-checksums to v0.2.7

packages/l/libdwarf/xmake.lua
New version of libdwarf detected (package version: 0.12.0, last github version: 2.0.0)
=> Auto-update libdwarf to 2.0.0

packages/z/zziplib/xmake.lua
New version of zziplib detected (package version: v0.13.79, last github version: v0.13.80)
=> Auto-update zziplib to v0.13.80

packages/t/tracy/xmake.lua
Hello. I update the version. [https://github.com/wolfpld/tracy/releases](https://github.com/wolfpld/tracy/releases)
Does xmake-repo support application packages?
Tracy has nested projects:
cli applications
[https://github.com/wolfpld/tracy/tree/master/capture](https://github.com/wolfpld/tracy/tree/master/capture) to capture traces
[https://github.com/wolfpld/tracy/tree/master/csvexport](https://github.com/wolfpld/tracy/tree/master/csvexport) …
=> Update tracy to 0.12.0

packages/p/protobuf-cpp/patches/31.0/gcc15.patch, packages/p/protobuf-cpp/patches/31.0/msvc2019-arm64.patch, packages/p/protobuf-cpp/xmake.lua
升级 protobuf-cpp 到 31.0
目前在 `-p linux -a x86_64` `-p linux -a arm64` `-p android -a arm64-v8a` 中测试没有问题，其它平台未知
=> protobuf-cpp: update to 31.0

packages/l/libomp/patches/001-cast-to-make-gcc-happy.patch, packages/l/libomp/patches/002-hacks-for-static-linking.patch, packages/l/libomp/xmake.lua
Attempt to add `MinGW` support to `omp` package.
Might improve https://github.com/xmake-io/xmake-repo/pull/7206 MinGW build.
Note, MacOS@MinGW much more likely supposed to use uasm.exe from MinGW environment rather use uasm from Mac OS environment. Yet I believe according to our recent discussion MinGW support is in a progress to be improved, so I decided to fallback for uasm by Mac OS environment. (I do not have another way to solve this).
=> libomp: add mingw platform support

packages/q/quill/xmake.lua
New version of quill detected (package version: v9.0.2, last github version: v9.0.3)
=> Auto-update quill to v9.0.3

packages/o/ocilib/xmake.lua
New version of ocilib detected (package version: v4.7.7, last github version: v4.8.0)
=> Auto-update ocilib to v4.8.0

packages/e/etl/xmake.lua
New version of etl detected (package version: 20.41.4, last github version: 20.41.5)
=> Auto-update etl to 20.41.5

packages/s/sqlitecpp/xmake.lua
New version of sqlitecpp detected (package version: 3.3.2, last github version: 3.3.3)
=> Auto-update sqlitecpp to 3.3.3

packages/a/assimp/xmake.lua
New version of assimp detected (package version: v5.4.3, last github version: v6.0.1)
=> Auto-update assimp to v6.0.1

packages/u/upa-url/xmake.lua
New version of upa-url detected (package version: v2.0.0, last github version: v2.1.0)
=> Auto-update upa-url to v2.1.0

packages/d/dlss/xmake.lua
New version of dlss detected (package version: v310.1.0, last github version: v310.2.1)
=> Auto-update dlss to v310.2.1

packages/d/directx-headers/xmake.lua
New version of directx-headers detected (package version: v1.615.0, last github version: v1.616.0)
=> Auto-update directx-headers to v1.616.0

packages/e/emmylua_debugger/xmake.lua
New version of emmylua_debugger detected (package version: 1.8.4, last github version: 1.8.5)
=> Auto-update emmylua_debugger to 1.8.5

packages/o/onnxruntime/xmake.lua
在 macos 的M2 芯片环境上调试 x86-64 架构的时候会出现dyld[12794]: Library not loaded: @rpath/libonnxruntime.1.16.1.dylib
=> Fix a dylib problem that fails to find onnxruntime

.github/workflows/android_windows.yml, packages/h/half/xmake.lua, packages/m/mimalloc/xmake.lua
https://github.com/xmake-io/xmake-repo/issues/7325
Some sort of solution, maybe not the best one.
Windows Android NDK use `C:` drive instead of `D:` drive.
Indeed Github actions and windows-latest worker change slightly, I think this is cause of this issue.
=> half: update to 2.2.1 & Fix Windows Android NDK Github CI

packages/l/libsvm/xmake.lua
New version of libsvm detected (package version: v335, last github version: v336)
=> Auto-update libsvm to v336

packages/a/aws-c-sdkutils/xmake.lua
New version of aws-c-sdkutils detected (package version: v0.2.3, last github version: v0.2.4)
=> Auto-update aws-c-sdkutils to v0.2.4

packages/a/apr/xmake.lua
New version of apr detected (package version: 1.7.5, last github version: 1.7.6)
=> Auto-update apr to 1.7.6

packages/m/msdfgen/xmake.lua
New version of msdfgen detected (package version: v1.12, last github version: v1.12.1)
=> Auto-update msdfgen to v1.12.1

packages/m/moltenvk/xmake.lua
New version of moltenvk detected (package version: v1.2.11, last github version: v1.3.0)
=> Auto-update moltenvk to v1.3.0

packages/a/aws-c-s3/xmake.lua
New version of aws-c-s3 detected (package version: v0.7.15, last github version: v0.8.1)
=> Auto-update aws-c-s3 to v0.8.1

packages/c/cgraph/xmake.lua
New version of cgraph detected (package version: v2.6.2, last github version: v3.1.0)
=> Auto-update cgraph to v3.1.0

packages/u/unzip/xmake.lua
We re going to fix GCC 15 build for `unzip` very important package.
https://patchwork.yoctoproject.org/project/oe-core/patch/20250319081610.3536475-19-raj.khem@gmail.com/
This could be another solution for GCC 15
```diff
--- a/unix/unxcfg.h
+++ b/unix/unxcfg.h
@@ -117,7 +117,6 @@ typedef struct stat z_stat;
#else
-   struct tm *gmtime(), *localtime();
#endif
#if (defined(BSD4_4) || (defined(SYSV) && defined(MODERN)))
```
=> unzip: fix gcc 15

packages/e/expresscpp/patches/v0.20.0/fix-build.diff, packages/e/expresscpp/xmake.lua
Fix build for Linux gcc15
Windows:  error: C:\a\xmake-repo\xmake-repo\packages\e\expresscpp\xmake.lua:29: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:75: @programdir\modules\core\tools\link.lua:193: LINK : fatal error LNK1104: cannot open file 'libboost_filesystem-vc143-mt-a64-1_88.lib'
I do not know how to fix this one.
=> expresscpp: fix build

packages/o/opencl-headers/xmake.lua
New version of opencl-headers detected (package version: v2024.10.24, last github version: v2025.06.13)
=> Auto-update opencl-headers to v2025.06.13

packages/n/node-addon-api/xmake.lua
New version of node-addon-api detected (package version: v8.3.1, last github version: v8.4.0)
=> Auto-update node-addon-api to v8.4.0

packages/k/kahip/xmake.lua
New version of kahip detected (package version: v3.18, last github version: v3.19)
=> Auto-update kahip to v3.19

packages/c/cpp-httplib/xmake.lua
New version of cpp-httplib detected (package version: v0.20.1, last github version: v0.21.0)
=> Auto-update cpp-httplib to v0.21.0

packages/b/bandit/patches/2023.08.05/debundle-snowhouse.patch, packages/b/bandit/xmake.lua
Latest release tag does not support snowhouse 5.0.0, so workaround is to use latest changes commit.
=> bandit: new package

packages/r/readerwriterqueue/xmake.lua
New version of readerwriterqueue detected (package version: v1.0.6, last github version: v1.0.7)
=> Auto-update readerwriterqueue to v1.0.7

packages/l/libunwind/xmake.lua
* Update libunwind package version to the latest 1.8.2 (May 23, 2025)
---
* 更新 libunwind 包版本到最新的 1.8.2（2025年5月23日）
=> Update libunwind to v1.8.2

packages/b/b2/xmake.lua
New version of b2 detected (package version: 5.3.0, last github version: 5.3.2)
=> Auto-update b2 to 5.3.2

packages/t/taocpp-json/xmake.lua
Latest pegtl release wont work, since too old.
```
C:\Users\Admin\AppData\Local\.xmake\packages\j\json\2025.03.11\36a027cd729542b880966f8d2d7625bd\include/tao/json/jaxn/internal/grammar.hpp: In static member function 'static bool tao::json::jaxn::internal::rules::sor_value_impl<String, Binary>::match_must(Input&, States&& ...)':
C:\Users\Admin\AppData\Local\.xmake\packages\j\json\2025.03.11\36a027cd729542b880966f8d2d7625bd\include/tao/json/jaxn/internal/grammar.hpp:245:77: error: 'optional' is not a member of 'tao::pegtl::rewind_mode' [-Wtemplate-body]
245 |             return Control< must< Rule > >::template match< A, rewind_mode::optional, Action, Control >( in, st... );
```
=> taocpp-json: add new package

packages/n/nzsl/rules/archive_shaders.lua
=> nzsl: Use add_orders if available

packages/f/frugally-deep/xmake.lua
New version of frugally-deep detected (package version: v0.17.1, last github version: v0.18.2)
=> Auto-update frugally-deep to v0.18.2

packages/d/dlib/xmake.lua
New version of dlib detected (package version: v19.24.9, last github version: v20.0)
=> Auto-update dlib to v20.0

packages/a/aws-c-mqtt/xmake.lua
New version of aws-c-mqtt detected (package version: v0.12.3, last github version: v0.13.2)
=> Auto-update aws-c-mqtt to v0.13.2

packages/c/cpp-channel/xmake.lua
New version of cpp-channel detected (package version: v0.8.3, last github version: v1.3.1)
=> Auto-update cpp-channel to v1.3.1

packages/g/g3log/xmake.lua
New version of g3log detected (package version: 2.4, last github version: 2.6)
=> Auto-update g3log to 2.6

packages/v/vk-bootstrap/xmake.lua
New version of vk-bootstrap detected (package version: v1.4.312, last github version: v1.4.315)
=> Auto-update vk-bootstrap to v1.4.315

packages/c/cgraph/xmake.lua
New version of cgraph detected (package version: v3.1.0, last github version: v3.1.1)
=> Auto-update cgraph to v3.1.1

packages/j/jsbsim/xmake.lua
New version of jsbsim detected (package version: v1.2.2, last github version: v1.2.3)
=> Auto-update jsbsim to v1.2.3

packages/i/ixwebsocket/xmake.lua
New version of ixwebsocket detected (package version: v11.4.5, last github version: v11.4.6)
=> Auto-update ixwebsocket to v11.4.6

packages/c/cwt-cucumber/xmake.lua
New version of cwt-cucumber detected (package version: 2.6, last github version: 2.7)
=> Auto-update cwt-cucumber to 2.7

packages/k/keystone/patches/0.9.2/fix-gcc15.diff, packages/k/keystone/xmake.lua, packages/l/libmem/patches/5.0.5/fix-mingw.diff, packages/l/libmem/xmake.lua
Just test, I assume keystone is broken for GCC15.
------
TODO: clang-cl build succeeds. (`C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\Llvm\bin\clang-cl.exe`)
=> Update libmem to 5.0.5 add MinGW support and add clang-cl support

packages/l/libuv/xmake.lua
New version of libuv detected (package version: v1.50.0, last github version: v1.51.0)
=> Auto-update libuv to v1.51.0

packages/c/cuda/xmake.lua
close https://github.com/xmake-io/xmake-repo/issues/7179
=> cuda: support download toolchains

packages/n/nghttp3/xmake.lua
New version of nghttp3 detected (package version: v1.8.0, last github version: v1.10.1)
=> Auto-update nghttp3 to v1.10.1

packages/l/lsquic/xmake.lua
New version of lsquic detected (package version: v4.2.0, last github version: v4.3.0)
=> Auto-update lsquic to v4.3.0

packages/x/xdl/xmake.lua
New version of xdl detected (package version: v2.2.0, last github version: v2.3.0)
=> Auto-update xdl to v2.3.0

packages/g/gsl-lite/xmake.lua
New version of gsl-lite detected (package version: v0.43.0, last github version: v1.0.1)
=> Auto-update gsl-lite to v1.0.1

packages/l/ls-qpack/xmake.lua
New version of ls-qpack detected (package version: v2.6.1, last github version: v2.6.2)
=> Auto-update ls-qpack to v2.6.2

packages/t/tinygltf/xmake.lua
New version of tinygltf detected (package version: v2.9.5, last github version: v2.9.6)
=> Auto-update tinygltf to v2.9.6

packages/t/tracy/xmake.lua
New version of tracy detected (package version: v0.12.1, last github version: v0.12.2)
=> Auto-update tracy to v0.12.2

packages/a/amrex/xmake.lua
New version of amrex detected (package version: 25.05, last github version: 25.06)
=> Auto-update amrex to 25.06

packages/c/cpptrace/xmake.lua
New version of cpptrace detected (package version: v1.0.1, last github version: v1.0.2)
=> Auto-update cpptrace to v1.0.2

packages/s/standardlib/xmake.lua
It looks like releases and commit history was cleaned by upstream, and it is now just mirror of his so called *foundationallib*.
=> standardlib: update to 2024.03.25

packages/k/kuba-zip/xmake.lua
New version of kuba-zip detected (package version: v0.3.3, last github version: v0.3.4)
=> Auto-update kuba-zip to v0.3.4

packages/l/libpng/xmake.lua
New version of libpng detected (package version: v1.6.48, last github version: v1.6.49)
=> Auto-update libpng to v1.6.49

packages/g/glaze/xmake.lua
=> glaze: update to 5.5.2

packages/s/skia/xmake.lua
Cannot use `xmake project -k vsxmake` because the skia package does not compile with MDd in xmake 3.0
Error:
```
skia.lib(skia.SkPaint.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in _A679C31107FE4E708DCAFD283F118DE0.o
skia.lib(skia.SkPaint.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in _A679C31107FE4E708DCAFD283F118DE0.o
skia.lib(skia.SkMemory_malloc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in _A679C31107FE4E708DCAFD283F118DE0.o
skia.lib(skia.SkMemory_malloc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in …
```
=> skia: fix build for MDd on Windows

packages/h/hexl/xmake.lua
New version of hexl detected (package version: v1.2.5, last github version: v1.2.6)
=> Auto-update hexl to v1.2.6

packages/f/freerdp/xmake.lua
New version of freerdp detected (package version: 3.15.0, last github version: 3.16.0)
=> Auto-update freerdp to 3.16.0

packages/k/kuba-zip/xmake.lua
New version of kuba-zip detected (package version: v0.3.4, last github version: v0.3.5)
=> Auto-update kuba-zip to v0.3.5

packages/n/nghttp2/xmake.lua
New version of nghttp2 detected (package version: 1.65.0, last github version: 1.66.0)
=> Auto-update nghttp2 to 1.66.0

packages/e/emmylua_debugger/xmake.lua
New version of emmylua_debugger detected (package version: 1.8.5, last github version: 1.8.6)
=> Auto-update emmylua_debugger to 1.8.6

packages/g/gdal/xmake.lua
New version of gdal detected (package version: 3.10.2, last github version: 3.11.1)
=> Auto-update gdal to 3.11.1

packages/h/harfbuzz/xmake.lua
New version of harfbuzz detected (package version: 10.4.0, last github version: 11.2.1)
=> Auto-update harfbuzz to 11.2.1

packages/a/actor-framework/xmake.lua
New version of actor-framework detected (package version: 1.0.2, last github version: 1.1.0)
=> Auto-update actor-framework to 1.1.0

packages/s/simdutf/xmake.lua
New version of simdutf detected (package version: v7.2.1, last github version: v7.3.2)
=> Auto-update simdutf to v7.3.2

packages/g/google-cloud-cpp/xmake.lua
New version of google-cloud-cpp detected (package version: v2.37.0, last github version: v2.38.0)
=> Auto-update google-cloud-cpp to v2.38.0

packages/e/expected-lite/xmake.lua
New version of expected-lite detected (package version: v0.8.0, last github version: v0.9.0)
=> Auto-update expected-lite to v0.9.0

packages/a/aws-c-io/xmake.lua
New version of aws-c-io detected (package version: v0.20.1, last github version: v0.21.0)
=> Auto-update aws-c-io to v0.21.0

packages/l/libsais/xmake.lua
New version of libsais detected (package version: v2.10.1, last github version: v2.10.2)
=> Auto-update libsais to v2.10.2

packages/b/b2/xmake.lua
New version of b2 detected (package version: 5.3.2, last github version: 5.3.3)
=> Auto-update b2 to 5.3.3

packages/a/aws-c-s3/xmake.lua
New version of aws-c-s3 detected (package version: v0.8.1, last github version: v0.8.3)
=> Auto-update aws-c-s3 to v0.8.3

packages/g/google-cloud-cpp/xmake.lua
New version of google-cloud-cpp detected (package version: v2.38.0, last github version: v2.39.0)
=> Auto-update google-cloud-cpp to v2.39.0

packages/i/igraph/xmake.lua
New version of igraph detected (package version: 0.10.15, last github version: 0.10.16)
=> Auto-update igraph to 0.10.16

packages/e/etl/xmake.lua
New version of etl detected (package version: 20.42.0, last github version: 20.42.1)
=> Auto-update etl to 20.42.1

packages/c/cutlass/xmake.lua
New version of cutlass detected (package version: v3.9.0, last github version: v4.0.0)
=> Auto-update cutlass to v4.0.0

packages/g/gyp-next/xmake.lua
New version of gyp-next detected (package version: v0.20.0, last github version: v0.20.2)
=> Auto-update gyp-next to v0.20.2

packages/f/fastgltf/xmake.lua
New version of fastgltf detected (package version: v0.8.0, last github version: v0.9.0)
=> Auto-update fastgltf to v0.9.0

.github/workflows/macos_arm64.yml, .github/workflows/macos_x86_64.yml, packages/s/superlu/xmake.lua
#7464 
From v7.0.1, `superlu` no longer provides a **static** `superlu_config.h` file. This `.h` file must be dynamically generated from the `superlu_config.h.in` template through CMake macros. The old `xmake.lua` completely bypassed CMake, resulting in `superlu_config.h` never being created in v7.0.1, which in turn caused a "file not found" error when executing `io.replace`.
Solution:
Use `io.writefile` to overwrite.
=> Superlu: update to v7.0.1

packages/l/libfabric/xmake.lua
New version of libfabric detected (package version: 2.1.0, last github version: 2.2.0)
=> Auto-update libfabric to 2.2.0

packages/c/cppzmq/xmake.lua
New version of cppzmq detected (package version: v4.10.0, last github version: v4.11.0)
=> Auto-update cppzmq to v4.11.0

packages/s/simsimd/xmake.lua
New version of simsimd detected (package version: v6.4.3, last github version: v6.5.0)
=> Auto-update simsimd to v6.5.0

packages/l/libzip/xmake.lua
New version of libzip detected (package version: v1.11.3, last github version: v1.11.4)
=> Auto-update libzip to v1.11.4

packages/a/aws-c-io/xmake.lua
New version of aws-c-io detected (package version: v0.21.0, last github version: v0.21.1)
=> Auto-update aws-c-io to v0.21.1

packages/l/littlefs/xmake.lua
New version of littlefs detected (package version: v2.11.0, last github version: v2.11.1)
=> Auto-update littlefs to v2.11.1

packages/a/aws-c-common/xmake.lua
New version of aws-c-common detected (package version: v0.12.3, last github version: v0.12.4)
=> Auto-update aws-c-common to v0.12.4

packages/n/nanobind/xmake.lua
New version of nanobind detected (package version: v2.7.0, last github version: v2.8.0)
=> Auto-update nanobind to v2.8.0

packages/l/libvorbis/xmake.lua
Part of pulseaudio PR.
https://github.com/xmake-io/xmake-repo/pull/7695
```xmake
local configs = {"-DCMAKE_POLICY_DEFAULT_CMP0057=NEW"}
```
=> libvorbis: add CMP flag to fix NDK build

packages/h/highs/xmake.lua
New version of highs detected (package version: v1.10.0, last github version: v1.11.0)
=> Auto-update highs to v1.11.0

packages/g/glaze/xmake.lua
New version of glaze detected (package version: v5.5.2, last github version: v5.5.4)
=> Auto-update glaze to v5.5.4

packages/x/xgrammar/xmake.lua
New version of xgrammar detected (package version: v0.1.19, last github version: v0.1.21)
=> Auto-update xgrammar to v0.1.21

packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.5.21, last github version: v1.5.23)
=> Auto-update s2n-tls to v1.5.23

packages/a/assimp/xmake.lua
New version of assimp detected (package version: v6.0.1, last github version: v6.0.2)
=> Auto-update assimp to v6.0.2

packages/c/c-blosc2/xmake.lua
New version of c-blosc2 detected (package version: v2.18.0, last github version: v2.19.1)
=> Auto-update c-blosc2 to v2.19.1

packages/m/marisa/xmake.lua
New version of marisa detected (package version: v0.3.0, last github version: v0.3.1)
=> Auto-update marisa to v0.3.1

packages/v/vcglib/xmake.lua
New version of vcglib detected (package version: 2023.12, last github version: 2025.07)
=> Auto-update vcglib to 2025.07

packages/c/catch2/xmake.lua
New version of catch2 detected (package version: v3.8.1, last github version: v3.9.0)
=> Auto-update catch2 to v3.9.0

packages/n/ngtcp2/xmake.lua
New version of ngtcp2 detected (package version: 1.13.0, last github version: 1.14.0)
=> Auto-update ngtcp2 to 1.14.0

packages/s/soxr/xmake.lua
I am not very familiar with the MSYS2 but this is workaround.
```
D:\a\_temp\msys64\mingw64\bin\xz.exe -d -f D:\a\_temp\msys64\tmp\.xmake\250725\_FCCFCA27021F473081250F5B39A30850.tar\soxr-0.1.3-Source.tar.xz
D:\a\_temp\msys64\usr\bin\tar.exe --force-local -xf D:\a\_temp\msys64\tmp\.xmake\250725\_FCCFCA27021F473081250F5B39A30850.tar\soxr-0.1.3-Source.tar
/usr/bin/tar: soxr-0.1.3-Source/inst-check-soxr-lsr: Cannot create symlink to ‘inst-check-soxr’: No such file or directory
/usr/bin/tar: Exiting with failure status due to previous errors
error: ...modules\private\action\require\impl\actions\download.lua:257: @programdir\modules\utils\archive\extract.lua:458: cannot extract soxr-0.1.3-Source.tar.xz, @programdir\modules\utils\archive\extract.lua:458: cannot extract soxr-0.1.3-Source.tar, …
```
=> soxr: Keep only .zip source, remove .tar.xz source to resolve MSYS2

packages/r/redis-plus-plus/xmake.lua
New version of redis-plus-plus detected (package version: 1.3.14, last github version: 1.3.15)
=> Auto-update redis-plus-plus to 1.3.15

packages/p/pyincpp/xmake.lua
New version of pyincpp detected (package version: v2.6.1, last github version: v2.6.2)
=> Auto-update pyincpp to v2.6.2

packages/l/lunasvg/xmake.lua
New version of lunasvg detected (package version: v3.3.0, last github version: v3.4.0)
=> Auto-update lunasvg to v3.4.0

packages/c/cpp-httplib/patches/v0.23.1/fix-mingw.diff, packages/c/cpp-httplib/xmake.lua
New version of cpp-httplib detected (package version: v0.22.0, last github version: v0.23.1)
=> Auto-update cpp-httplib to v0.23.1

packages/a/aws-c-io/xmake.lua
New version of aws-c-io detected (package version: v0.21.1, last github version: v0.21.2)
=> Auto-update aws-c-io to v0.21.2

packages/o/onnxruntime/xmake.lua
v1.22.1 is released for windows only.
=> onnxruntime: update to 1.22.1(windows)

packages/x/xgrammar/xmake.lua
New version of xgrammar detected (package version: v0.1.21, last github version: v0.1.22)
=> Auto-update xgrammar to v0.1.22

packages/c/cppcheck/xmake.lua
New version of cppcheck detected (package version: 2.17.1, last github version: 2.18.0)
=> Auto-update cppcheck to 2.18.0

packages/c/cutlass/xmake.lua
New version of cutlass detected (package version: v4.0.0, last github version: v4.1.0)
=> Auto-update cutlass to v4.1.0

packages/n/node-addon-api/xmake.lua
New version of node-addon-api detected (package version: v8.4.0, last github version: v8.5.0)
=> Auto-update node-addon-api to v8.5.0

packages/i/ittapi/xmake.lua
New version of ittapi detected (package version: v3.26.1, last github version: v3.26.2)
=> Auto-update ittapi to v3.26.2

packages/r/re-flex/xmake.lua
New version of re-flex detected (package version: v5.3.0, last github version: v6.0.0)
=> Auto-update re-flex to v6.0.0

packages/l/lzav/xmake.lua
New version of lzav detected (package version: 4.19, last github version: 4.23)
=> Auto-update lzav to 4.23

packages/m/maddy/xmake.lua
New version of maddy detected (package version: 1.5.0, last github version: 1.6.0)
=> Auto-update maddy to 1.6.0

packages/l/luau/xmake.lua
New version of luau detected (package version: 0.683, last github version: 0.686)
=> Auto-update luau to 0.686

packages/p/portaudio/xmake.lua
because vs_runtime option has been renamed
=> portaudio: Fix building with latest xmake

packages/i/ittapi/xmake.lua
New version of ittapi detected (package version: v3.26.2, last github version: v3.26.3)
=> Auto-update ittapi to v3.26.3

packages/o/openexr/xmake.lua
New version of openexr detected (package version: v3.3.4, last github version: v3.3.5)
=> Auto-update openexr to v3.3.5

packages/d/dirent/xmake.lua
New version of dirent detected (package version: 1.25, last github version: 1.26)
=> Auto-update dirent to 1.26

packages/u/utf8proc/xmake.lua
update the patch checksum for utf8proc version 2.10.0. 
old checksum error!
=> fixed: update the patch checksum for utf8proc version 2.10.0

packages/c/cpr/xmake.lua
New version of cpr detected (package version: 1.11.2, last github version: 1.12.0)
=> Auto-update cpr to 1.12.0

packages/l/libdwarf/xmake.lua
New version of libdwarf detected (package version: 2.0.0, last github version: 2.1.0)
=> Auto-update libdwarf to 2.1.0

packages/l/libraqm/xmake.lua
New version of libraqm detected (package version: v0.10.2, last github version: v0.10.3)
=> Auto-update libraqm to v0.10.3

packages/l/leancrypto/xmake.lua
New version of leancrypto detected (package version: v1.4.0, last github version: v1.5.1)
=> Auto-update leancrypto to v1.5.1

packages/p/pdcursesmod/xmake.lua
New version of pdcursesmod detected (package version: v4.5.2, last github version: v4.5.3)
=> Auto-update pdcursesmod to v4.5.3

packages/s/simdutf/xmake.lua
New version of simdutf detected (package version: v7.3.4, last github version: v7.3.6)
=> Auto-update simdutf to v7.3.6

packages/t/trantor/xmake.lua
New version of trantor detected (package version: v1.5.23, last github version: v1.5.24)
=> Auto-update trantor to v1.5.24

packages/a/amrex/xmake.lua
New version of amrex detected (package version: 25.06, last github version: 25.08)
=> Auto-update amrex to 25.08

packages/y/yalantinglibs/xmake.lua
New version of yalantinglibs detected (package version: 0.5.3, last github version: 0.5.5)
=> Auto-update yalantinglibs to 0.5.5

packages/c/cppcheck/xmake.lua
New version of cppcheck detected (package version: 2.18.0, last github version: 2.18.1)
=> Auto-update cppcheck to 2.18.1

packages/l/libsais/xmake.lua
New version of libsais detected (package version: v2.10.2, last github version: v2.10.3)
=> Auto-update libsais to v2.10.3

packages/h/hyprwayland-scanner/xmake.lua
New version of hyprwayland-scanner detected (package version: v0.4.4, last github version: v0.4.5)
=> Auto-update hyprwayland-scanner to v0.4.5

packages/w/wintoast/xmake.lua
New version of wintoast detected (package version: v1.3.1, last github version: v1.3.2)
=> Auto-update wintoast to v1.3.2

packages/s/steam-audio/xmake.lua
New version of steam-audio detected (package version: v4.6.1, last github version: v4.7.0)
=> Auto-update steam-audio to v4.7.0

packages/v/vcpkg/xmake.lua
New version of vcpkg detected (package version: 2024.11.16, last github version: 2025.07.25)
=> Auto-update vcpkg to 2025.07.25

packages/v/verilator/xmake.lua
New version of verilator detected (package version: v5.036, last github version: v5.038)
=> Auto-update verilator to v5.038

packages/g/glaze/xmake.lua
New version of glaze detected (package version: v5.5.5, last github version: v5.6.0)
=> Auto-update glaze to v5.6.0

packages/v/vk-bootstrap/xmake.lua
New version of vk-bootstrap detected (package version: v1.4.315, last github version: v1.4.325)
=> Auto-update vk-bootstrap to v1.4.325

packages/m/mongoose/xmake.lua
New version of mongoose detected (package version: 7.18, last github version: 7.19)
=> Auto-update mongoose to 7.19

packages/r/rocksdb/xmake.lua
New version of rocksdb detected (package version: v10.4.2, last github version: v10.5.1)
=> Auto-update rocksdb to v10.5.1

packages/o/openpgl/xmake.lua
New version of openpgl detected (package version: 0.7.0, last github version: 0.7.1)
=> Auto-update openpgl to 0.7.1

packages/l/libassert/xmake.lua
New version of libassert detected (package version: v2.2.0, last github version: v2.2.1)
=> Auto-update libassert to v2.2.1

packages/v/vxl/xmake.lua
New version of vxl detected (package version: v3.3.2, last github version: v3.5.0)
=> Auto-update vxl to v3.5.0

packages/l/libzchunk/xmake.lua
New version of libzchunk detected (package version: 1.5.1, last github version: 1.5.2)
=> Auto-update libzchunk to 1.5.2

packages/p/pybind11/xmake.lua
New version of pybind11 detected (package version: v3.0.0, last github version: v3.0.1)
=> Auto-update pybind11 to v3.0.1

packages/d/dlss/xmake.lua
New version of dlss detected (package version: v310.2.1, last github version: v310.3.0)
=> Auto-update dlss to v310.3.0

packages/l/libbpf/xmake.lua
Based on #7975, but added Android support back.
Android needs NDK SDK version >= 23.
=> libbpf: add back android support

packages/c/cimg/xmake.lua
v3.6.0 checksum has been changed because of a force-push to v.3.6.0 tag.
=> cimg: update to v3.6.1

packages/s/sqlgen/patches/0.2.0/cmake.patch, packages/s/sqlgen/xmake.lua
I'm not really sure how cmake detect packages.
The patch for sqlite3 seems a bit hacky and cmake can't detect the mariadb package for some reason, this is why I commented it out.
=> Add sqlgen package

packages/r/rapidcsv/xmake.lua
New version of rapidcsv detected (package version: v8.87, last github version: v8.88)
=> Auto-update rapidcsv to v8.88

packages/v/veil/xmake.lua
New version of veil detected (package version: v1.4.1, last github version: v1.5.0)
=> Auto-update veil to v1.5.0

packages/a/aurora-au/xmake.lua
New version of aurora-au detected (package version: 0.4.1, last github version: 0.5.0)
=> Auto-update aurora-au to 0.5.0

packages/s/s2n-tls/xmake.lua
New version of s2n-tls detected (package version: v1.5.23, last github version: v1.5.25)
=> Auto-update s2n-tls to v1.5.25

packages/p/protobuf-cpp/xmake.lua
New version of protobuf-cpp detected (package version: 31.1, last github version: 32.0)
=> Auto-update protobuf-cpp to 32.0

packages/l/libsolv/xmake.lua
New version of libsolv detected (package version: 0.7.34, last github version: 0.7.35)
=> Auto-update libsolv to 0.7.35

packages/e/emmylua_debugger/xmake.lua
New version of emmylua_debugger detected (package version: 1.8.6, last github version: 1.8.7)
=> Auto-update emmylua_debugger to 1.8.7

packages/d/dlss/xmake.lua
New version of dlss detected (package version: v310.3.0, last github version: v310.4.0)
=> Auto-update dlss to v310.4.0

packages/l/libcbor/xmake.lua
New version of libcbor detected (package version: v0.12.0, last github version: v0.13.0)
=> Auto-update libcbor to v0.13.0

packages/s/sdl2webgpu/xmake.lua
https://github.com/eliemichel/sdl2webgpu
Based on the xmake.lua file for glfw3webgpu.
=> sdl2webgpu: add package

packages/l/luau/xmake.lua
New version of luau detected (package version: 0.686, last github version: 0.689)
=> Auto-update luau to 0.689

packages/l/libcpuid/xmake.lua
New version of libcpuid detected (package version: v0.8.0, last github version: v0.8.1)
=> Auto-update libcpuid to v0.8.1

packages/q/qdldl/xmake.lua
New version of qdldl detected (package version: v0.1.8, last github version: v0.1.9)
=> Auto-update qdldl to v0.1.9

packages/n/nghttp2/xmake.lua
New version of nghttp2 detected (package version: 1.66.0, last github version: 1.67.0)
=> Auto-update nghttp2 to 1.67.0

packages/s/simdutf/xmake.lua
New version of simdutf detected (package version: v7.3.6, last github version: v7.4.0)
=> Auto-update simdutf to v7.4.0

packages/l/librdkafka/xmake.lua
New version of librdkafka detected (package version: v2.11.0, last github version: v2.11.1)
=> Auto-update librdkafka to v2.11.1

packages/a/aws-c-event-stream/xmake.lua
New version of aws-c-event-stream detected (package version: v0.5.5, last github version: v0.5.6)
=> Auto-update aws-c-event-stream to v0.5.6

packages/o/openvr/xmake.lua
New version of openvr detected (package version: v2.12.1, last github version: v2.12.14)
=> Auto-update openvr to v2.12.14

packages/x/xgrammar/xmake.lua
New version of xgrammar detected (package version: v0.1.23, last github version: v0.1.24)
=> Auto-update xgrammar to v0.1.24

packages/d/dylib/xmake.lua
New version of dylib detected (package version: v2.2.1, last github version: v3.0.1)
=> Auto-update dylib to v3.0.1

packages/o/openal-soft/xmake.lua
OpenAL Soft's CMake configuration attempts to detect GCC's support for protected visibility using the HAVE_GCC_PROTECTED_VISIBILITY check. This detection fails on systems like NixOS and Fedora, leading to build errors. 
Solution:
This commit unconditionally disables the HAVE_GCC_PROTECTED_VISIBILITY check in the CMakeLists.txt file by replacing the conditional block with a fixed if(0) statement. This ensures that the build process proceeds without being affected by the faulty visibility detection, thereby resolving the build issues.
This issue has been previously reported and discussed in the OpenAL Soft issue tracker: [Issue #864](https://github.com/kcat/openal-soft/issues/864).
=> OpenAL Soft Fix: Disable GCC Protected Visibility Test to Resolve Build Failures on NixOS and Similar Systems

packages/a/aws-c-auth/xmake.lua
New version of aws-c-auth detected (package version: v0.9.0, last github version: v0.9.1)
=> Auto-update aws-c-auth to v0.9.1

packages/x/xlsxio/xmake.lua
New version of xlsxio detected (package version: 0.2.35, last github version: 0.2.36)
=> Auto-update xlsxio to 0.2.36

packages/c/cppcheck/xmake.lua
New version of cppcheck detected (package version: 2.18.1, last github version: 2.18.3)
=> Auto-update cppcheck to 2.18.3

packages/a/aws-c-io/xmake.lua
New version of aws-c-io detected (package version: v0.21.2, last github version: v0.22.0)
=> Auto-update aws-c-io to v0.22.0

packages/m/miniaudio/xmake.lua
New version of miniaudio detected (package version: 0.11.22, last github version: 0.11.23)
=> Auto-update miniaudio to 0.11.23

packages/p/p11-kit/xmake.lua
New version of p11-kit detected (package version: 0.25.5, last github version: 0.25.8)
=> Auto-update p11-kit to 0.25.8

packages/l/libunwind/xmake.lua
New version of libunwind detected (package version: v1.8.2, last github version: v1.8.3)
=> Auto-update libunwind to v1.8.3

packages/o/onednn/xmake.lua
New version of onednn detected (package version: v3.9, last github version: v3.9.1)
=> Auto-update onednn to v3.9.1

packages/x/xxmlxx/xmake.lua
a new header only package named _xxmlxx_.
https://github.com/luckydu-henry/xxmlxx
> An extremely light and efficient XML library (probably the smallest one ever had) containing almost complete XML IO and > handling features.
=> new package xxmlxx: 2025.09.14

packages/l/libatomic_ops/xmake.lua
New version of libatomic_ops detected (package version: v7.8.2, last github version: v7.8.4)
=> Auto-update libatomic_ops to v7.8.4

packages/d/dr_mp3/xmake.lua
New version of dr_mp3 detected (package version: 0.6.40, last github version: 0.7.1)
=> Auto-update dr_mp3 to 0.7.1

packages/f/fast-cdr/xmake.lua
New version of fast-cdr detected (package version: v2.3.0, last github version: v2.3.1)
=> Auto-update fast-cdr to v2.3.1

packages/g/glaze/xmake.lua
New version of glaze detected (package version: v5.6.0, last github version: v5.7.1)
=> Auto-update glaze to v5.7.1

packages/p/plutovg/xmake.lua
New version of plutovg detected (package version: v1.3.0, last github version: v1.3.1)
=> Auto-update plutovg to v1.3.1

packages/t/tgbot-cpp/xmake.lua
New version of tgbot-cpp detected (package version: v1.9, last github version: v1.9.1)
=> Auto-update tgbot-cpp to v1.9.1

packages/a/audit/xmake.lua, packages/c/checkpolicy/xmake.lua, packages/l/libcap-ng/xmake.lua, packages/l/libselinux/xmake.lua, packages/l/libsemanage/xmake.lua, packages/l/libsepol/xmake.lua, packages/p/policycoreutils/xmake.lua, packages/s/secilc/xmake.lua, scripts/test.lua
(selinux)
- libsepol
- libselinux
- libsemanage
- audit
- libcap-ng
- openldap (fixes, #8110)
- krb5 (fixes, #8125)
- checkpolicy
- secilc
- policycoreutils
=> selinux: add packages.

packages/p/p11-kit/xmake.lua
The original package moved the include files but didn't fix pkg-config, I restored the original includedir structure.
=> p11-kit: fix pkg-config and upgrade to 0.25.9

packages/f/fast_float/xmake.lua
New version of fast_float detected (package version: v8.0.2, last github version: v8.1.0)
=> Auto-update fast_float to v8.1.0

packages/x/xgrammar/xmake.lua
New version of xgrammar detected (package version: v0.1.24, last github version: v0.1.25)
=> Auto-update xgrammar to v0.1.25

packages/c/cutlass/xmake.lua
New version of cutlass detected (package version: v4.1.0, last github version: v4.2.0)
=> Auto-update cutlass to v4.2.0

packages/g/glgpuselect/xmake.lua
New version of glgpuselect detected (package version: 0.1.1, last github version: 0.1.2)
=> Auto-update glgpuselect to 0.1.2

packages/p/protobuf-cpp/xmake.lua
New version of protobuf-cpp detected (package version: 32.0, last github version: 32.1)
=> Auto-update protobuf-cpp to 32.1

packages/a/ada/xmake.lua
New version of ada detected (package version: v3.2.7, last github version: v3.3.0)
=> Auto-update ada to v3.3.0

packages/n/nghttp2/xmake.lua
New version of nghttp2 detected (package version: 1.67.0, last github version: 1.67.1)
=> Auto-update nghttp2 to 1.67.1

packages/k/kvazaar/xmake.lua
New version of kvazaar detected (package version: v2.3.1, last github version: v2.3.2)
=> Auto-update kvazaar to v2.3.2

packages/e/expat/xmake.lua
New version of expat detected (package version: 2.7.1, last github version: 2.7.3)
=> Auto-update expat to 2.7.3

packages/a/amrex/xmake.lua
New version of amrex detected (package version: 25.08, last github version: 25.09)
=> Auto-update amrex to 25.09

packages/b/bzip2/patches/cygming.patch, packages/b/bzip2/patches/show-progress.patch, packages/b/bzip2/xmake.lua
=> bzip2: apply patches from msys2/MINGW-packages.

packages/c/croaring/xmake.lua
New version of croaring detected (package version: v4.3.6, last github version: v4.3.12)
=> Auto-update croaring to v4.3.12

packages/c/cjson/xmake.lua
New version of cjson detected (package version: v1.7.18, last github version: v1.7.19)
=> Auto-update cjson to v1.7.19

packages/d/directx-headers/xmake.lua
New version of directx-headers detected (package version: v1.616.0, last github version: v1.618.1)
=> Auto-update directx-headers to v1.618.1

packages/l/libwfkafka/xmake.lua
New version of libwfkafka detected (package version: v0.11.7, last github version: v0.11.11)
=> Auto-update libwfkafka to v0.11.11

packages/c/cgraph/xmake.lua
New version of cgraph detected (package version: v3.1.1, last github version: v3.1.2)
=> Auto-update cgraph to v3.1.2

packages/l/littlefs/xmake.lua
New version of littlefs detected (package version: v2.11.1, last github version: v2.11.2)
=> Auto-update littlefs to v2.11.2

packages/l/llhttp/port/xmake.lua, packages/l/llhttp/xmake.lua
Since it uses two times install, first time from CMake, second time from XMake, I have to add cflags to both buildsystems.
Fix llhttp for https://github.com/xmake-io/xmake-repo/pull/8278
=> llhttp: support cross plat

packages/l/libjuice/xmake.lua
New version of libjuice detected (package version: v1.6.1, last github version: v1.6.2)
=> Auto-update libjuice to v1.6.2

packages/s/simplecpp/xmake.lua
New version of simplecpp detected (package version: 1.5.1, last github version: 1.5.2)
=> Auto-update simplecpp to 1.5.2

packages/d/duckdb/xmake.lua
New version of duckdb detected (package version: v1.3.2, last github version: v1.4.0)
=> Auto-update duckdb to v1.4.0

packages/r/rapidcsv/xmake.lua
New version of rapidcsv detected (package version: v8.88, last github version: v8.89)
=> Auto-update rapidcsv to v8.89

packages/l/libdatachannel/xmake.lua
New version of libdatachannel detected (package version: v0.23.1, last github version: v0.23.2)
=> Auto-update libdatachannel to v0.23.2

packages/i/imath/xmake.lua
New version of imath detected (package version: v3.1.12, last github version: v3.2.1)
=> Auto-update imath to v3.2.1

packages/p/pahomqttc/xmake.lua
New version of pahomqttc detected (package version: v1.3.14, last github version: v1.3.15)
=> Auto-update pahomqttc to v1.3.15

packages/s/sentry-native/xmake.lua
New version of sentry-native detected (package version: 0.11.1, last github version: 0.11.2)
=> Auto-update sentry-native to 0.11.2

packages/c/catch2/xmake.lua
New version of catch2 detected (package version: v3.10.0, last github version: v3.11.0)
=> Auto-update catch2 to v3.11.0

packages/a/atomic_queue/xmake.lua
New version of atomic_queue detected (package version: v1.6.9, last github version: v1.7.1)
=> Auto-update atomic_queue to v1.7.1

packages/l/libsystemd/xmake.lua
Since other pakcages are unlikely to have dependencies on systemd tools, so we only need to build libsystemd/libudev. `meson.build` is stripped to maintain a clean installdir and improve build speed.
- systemd
- #8113 
- #8114 
- #8165 
- #8166 
- #8169 
- #8168
=> libsystemd: add package.

packages/n/nzsl/xmake.lua
asan policy is not passed to xmake tool, so we need to pass it ourselves
=> nzsl: fix compilation when asan is enabled

packages/l/libsdl3_ttf/xmake.lua
=> libsdl3_ttf: fix windows download and disable submodules for git clone
